-- Shooting Drills Seed — 40 drills across all disciplines
-- Created: 2026-04-27

INSERT INTO public.shooting_drills (
  id, name, origin, drill_series,
  discipline, holster_required, props_required, movement_required, movement_description,
  round_count, target_type, target_count, start_position, distance_yards, description,
  range_depth_yards, range_width_feet,
  par_time_seconds, time_estimate_minutes, setup_time_minutes,
  scoring_method, performance_tiers, classification_benchmark,
  skill_focus, difficulty, stress_inoculation,
  dry_fire_capable, hand_variants, scaled_variations,
  competition_relevance, recommended_frequency, recommended_frequency_notes,
  prerequisite_drill_ids, night_vision_capable,
  video_reference_url, source_url
) VALUES

-- ── PISTOL ───────────────────────────────────────────────────────────────────

('bill-drill',
 'Bill Drill', 'Ken Hackathorn', NULL,
 ARRAY['pistol','revolver'], true, NULL, false, NULL,
 6, 'IPSC cardboard', 1, 'Holster', 7,
 'Draw and fire 6 rounds as fast as possible into the A-zone. All hits must be in the A-zone. Timer stops on last shot.',
 7, NULL,
 2.0, 5, 2,
 'Time Only', '{"world_class":1.5,"excellent":1.8,"good":2.0,"passing":2.5}', NULL,
 ARRAY['draw','speed','trigger_control'], 2, false,
 false, '{"sho":false,"who":false}', NULL,
 NULL, 'weekly', 'Build to 3x/week for speed work. Plateau is normal around 1.8s — focus on draw-to-first-shot.',
 NULL, false,
 NULL, NULL),

('fast-drill',
 'F.A.S.T. (Fundamentals, Accuracy, and Speed Test)', 'Todd Louis Green', NULL,
 ARRAY['pistol'], true, NULL, false, NULL,
 6, 'FAST target (3x5 headbox + 8in body circle)', 1, 'Holster', 7,
 'Start with 2 rounds in gun, 4 rounds in spare magazine. Draw and fire 2 rounds to the 3x5 headbox, perform a slidelock reload, then fire 4 rounds to the 8in body circle. Misses add 3 seconds each.',
 7, NULL,
 5.0, 10, 3,
 'Time + Points', '{"world_class":3.0,"excellent":4.0,"good":5.0,"passing":7.0}', NULL,
 ARRAY['draw','reload','accuracy','speed'], 3, false,
 false, NULL, '{"beginner":{"distance_yards":5,"par_time":10.0,"notes":"Extend par to build confidence with reload"}}',
 NULL, 'weekly', NULL,
 ARRAY['bill-drill'], false,
 NULL, NULL),

('dot-torture',
 'Dot Torture', 'David Blinder / Pistol-Training.com', NULL,
 ARRAY['pistol','revolver'], false, NULL, false, NULL,
 50, 'Dot Torture target (10 x 2in dots)', 1, 'Low Ready', 3,
 '10 dots, each with a specific string. Dot 1: 5 rounds freestyle. Dot 2: 5 rounds freestyle. Dots 3 & 4: 4 rounds draw-fire-holster alternating between dots. Dot 5: 5 rounds SHO only. Dots 6 & 7: 4 rounds 2 to each freestyle. Dot 8: 5 rounds WHO only. Dots 9 & 10: 4 rounds with reload between, 2 to each. Score out of 50.',
 3, 5,
 NULL, 20, 5,
 'Points Only', '{"world_class":50,"excellent":48,"good":45,"passing":40}', NULL,
 ARRAY['accuracy','trigger_control','support_hand','strong_hand','reload'], 2, false,
 true, NULL, '{"beginner":{"distance_yards":3},"advanced":{"distance_yards":7}}',
 NULL, 'weekly', 'Move back 1 yard when you score 48+ consistently. 7 yards is a legitimate standard.',
 NULL, false,
 NULL, 'https://pistol-training.com/drills/dot-torture/'),

('mozambique',
 'Failure to Stop (Mozambique)', 'Jeff Cooper', NULL,
 ARRAY['pistol','revolver'], true, NULL, false, NULL,
 3, 'IPSC cardboard', 1, 'Holster', 5,
 'On signal, draw and fire 2 rounds to the body (A-zone), then 1 round to the head (A-zone). Simulate a threat not stopping after center-mass hits.',
 5, NULL,
 2.5, 5, 1,
 'Time + Points', NULL, NULL,
 ARRAY['draw','accuracy','target_discrimination'], 1, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('hackathorn-standards',
 'Hackathorn Standards', 'Ken Hackathorn', NULL,
 ARRAY['pistol'], true, NULL, false, NULL,
 30, 'IDPA silhouette', 1, 'Holster', 10,
 'Multi-string qualification covering draw, accuracy, speed, and reload. Strings fired at 3, 5, 7, 10, and 15 yards with time limits per string. Full course of fire in official Hackathorn materials.',
 15, NULL,
 NULL, 30, 5,
 'Points Only', '{"world_class":290,"excellent":270,"good":250,"passing":225}', 'Hackathorn Standard tiers',
 ARRAY['draw','accuracy','reload','speed'], 3, false,
 false, NULL, NULL,
 NULL, 'monthly', 'Use as monthly benchmark. Track score over time.',
 ARRAY['bill-drill','fast-drill'], false,
 NULL, NULL),

('one-reload-one',
 '1-Reload-1', NULL, NULL,
 ARRAY['pistol','revolver'], true, NULL, false, NULL,
 2, 'IPSC cardboard', 1, 'Holster', 7,
 'Draw and fire 1 round to the A-zone. Perform an emergency reload. Fire 1 round to the A-zone. Focus is on the reload, not split time.',
 7, NULL,
 3.0, 5, 1,
 'Time Only', NULL, NULL,
 ARRAY['draw','reload'], 2, false,
 true, NULL, NULL,
 NULL, 'weekly', 'Run 10 reps dry, then 5 live. Timer should be at or below 3s at 7 yards.',
 NULL, false,
 NULL, NULL),

('idpa-5x5',
 'IDPA 5x5 Classifier', 'IDPA', NULL,
 ARRAY['pistol','revolver'], true, NULL, false, NULL,
 25, 'IDPA silhouette', 1, 'Holster', 10,
 '5 strings of 5 shots each. String 1: freestyle. String 2: SHO only. String 3: WHO only. String 4: freestyle with reload after round 3. String 5: freestyle. Points down are added to time.',
 10, NULL,
 NULL, 20, 5,
 'Time + Points', NULL, 'IDPA skill classification',
 ARRAY['draw','accuracy','reload','speed','strong_hand','support_hand'], 3, false,
 false, NULL, NULL,
 ARRAY['IDPA'], 'monthly', 'Official IDPA classifier. Track classification changes over time.',
 ARRAY['dot-torture'], false,
 NULL, 'https://www.idpa.com'),

('zipper-drill',
 'Zipper Drill', NULL, NULL,
 ARRAY['pistol','rifle'], false, NULL, false, NULL,
 6, 'IPSC cardboard', 1, 'Low Ready', 7,
 'Fire 6 shots walking up the target vertically: pelvic girdle, solar plexus, sternum, chin, nose, forehead. Tests vertical target tracking and consistent trigger control through the entire string.',
 7, NULL,
 3.0, 5, 1,
 'Time Only', NULL, NULL,
 ARRAY['trigger_control','accuracy','speed'], 2, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('casino-drill',
 'Casino Drill', 'Paul Howe / CSAT', NULL,
 ARRAY['pistol'], true, ARRAY['6 IPSC targets'], false, NULL,
 21, 'IPSC cardboard', 6, 'Holster', 10,
 '6 targets in a row. Fire 1 round on target 1, 2 on target 2, 3 on target 3, then 3 on target 4, 2 on target 5, 1 on target 6. Reload as needed. All hits must be A-zone.',
 10, 21,
 NULL, 15, 5,
 'Time + Points', NULL, NULL,
 ARRAY['draw','transitions','accuracy','reload'], 4, true,
 false, NULL, NULL,
 ARRAY['USPSA','IPSC'], 'monthly', NULL,
 ARRAY['bill-drill','one-reload-one'], false,
 NULL, NULL),

('el-presidente',
 'El Presidente', 'Jeff Cooper', NULL,
 ARRAY['pistol'], true, ARRAY['3 IPSC targets'], true, 'Turn 180° on start signal',
 12, 'IPSC cardboard', 3, 'Holster', 10,
 'Start facing downrange with hands raised. On signal, turn 180°, draw and engage 3 targets with 2 rounds each, perform a reload, engage 3 targets again with 2 rounds each. All hits A-zone.',
 10, 21,
 NULL, 15, 5,
 'Time + Points', '{"world_class":10.0,"excellent":12.0,"good":15.0,"passing":20.0}', NULL,
 ARRAY['draw','reload','transitions','speed'], 4, true,
 false, NULL, NULL,
 ARRAY['USPSA','IPSC'], 'weekly', NULL,
 ARRAY['bill-drill','one-reload-one'], false,
 NULL, NULL),

('the-test-werner',
 'The Test', 'Claude Werner', NULL,
 ARRAY['pistol'], true, NULL, false, NULL,
 10, '3x5 index card', 1, 'Holster', 10,
 '10 rounds in 10 seconds on a 3x5 index card at 10 yards from the holster. All 10 rounds must land inside the card for a clean run. The gold standard of practical accuracy benchmarks.',
 10, NULL,
 10.0, 10, 2,
 'Points Only', '{"world_class":10,"excellent":10,"good":8,"passing":7}', NULL,
 ARRAY['draw','accuracy','trigger_control'], 4, true,
 false, NULL, NULL,
 NULL, 'monthly', 'A perfect score is the only acceptable score. If you miss, it counts.',
 ARRAY['fast-drill','dot-torture'], false,
 NULL, NULL),

('fbi-qualification',
 'FBI Pistol Qualification', 'FBI', NULL,
 ARRAY['pistol'], true, NULL, true, 'Various positions at multiple distances',
 60, 'QIT-99 silhouette', 1, 'Holster', 25,
 'Full FBI pistol qualification course. Strings at 3, 5, 7, 15, and 25 yards. Multiple positions, time limits, and magazine counts per string. Includes SHO, WHO, kneeling, and standing strings. Passing score is 80% (48/60 rounds in scoring zone).',
 25, NULL,
 NULL, 45, 10,
 'Points Only', '{"passing":48}', 'FBI Agent Qualification',
 ARRAY['draw','accuracy','reload','movement','support_hand','strong_hand'], 3, true,
 false, NULL, NULL,
 NULL, 'quarterly', 'Run annually at minimum. A common benchmark for defensive pistol competency.',
 ARRAY['idpa-5x5'], false,
 NULL, 'https://www.fbi.gov'),

('2x2x2-drill',
 '2x2x2 Drill', NULL, NULL,
 ARRAY['pistol'], true, NULL, false, NULL,
 6, 'IPSC cardboard', 1, 'Holster', 7,
 'Draw and fire 2 rounds at 2 yards in 2 seconds. Simple metric for draw-to-first-shot and split time at contact distance.',
 3, NULL,
 2.0, 5, 1,
 'Time Only', '{"world_class":1.0,"excellent":1.5,"good":2.0,"passing":2.5}', NULL,
 ARRAY['draw','speed','trigger_control'], 1, false,
 true, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('par-time-standard',
 '5-Shot Par Time Standard', NULL, NULL,
 ARRAY['pistol','revolver'], false, NULL, false, NULL,
 5, 'IPSC cardboard', 1, 'Low Ready', 7,
 '5 rounds from low ready into the A-zone under par time. Timer cuts off at par. Any rounds after the beep do not count. Adjust distance and par to track improvement over time.',
 7, NULL,
 3.0, 5, 1,
 'Time Only', NULL, NULL,
 ARRAY['speed','trigger_control','accuracy'], 1, false,
 false, NULL, '{"beginner":{"distance_yards":3,"par_time":5.0},"advanced":{"distance_yards":15,"par_time":3.0}}',
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('rangemaster-qual',
 'Rangemaster Firearms Instructor Qualification', 'Tom Givens / Rangemaster', NULL,
 ARRAY['pistol'], true, NULL, false, NULL,
 60, 'B-27 silhouette', 1, 'Holster', 15,
 'Multi-string course of fire at 3, 5, 7, 10, and 15 yards. Includes one-handed, support-hand-only, and slidelock reload strings. Passing score is 90% (54/60). Used for instructor certification and as a civilian defensive pistol benchmark.',
 15, NULL,
 NULL, 40, 10,
 'Points Only', '{"passing":54}', 'Rangemaster Instructor Qualification',
 ARRAY['draw','accuracy','reload','strong_hand','support_hand'], 3, false,
 false, NULL, NULL,
 NULL, 'semi-annually', NULL,
 ARRAY['idpa-5x5'], false,
 NULL, NULL),

-- ── RIFLE ────────────────────────────────────────────────────────────────────

('vtac-1-5',
 'VTAC 1-5 Drill', 'Kyle Lamb / VTAC', NULL,
 ARRAY['rifle'], false, NULL, false, NULL,
 15, 'IPSC cardboard', 1, 'Low Ready', 100,
 'Fire 1 round, then 2, then 3, then 4, then 5 in sequence. All rounds in A-zone. Focus on consistent trigger press through increasing round count per string.',
 100, NULL,
 NULL, 10, 2,
 'Time Only', NULL, NULL,
 ARRAY['accuracy','trigger_control','speed'], 3, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('9-hole-drill',
 '9-Hole Drill', 'Kyle Lamb / VTAC', NULL,
 ARRAY['rifle'], false, NULL, false, NULL,
 18, 'Custom 9-hole paper', 1, 'Low Ready', 50,
 'Fire 2 rounds into each of 9 holes on the target. Tests precise aiming at multiple distinct aim points and consistent trigger press. Score out of 18.',
 50, NULL,
 NULL, 10, 3,
 'Points Only', NULL, NULL,
 ARRAY['accuracy','trigger_control'], 3, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('seb-cold-bore',
 'SEB Cold Bore Challenge', 'SEB / NRL', NULL,
 ARRAY['rifle'], false, NULL, false, NULL,
 1, 'Steel (1 MOA)', 1, 'Bench', 100,
 'One cold bore shot on a 1 MOA steel target at the start of each range session before the barrel has warmed. Recorded as hit or miss. Builds discipline around first-round accuracy and tracks cold bore shift.',
 100, NULL,
 NULL, 2, 1,
 'Pass-Fail', NULL, NULL,
 ARRAY['accuracy','trigger_control'], 1, false,
 false, NULL, NULL,
 ARRAY['PRS','NRL'], 'pre-competition', 'Run at the start of every range session. Track hit/miss percentage over time.',
 NULL, false,
 NULL, NULL),

('trex-rifle-standards',
 'TREX Arms Rifle Standards', 'TREX Arms', NULL,
 ARRAY['rifle'], false, NULL, false, NULL,
 20, 'IPSC cardboard', 1, 'Low Ready', 50,
 'Multi-string standards covering speed, accuracy, and reloads at 50 yards. Strings include speed shots, precision strings, and reload under time. Full course in TREX Arms content.',
 50, NULL,
 NULL, 15, 3,
 'Time + Points', NULL, NULL,
 ARRAY['accuracy','reload','transitions','speed'], 3, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('positional-standards-rifle',
 'Positional Shooting Standards', NULL, NULL,
 ARRAY['rifle'], false, NULL, false, NULL,
 10, 'NRA B8', 1, 'Freestyle', 100,
 '2 rounds each from 5 positions: prone, sitting, kneeling, standing, and supported kneeling. Score out of 100. Each position in 60 seconds.',
 100, NULL,
 60, 20, 5,
 'Points Only', '{"world_class":100,"excellent":95,"good":90,"passing":80}', NULL,
 ARRAY['accuracy'], 2, false,
 false, NULL, NULL,
 NULL, 'monthly', NULL,
 NULL, false,
 NULL, NULL),

('prs-positional-standards',
 'PRS Positional Standards', 'PRS Community', NULL,
 ARRAY['rifle'], false, ARRAY['barricade','andersons / vehicle props'], true, 'Transition between 5 field positions',
 10, 'Steel (8in)', 1, 'Freestyle', 200,
 'Fire 2 rounds from 5 positions: prone, prone barricade, kneeling barricade, standing barricade, and unsupported. 10-second par per 2-round string. All rounds on an 8-inch steel plate at 200 yards.',
 200, NULL,
 10, 20, 10,
 'Pass-Fail', NULL, NULL,
 ARRAY['accuracy','movement'], 4, true,
 false, NULL, NULL,
 ARRAY['PRS','NRL'], 'weekly', NULL,
 ARRAY['positional-standards-rifle'], false,
 NULL, NULL),

('cold-bore-fouled-comparison',
 'Cold Bore vs. Fouled Bore Comparison', NULL, NULL,
 ARRAY['rifle'], false, NULL, false, NULL,
 3, 'NRA B8', 1, 'Bench', 100,
 'Fire 1 round cold bore, mark the impact. Fire 2 rounds fouled bore, mark impacts. Measure the shift. Run at the start of every precision session to build a personal cold bore shift data set.',
 100, NULL,
 NULL, 5, 2,
 'Points Only', NULL, NULL,
 ARRAY['accuracy'], 1, false,
 false, NULL, NULL,
 ARRAY['PRS','NRL','Benchrest'], 'pre-competition', 'Every range session. Data accumulates into a cold bore shift average for your load.',
 NULL, false,
 NULL, NULL),

('vtac-2x2x2-rifle',
 'VTAC 2x2x2 Rifle', 'Kyle Lamb / VTAC', NULL,
 ARRAY['rifle'], false, ARRAY['3 IPSC targets'], false, NULL,
 6, 'IPSC cardboard', 3, 'Low Ready', 50,
 'Fire 2 rounds on each of 3 targets in 2 seconds. All rounds must be A-zone hits. Builds transition speed at rifle distance.',
 50, 21,
 2.0, 5, 3,
 'Time Only', '{"world_class":1.5,"excellent":2.0,"good":2.5,"passing":3.0}', NULL,
 ARRAY['transitions','speed','accuracy'], 3, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 ARRAY['vtac-1-5'], false,
 NULL, NULL),

('andersen-steel-standards',
 '400-Yard Precision Standards', 'PRS Community', NULL,
 ARRAY['rifle'], false, ARRAY['andersons / barricade'], false, NULL,
 5, 'Steel (6in)', 1, 'Prone', 400,
 '5 rounds on a 6-inch steel plate at 400 yards from prone. A test of first-round hit probability at mid-range precision distance. Missed rounds count as misses — no sighter shots.',
 400, NULL,
 NULL, 10, 3,
 'Pass-Fail', '{"world_class":5,"excellent":4,"good":3,"passing":2}', NULL,
 ARRAY['accuracy','trigger_control'], 3, false,
 false, NULL, NULL,
 ARRAY['PRS','NRL'], 'monthly', NULL,
 ARRAY['cold-bore-fouled-comparison'], false,
 NULL, NULL),

-- ── SHOTGUN ──────────────────────────────────────────────────────────────────

('figure-8-shotgun',
 'Figure 8 Shotgun', NULL, NULL,
 ARRAY['shotgun'], false, NULL, false, NULL,
 8, 'Clay / steel', 2, 'Low Ready', 15,
 'Engage two targets in a figure-8 pattern — 4 rounds alternating between left and right targets, then 4 rounds in reverse. Tests transitions and consistent follow-through between targets.',
 15, 10,
 NULL, 10, 3,
 'Points Only', NULL, NULL,
 ARRAY['transitions','accuracy','reload'], 2, false,
 false, NULL, NULL,
 ARRAY['3-Gun'], 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('shotgun-reload-par',
 'Shotgun Reload Under Par', NULL, NULL,
 ARRAY['shotgun'], false, NULL, false, NULL,
 4, 'Steel', 2, 'Low Ready', 15,
 'Fire 2 rounds, reload 2 rounds, fire 2 rounds. Measures reload speed under time pressure. Use a shot timer to track improvement.',
 15, NULL,
 10.0, 10, 2,
 'Time Only', NULL, NULL,
 ARRAY['reload','speed'], 3, false,
 false, NULL, NULL,
 ARRAY['3-Gun'], 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('langdon-shotgun-8',
 '8-Round Shotgun Standards', 'Ernest Langdon', NULL,
 ARRAY['shotgun'], false, NULL, false, NULL,
 8, 'IPSC cardboard', 1, 'Low Ready', 15,
 'Multi-string shotgun standards covering accuracy, speed, and reload. Strings include slug transitions and buckshot accuracy. Full course in Langdon Tactical materials.',
 15, NULL,
 NULL, 15, 5,
 'Time + Points', NULL, NULL,
 ARRAY['accuracy','reload','speed'], 3, false,
 false, NULL, NULL,
 ARRAY['3-Gun'], 'monthly', NULL,
 ARRAY['shotgun-reload-par'], false,
 NULL, NULL),

('shotgun-slug-transition',
 'Shotgun Slug Transition', NULL, NULL,
 ARRAY['shotgun'], false, NULL, false, NULL,
 6, 'IPSC cardboard + steel',  2, 'Low Ready', 25,
 'Start with buckshot loaded. Engage first target with 2 rounds of buckshot, reload with 2 slugs, engage steel plate at distance with 2 slug rounds. Tests the buckshot-to-slug transition fundamental to 3-gun competition.',
 25, 10,
 15.0, 10, 5,
 'Time Only', NULL, NULL,
 ARRAY['reload','transitions','accuracy'], 4, false,
 false, NULL, NULL,
 ARRAY['3-Gun'], 'monthly', NULL,
 ARRAY['shotgun-reload-par'], false,
 NULL, NULL),

-- ── REVOLVER ─────────────────────────────────────────────────────────────────

('revolver-speed-load',
 'Revolver Speed Load Standards', NULL, NULL,
 ARRAY['revolver'], true, NULL, false, NULL,
 12, 'IPSC cardboard', 1, 'Holster', 7,
 'Draw, fire 6 rounds, speed reload using speedloader, fire 6 more rounds. Tests revolver-specific reload speed. All rounds in A-zone.',
 7, NULL,
 6.0, 10, 2,
 'Time Only', NULL, NULL,
 ARRAY['draw','reload','speed'], 3, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('revolver-4-second',
 '4-Second Revolver Standard', 'NRA', NULL,
 ARRAY['revolver'], true, NULL, false, NULL,
 6, 'NRA B8', 1, 'Holster', 15,
 'Draw and fire 6 rounds on the B8 center in 4 seconds. Score out of 60. Tests the revolver draw, double-action trigger management, and accuracy at standard defensive distance.',
 15, NULL,
 4.0, 5, 1,
 'Time + Points', NULL, NULL,
 ARRAY['draw','accuracy','trigger_control'], 3, false,
 false, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('revolver-5-stage',
 'Revolver 5-Stage Standards', NULL, NULL,
 ARRAY['revolver'], true, NULL, false, NULL,
 30, 'IDPA silhouette', 1, 'Holster', 10,
 'Five 6-round strings emphasizing different skills: freestyle, SHO, WHO, combat reload (speedloader), and tactical reload (loose rounds). Total 30 rounds scored on time + points.',
 10, NULL,
 NULL, 25, 5,
 'Time + Points', NULL, NULL,
 ARRAY['draw','reload','strong_hand','support_hand','accuracy'], 3, false,
 false, NULL, NULL,
 NULL, 'monthly', NULL,
 ARRAY['revolver-speed-load','revolver-4-second'], false,
 NULL, NULL),

-- ── RIMFIRE ──────────────────────────────────────────────────────────────────

('rimfire-dot-torture',
 'Rimfire Dot Torture', 'Adapted from David Blinder', NULL,
 ARRAY['rimfire'], false, NULL, false, NULL,
 50, 'Dot Torture target (10 x 2in dots)', 1, 'Low Ready', 5,
 'Same course of fire as standard Dot Torture at reduced distance. Excellent for fundamentals practice at low cost.',
 5, 5,
 NULL, 20, 5,
 'Points Only', '{"world_class":50,"excellent":48,"good":45,"passing":40}', NULL,
 ARRAY['accuracy','trigger_control'], 1, false,
 true, NULL, '{"advanced":{"distance_yards":7}}',
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL),

('rimfire-benchrest-50ft',
 '22 LR Benchrest Standards', NULL, NULL,
 ARRAY['rimfire'], false, NULL, false, NULL,
 5, 'NRA 50ft Rimfire target', 1, 'Bench', 17,
 '5-shot group from the bench at 50 feet (NRA standard rimfire benchrest distance). Measure group size. Score 10-ring X count. Establishes baseline accuracy for a rifle and load combination.',
 17, NULL,
 NULL, 5, 2,
 'Points Only', NULL, NULL,
 ARRAY['accuracy','trigger_control'], 2, false,
 false, NULL, NULL,
 NULL, 'monthly', 'Run with each ammo lot to establish a load accuracy baseline.',
 NULL, false,
 NULL, NULL),

('nrl22-field-standards',
 'NRL22 Field Standards', 'NRL', NULL,
 ARRAY['rimfire'], false, ARRAY['barricade'], true, 'Transition between 3 field positions',
 6, 'Steel (2in)', 1, 'Freestyle', 50,
 'Fire 2 rounds from each of 3 positions — prone, kneeling barricade, and standing — at a 2-inch steel plate at 50 yards. 30-second par total. Mirrors NRL22 match stage format.',
 50, NULL,
 30, 10, 5,
 'Pass-Fail', NULL, NULL,
 ARRAY['accuracy','movement'], 3, false,
 false, NULL, NULL,
 ARRAY['NRL'], 'weekly', NULL,
 ARRAY['rimfire-dot-torture'], false,
 NULL, NULL),

('steel-challenge-smoke-hope',
 'Steel Challenge — Smoke & Hope', 'SCSA', NULL,
 ARRAY['pistol','rimfire'], false, ARRAY['5 steel plates'], false, NULL,
 5, 'Steel (18in plates + 8in stop plate)', 5, 'Freestyle', 7,
 'Five steel plates in the Smoke & Hope arrangement. Engage 4 plates in any order, finish on the large stop plate. Run 5 strings, drop the worst, score the best 4. Pure speed drill.',
 7, 15,
 NULL, 20, 10,
 'Time Only', '{"world_class":1.5,"excellent":2.0,"good":2.5,"passing":3.5}', NULL,
 ARRAY['transitions','speed','trigger_control'], 2, false,
 false, NULL, NULL,
 ARRAY['USPSA','SCSA'], 'weekly', NULL,
 NULL, false,
 NULL, NULL),

-- ── MULTI-DISCIPLINE / SPECIALIZED ───────────────────────────────────────────

('sport-rifle-qual',
 'Sportsman''s Team Challenge Qualifier', NULL, NULL,
 ARRAY['rifle','pistol'], false, NULL, false, NULL,
 20, 'IPSC cardboard', 2, 'Low Ready', 25,
 '10 rounds rifle + 10 rounds pistol on two IPSC targets. Alternating rifle/pistol strings at 25 yards. Tests the multi-gun transition fundamental — safe chamber check and weapon transition under time pressure.',
 25, 10,
 NULL, 15, 5,
 'Time + Points', NULL, NULL,
 ARRAY['transitions','accuracy','speed'], 3, false,
 false, NULL, NULL,
 ARRAY['3-Gun'], 'monthly', NULL,
 NULL, false,
 NULL, NULL),

('kneeling-unsupported-precision',
 'Kneeling Unsupported Precision Standard', NULL, NULL,
 ARRAY['rifle'], false, NULL, false, NULL,
 5, 'NRA B8', 1, 'Freestyle', 100,
 '5 rounds kneeling unsupported at 100 yards on a B8 center. No bipod, no bags, no sling support. Score out of 50. This single string exposes position stability issues faster than any other test.',
 100, NULL,
 60, 5, 2,
 'Points Only', '{"world_class":50,"excellent":48,"good":45,"passing":40}', NULL,
 ARRAY['accuracy'], 3, false,
 false, NULL, NULL,
 ARRAY['PRS','NRL'], 'monthly', NULL,
 ARRAY['positional-standards-rifle'], false,
 NULL, NULL),

('draw-to-first-shot',
 'Draw to First Shot (Par)', NULL, NULL,
 ARRAY['pistol'], true, NULL, false, NULL,
 1, 'IPSC cardboard', 1, 'Holster', 7,
 'Draw and fire 1 round A-zone. Record split time from buzzer to shot. The most isolated measurement of draw mechanics. Run 10 reps per session and average.',
 7, NULL,
 1.5, 5, 1,
 'Time Only', '{"world_class":0.8,"excellent":1.0,"good":1.3,"passing":1.5}', NULL,
 ARRAY['draw','speed'], 1, false,
 true, NULL, NULL,
 NULL, 'weekly', 'Your draw-to-first-shot time drives everything downstream. Master this before chasing split times.',
 NULL, false,
 NULL, NULL),

('reload-from-slide-lock',
 'Slidelock Reload Speed Standard', NULL, NULL,
 ARRAY['pistol'], false, NULL, false, NULL,
 2, 'IPSC cardboard', 1, 'Low Ready', 7,
 'Start at low ready with slide locked back (empty gun). On signal, perform a slidelock reload and fire 1 round A-zone. Isolates the reload without the draw variable.',
 7, NULL,
 2.0, 5, 1,
 'Time Only', '{"world_class":1.0,"excellent":1.3,"good":1.6,"passing":2.0}', NULL,
 ARRAY['reload','speed'], 2, false,
 true, NULL, NULL,
 NULL, 'weekly', NULL,
 NULL, false,
 NULL, NULL)

ON CONFLICT (id) DO NOTHING;
