// 50 New Cartridges for Gun Vault App
// Add these to seedCartridges array in /Users/banner-james/Desktop/gun-app/web/src/seedCartridges.ts

// ========================================
// EUROPEAN MILITARY CARTRIDGES (15)
// ========================================

{
  name: "8mm Lebel",
  alternateNames: ["8x50mmR Lebel", "8mm French"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Obsolete",
  availability: "Collector Only",
  yearIntroduced: 1886,
  inventor: "Colonel Nicolas Lebel",
  manufacturer: "French State Arsenal",
  countryOfOrigin: "France",
  bulletDiameterInch: 0.323,
  bulletDiameterMM: 8.2,
  baseDiameterInch: 0.540,
  baseDiameterMM: 13.72,
  rimDiameterInch: 0.625,
  rimDiameterMM: 15.88,
  caseLengthInch: 1.969,
  caseLengthMM: 50.0,
  overallLengthInch: 3.071,
  overallLengthMM: 78.0,
  caseCapacityGrains: 52.0,
  maxPressurePSI: 45000,
  commonBulletWeights: [198, 232, 240],
  velocityRangeFPS: { min: 2280, max: 2380 },
  energyRangeFTLBS: { min: 2275, max: 2480 },
  effectiveRangeYards: 500,
  maxRangeYards: 3000,
  primaryUse: ["Military"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [
    { country: "France", years: "1886-1940", conflicts: ["WWI", "WWII"] },
    { country: "French Colonial Forces", years: "1886-1960s", conflicts: ["Various colonial conflicts"] }
  ],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["7.92x57mm Mauser", ".303 British"],
  supersededBy: "7.5x54mm French MAS",
  description: "First smokeless powder military cartridge in the world. Featured unusual rimmed, tapered case design. Gave France temporary military advantage in 1880s-90s.",
  history: "Revolutionary cartridge introduced in 1886, making France the first nation to adopt smokeless powder for infantry rifles. Used extensively in WWI in the Lebel rifle. The rimmed case and tapered design made it difficult to use in modern magazine systems. Replaced by 7.5x54mm French in 1920s but remained in service through WWII.",
  notableFirearms: ["Lebel Model 1886", "Berthier rifles", "Chauchat machine gun", "Hotchkiss M1914"],
  trivia: "This cartridge started the smokeless powder revolution that made all black powder military rifles obsolete overnight. The unusual design with extreme taper was necessary for the tube magazine of the Lebel rifle."
},

{
  name: "6.5x50mm Arisaka",
  alternateNames: ["6.5mm Japanese", "6.5x50mmSR Arisaka"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Obsolete",
  availability: "Scarce",
  yearIntroduced: 1897,
  inventor: "Colonel Arisaka Nariakira",
  manufacturer: "Japanese Imperial Arsenal",
  countryOfOrigin: "Japan",
  bulletDiameterInch: 0.264,
  bulletDiameterMM: 6.71,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.478,
  rimDiameterMM: 12.14,
  caseLengthInch: 1.969,
  caseLengthMM: 50.0,
  overallLengthInch: 3.071,
  overallLengthMM: 78.0,
  caseCapacityGrains: 47.5,
  maxPressurePSI: 46000,
  commonBulletWeights: [139, 156, 160],
  velocityRangeFPS: { min: 2300, max: 2500 },
  energyRangeFTLBS: { min: 1750, max: 2000 },
  effectiveRangeYards: 600,
  maxRangeYards: 3200,
  primaryUse: ["Military"],
  huntingGameSize: ["Medium Game"],
  militaryAdoption: [
    { country: "Japan", years: "1897-1945", conflicts: ["Russo-Japanese War", "WWI", "WWII", "Sino-Japanese Wars"] }
  ],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["6.5x55mm Swedish", "6.5x52mm Carcano"],
  supersededBy: "7.7x58mm Arisaka",
  description: "Japanese military cartridge used from Russo-Japanese War through WWII. Known for mild recoil and adequate performance. Semi-rimmed design.",
  history: "Adopted by Imperial Japanese Army in 1897 for the Type 30 Arisaka rifle. Served through the Russo-Japanese War, WWI, and WWII. The mild recoil suited smaller-statured Japanese soldiers. Partially replaced by 7.7x58mm in late 1930s but both cartridges were used throughout WWII due to logistics.",
  notableFirearms: ["Type 30 Arisaka", "Type 38 Arisaka", "Type 44 Cavalry Carbine", "Type 96 Light Machine Gun"],
  trivia: "Despite being a 6.5mm cartridge, it had a reputation for poor performance in WWII. This was mainly due to Japanese military using full metal jacket bullets that didn't expand, not the cartridge itself."
},

{
  name: "7.5x54mm French MAS",
  alternateNames: ["7.5 French", "7.5x54mm MAS"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Limited",
  availability: "Limited",
  yearIntroduced: 1929,
  inventor: "French Ordnance",
  manufacturer: "French State Arsenal",
  countryOfOrigin: "France",
  bulletDiameterInch: 0.308,
  bulletDiameterMM: 7.82,
  baseDiameterInch: 0.488,
  baseDiameterMM: 12.4,
  rimDiameterInch: 0.490,
  rimDiameterMM: 12.45,
  caseLengthInch: 2.126,
  caseLengthMM: 54.0,
  overallLengthInch: 3.031,
  overallLengthMM: 77.0,
  caseCapacityGrains: 56.0,
  maxPressurePSI: 56000,
  commonBulletWeights: [139, 150, 174],
  velocityRangeFPS: { min: 2650, max: 2750 },
  energyRangeFTLBS: { min: 2450, max: 2700 },
  effectiveRangeYards: 800,
  maxRangeYards: 3800,
  primaryUse: ["Military", "Hunting"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [
    { country: "France", years: "1929-1980s", conflicts: ["WWII", "Indochina War", "Algerian War"] },
    { country: "Former French Colonies", years: "1950s-present", conflicts: ["Various"] }
  ],
  currentMilitaryUse: ["Some African nations"],
  lawEnforcementUse: false,
  similarCartridges: [".308 Winchester", "7.62x51mm NATO"],
  supersededBy: "5.56x45mm NATO",
  description: "French military cartridge that replaced 8mm Lebel. Similar performance to .308 Winchester. Used in iconic MAS-36 and MAS-49 rifles.",
  history: "Developed in 1920s to replace the obsolete 8mm Lebel. After initial problems with the 7.5x57mm version, it was shortened to 7.5x54mm in 1929. Served France through WWII, Indochina, and Algeria. Excellent cartridge that never gained civilian popularity despite good ballistics.",
  notableFirearms: ["MAS-36", "MAS-49", "MAS-49/56", "MAC Mle 1929", "Chatellerault M1924/29"],
  trivia: "France stubbornly kept this cartridge when NATO standardized on 7.62x51mm, then ironically adopted 5.56 NATO in the 1970s, skipping 7.62 NATO entirely for rifles."
},

{
  name: "6.5x52mm Carcano",
  alternateNames: ["6.5mm Carcano", "6.5x52mm Italian"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Obsolete",
  availability: "Limited",
  yearIntroduced: 1891,
  inventor: "Salvatore Carcano",
  manufacturer: "Italian State Arsenal",
  countryOfOrigin: "Italy",
  bulletDiameterInch: 0.268,
  bulletDiameterMM: 6.8,
  baseDiameterInch: 0.445,
  baseDiameterMM: 11.3,
  rimDiameterInch: 0.449,
  rimDiameterMM: 11.4,
  caseLengthInch: 2.047,
  caseLengthMM: 52.0,
  overallLengthInch: 2.953,
  overallLengthMM: 75.0,
  caseCapacityGrains: 45.0,
  maxPressurePSI: 46000,
  commonBulletWeights: [139, 156, 162],
  velocityRangeFPS: { min: 2300, max: 2500 },
  energyRangeFTLBS: { min: 1750, max: 2050 },
  effectiveRangeYards: 600,
  maxRangeYards: 3000,
  primaryUse: ["Military"],
  huntingGameSize: ["Medium Game"],
  militaryAdoption: [
    { country: "Italy", years: "1891-1945", conflicts: ["WWI", "WWII", "Italo-Turkish War", "Ethiopian War"] }
  ],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["6.5x50mm Arisaka", "6.5x55mm Swedish"],
  supersededBy: "7.35x51mm Carcano",
  description: "Italian military cartridge with mild recoil and good accuracy. Unfairly maligned due to poor ammunition quality in surplus market. Used in infamous JFK assassination rifle.",
  history: "Adopted by Italy in 1891 for the Carcano rifle. Part of the trend toward smaller-caliber, high-velocity cartridges. Served Italy through both World Wars. Gained infamy when Lee Harvey Oswald used a 6.5 Carcano rifle in the JFK assassination. The cartridge itself was adequate, but deteriorated surplus ammunition gave it a poor reputation.",
  notableFirearms: ["Carcano M1891", "M1938 Carbine", "Breda M1930", "Fiat-Revelli M1914"],
  trivia: "The Carcano rifle used to assassinate President Kennedy was a $12.78 mail-order surplus rifle. The cartridge's poor reputation is mostly due to corroded surplus ammo, not the design itself."
},

{
  name: "7.92x57mm Mauser",
  alternateNames: ["8mm Mauser", "8x57mm", "7.92x57mm IS", "8mm German"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 1888,
  inventor: "German Ordnance",
  manufacturer: "DWM",
  countryOfOrigin: "Germany",
  bulletDiameterInch: 0.323,
  bulletDiameterMM: 8.2,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.95,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.244,
  caseLengthMM: 57.0,
  overallLengthInch: 3.228,
  overallLengthMM: 82.0,
  caseCapacityGrains: 61.0,
  maxPressurePSI: 56000,
  commonBulletWeights: [150, 170, 196, 198],
  velocityRangeFPS: { min: 2500, max: 2900 },
  energyRangeFTLBS: { min: 2400, max: 3000 },
  effectiveRangeYards: 800,
  maxRangeYards: 4000,
  primaryUse: ["Military", "Hunting"],
  huntingGameSize: ["Medium Game", "Large Game", "Dangerous Game"],
  militaryAdoption: [
    { country: "Germany", years: "1888-1945", conflicts: ["WWI", "WWII"] },
    { country: "Yugoslavia", years: "1920s-1990s", conflicts: ["WWII", "Yugoslav Wars"] },
    { country: "Poland", years: "1918-1939", conflicts: ["Polish-Soviet War", "WWII"] },
    { country: "Czechoslovakia", years: "1918-1950s", conflicts: ["WWII"] }
  ],
  currentMilitaryUse: ["Various nations (limited)"],
  lawEnforcementUse: false,
  similarCartridges: [".30-06 Springfield", ".303 British", "7.62x54R"],
  supersededBy: "7.62x51mm NATO",
  description: "Legendary German military cartridge used in both World Wars. Excellent hunting cartridge, especially with heavy bullets. Commercial loads are downloaded due to weak surplus rifles.",
  history: "Introduced in 1888 for the Mauser Gewehr 88. Originally used a .318 bullet (J bore), changed to .323 in 1905 (S bore). The 'IS' designation (Infanterie Spitzer) refers to pointed bullets. Equipped German forces in both World Wars and was adopted by numerous other nations. Remains popular in Europe for hunting.",
  notableFirearms: ["Mauser Gewehr 98", "Karabiner 98k", "MG 34", "MG 42", "FG 42", "Czech VZ.24"],
  trivia: "American ammunition manufacturers load 8mm Mauser to reduced pressures due to weak surplus rifles on market. European loads are much hotter. Always check your rifle's strength before using hot loads."
},

{
  name: "7.62x54R",
  alternateNames: ["7.62x54mmR", "7.62 Russian", "7.62 Soviet"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Active",
  availability: "Abundant",
  yearIntroduced: 1891,
  inventor: "Russian Imperial Army",
  manufacturer: "Tula Arsenal",
  countryOfOrigin: "Russia",
  bulletDiameterInch: 0.312,
  bulletDiameterMM: 7.92,
  baseDiameterInch: 0.485,
  baseDiameterMM: 12.32,
  rimDiameterInch: 0.566,
  rimDiameterMM: 14.37,
  caseLengthInch: 2.115,
  caseLengthMM: 53.72,
  overallLengthInch: 3.037,
  overallLengthMM: 77.16,
  caseCapacityGrains: 56.0,
  maxPressurePSI: 56000,
  commonBulletWeights: [147, 150, 174, 180, 203],
  velocityRangeFPS: { min: 2600, max: 2850 },
  energyRangeFTLBS: { min: 2500, max: 3000 },
  effectiveRangeYards: 1000,
  maxRangeYards: 4200,
  primaryUse: ["Military", "Hunting", "Target"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [
    { country: "Russia/Soviet Union", years: "1891-present", conflicts: ["WWI", "Russian Civil War", "WWII", "Cold War", "Afghanistan", "Chechnya"] },
    { country: "Finland", years: "1918-present", conflicts: ["Winter War", "Continuation War"] },
    { country: "China", years: "1950s-1970s", conflicts: ["Korean War", "Vietnam War"] }
  ],
  currentMilitaryUse: ["Russia", "Former Soviet states", "Many nations"],
  lawEnforcementUse: true,
  similarCartridges: [".30-06 Springfield", ".308 Winchester", "7.92x57mm Mauser"],
  description: "Oldest military cartridge still in frontline service. Rimmed design from 1891 still equipping Russian military. Excellent long-range performance with heavy bullets.",
  history: "Adopted by Imperial Russia in 1891 for the Mosin-Nagant rifle. Survived the Russian Revolution, both World Wars, and Cold War. Still standard Russian sniper and machine gun cartridge. One of the most produced cartridges in history - billions of rounds manufactured. The 'R' designation means 'rimmed'.",
  notableFirearms: ["Mosin-Nagant", "SVD Dragunov", "PKM Machine Gun", "SVT-40", "PSL"],
  trivia: "This cartridge is over 130 years old and still in frontline military service - the longest-serving military cartridge in history. Cheap surplus ammunition has made it popular with civilian shooters."
},

{
  name: "7.5x55mm Swiss",
  alternateNames: ["7.5 Swiss", "GP11", "7.5x55mm Schmidt-Rubin"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1911,
  inventor: "Swiss Federal Ammunition Factory",
  manufacturer: "RUAG Ammotec",
  countryOfOrigin: "Switzerland",
  bulletDiameterInch: 0.308,
  bulletDiameterMM: 7.82,
  baseDiameterInch: 0.480,
  baseDiameterMM: 12.2,
  rimDiameterInch: 0.488,
  rimDiameterMM: 12.4,
  caseLengthInch: 2.165,
  caseLengthMM: 55.0,
  overallLengthInch: 3.031,
  overallLengthMM: 77.0,
  caseCapacityGrains: 58.0,
  maxPressurePSI: 56000,
  commonBulletWeights: [165, 174, 180],
  velocityRangeFPS: { min: 2550, max: 2750 },
  energyRangeFTLBS: { min: 2450, max: 2850 },
  effectiveRangeYards: 1000,
  maxRangeYards: 4000,
  primaryUse: ["Military", "Target", "Hunting"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [
    { country: "Switzerland", years: "1911-present", conflicts: ["None (Swiss neutrality)"] }
  ],
  currentMilitaryUse: ["Switzerland (limited, transitioning to 5.56)"],
  lawEnforcementUse: false,
  similarCartridges: [".308 Winchester", "7.62x51mm NATO"],
  description: "Extremely accurate Swiss military cartridge. Known for outstanding Swiss GP11 military ammunition quality. Popular for precision shooting and hunting.",
  history: "Adopted by Switzerland in 1911 for the Schmidt-Rubin rifles. Swiss neutrality meant it never saw combat but was perfected for accuracy. Swiss GP11 military surplus ammunition is famous for being match-grade quality. Still used for Swiss militia training and competition shooting.",
  notableFirearms: ["K31", "Schmidt-Rubin 1889", "Schmidt-Rubin 1911", "K11", "Stgw 57"],
  trivia: "Swiss GP11 military surplus ammunition is so accurate that competitive shooters prefer it over modern match ammunition. The Swiss made match-grade ammunition as their standard military load."
},

{
  name: "6.5x55mm Swedish",
  alternateNames: ["6.5 Swede", "6.5x55", "6.5 Swedish Mauser"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 1894,
  inventor: "Swedish-Norwegian Rifle Commission",
  manufacturer: "Various",
  countryOfOrigin: "Sweden/Norway",
  bulletDiameterInch: 0.264,
  bulletDiameterMM: 6.71,
  baseDiameterInch: 0.480,
  baseDiameterMM: 12.19,
  rimDiameterInch: 0.480,
  rimDiameterMM: 12.19,
  caseLengthInch: 2.165,
  caseLengthMM: 55.0,
  overallLengthInch: 3.150,
  overallLengthMM: 80.0,
  caseCapacityGrains: 56.0,
  maxPressurePSI: 55000,
  commonBulletWeights: [120, 130, 139, 140, 156],
  velocityRangeFPS: { min: 2600, max: 2900 },
  energyRangeFTLBS: { min: 2200, max: 2650 },
  effectiveRangeYards: 1000,
  maxRangeYards: 4000,
  primaryUse: ["Military", "Hunting", "Target", "Competition"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [
    { country: "Sweden", years: "1894-1990s", conflicts: ["None (Swedish neutrality)"] },
    { country: "Norway", years: "1894-1950s", conflicts: ["WWII resistance"] }
  ],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["6.5 Creedmoor", ".260 Remington", "6.5 PRC"],
  modernEquivalent: "6.5 Creedmoor",
  description: "Legendary Scandinavian cartridge beloved by hunters and target shooters. Mild recoil, excellent long-range ballistics. Predecessor to modern 6.5mm craze.",
  history: "Jointly developed by Sweden and Norway in 1894 for their Mauser rifles. Never saw major combat but excelled in hunting and target shooting. Scandinavian moose hunters have used it for over a century. Gained cult following worldwide for its accuracy and mild recoil. The 6.5 Creedmoor is basically a modernized Swedish Mauser.",
  notableFirearms: ["Swedish Mauser M96", "Norwegian Krag-Jørgensen", "CZ 550", "Sako 85"],
  trivia: "This 130-year-old cartridge is the grandfather of the modern 6.5mm renaissance. It can do almost everything the 6.5 Creedmoor can, and it did it 113 years earlier. Scandinavian hunters regularly take moose with it."
},

{
  name: "7.35x51mm Carcano",
  alternateNames: ["7.35 Carcano", "7.35mm Italian"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Obsolete",
  availability: "Collector Only",
  yearIntroduced: 1938,
  inventor: "Italian Ordnance",
  manufacturer: "Italian State Arsenal",
  countryOfOrigin: "Italy",
  bulletDiameterInch: 0.300,
  bulletDiameterMM: 7.62,
  baseDiameterInch: 0.445,
  baseDiameterMM: 11.3,
  rimDiameterInch: 0.449,
  rimDiameterMM: 11.4,
  caseLengthInch: 2.008,
  caseLengthMM: 51.0,
  overallLengthInch: 2.953,
  overallLengthMM: 75.0,
  caseCapacityGrains: 44.0,
  maxPressurePSI: 48000,
  commonBulletWeights: [128, 139],
  velocityRangeFPS: { min: 2400, max: 2500 },
  energyRangeFTLBS: { min: 1825, max: 2050 },
  effectiveRangeYards: 600,
  maxRangeYards: 3000,
  primaryUse: ["Military"],
  militaryAdoption: [
    { country: "Italy", years: "1938-1945", conflicts: ["WWII"] }
  ],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".308 Winchester", "7.62x39mm"],
  supersededBy: "Returned to 6.5x52mm Carcano",
  description: "Short-lived Italian military cartridge meant to replace 6.5 Carcano. Better performance but introduced at worst possible time. Abandoned mid-WWII.",
  history: "Italy adopted this as replacement for 6.5 Carcano in 1938, seeking better terminal performance. Limited production began but WWII disrupted conversion. By 1940, Italy was converting rifles back to 6.5mm due to logistics nightmare of two calibers during war. One of history's most poorly-timed cartridge introductions.",
  notableFirearms: ["Carcano M1938", "Carcano M1938 Carbine"],
  trivia: "This cartridge was introduced and then abandoned within 7 years - possibly the shortest-lived military standard cartridge in history. Italy literally converted rifles TO this cartridge, then converted them back."
},

{
  name: "7mm Mauser",
  alternateNames: ["7x57mm", "7x57mm Mauser", ".275 Rigby"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 1892,
  inventor: "Paul Mauser",
  manufacturer: "DWM",
  countryOfOrigin: "Germany",
  bulletDiameterInch: 0.284,
  bulletDiameterMM: 7.21,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.95,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.244,
  caseLengthMM: 57.0,
  overallLengthInch: 3.071,
  overallLengthMM: 78.0,
  caseCapacityGrains: 58.0,
  maxPressurePSI: 51000,
  commonBulletWeights: [120, 139, 140, 150, 175],
  velocityRangeFPS: { min: 2600, max: 2900 },
  energyRangeFTLBS: { min: 2200, max: 2800 },
  effectiveRangeYards: 800,
  maxRangeYards: 4000,
  primaryUse: ["Military", "Hunting"],
  huntingGameSize: ["Medium Game", "Large Game", "Dangerous Game"],
  militaryAdoption: [
    { country: "Spain", years: "1893-1950s", conflicts: ["Spanish-American War", "Spanish Civil War"] },
    { country: "Mexico", years: "1895-1930s", conflicts: ["Mexican Revolution"] },
    { country: "Serbia", years: "1899-1918", conflicts: ["WWI"] }
  ],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".308 Winchester", ".270 Winchester"],
  description: "Classic African hunting cartridge beloved by professional hunters. Mild recoil but deadly effective with proper bullets. W.D.M. Bell's elephant cartridge.",
  history: "Designed by Paul Mauser in 1892 and adopted by Spain in 1893. Proved devastatingly effective in Spanish-American War, leading US to adopt .30-06. Famous as the cartridge used by W.D.M. Bell to take over 1,000 elephants with precise shot placement. Marketed as .275 Rigby in Britain. Still highly regarded for hunting.",
  notableFirearms: ["Mauser M1893", "M1895 Chilean Mauser", "Ruger M77", "CZ 550"],
  trivia: "Legendary hunter W.D.M. Bell killed over 1,000 elephants with 7mm Mauser using precise brain shots. American loads are reduced pressure for liability - European loads are much more powerful."
},

{
  name: "7.62x39mm Soviet",
  alternateNames: ["7.62 Soviet", "7.62x39", "M43"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Active",
  availability: "Abundant",
  yearIntroduced: 1943,
  inventor: "Soviet Ordnance",
  manufacturer: "Tula Arsenal",
  countryOfOrigin: "Soviet Union",
  parentCase: "7.62x41mm experimental",
  bulletDiameterInch: 0.312,
  bulletDiameterMM: 7.92,
  baseDiameterInch: 0.445,
  baseDiameterMM: 11.30,
  rimDiameterInch: 0.447,
  rimDiameterMM: 11.35,
  caseLengthInch: 1.528,
  caseLengthMM: 38.80,
  overallLengthInch: 2.205,
  overallLengthMM: 56.0,
  caseCapacityGrains: 35.5,
  maxPressurePSI: 50000,
  commonBulletWeights: [122, 123, 154],
  velocityRangeFPS: { min: 2300, max: 2400 },
  energyRangeFTLBS: { min: 1450, max: 1550 },
  effectiveRangeYards: 400,
  maxRangeYards: 2500,
  primaryUse: ["Military", "Hunting", "Self Defense"],
  huntingGameSize: ["Medium Game"],
  militaryAdoption: [
    { country: "Soviet Union/Russia", years: "1943-present", conflicts: ["WWII", "Cold War conflicts", "Afghanistan", "Chechnya"] },
    { country: "China", years: "1949-present", conflicts: ["Korean War", "Vietnam War"] },
    { country: "North Vietnam", years: "1950s-1975", conflicts: ["Vietnam War"] },
    { country: "Over 50 nations", years: "1950s-present", conflicts: ["Countless conflicts worldwide"] }
  ],
  currentMilitaryUse: ["Russia", "China", "50+ nations", "Insurgent groups worldwide"],
  lawEnforcementUse: false,
  similarCartridges: [".300 Blackout", ".30-30 Winchester"],
  description: "Intermediate rifle cartridge powering the AK-47 and variants. Most widely used military cartridge in history by number of rifles. Reliable and effective at moderate ranges.",
  history: "Developed during WWII as intermediate cartridge combining rifle power with submachine gun controllability. First issued in SKS, then became famous in AK-47. The AK-47/AKM family has produced over 100 million rifles. Extremely common worldwide due to Soviet exports and licensed production. More rifles chambered for this than any cartridge in history.",
  notableFirearms: ["AK-47", "AKM", "SKS", "RPD", "RPK", "Ruger Mini-30"],
  trivia: "This cartridge powers more rifles than any other in existence - estimated 100-200 million rifles worldwide. Despite being 80+ years old, it will likely remain dominant for another generation due to the sheer number of AKs in circulation."
},

{
  name: "5.45x39mm Soviet",
  alternateNames: ["5.45 Soviet", "5.45x39", ".220 Russian"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1974,
  inventor: "Soviet Ordnance",
  manufacturer: "Tula Arsenal",
  countryOfOrigin: "Soviet Union",
  derivedFrom: "Influenced by 5.56x45mm NATO",
  bulletDiameterInch: 0.220,
  bulletDiameterMM: 5.6,
  baseDiameterInch: 0.390,
  baseDiameterMM: 9.91,
  rimDiameterInch: 0.392,
  rimDiameterMM: 9.96,
  caseLengthInch: 1.535,
  caseLengthMM: 39.0,
  overallLengthInch: 2.244,
  overallLengthMM: 57.0,
  caseCapacityGrains: 28.0,
  maxPressurePSI: 55000,
  commonBulletWeights: [52, 53, 60],
  velocityRangeFPS: { min: 2900, max: 3000 },
  energyRangeFTLBS: { min: 950, max: 1100 },
  effectiveRangeYards: 500,
  maxRangeYards: 2800,
  primaryUse: ["Military"],
  militaryAdoption: [
    { country: "Soviet Union/Russia", years: "1974-present", conflicts: ["Afghanistan", "Chechnya", "Syria", "Ukraine"] },
    { country: "Former Soviet states", years: "1974-present", conflicts: ["Various"] }
  ],
  currentMilitaryUse: ["Russia", "Belarus", "Former Soviet states"],
  lawEnforcementUse: false,
  similarCartridges: ["5.56x45mm NATO", ".223 Remington"],
  description: "Soviet answer to 5.56 NATO. Smaller, higher velocity than 7.62x39mm. Known for tumbling bullet design causing severe wounds.",
  history: "Developed as Soviet response to US adoption of 5.56mm. After Afghanistan experience with 7.62x39mm, Soviets wanted lighter recoiling, flatter-shooting cartridge. Introduced in 1974 with AK-74. The bullet has unique construction with air space in tip, causing it to tumble violently on impact. Replaced 7.62x39mm as Soviet standard rifle cartridge.",
  notableFirearms: ["AK-74", "AK-74M", "AKS-74U", "RPK-74", "AN-94"],
  trivia: "The 7N6 bullet design has a hollow tip that causes extreme tumbling and fragmentation, earning it the nickname 'the poison bullet.' It's actually more lethal than 5.56 NATO at close range due to this effect."
},

{
  name: "4.6x30mm HK",
  alternateNames: ["4.6x30mm", "HK 4.6x30"],
  type: "Pistol",
  standardization: "Proprietary",
  productionStatus: "Active",
  availability: "Limited",
  yearIntroduced: 1999,
  inventor: "Heckler & Koch",
  manufacturer: "Heckler & Koch",
  countryOfOrigin: "Germany",
  bulletDiameterInch: 0.180,
  bulletDiameterMM: 4.6,
  baseDiameterInch: 0.354,
  baseDiameterMM: 9.0,
  rimDiameterInch: 0.354,
  rimDiameterMM: 9.0,
  caseLengthInch: 1.181,
  caseLengthMM: 30.0,
  overallLengthInch: 1.535,
  overallLengthMM: 39.0,
  caseCapacityGrains: 14.0,
  maxPressurePSI: 54000,
  commonBulletWeights: [26, 31, 40],
  velocityRangeFPS: { min: 2300, max: 2400 },
  energyRangeFTLBS: { min: 300, max: 400 },
  effectiveRangeYards: 200,
  maxRangeYards: 1500,
  primaryUse: ["Military", "Self Defense"],
  militaryAdoption: [
    { country: "Germany", years: "2001-present", conflicts: ["Afghanistan"] },
    { country: "Various special forces", years: "2000s-present", conflicts: ["Counter-terrorism"] }
  ],
  currentMilitaryUse: ["German KSK", "Various special forces units"],
  lawEnforcementUse: true,
  similarCartridges: ["5.7x28mm FN", "5.56x45mm NATO"],
  description: "Personal Defense Weapon cartridge designed to defeat body armor. High velocity, low recoil. Developed for MP7 submachine gun.",
  history: "Developed by Heckler & Koch in 1990s for NATO PDW trials. Designed to replace 9mm for vehicle crews, pilots, and rear-echelon troops who needed better armor penetration. Lost NATO competition to 5.7x28mm but still adopted by German military and various special forces. Proprietary to HK, limiting civilian adoption.",
  notableFirearms: ["HK MP7", "HK MP7A1"],
  trivia: "This tiny cartridge can penetrate CRISAT body armor at 200 meters - something 9mm cannot do. The MP7 can fire 950 rounds per minute while weighing less than most pistols."
},

{
  name: "5.7x28mm FN",
  alternateNames: ["5.7x28", "Five-seveN"],
  type: "Pistol",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1990,
  inventor: "FN Herstal",
  manufacturer: "FN Herstal",
  countryOfOrigin: "Belgium",
  bulletDiameterInch: 0.224,
  bulletDiameterMM: 5.7,
  baseDiameterInch: 0.313,
  baseDiameterMM: 7.95,
  rimDiameterInch: 0.313,
  rimDiameterMM: 7.95,
  caseLengthInch: 1.102,
  caseLengthMM: 28.0,
  overallLengthInch: 1.594,
  overallLengthMM: 40.5,
  caseCapacityGrains: 12.5,
  maxPressurePSI: 50000,
  commonBulletWeights: [27, 31, 40],
  velocityRangeFPS: { min: 2100, max: 2350 },
  energyRangeFTLBS: { min: 250, max: 330 },
  effectiveRangeYards: 200,
  maxRangeYards: 1500,
  primaryUse: ["Military", "Self Defense", "Target"],
  militaryAdoption: [
    { country: "Over 40 nations", years: "1990s-present", conflicts: ["Various counter-terrorism operations"] }
  ],
  currentMilitaryUse: ["US Secret Service", "40+ nations", "Various police units"],
  lawEnforcementUse: true,
  similarCartridges: ["4.6x30mm HK", ".22 TCM"],
  description: "High-velocity pistol cartridge designed to defeat body armor. Chambered in FN Five-seveN pistol and P90 submachine gun. Very low recoil.",
  history: "Developed by FN Herstal in late 1980s for NATO PDW requirement. Won NATO trials over HK's 4.6x30mm. Designed for P90 submachine gun and Five-seveN pistol. Civilian adoption limited by high cost and armor-piercing reputation, though civilian ammunition is not armor-piercing. Gained popularity after US Secret Service adoption.",
  notableFirearms: ["FN P90", "FN Five-seveN pistol", "FN PS90", "Ruger-57"],
  trivia: "The P90's 50-round magazine lays flat on top of the gun and feeds downward through a complex 90-degree rotation mechanism. The cartridge can hold 20+1 rounds in a pistol the size of a Glock 19."
},

// Continue to Part 2...

// ========================================
// EUROPEAN SPORTING CARTRIDGES (15)
// ========================================

{
  name: "6.5x57mm Mauser",
  alternateNames: ["6.5x57", "6.5 Mauser"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Limited",
  availability: "Limited",
  yearIntroduced: 1894,
  inventor: "Paul Mauser",
  manufacturer: "DWM",
  countryOfOrigin: "Germany",
  parentCase: "7x57mm Mauser",
  derivedFrom: "7x57mm Mauser necked down",
  bulletDiameterInch: 0.264,
  bulletDiameterMM: 6.71,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.95,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.244,
  caseLengthMM: 57.0,
  overallLengthInch: 3.071,
  overallLengthMM: 78.0,
  caseCapacityGrains: 55.0,
  maxPressurePSI: 51000,
  commonBulletWeights: [120, 129, 140, 156],
  velocityRangeFPS: { min: 2700, max: 2950 },
  energyRangeFTLBS: { min: 2200, max: 2700 },
  effectiveRangeYards: 800,
  maxRangeYards: 4000,
  primaryUse: ["Hunting", "Target"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["6.5x55mm Swedish", "6.5 Creedmoor", ".260 Remington"],
  description: "Excellent European sporting cartridge combining 7x57 Mauser case with 6.5mm bullet. Popular with European hunters for low recoil and flat trajectory.",
  history: "Developed by necking down 7x57mm Mauser to 6.5mm in 1894. Popular in Europe and Scandinavia for deer and mountain game. Never achieved the fame of its parent cartridge or the 6.5x55 Swedish, but remained a solid performer. Declined after WWII but still produced by European ammunition makers.",
  notableFirearms: ["Custom Mauser sporters", "Mannlicher-Schoenauer rifles", "Various European hunting rifles"],
  trivia: "This cartridge is essentially what Americans later created with .260 Remington - a 6.5mm bullet in a .308-length case. Europeans were doing this 65 years earlier."
},

{
  name: "9.3x62mm Mauser",
  alternateNames: ["9.3x62", "9.3 Mauser"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 1905,
  inventor: "Otto Bock",
  manufacturer: "Deutsche Waffen- und Munitionsfabriken",
  countryOfOrigin: "Germany",
  parentCase: "8x57mm Mauser",
  derivedFrom: "8x57mm Mauser case enlarged",
  bulletDiameterInch: 0.366,
  bulletDiameterMM: 9.3,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.95,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.441,
  caseLengthMM: 62.0,
  overallLengthInch: 3.346,
  overallLengthMM: 85.0,
  caseCapacityGrains: 75.0,
  maxPressurePSI: 56000,
  commonBulletWeights: [232, 250, 286, 300],
  velocityRangeFPS: { min: 2300, max: 2500 },
  energyRangeFTLBS: { min: 3600, max: 4200 },
  effectiveRangeYards: 300,
  maxRangeYards: 3500,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Large Game", "Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".375 H&H Magnum", ".35 Whelen", "9.3x74mmR"],
  description: "Premier European dangerous game cartridge. Legendary in Africa for elephant, buffalo, and lion. Can be chambered in standard-length Mauser actions.",
  history: "Developed in 1905 by Otto Bock for hunting German colonial territories in Africa. Designed to fit standard Mauser 98 actions while providing dangerous game power. Became immensely popular with professional hunters and colonials. Regarded by many as the perfect all-around African cartridge. Still widely used in Europe and Africa today.",
  notableFirearms: ["Mauser M98", "CZ 550", "Sako 85", "Blaser R8", "Merkel rifles"],
  trivia: "Many professional hunters consider this superior to .375 H&H for thick-skinned dangerous game at close range. It fits in a standard-length action while .375 H&H requires magnum-length, making rifles lighter and handier."
},

{
  name: "9.3x74mmR",
  alternateNames: ["9.3x74R", "9.3x72R"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Limited",
  yearIntroduced: 1900,
  inventor: "RWS",
  manufacturer: "RWS",
  countryOfOrigin: "Germany",
  bulletDiameterInch: 0.366,
  bulletDiameterMM: 9.3,
  baseDiameterInch: 0.491,
  baseDiameterMM: 12.47,
  rimDiameterInch: 0.579,
  rimDiameterMM: 14.70,
  caseLengthInch: 2.913,
  caseLengthMM: 74.0,
  overallLengthInch: 3.622,
  overallLengthMM: 92.0,
  caseCapacityGrains: 79.0,
  maxPressurePSI: 52000,
  commonBulletWeights: [250, 285, 293],
  velocityRangeFPS: { min: 2300, max: 2450 },
  energyRangeFTLBS: { min: 3700, max: 4100 },
  effectiveRangeYards: 300,
  maxRangeYards: 3500,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Large Game", "Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["9.3x62mm Mauser", ".375 H&H Magnum"],
  description: "Rimmed version of 9.3mm for European double rifles and combination guns. Popular for driven hunts in Europe and dangerous game in Africa.",
  history: "Introduced around 1900 for European single-shot and double rifles. The rimmed case works perfectly in break-action guns. Very popular in Germany, Austria, and Scandinavia for moose, bear, and boar. Also used extensively in Africa. The rimmed design prevents use in bolt actions but ideal for doubles and drillings.",
  notableFirearms: ["Merkel double rifles", "Krieghoff double rifles", "Blaser K95", "Heym double rifles"],
  trivia: "This is the most popular dangerous game cartridge for European-style double rifles. The elegant double rifle in 9.3x74R is the ultimate status symbol for European hunters."
},

{
  name: "8x68mm S",
  alternateNames: ["8x68S", "8mm S"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Limited",
  yearIntroduced: 1939,
  inventor: "RWS",
  manufacturer: "RWS",
  countryOfOrigin: "Germany",
  bulletDiameterInch: 0.323,
  bulletDiameterMM: 8.2,
  baseDiameterInch: 0.528,
  baseDiameterMM: 13.41,
  rimDiameterInch: 0.528,
  rimDiameterMM: 13.41,
  caseLengthInch: 2.677,
  caseLengthMM: 68.0,
  overallLengthInch: 3.386,
  overallLengthMM: 86.0,
  caseCapacityGrains: 84.0,
  maxPressurePSI: 60000,
  commonBulletWeights: [170, 196, 220],
  velocityRangeFPS: { min: 2900, max: 3150 },
  energyRangeFTLBS: { min: 3700, max: 4200 },
  effectiveRangeYards: 600,
  maxRangeYards: 4500,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Large Game", "Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".300 Winchester Magnum", ".338 Winchester Magnum"],
  description: "Powerful German magnum cartridge. The 'S' designation means modern bore diameter (.323) versus older .318 bore. Flat-shooting and hard-hitting.",
  history: "Developed by RWS in 1939 as a magnum hunting cartridge. Based on .375 H&H case shortened and rebated rim. The 'S' (schweres) designation distinguishes it from older 8x68mm that used .318 bore. Never achieved wide popularity outside Germany but remains respected for its power and flat trajectory.",
  notableFirearms: ["Mauser M98", "Sauer 202", "Blaser R93", "Custom European hunting rifles"],
  trivia: "This cartridge approaches .300 Win Mag performance but in 8mm. Germans love their 8mm cartridges, and this is their answer to American magnums."
},

{
  name: ".318 Westley Richards",
  alternateNames: [".318 WR", ".318 Rimless Nitro Express"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Obsolete",
  availability: "Collector Only",
  yearIntroduced: 1910,
  inventor: "Leslie Taylor",
  manufacturer: "Westley Richards",
  countryOfOrigin: "United Kingdom",
  bulletDiameterInch: 0.330,
  bulletDiameterMM: 8.38,
  baseDiameterInch: 0.540,
  baseDiameterMM: 13.72,
  rimDiameterInch: 0.540,
  rimDiameterMM: 13.72,
  caseLengthInch: 2.520,
  caseLengthMM: 64.0,
  overallLengthInch: 3.390,
  overallLengthMM: 86.1,
  caseCapacityGrains: 72.0,
  maxPressurePSI: 50000,
  commonBulletWeights: [180, 250],
  velocityRangeFPS: { min: 2400, max: 2700 },
  energyRangeFTLBS: { min: 3200, max: 4000 },
  effectiveRangeYards: 400,
  maxRangeYards: 3800,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Large Game", "Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".333 Jeffery", "8x68mm S"],
  supersededBy: ".375 H&H Magnum",
  description: "British medium-bore dangerous game cartridge. Highly effective but eclipsed by .375 H&H. Popular with ivory hunters in early 20th century.",
  history: "Introduced by Westley Richards in 1910 as a medium-bore dangerous game round. Very popular with professional hunters and ivory traders from 1910-1930s. Used extensively by legendary hunter John 'Pondoro' Taylor who wrote extensively about its effectiveness. Faded after .375 H&H became the standard. The unusual .330 caliber made it somewhat proprietary.",
  notableFirearms: ["Westley Richards bolt rifles", "Westley Richards Droplock double rifles", "Custom Mauser actions"],
  trivia: "John 'Pondoro' Taylor, who developed the 'Taylor Knockout Factor,' used this cartridge for much of his hunting career and praised it as nearly perfect for everything except elephant."
},

{
  name: ".375 H&H Magnum",
  alternateNames: [".375 Holland & Holland", ".375 H&H", "9.5x72mm"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Abundant",
  yearIntroduced: 1912,
  inventor: "Holland & Holland",
  manufacturer: "Holland & Holland",
  countryOfOrigin: "United Kingdom",
  bulletDiameterInch: 0.375,
  bulletDiameterMM: 9.53,
  baseDiameterInch: 0.513,
  baseDiameterMM: 13.03,
  rimDiameterInch: 0.532,
  rimDiameterMM: 13.51,
  caseLengthInch: 2.850,
  caseLengthMM: 72.39,
  overallLengthInch: 3.600,
  overallLengthMM: 91.44,
  caseCapacityGrains: 95.0,
  maxPressurePSI: 62000,
  commonBulletWeights: [235, 270, 300],
  velocityRangeFPS: { min: 2400, max: 2700 },
  energyRangeFTLBS: { min: 4000, max: 4900 },
  effectiveRangeYards: 400,
  maxRangeYards: 4000,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Large Game", "Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".375 Ruger", ".375 Weatherby", "9.3x62mm Mauser"],
  description: "The most famous dangerous game cartridge in the world. Minimum legal caliber for dangerous game in many African countries. Perfect balance of power and shootability.",
  history: "Introduced by London gunmaker Holland & Holland in 1912. Quickly became the standard dangerous game cartridge. Used by virtually every famous African hunter. Its belted case design became the template for most magnum cartridges. Required by law in many African jurisdictions for hunting dangerous game. Over 100 years later, still the gold standard.",
  notableFirearms: ["Winchester Model 70", "Ruger Safari Magnum", "CZ 550", "Mauser M98", "Blaser R8"],
  trivia: "This cartridge has probably killed more elephants, buffalo, and lions than all other cartridges combined. Robert Ruark's famous book 'Use Enough Gun' was about this cartridge. Many countries require .375 minimum for dangerous game."
},

{
  name: ".416 Rigby",
  alternateNames: [".416 Rigby Magnum", "10.6x74mm"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1911,
  inventor: "John Rigby & Company",
  manufacturer: "John Rigby & Company",
  countryOfOrigin: "United Kingdom",
  bulletDiameterInch: 0.416,
  bulletDiameterMM: 10.57,
  baseDiameterInch: 0.590,
  baseDiameterMM: 14.99,
  rimDiameterInch: 0.590,
  rimDiameterMM: 14.99,
  caseLengthInch: 2.900,
  caseLengthMM: 73.66,
  overallLengthInch: 3.750,
  overallLengthMM: 95.25,
  caseCapacityGrains: 110.0,
  maxPressurePSI: 52000,
  commonBulletWeights: [350, 400, 410],
  velocityRangeFPS: { min: 2300, max: 2450 },
  energyRangeFTLBS: { min: 5000, max: 5500 },
  effectiveRangeYards: 300,
  maxRangeYards: 3500,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".416 Remington Magnum", ".416 Weatherby", ".404 Jeffery"],
  description: "Legendary British dangerous game cartridge. Designed specifically for African Big Five. Power without excessive recoil. The aristocrat of dangerous game rounds.",
  history: "Developed by John Rigby & Company in 1911 for hunting African dangerous game. Specifically designed for stopping charging elephants and buffalo. Used extensively during golden age of African safari hunting. The large case operates at moderate pressures for reliable extraction in heat and dust. Fell out of favor mid-20th century but revived in 1980s-90s. Now considered one of the finest dangerous game cartridges.",
  notableFirearms: ["Rigby Highland Stalker", "Dakota Arms Model 76", "Ruger Safari Magnum", "CZ 550", "Mauser M98"],
  trivia: "Harry Selby, one of Africa's most famous professional hunters, used .416 Rigby almost exclusively for 50+ years. He once said it was the only caliber you'd ever need in Africa. Featured prominently in the movie 'The Ghost and the Darkness.'"
},

{
  name: ".505 Gibbs",
  alternateNames: [".505 Magnum Rimless", "12.7x70mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Limited",
  availability: "Scarce",
  yearIntroduced: 1911,
  inventor: "George Gibbs",
  manufacturer: "George Gibbs",
  countryOfOrigin: "United Kingdom",
  bulletDiameterInch: 0.505,
  bulletDiameterMM: 12.83,
  baseDiameterInch: 0.640,
  baseDiameterMM: 16.26,
  rimDiameterInch: 0.640,
  rimDiameterMM: 16.26,
  caseLengthInch: 2.760,
  caseLengthMM: 70.1,
  overallLengthInch: 3.750,
  overallLengthMM: 95.25,
  caseCapacityGrains: 140.0,
  maxPressurePSI: 42000,
  commonBulletWeights: [525, 570, 600],
  velocityRangeFPS: { min: 2150, max: 2300 },
  energyRangeFTLBS: { min: 6800, max: 7500 },
  effectiveRangeYards: 200,
  maxRangeYards: 3000,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".500 Jeffery", ".500 A-Square", ".460 Weatherby"],
  description: "Massive British dangerous game cartridge. Among the most powerful sporting cartridges ever made. For the most dangerous situations in thick bush.",
  history: "Introduced in 1911 by British gunmaker George Gibbs as the ultimate stopping rifle for dangerous game. Designed for close-range encounters with elephant, rhino, and buffalo in thick bush. The huge 500-600 grain bullets at moderate velocity provide incredible penetration and shocking power. Extremely limited production and use even in its heyday. True collector's cartridge today.",
  notableFirearms: ["Gibbs bolt rifles", "Custom Mauser actions", "Modern Heym rifles"],
  trivia: "This cartridge generates over 100 foot-pounds of free recoil energy - more than double a .375 H&H. It's seriously punishing to shoot. Used primarily as a backup rifle by professional hunters when clients wounded dangerous game."
},

{
  name: ".450 Rigby",
  alternateNames: [".450 Rigby Rimless", "11.6x76mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Limited",
  availability: "Scarce",
  yearIntroduced: 1995,
  inventor: "Paul Roberts / John Rigby & Company",
  manufacturer: "John Rigby & Company",
  countryOfOrigin: "United Kingdom",
  parentCase: ".416 Rigby",
  derivedFrom: ".416 Rigby case expanded",
  bulletDiameterInch: 0.458,
  bulletDiameterMM: 11.63,
  baseDiameterInch: 0.590,
  baseDiameterMM: 14.99,
  rimDiameterInch: 0.590,
  rimDiameterMM: 14.99,
  caseLengthInch: 2.992,
  caseLengthMM: 76.0,
  overallLengthInch: 3.750,
  overallLengthMM: 95.25,
  caseCapacityGrains: 115.0,
  maxPressurePSI: 52000,
  commonBulletWeights: [480, 500, 550],
  velocityRangeFPS: { min: 2300, max: 2500 },
  energyRangeFTLBS: { min: 5900, max: 7000 },
  effectiveRangeYards: 250,
  maxRangeYards: 3200,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".458 Lott", ".458 Winchester Magnum", ".460 Weatherby"],
  description: "Modern dangerous game cartridge from prestigious Rigby company. More powerful than .458 Lott with softer recoil than .505 Gibbs. For serious elephant hunters.",
  history: "Introduced in 1995 by Paul Roberts and John Rigby & Company as a modern dangerous game cartridge. Based on .416 Rigby case necked up to .458. Provides power level between .458 Lott and .505 Gibbs with manageable recoil. Uses modern powders and pressures for excellent ballistics. Rare and expensive but growing in popularity among serious African hunters.",
  notableFirearms: ["Rigby Highland Stalker", "Rigby Big Game rifle", "CZ 550", "Custom Mauser actions"],
  trivia: "This is one of the newest 'old school' dangerous game cartridges. It combines traditional British cartridge design with modern ballistics. A Rigby rifle in .450 Rigby costs more than most cars."
},

{
  name: "7x64mm Brenneke",
  alternateNames: ["7x64", "7x64mm"],
  type: "Rifle",
  standardization: "CIP",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1917,
  inventor: "Wilhelm Brenneke",
  manufacturer: "RWS",
  countryOfOrigin: "Germany",
  parentCase: "8x64mm S",
  bulletDiameterInch: 0.284,
  bulletDiameterMM: 7.21,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.95,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.520,
  caseLengthMM: 64.0,
  overallLengthInch: 3.346,
  overallLengthMM: 85.0,
  caseCapacityGrains: 66.0,
  maxPressurePSI: 56000,
  commonBulletWeights: [139, 154, 162, 175],
  velocityRangeFPS: { min: 2800, max: 3100 },
  energyRangeFTLBS: { min: 2900, max: 3400 },
  effectiveRangeYards: 600,
  maxRangeYards: 4200,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".270 Winchester", ".280 Remington", "7mm Remington Magnum"],
  description: "Excellent German hunting cartridge. More powerful than 7x57 Mauser but fits standard Mauser action. Very popular in Europe for red stag and chamois.",
  history: "Developed by Wilhelm Brenneke in 1917 as a powerful 7mm for European game. Designed to provide magnum-like performance in standard-length Mauser actions. Very popular in Germany, Austria, and Scandinavia. Never caught on in America despite excellent performance. Ballistically similar to .280 Remington but predates it by 40 years.",
  notableFirearms: ["Mauser M98", "Sauer 202", "Blaser R93", "Steyr Mannlicher", "Merkel rifles"],
  trivia: "This cartridge does everything .270 Winchester does, but came first and is more popular in Europe. It's proof that geography, not just performance, determines cartridge popularity."
},

{
  name: ".280 Remington",
  alternateNames: ["7mm Express Remington", "7mm-06"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 1957,
  inventor: "Remington Arms",
  manufacturer: "Remington Arms",
  countryOfOrigin: "United States",
  parentCase: ".30-06 Springfield",
  derivedFrom: ".30-06 necked down to 7mm",
  bulletDiameterInch: 0.284,
  bulletDiameterMM: 7.21,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.540,
  caseLengthMM: 64.52,
  overallLengthInch: 3.330,
  overallLengthMM: 84.58,
  caseCapacityGrains: 67.0,
  maxPressurePSI: 60000,
  commonBulletWeights: [140, 150, 160, 168],
  velocityRangeFPS: { min: 2800, max: 3000 },
  energyRangeFTLBS: { min: 2800, max: 3100 },
  effectiveRangeYards: 700,
  maxRangeYards: 4200,
  primaryUse: ["Hunting", "Target"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".270 Winchester", "7mm-08 Remington", "7x64mm Brenneke"],
  description: "Underappreciated 7mm cartridge with excellent ballistics. More powerful than .270 Win with better bullets. The thinking person's deer rifle.",
  history: "Introduced by Remington in 1957 as 7mm Express, renamed .280 Remington in 1979. Created by necking .30-06 case down to 7mm. Poor marketing and competition from .270 Winchester limited adoption. Jack O'Connor, famous outdoor writer, famously dismissed it in favor of .270, hurting its reputation. Actually superior ballistics but never overcame marketing problems.",
  notableFirearms: ["Remington Model 700", "Remington Model 740", "Browning X-Bolt", "Tikka T3x"],
  trivia: "This is one of the best cartridges that nobody uses. It outperforms .270 Winchester and approaches 7mm Rem Mag performance, but Remington's terrible marketing doomed it to also-ran status. It's having a renaissance among knowledgeable hunters."
},

{
  name: ".257 Weatherby Magnum",
  alternateNames: [".257 Wby Mag"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1944,
  inventor: "Roy Weatherby",
  manufacturer: "Weatherby",
  countryOfOrigin: "United States",
  parentCase: ".375 H&H Magnum",
  derivedFrom: ".375 H&H case blown out and necked down",
  bulletDiameterInch: 0.257,
  bulletDiameterMM: 6.53,
  baseDiameterInch: 0.513,
  baseDiameterMM: 13.03,
  rimDiameterInch: 0.532,
  rimDiameterMM: 13.51,
  caseLengthInch: 2.549,
  caseLengthMM: 64.74,
  overallLengthInch: 3.170,
  overallLengthMM: 80.52,
  caseCapacityGrains: 82.0,
  maxPressurePSI: 65000,
  commonBulletWeights: [75, 87, 100, 110, 120],
  velocityRangeFPS: { min: 3400, max: 3825 },
  energyRangeFTLBS: { min: 2500, max: 3300 },
  effectiveRangeYards: 500,
  maxRangeYards: 4500,
  primaryUse: ["Hunting", "Varmint"],
  huntingGameSize: ["Varmint", "Medium Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".25-06 Remington", "6.5-300 Weatherby"],
  description: "Extremely fast and flat-shooting magnum. Roy Weatherby's favorite cartridge. Devastating on deer-sized game at long range. Barrel burner.",
  history: "Developed by Roy Weatherby in 1944 as his first commercial magnum cartridge. Based on blown-out .375 H&H case necked to .257. Weatherby's personal favorite cartridge. Known for exceptional velocity and flat trajectory. Popular with western hunters and long-range shooters. Heavy recoil for a .25 caliber and significant barrel wear, but dramatic performance.",
  notableFirearms: ["Weatherby Mark V", "Weatherby Vanguard", "Custom rifles"],
  trivia: "This cartridge held the record for commercially available velocity for decades. It can push 100-grain bullets over 3,600 fps. Roy Weatherby used it to take game on six continents and called it 'the most useful all-around cartridge.'"
},

{
  name: "6mm Remington",
  alternateNames: [".244 Remington", "6mm Rem"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1955,
  inventor: "Remington Arms",
  manufacturer: "Remington Arms",
  countryOfOrigin: "United States",
  parentCase: "7x57mm Mauser",
  derivedFrom: "7x57mm necked down to 6mm",
  bulletDiameterInch: 0.243,
  bulletDiameterMM: 6.17,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.233,
  caseLengthMM: 56.72,
  overallLengthInch: 2.825,
  overallLengthMM: 71.76,
  caseCapacityGrains: 53.0,
  maxPressurePSI: 62000,
  commonBulletWeights: [75, 87, 95, 100, 105],
  velocityRangeFPS: { min: 3100, max: 3500 },
  energyRangeFTLBS: { min: 2200, max: 2700 },
  effectiveRangeYards: 600,
  maxRangeYards: 4000,
  primaryUse: ["Varmint", "Hunting", "Target"],
  huntingGameSize: ["Varmint", "Medium Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".243 Winchester", "6mm Creedmoor"],
  description: "Fast, flat-shooting 6mm that lost the marketing war to .243 Winchester. Actually superior ballistics but doomed by slow-twist barrels in original rifles.",
  history: "Introduced as .244 Remington in 1955 to compete with Winchester's .243. Initially marketed as varmint cartridge with slow twist barrels that wouldn't stabilize heavier bullets. Winchester's .243 had faster twist and was marketed for deer. Remington lost the competition badly. Renamed 6mm Remington in 1963 with proper twist but damage was done. Excellent cartridge that never recovered from poor initial marketing.",
  notableFirearms: ["Remington Model 700", "Remington Model 742", "Ruger Model 77", "Savage 110"],
  trivia: "This is the cartridge that taught Remington a harsh lesson about marketing. It's actually ballistically superior to .243 Winchester but sold a fraction as many rifles due to Remington's bungled launch."
},

{
  name: ".22-250 Remington",
  alternateNames: [".22 Varminter", ".22-250"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Abundant",
  yearIntroduced: 1965,
  inventor: "J.E. Gebby, J.B. Smith, Grosvenor Wotkyns",
  manufacturer: "Remington Arms (commercial)",
  countryOfOrigin: "United States",
  parentCase: ".250 Savage",
  derivedFrom: ".250 Savage necked down to .22",
  bulletDiameterInch: 0.224,
  bulletDiameterMM: 5.69,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 1.912,
  caseLengthMM: 48.59,
  overallLengthInch: 2.350,
  overallLengthMM: 59.69,
  caseCapacityGrains: 45.0,
  maxPressurePSI: 65000,
  commonBulletWeights: [40, 50, 55, 60, 64],
  velocityRangeFPS: { min: 3600, max: 4000 },
  energyRangeFTLBS: { min: 1300, max: 1800 },
  effectiveRangeYards: 500,
  maxRangeYards: 3500,
  primaryUse: ["Varmint", "Target"],
  huntingGameSize: ["Varmint"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".220 Swift", ".22 Creedmoor", ".223 Remington"],
  description: "Premier varmint cartridge. Started as wildcat, became one of most popular varmint rounds. Extreme velocity and flat trajectory for long-range prairie dog hunting.",
  history: "Originated as wildcat cartridge around 1937 by several gunsmiths, most notably J.E. Gebby. Known as .22 Varminter for decades. Remington finally commercialized it in 1965 as .22-250 Remington. Immediately became dominant varmint cartridge. Can achieve velocities near .220 Swift but from shorter case in standard actions. Extremely popular with prairie dog hunters and long-range varmint shooters.",
  notableFirearms: ["Remington Model 700", "Ruger M77", "Savage 12 F/TR", "Tikka T3x"],
  trivia: "This cartridge existed as a wildcat for nearly 30 years before being commercialized. It's proof that sometimes wildcatters get it right - it became immediately popular and remains one of the top varmint cartridges 60 years later."
},

{
  name: ".204 Ruger",
  alternateNames: [".204"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 2004,
  inventor: "Hornady / Ruger",
  manufacturer: "Hornady",
  countryOfOrigin: "United States",
  parentCase: ".222 Remington Magnum",
  derivedFrom: ".222 Remington Magnum necked down",
  bulletDiameterInch: 0.204,
  bulletDiameterMM: 5.18,
  baseDiameterInch: 0.376,
  baseDiameterMM: 9.55,
  rimDiameterInch: 0.378,
  rimDiameterMM: 9.60,
  caseLengthInch: 1.850,
  caseLengthMM: 46.99,
  overallLengthInch: 2.260,
  overallLengthMM: 57.40,
  caseCapacityGrains: 32.0,
  maxPressurePSI: 62000,
  commonBulletWeights: [24, 32, 40],
  velocityRangeFPS: { min: 3900, max: 4225 },
  energyRangeFTLBS: { min: 1000, max: 1350 },
  effectiveRangeYards: 450,
  maxRangeYards: 3200,
  primaryUse: ["Varmint", "Target"],
  huntingGameSize: ["Varmint"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".17 Remington", ".20 Tactical", ".223 Remington"],
  description: "Extremely fast .20 caliber varmint round. Joint development between Hornady and Ruger. Less wind drift than .17s, flatter than .22s. Perfect prairie dog round.",
  history: "Jointly developed by Hornady and Ruger in 2004 as modern varmint cartridge. Based on .222 Remington Magnum case necked to .204. Designed to provide .220 Swift-like velocity with less powder, barrel wear, and recoil. Quickly gained popularity among varmint hunters. Fills niche between .17 and .22 calibers. Excellent ballistics with minimal recoil and barrel wear.",
  notableFirearms: ["Ruger M77", "Savage Model 12", "CZ 527", "Thompson Center Venture"],
  trivia: "This was the highest velocity factory cartridge for several years after introduction. The 32-grain V-Max load reaches 4,225 fps from a 26-inch barrel. It's the newest successful commercial centerfire rifle cartridge in decades."
},


// ========================================
// ANTI-MATERIAL / LARGE CALIBERS (10)
// Between .50 BMG and .338 Lapua
// ========================================

{
  name: ".416 Barrett",
  alternateNames: [".416 Barrett", "10.6x83mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Active",
  availability: "Limited",
  yearIntroduced: 2005,
  inventor: "Chris Barrett",
  manufacturer: "Barrett Firearms",
  countryOfOrigin: "United States",
  parentCase: ".50 BMG",
  derivedFrom: ".50 BMG necked down to .416",
  bulletDiameterInch: 0.416,
  bulletDiameterMM: 10.57,
  baseDiameterInch: 0.804,
  baseDiameterMM: 20.42,
  rimDiameterInch: 0.804,
  rimDiameterMM: 20.42,
  caseLengthInch: 3.268,
  caseLengthMM: 83.0,
  overallLengthInch: 4.650,
  overallLengthMM: 118.11,
  caseCapacityGrains: 205.0,
  maxPressurePSI: 65000,
  commonBulletWeights: [395, 400, 452],
  velocityRangeFPS: { min: 3000, max: 3250 },
  energyRangeFTLBS: { min: 8200, max: 9800 },
  effectiveRangeYards: 2500,
  maxRangeYards: 7000,
  primaryUse: ["Military", "Target"],
  militaryAdoption: [],
  currentMilitaryUse: ["US military testing (limited)"],
  lawEnforcementUse: false,
  similarCartridges: [".408 CheyTac", ".50 BMG", ".338 Lapua Magnum"],
  description: "Extreme long-range precision cartridge. Less recoil than .50 BMG with better ballistics. Developed for anti-material and extreme long-range shooting.",
  history: "Developed by Barrett Firearms in 2005 as alternative to .50 BMG with better ballistic coefficient and less recoil. Designed for the Barrett M98B rifle. Provides .50 BMG-class energy with .338 Lapua-class recoil. Used for extreme long-range precision shooting and military testing. Better ballistic coefficient than .50 BMG means less wind drift at extreme ranges.",
  notableFirearms: ["Barrett M98B", "Barrett MRAD"],
  trivia: "This cartridge holds several extreme long-range records. The high BC .416 bullets experience significantly less wind drift than .50 BMG at ranges beyond 1,500 yards, making it more accurate for extreme precision work."
},

{
  name: ".408 CheyTac",
  alternateNames: [".408 CT", "10.3x77mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Active",
  availability: "Limited",
  yearIntroduced: 2001,
  inventor: "Dr. John Taylor / William Wordman",
  manufacturer: "CheyTac LLC",
  countryOfOrigin: "United States",
  parentCase: ".505 Gibbs",
  derivedFrom: ".505 Gibbs case modified and necked down",
  bulletDiameterInch: 0.408,
  bulletDiameterMM: 10.36,
  baseDiameterInch: 0.672,
  baseDiameterMM: 17.07,
  rimDiameterInch: 0.640,
  rimDiameterMM: 16.26,
  caseLengthInch: 3.035,
  caseLengthMM: 77.09,
  overallLengthInch: 4.730,
  overallLengthMM: 120.14,
  caseCapacityGrains: 148.0,
  maxPressurePSI: 65000,
  commonBulletWeights: [305, 419, 450],
  velocityRangeFPS: { min: 2850, max: 3050 },
  energyRangeFTLBS: { min: 7600, max: 8900 },
  effectiveRangeYards: 2500,
  maxRangeYards: 6500,
  primaryUse: ["Military", "Target"],
  militaryAdoption: [],
  currentMilitaryUse: ["Various special forces (limited)"],
  lawEnforcementUse: false,
  similarCartridges: [".416 Barrett", ".375 CheyTac", ".338 Lapua Magnum"],
  description: "Ultra long-range precision cartridge. Designed for 2,000+ yard shots. Extremely high ballistic coefficient bullets for minimal wind drift.",
  history: "Developed in 2001 by CheyTac Associates for extreme long-range precision shooting. Part of complete Intervention weapon system including rifle, ammunition, and ballistic computer. Specifically designed for consistent accuracy beyond 2,000 yards. The .408 diameter was chosen for optimal balance of BC, sectional density, and manageable recoil. Used for extreme long-range military sniping and competition.",
  notableFirearms: ["CheyTac M200 Intervention", "EDM Arms Windrunner", "Desert Tech HTI"],
  trivia: "This cartridge was used to set multiple extreme long-range records. A .408 CheyTac rifle made a confirmed hit at 2,850 yards in Afghanistan. The Intervention system can calculate ballistics for shots beyond 3,000 yards."
},

{
  name: ".375 CheyTac",
  alternateNames: [".375 CT", "9.5x77mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Active",
  availability: "Scarce",
  yearIntroduced: 2002,
  inventor: "Dr. John Taylor / CheyTac",
  manufacturer: "CheyTac LLC",
  countryOfOrigin: "United States",
  parentCase: ".408 CheyTac",
  derivedFrom: ".408 CheyTac necked down",
  bulletDiameterInch: 0.375,
  bulletDiameterMM: 9.53,
  baseDiameterInch: 0.672,
  baseDiameterMM: 17.07,
  rimDiameterInch: 0.640,
  rimDiameterMM: 16.26,
  caseLengthInch: 3.035,
  caseLengthMM: 77.09,
  overallLengthInch: 4.650,
  overallLengthMM: 118.11,
  caseCapacityGrains: 145.0,
  maxPressurePSI: 65000,
  commonBulletWeights: [325, 350, 400],
  velocityRangeFPS: { min: 2900, max: 3100 },
  energyRangeFTLBS: { min: 7000, max: 8500 },
  effectiveRangeYards: 2300,
  maxRangeYards: 6000,
  primaryUse: ["Target", "Military"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".408 CheyTac", ".375 Snipetac", ".338 Lapua Magnum"],
  description: "Smaller sibling of .408 CheyTac. Less recoil with still extreme long-range capability. Excellent ballistic coefficient for precision shooting.",
  history: "Developed by CheyTac in 2002 as a lighter-recoiling alternative to .408 CheyTac. Necking down .408 to .375 provided better barrel life and less recoil while maintaining extreme range capability. Less popular than .408 but used by some precision shooters who want less recoil. Provides ballistic performance between .338 Lapua and .408 CheyTac.",
  notableFirearms: ["CheyTac M200 Intervention", "EDM Arms Windrunner", "Custom long-range rifles"],
  trivia: "This cartridge represents the sweet spot between .338 Lapua and .408 CheyTac for many precision shooters. It offers 80% of .408's capability with significantly less recoil and barrel wear."
},

{
  name: ".460 Steyr",
  alternateNames: [".460 Steyr Magnum", "11.7x70mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Obsolete",
  availability: "Collector Only",
  yearIntroduced: 1990,
  inventor: "Steyr Mannlicher",
  manufacturer: "Steyr Mannlicher",
  countryOfOrigin: "Austria",
  bulletDiameterInch: 0.458,
  bulletDiameterMM: 11.63,
  baseDiameterInch: 0.540,
  baseDiameterMM: 13.72,
  rimDiameterInch: 0.540,
  rimDiameterMM: 13.72,
  caseLengthInch: 2.756,
  caseLengthMM: 70.0,
  overallLengthInch: 3.346,
  overallLengthMM: 85.0,
  caseCapacityGrains: 115.0,
  maxPressurePSI: 60000,
  commonBulletWeights: [500, 550],
  velocityRangeFPS: { min: 2300, max: 2500 },
  energyRangeFTLBS: { min: 6000, max: 7500 },
  effectiveRangeYards: 300,
  maxRangeYards: 3500,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".458 Lott", ".450 Rigby", ".460 Weatherby"],
  description: "Short-lived Austrian dangerous game cartridge. Designed for Steyr's Scout rifle concept applied to dangerous game. Powerful but commercial failure.",
  history: "Introduced by Steyr Mannlicher in 1990 as modern dangerous game cartridge. Used in the Steyr HS .460 rifle, a unique dangerous game rifle with forward-mounted scope. Designed to provide .458 Lott-class power in compact package. Commercial failure due to high cost and limited rifle availability. Discontinued in late 1990s. Rare and collectible today.",
  notableFirearms: ["Steyr HS .460"],
  trivia: "This cartridge was chambered in one of the most unusual dangerous game rifles ever made - the Steyr HS .460 had a forward-mounted scout scope for dangerous game hunting. Jeff Cooper called it interesting but it never caught on."
},

{
  name: "14.5x114mm Soviet",
  alternateNames: ["14.5x114mm", "14.5 Soviet"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Active",
  availability: "Military Surplus",
  yearIntroduced: 1939,
  inventor: "Soviet Ordnance",
  manufacturer: "Tula Arsenal",
  countryOfOrigin: "Soviet Union",
  bulletDiameterInch: 0.571,
  bulletDiameterMM: 14.5,
  baseDiameterInch: 1.030,
  baseDiameterMM: 26.16,
  rimDiameterInch: 1.102,
  rimDiameterMM: 28.0,
  caseLengthInch: 4.488,
  caseLengthMM: 114.0,
  overallLengthInch: 5.984,
  overallLengthMM: 152.0,
  caseCapacityGrains: 340.0,
  maxPressurePSI: 52000,
  commonBulletWeights: [978, 1000],
  velocityRangeFPS: { min: 3250, max: 3350 },
  energyRangeFTLBS: { min: 22000, max: 24000 },
  effectiveRangeYards: 2000,
  maxRangeYards: 8000,
  primaryUse: ["Military"],
  militaryAdoption: [
    { country: "Soviet Union/Russia", years: "1939-present", conflicts: ["WWII", "Cold War", "Afghanistan", "Chechnya"] },
    { country: "China", years: "1950s-present", conflicts: ["Korean War", "Vietnam War"] }
  ],
  currentMilitaryUse: ["Russia", "China", "Former Soviet states", "40+ nations"],
  lawEnforcementUse: false,
  similarCartridges: [".50 BMG", "12.7x108mm Soviet"],
  description: "Massive Soviet anti-material cartridge. More powerful than .50 BMG. Used in heavy machine guns and anti-material rifles for destroying vehicles and equipment.",
  history: "Developed in 1939 for Soviet heavy machine guns and anti-tank rifles. Designed to penetrate armor and destroy light vehicles. Used extensively in WWII in PTRD and PTRS anti-tank rifles. Continued use in KPV heavy machine gun. Still in widespread military service as anti-material and anti-aircraft round. More powerful than .50 BMG but less common internationally.",
  notableFirearms: ["PTRD-41", "PTRS-41", "KPV heavy machine gun", "Modern anti-material rifles"],
  trivia: "This cartridge generates over 24,000 ft-lbs of energy - about 50% more than .50 BMG. It's powerful enough to disable light armored vehicles. The recoil is absolutely punishing in shoulder-fired weapons."
},

{
  name: "12.7x108mm Soviet",
  alternateNames: ["12.7x108mm", "12.7 Soviet", ".50 Russian"],
  type: "Rifle",
  standardization: "Military",
  productionStatus: "Active",
  availability: "Military Surplus",
  yearIntroduced: 1934,
  inventor: "Soviet Ordnance",
  manufacturer: "Tula Arsenal",
  countryOfOrigin: "Soviet Union",
  bulletDiameterInch: 0.511,
  bulletDiameterMM: 12.98,
  baseDiameterInch: 0.860,
  baseDiameterMM: 21.84,
  rimDiameterInch: 0.894,
  rimDiameterMM: 22.7,
  caseLengthInch: 4.252,
  caseLengthMM: 108.0,
  overallLengthInch: 5.787,
  overallLengthMM: 147.0,
  caseCapacityGrains: 240.0,
  maxPressurePSI: 52000,
  commonBulletWeights: [745, 800, 850],
  velocityRangeFPS: { min: 2750, max: 2850 },
  energyRangeFTLBS: { min: 13500, max: 14500 },
  effectiveRangeYards: 2000,
  maxRangeYards: 7500,
  primaryUse: ["Military"],
  militaryAdoption: [
    { country: "Soviet Union/Russia", years: "1934-present", conflicts: ["WWII", "Cold War", "Afghanistan", "Chechnya", "Ukraine"] },
    { country: "China", years: "1950s-present", conflicts: ["Korean War", "Vietnam War"] }
  ],
  currentMilitaryUse: ["Russia", "China", "Former Soviet states", "50+ nations"],
  lawEnforcementUse: false,
  similarCartridges: [".50 BMG", "14.5x114mm Soviet"],
  description: "Soviet equivalent to .50 BMG. Standard heavy machine gun and sniper rifle cartridge for Russian military. Extremely powerful anti-material round.",
  history: "Developed in 1934 for Soviet heavy machine guns and anti-aircraft weapons. Similar role to American .50 BMG. Used in famous DShK heavy machine gun. Saw extensive combat in WWII and every Soviet/Russian conflict since. Currently used in OSV-96 and KSVK sniper rifles. Slightly shorter but fatter case than .50 BMG. Not interchangeable despite similar bore diameter.",
  notableFirearms: ["DShK heavy machine gun", "NSV heavy machine gun", "OSV-96 sniper rifle", "KSVK sniper rifle"],
  trivia: "This cartridge and .50 BMG are roughly equivalent but NOT interchangeable. The Soviet round is slightly larger in diameter. During the Cold War, each superpower had its own .50 caliber standard."
},

{
  name: ".510 DTC EUROP",
  alternateNames: [".510 DTC", "12.95x99mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Limited",
  availability: "Scarce",
  yearIntroduced: 2003,
  inventor: "Dan Geissele",
  manufacturer: "DTC (Defense Technology Corporation)",
  countryOfOrigin: "France/United States",
  parentCase: ".50 BMG",
  derivedFrom: ".50 BMG rebated and modified",
  bulletDiameterInch: 0.510,
  bulletDiameterMM: 12.95,
  baseDiameterInch: 0.800,
  baseDiameterMM: 20.32,
  rimDiameterInch: 0.804,
  rimDiameterMM: 20.42,
  caseLengthInch: 3.898,
  caseLengthMM: 99.0,
  overallLengthInch: 5.780,
  overallLengthMM: 146.8,
  caseCapacityGrains: 235.0,
  maxPressurePSI: 55000,
  commonBulletWeights: [750, 800],
  velocityRangeFPS: { min: 2800, max: 3000 },
  energyRangeFTLBS: { min: 13000, max: 15000 },
  effectiveRangeYards: 2500,
  maxRangeYards: 7500,
  primaryUse: ["Military", "Target"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".50 BMG", ".416 Barrett", "12.7x108mm Soviet"],
  description: "European alternative to .50 BMG. Developed to comply with French restrictions on military-caliber ammunition. Slightly different dimensions avoid legal issues.",
  history: "Developed in 2003 to circumvent European regulations prohibiting civilian ownership of military-caliber ammunition. By changing dimensions slightly from .50 BMG, it became legally distinct. Popular in France and other European countries with .50 BMG restrictions. Ballistically very similar to .50 BMG. Allows European shooters and manufacturers to work with .50-caliber-class cartridges legally.",
  notableFirearms: ["PGM Hecate II", "Accuracy International AX50 ELR", "European anti-material rifles"],
  trivia: "This cartridge exists purely due to legal restrictions. It's proof that gun designers will always find workarounds to regulations. Performance is nearly identical to .50 BMG but it's technically not a military cartridge."
},

{
  name: ".50 Beowulf",
  alternateNames: ["12.7x42mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 2001,
  inventor: "Bill Alexander",
  manufacturer: "Alexander Arms",
  countryOfOrigin: "United States",
  parentCase: ".50 AE",
  derivedFrom: ".50 Action Express modified",
  bulletDiameterInch: 0.500,
  bulletDiameterMM: 12.7,
  baseDiameterInch: 0.445,
  baseDiameterMM: 11.3,
  rimDiameterInch: 0.445,
  rimDiameterMM: 11.3,
  caseLengthInch: 1.650,
  caseLengthMM: 41.91,
  overallLengthInch: 2.250,
  overallLengthMM: 57.15,
  caseCapacityGrains: 38.0,
  maxPressurePSI: 33000,
  commonBulletWeights: [300, 325, 350, 400],
  velocityRangeFPS: { min: 1700, max: 2000 },
  energyRangeFTLBS: { min: 2200, max: 2900 },
  effectiveRangeYards: 200,
  maxRangeYards: 1500,
  primaryUse: ["Hunting", "Self Defense"],
  huntingGameSize: ["Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: true,
  similarCartridges: [".458 SOCOM", ".450 Bushmaster", ".499 LWR"],
  description: "Big-bore AR-15 cartridge for hunting and close-range power. Designed to chamber in standard AR-15 with minimal modifications. Devastating stopping power.",
  history: "Developed by Bill Alexander in 2001 specifically for AR-15 platform. Named after the legendary warrior Beowulf. Designed to provide big-game hunting power and barrier-penetration capability in AR-15. Uses standard AR-15 bolt face and magazines (though reduced capacity). Popular for hog hunting, home defense, and close-range hunting. Competes with .458 SOCOM and .450 Bushmaster in AR-15 big-bore market.",
  notableFirearms: ["Alexander Arms AR-15 rifles", "Various AR-15 uppers", "Custom AR builds"],
  trivia: "This cartridge can launch a 400-grain bullet from an AR-15 - that's the same bullet weight as .45-70 Government from a lever action. The recoil in a lightweight AR-15 is substantial but controllable."
},

{
  name: ".458 SOCOM",
  alternateNames: [".458 SOCOM", "11.6x40mm"],
  type: "Rifle",
  standardization: "Proprietary",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 2001,
  inventor: "Marty ter Weeme / Tony Rumore",
  manufacturer: "Teppo Jutsu LLC",
  countryOfOrigin: "United States",
  parentCase: ".50 AE",
  derivedFrom: ".50 Action Express shortened and modified",
  bulletDiameterInch: 0.458,
  bulletDiameterMM: 11.63,
  baseDiameterInch: 0.473,
  baseDiameterMM: 12.01,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 1.575,
  caseLengthMM: 40.0,
  overallLengthInch: 2.260,
  overallLengthMM: 57.4,
  caseCapacityGrains: 36.0,
  maxPressurePSI: 35000,
  commonBulletWeights: [250, 300, 350, 400, 500],
  velocityRangeFPS: { min: 1600, max: 2050 },
  energyRangeFTLBS: { min: 2000, max: 3000 },
  effectiveRangeYards: 250,
  maxRangeYards: 1500,
  primaryUse: ["Military", "Hunting", "Self Defense"],
  huntingGameSize: ["Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: ["US SOCOM (very limited testing)"],
  lawEnforcementUse: true,
  similarCartridges: [".50 Beowulf", ".450 Bushmaster", ".45 Raptor"],
  description: "Big-bore AR-15 cartridge developed at request of US Special Operations Command. Extreme close-range stopping power and barrier penetration in standard AR-15 platform.",
  history: "Developed in 2001 at the request of US Special Operations Command who wanted more stopping power than 5.56mm for close quarters battle. Designed to fit AR-15 platform with minimal modifications. Uses standard AR bolt face. Can load 10 rounds in standard 30-round magazine. Popular for hog hunting, dangerous game backup, and home defense. Competes with .50 Beowulf and .450 Bushmaster.",
  notableFirearms: ["AR-15 rifles and uppers", "Rock River Arms LAR-458", "Various custom AR builds"],
  trivia: "SOCOM reportedly wanted something that could stop a threat with one shot even through intermediate barriers like car doors and walls. The .458 SOCOM delivers .45-70-class energy from a semi-automatic AR-15."
},

{
  name: ".450 Bushmaster",
  alternateNames: [".450 BM", "11.5x43mm"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 2007,
  inventor: "Tim LeGendre / Bushmaster",
  manufacturer: "Bushmaster / Hornady",
  countryOfOrigin: "United States",
  parentCase: ".284 Winchester",
  derivedFrom: ".284 Winchester case shortened and enlarged",
  bulletDiameterInch: 0.452,
  bulletDiameterMM: 11.48,
  baseDiameterInch: 0.500,
  baseDiameterMM: 12.7,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 1.700,
  caseLengthMM: 43.18,
  overallLengthInch: 2.260,
  overallLengthMM: 57.4,
  caseCapacityGrains: 45.0,
  maxPressurePSI: 38500,
  commonBulletWeights: [245, 250, 260, 300],
  velocityRangeFPS: { min: 2100, max: 2300 },
  energyRangeFTLBS: { min: 2400, max: 2900 },
  effectiveRangeYards: 250,
  maxRangeYards: 1800,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".458 SOCOM", ".50 Beowulf", ".45-70 Government"],
  description: "SAAMI-standardized big-bore AR-15 cartridge. Legal for deer hunting in many straight-wall-only states. Most commercially successful large-bore AR cartridge.",
  history: "Originally developed by Tim LeGendre and licensed to Bushmaster in 2007. Commercialized with Hornady ammunition support. SAAMI standardization gave it advantage over proprietary competitors. Became very popular when several Midwestern states legalized straight-wall cartridges for deer hunting. Ohio, Indiana, and Michigan hunters embraced it. Most commercially successful of the AR-15 big-bore cartridges.",
  notableFirearms: ["Ruger AR-556", "Bushmaster AR-15", "CVA Scout rifle", "Various AR-15 uppers"],
  trivia: "This cartridge's popularity exploded when states like Ohio and Michigan legalized straight-wall rifle cartridges for deer hunting. It's now the most popular big-bore AR-15 cartridge and outsells .458 SOCOM and .50 Beowulf combined."
},


// ========================================
// WILDCAT CARTRIDGES - HISTORICALLY SIGNIFICANT (10)
// ========================================

{
  name: ".35 Whelen",
  alternateNames: [".35 Whelen Improved", "9x63mm"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1922,
  inventor: "James Howe / Col. Townsend Whelen",
  manufacturer: "Remington (commercial)",
  countryOfOrigin: "United States",
  parentCase: ".30-06 Springfield",
  derivedFrom: ".30-06 Springfield necked up to .35",
  bulletDiameterInch: 0.358,
  bulletDiameterMM: 9.09,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.494,
  caseLengthMM: 63.35,
  overallLengthInch: 3.340,
  overallLengthMM: 84.84,
  caseCapacityGrains: 68.0,
  maxPressurePSI: 62000,
  commonBulletWeights: [180, 200, 225, 250],
  velocityRangeFPS: { min: 2400, max: 2750 },
  energyRangeFTLBS: { min: 2900, max: 3500 },
  effectiveRangeYards: 400,
  maxRangeYards: 3800,
  primaryUse: ["Hunting"],
  huntingGameSize: ["Medium Game", "Large Game", "Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".338-06", "9.3x62mm Mauser", ".350 Remington Magnum"],
  description: "Classic wildcat-turned-commercial medium-bore. Legendary brush gun and bear cartridge. .30-06 power in larger diameter. Perfect for big timber hunting.",
  history: "Developed as wildcat in 1922 by James Howe and named after Col. Townsend Whelen. Gained cult following among hunters for its power and moderate recoil. Remained wildcat for 65 years until Remington commercialized it in 1988. Famous quote: 'The .30-06 is never a mistake.' Response: 'Only a .35 Whelen is better.' Popular in Alaska and Canadian bush for big bears.",
  notableFirearms: ["Remington Model 700", "Remington 760", "Ruger Hawkeye", "Custom Mauser conversions"],
  trivia: "This cartridge was named after Col. Townsend Whelen, but he didn't actually develop it - James Howe did. Whelen was so famous that Howe named it after him anyway. It remained a wildcat for 66 years before commercialization."
},

{
  name: ".257 Roberts",
  alternateNames: [".257 Bob", "6.5x57mm Roberts"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1934,
  inventor: "Ned Roberts / A.O. Niedner",
  manufacturer: "Remington (commercial)",
  countryOfOrigin: "United States",
  parentCase: "7x57mm Mauser",
  derivedFrom: "7x57mm Mauser necked down to .25",
  bulletDiameterInch: 0.257,
  bulletDiameterMM: 6.53,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.233,
  caseLengthMM: 56.72,
  overallLengthInch: 2.780,
  overallLengthMM: 70.61,
  caseCapacityGrains: 56.0,
  maxPressurePSI: 54000,
  commonBulletWeights: [87, 100, 110, 117, 120],
  velocityRangeFPS: { min: 2800, max: 3150 },
  energyRangeFTLBS: { min: 2200, max: 2700 },
  effectiveRangeYards: 500,
  maxRangeYards: 4000,
  primaryUse: ["Hunting", "Target"],
  huntingGameSize: ["Varmint", "Medium Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".25-06 Remington", "6.5x55mm Swedish"],
  description: "Classic quarter-bore beloved by riflemen. Perfect deer and antelope cartridge. Mild recoil with flat trajectory. 'Bob' to its friends.",
  history: "Originated as wildcat in 1920s by Ned Roberts and A.O. Niedner, necking down 7x57 Mauser. Remington commercialized in 1934. Unfortunately, Remington used conservative loads due to weak surplus Mauser actions on market, neutering its performance. Proper handloads or +P ammunition show its true potential. Never achieved massive popularity but has devoted following. One of the most beloved wildcats-turned-commercial.",
  notableFirearms: ["Remington Model 700", "Ruger M77", "Browning X-Bolt", "Kimber 84M"],
  trivia: "Factory .257 Roberts ammo is significantly downloaded because Remington feared liability from weak surplus military Mausers. Handloaders and modern rifles can safely achieve much better performance. It's fast becoming a forgotten classic."
},

{
  name: "6mm-284",
  alternateNames: ["6-284 Winchester", "6mm-284 Win"],
  type: "Rifle",
  standardization: "Wildcat",
  productionStatus: "Limited",
  availability: "Scarce",
  yearIntroduced: 1960s,
  inventor: "Benchrest shooters",
  countryOfOrigin: "United States",
  parentCase: ".284 Winchester",
  derivedFrom: ".284 Winchester necked down to 6mm",
  bulletDiameterInch: 0.243,
  bulletDiameterMM: 6.17,
  baseDiameterInch: 0.501,
  baseDiameterMM: 12.73,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.170,
  caseLengthMM: 55.12,
  overallLengthInch: 2.800,
  overallLengthMM: 71.12,
  caseCapacityGrains: 66.0,
  maxPressurePSI: 62000,
  commonBulletWeights: [80, 95, 105, 107, 115],
  velocityRangeFPS: { min: 3200, max: 3500 },
  energyRangeFTLBS: { min: 2500, max: 3100 },
  effectiveRangeYards: 800,
  maxRangeYards: 4200,
  primaryUse: ["Competition", "Target"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["6mm Creedmoor", "6.5-284 Norma", ".243 Winchester"],
  modernEquivalent: "6mm Creedmoor",
  description: "Legendary benchrest and long-range competition wildcat. Dominated 1000-yard competition for decades. Extreme accuracy with high velocity. Barrel burner.",
  history: "Developed in 1960s by benchrest shooters seeking extreme accuracy. Necking .284 Winchester to 6mm created high-velocity, high-capacity case in short action. Dominated long-range competition for 30+ years. Never commercialized but remained popular wildcat. Inspired development of 6.5-284 Norma. The 6mm Creedmoor is essentially a commercial version of this concept. Still used by some long-range competitors.",
  notableFirearms: ["Custom benchrest rifles", "Custom long-range competition rifles"],
  trivia: "This wildcat dominated 1000-yard benchrest competition so thoroughly that many ranges' record boards were filled with it. Barrel life is only 800-1200 rounds due to extreme powder capacity and velocity."
},

{
  name: ".280 Ackley Improved",
  alternateNames: [".280 AI", ".280 Rem AI"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1960s,
  inventor: "P.O. Ackley",
  manufacturer: "Nosler (commercial)",
  countryOfOrigin: "United States",
  parentCase: ".280 Remington",
  derivedFrom: ".280 Remington with 40-degree shoulder and less taper",
  bulletDiameterInch: 0.284,
  bulletDiameterMM: 7.21,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.540,
  caseLengthMM: 64.52,
  overallLengthInch: 3.330,
  overallLengthMM: 84.58,
  caseCapacityGrains: 71.0,
  maxPressurePSI: 63000,
  commonBulletWeights: [140, 150, 160, 168],
  velocityRangeFPS: { min: 2900, max: 3100 },
  energyRangeFTLBS: { min: 2950, max: 3300 },
  effectiveRangeYards: 700,
  maxRangeYards: 4300,
  primaryUse: ["Hunting", "Target"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".280 Remington", "7mm Remington Magnum", ".270 Winchester"],
  description: "Improved .280 Remington with more powder capacity. Approaches 7mm Rem Mag performance without magnum recoil or barrel wear. Finally SAAMI standardized by Nosler.",
  history: "Created by legendary wildcatter P.O. Ackley by fire-forming .280 Remington brass to 40-degree shoulder with less body taper. Increases powder capacity by ~6%. Wildcat for 45+ years until Nosler commercialized it in 2007 and achieved SAAMI standardization. Provides 7mm Rem Mag ballistics with standard-length action and less powder. Growing in popularity.",
  notableFirearms: ["Nosler M48", "Kimber 8400", "Montana Rifle Company", "Custom rifles"],
  trivia: "P.O. Ackley 'improved' dozens of cartridges, but this is probably his most successful design. It sat as a wildcat for over 40 years before Nosler finally commercialized it. Now you can buy factory rifles and ammo."
},

{
  name: ".30-06 Ackley Improved",
  alternateNames: [".30-06 AI", "30-06 Improved"],
  type: "Rifle",
  standardization: "Wildcat",
  productionStatus: "Limited",
  availability: "Scarce",
  yearIntroduced: 1960s,
  inventor: "P.O. Ackley",
  countryOfOrigin: "United States",
  parentCase: ".30-06 Springfield",
  derivedFrom: ".30-06 Springfield with 40-degree shoulder and minimal taper",
  bulletDiameterInch: 0.308,
  bulletDiameterMM: 7.82,
  baseDiameterInch: 0.471,
  baseDiameterMM: 11.96,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.494,
  caseLengthMM: 63.35,
  overallLengthInch: 3.340,
  overallLengthMM: 84.84,
  caseCapacityGrains: 72.0,
  maxPressurePSI: 62000,
  commonBulletWeights: [150, 165, 168, 180, 200],
  velocityRangeFPS: { min: 2800, max: 3050 },
  energyRangeFTLBS: { min: 2900, max: 3300 },
  effectiveRangeYards: 800,
  maxRangeYards: 4300,
  primaryUse: ["Hunting", "Target"],
  huntingGameSize: ["Medium Game", "Large Game", "Dangerous Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".30-06 Springfield", ".300 Winchester Magnum"],
  description: "Improved version of legendary .30-06. Gains 150-200 fps over standard .30-06. Still just a wildcat but popular among custom rifle builders and handloaders.",
  history: "Created by P.O. Ackley by fire-forming .30-06 brass to minimum body taper and 40-degree shoulder. Increases powder capacity ~6-7%. Never commercialized but remains popular wildcat. Standard .30-06 ammo can be fired to form cases. Provides significant velocity increase over standard .30-06 with same pressures. Popular with custom rifle builders and serious handloaders.",
  notableFirearms: ["Custom rifles", "Re-chambered military Mausers", "Rebarreled sporters"],
  trivia: "Why improve the perfect cartridge? Because wildcatters can't leave well enough alone! This adds 150-200 fps to .30-06 performance, which is significant. It's popular enough that reamer makers keep it in stock."
},

{
  name: "6.5-284 Norma",
  alternateNames: ["6.5-284", "6.5x284"],
  type: "Rifle",
  standardization: "Wildcat",
  productionStatus: "Active",
  availability: "Moderate",
  yearIntroduced: 1960s,
  inventor: "Wildcatters",
  manufacturer: "Norma (commercial ammunition)",
  countryOfOrigin: "United States/Sweden",
  parentCase: ".284 Winchester",
  derivedFrom: ".284 Winchester necked down to 6.5mm",
  bulletDiameterInch: 0.264,
  bulletDiameterMM: 6.71,
  baseDiameterInch: 0.501,
  baseDiameterMM: 12.73,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.170,
  caseLengthMM: 55.12,
  overallLengthInch: 2.800,
  overallLengthMM: 71.12,
  caseCapacityGrains: 66.0,
  maxPressurePSI: 60000,
  commonBulletWeights: [120, 130, 140, 143, 147],
  velocityRangeFPS: { min: 2900, max: 3200 },
  energyRangeFTLBS: { min: 2600, max: 3200 },
  effectiveRangeYards: 1200,
  maxRangeYards: 4500,
  primaryUse: ["Competition", "Target", "Hunting"],
  huntingGameSize: ["Medium Game", "Large Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: ["6.5 Creedmoor", "6.5 PRC", ".260 Remington"],
  modernEquivalent: "6.5 PRC",
  description: "Legendary long-range competition wildcat. Dominated 1000-yard competition before 6.5 Creedmoor. More powder capacity than Creedmoor but requires long action. Still competitive.",
  history: "Developed in 1960s by necking .284 Winchester to 6.5mm. Quickly became dominant in long-range competition. Swedish ammunition maker Norma began producing factory ammunition in 1990s. Never achieved full SAAMI standardization but widely used. Dominated 1000-yard competition until 6.5 Creedmoor's introduction. Offers more velocity than Creedmoor but requires long action. Still very popular in F-Class and long-range hunting.",
  notableFirearms: ["Custom long-range rifles", "Competition precision rifles", "High-end hunting rifles"],
  trivia: "This wildcat was so successful that major ammunition manufacturers made factory loads despite never being SAAMI standardized. It held more 1000-yard shooting records than any other cartridge before 6.5 Creedmoor arrived."
},

{
  name: ".22 K-Hornet",
  alternateNames: [".22 K Hornet", ".22 Kilbourn Hornet"],
  type: "Rifle",
  standardization: "Wildcat",
  productionStatus: "Limited",
  availability: "Scarce",
  yearIntroduced: 1940s,
  inventor: "Lysle Kilbourn",
  countryOfOrigin: "United States",
  parentCase: ".22 Hornet",
  derivedFrom: ".22 Hornet blown out with sharper shoulder",
  bulletDiameterInch: 0.224,
  bulletDiameterMM: 5.69,
  baseDiameterInch: 0.350,
  baseDiameterMM: 8.89,
  rimDiameterInch: 0.350,
  rimDiameterMM: 8.89,
  caseLengthInch: 1.403,
  caseLengthMM: 35.64,
  overallLengthInch: 1.723,
  overallLengthMM: 43.76,
  caseCapacityGrains: 13.5,
  maxPressurePSI: 46000,
  commonBulletWeights: [35, 40, 45, 50],
  velocityRangeFPS: { min: 2800, max: 3150 },
  energyRangeFTLBS: { min: 650, max: 950 },
  effectiveRangeYards: 250,
  maxRangeYards: 2000,
  primaryUse: ["Varmint", "Target"],
  huntingGameSize: ["Varmint"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".22 Hornet", ".17 Ackley Hornet", ".218 Bee"],
  description: "Improved .22 Hornet with more powder capacity. Gains 200+ fps over standard Hornet. Perfect small varmint cartridge with minimal report and recoil.",
  history: "Developed by Lysle Kilbourn in 1940s by fire-forming .22 Hornet brass to sharper shoulder angle and less body taper. Increases powder capacity significantly over standard Hornet. Provides noticeable velocity increase with same barrel length. Can be formed by firing standard .22 Hornet ammunition in K-Hornet chamber. Popular among handloaders and small rifle enthusiasts. Never commercialized but remains cult favorite.",
  notableFirearms: ["Custom single-shot rifles", "Rebarreled bolt actions", "Contender pistols"],
  trivia: "This is the cartridge that proved you could improve even tiny cartridges. The velocity gain over standard .22 Hornet is dramatic considering the case size. It's kept alive by dedicated small-caliber enthusiasts."
},

{
  name: ".17 Ackley Hornet",
  alternateNames: [".17 AH", ".17 Ackley Bee"],
  type: "Rifle",
  standardization: "Wildcat",
  productionStatus: "Limited",
  availability: "Collector Only",
  yearIntroduced: 1960s,
  inventor: "P.O. Ackley",
  countryOfOrigin: "United States",
  parentCase: ".22 Hornet",
  derivedFrom: ".22 K-Hornet necked down to .17",
  bulletDiameterInch: 0.172,
  bulletDiameterMM: 4.37,
  baseDiameterInch: 0.350,
  baseDiameterMM: 8.89,
  rimDiameterInch: 0.350,
  rimDiameterMM: 8.89,
  caseLengthInch: 1.403,
  caseLengthMM: 35.64,
  overallLengthInch: 1.723,
  overallLengthMM: 43.76,
  caseCapacityGrains: 13.5,
  maxPressurePSI: 46000,
  commonBulletWeights: [20, 25],
  velocityRangeFPS: { min: 3600, max: 3900 },
  energyRangeFTLBS: { min: 650, max: 800 },
  effectiveRangeYards: 200,
  maxRangeYards: 1800,
  primaryUse: ["Varmint", "Target"],
  huntingGameSize: ["Varmint"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".17 Hornet", ".17 Mach 2", ".22 K-Hornet"],
  modernEquivalent: ".17 Hornet",
  description: "Tiny wildcat with extreme velocity. P.O. Ackley's experiment with .17 caliber. Inspired modern .17 Hornet. Devastating on small varmints at close range.",
  history: "Created by P.O. Ackley in 1960s by necking down .22 K-Hornet to .17 caliber. One of the earliest successful .17 caliber wildcats. Extremely difficult to form brass and load. Demonstrated viability of .17 caliber centerfire cartridges. Largely forgotten after Hornady introduced commercial .17 Hornet in 2012. Historical significance as precursor to modern .17 caliber cartridges.",
  notableFirearms: ["Custom single-shot rifles", "Specialized varmint rifles"],
  trivia: "P.O. Ackley experimented with this in the 1960s when .17 caliber bullets were nearly impossible to find. It took another 50 years for the commercial .17 Hornet to vindicate his vision. Case forming was so difficult that few shooters ever tried it."
},

{
  name: ".25-06 Remington",
  alternateNames: [".25-06", ".25-06 Springfield"],
  type: "Rifle",
  standardization: "SAAMI",
  productionStatus: "Active",
  availability: "Common",
  yearIntroduced: 1969,
  inventor: "A.O. Niedner / Charles Newton",
  manufacturer: "Remington (commercial)",
  countryOfOrigin: "United States",
  parentCase: ".30-06 Springfield",
  derivedFrom: ".30-06 Springfield necked down to .25",
  bulletDiameterInch: 0.257,
  bulletDiameterMM: 6.53,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 2.494,
  caseLengthMM: 63.35,
  overallLengthInch: 3.250,
  overallLengthMM: 82.55,
  caseCapacityGrains: 68.0,
  maxPressurePSI: 63000,
  commonBulletWeights: [85, 90, 100, 110, 115, 120],
  velocityRangeFPS: { min: 2900, max: 3400 },
  energyRangeFTLBS: { min: 2400, max: 3000 },
  effectiveRangeYards: 600,
  maxRangeYards: 4500,
  primaryUse: ["Hunting", "Varmint", "Target"],
  huntingGameSize: ["Varmint", "Medium Game"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".257 Weatherby Magnum", ".257 Roberts", ".243 Winchester"],
  description: "Classic quarter-bore speed demon. Legendary wildcat that finally went commercial in 1969. Flat trajectory, mild recoil. Perfect western plains cartridge.",
  history: "Originated as wildcat around 1912 by A.O. Niedner and Charles Newton, necking .30-06 to .25. One of the oldest and most popular wildcats, widely used for 50+ years before commercialization. Remington finally standardized it in 1969 and it became immediately popular. Combines flat trajectory with mild recoil. Dominant western varmint and deer cartridge. One of the most successful wildcat-to-commercial conversions.",
  notableFirearms: ["Remington Model 700", "Ruger M77", "Browning X-Bolt", "Weatherby Vanguard"],
  trivia: "This cartridge existed as a wildcat for 57 years before Remington commercialized it. It became an instant success and remains one of the most popular .25 calibers. The wildcat proved the concept for over half a century."
},

{
  name: ".22-250 Remington (Pre-SAAMI)",
  alternateNames: [".22 Varminter", ".22-250 Varminter"],
  type: "Rifle",
  standardization: "Wildcat",
  productionStatus: "Obsolete",
  availability: "Historical",
  yearIntroduced: 1937,
  inventor: "J.E. Gebby, J.B. Smith, Grosvenor Wotkyns",
  countryOfOrigin: "United States",
  parentCase: ".250 Savage",
  derivedFrom: ".250 Savage necked down to .22",
  bulletDiameterInch: 0.224,
  bulletDiameterMM: 5.69,
  baseDiameterInch: 0.470,
  baseDiameterMM: 11.94,
  rimDiameterInch: 0.473,
  rimDiameterMM: 12.01,
  caseLengthInch: 1.912,
  caseLengthMM: 48.59,
  overallLengthInch: 2.350,
  overallLengthMM: 59.69,
  caseCapacityGrains: 45.0,
  maxPressurePSI: 65000,
  commonBulletWeights: [50, 55, 60],
  velocityRangeFPS: { min: 3600, max: 4000 },
  energyRangeFTLBS: { min: 1300, max: 1800 },
  effectiveRangeYards: 500,
  maxRangeYards: 3500,
  primaryUse: ["Varmint"],
  militaryAdoption: [],
  currentMilitaryUse: [],
  lawEnforcementUse: false,
  similarCartridges: [".220 Swift", ".22-250 Remington (SAAMI)"],
  supersededBy: ".22-250 Remington (SAAMI standardized 1965)",
  description: "Historical wildcat version of .22-250. Existed for 28 years before SAAMI standardization. Proved the concept and dominated varmint hunting as wildcat.",
  history: "Multiple gunsmiths independently developed this wildcat in late 1930s by necking .250 Savage to .22. J.E. Gebby, J.B. Smith, and Grosvenor Wotkyns all created similar versions. Known variously as .22 Varminter, .22 Wotkyns, or .22 Gebby. Became most popular varmint wildcat by 1950s. Remington finally commercialized it in 1965 as .22-250 Remington. This entry represents the pre-SAAMI wildcat version.",
  notableFirearms: ["Custom rifles on Mauser actions", "Re-barreled sporters", "Wildcat single-shots"],
  trivia: "For nearly 30 years, this was THE varmint cartridge despite being a wildcat requiring custom barrels and handloading. So many gunsmiths chambered rifles for it that Remington had no choice but to commercialize it. It's the most successful wildcat in history by number of rifles chambered before standardization."
},

