// Generated from ammo inventory spreadsheet (124 lots)
import type { AmmoLot } from './types';

export const seedAmmo: Omit<AmmoLot, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    "caliber": ".22 LR",
    "brand": "Aguila",
    "productLine": "Prime Super Extra",
    "grainWeight": 38,
    "bulletType": "CPHP",
    "quantity": 1400,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 1400,
    "advertisedFPS": 1280,
    "muzzleEnergy": 138
  },
  {
    "caliber": ".22 LR",
    "brand": "Aguila",
    "productLine": "Prime Supermaximum",
    "grainWeight": 30,
    "bulletType": "CPSP",
    "quantity": 1050,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 1050,
    "advertisedFPS": 1750,
    "muzzleEnergy": 204
  },
  {
    "caliber": ".22 LR",
    "brand": "CCI",
    "productLine": "Green Tag",
    "grainWeight": 40,
    "bulletType": "LRN",
    "quantity": 2250,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 2250,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "CCI",
    "productLine": "Pistol Match Competition",
    "grainWeight": 40,
    "bulletType": "LRN",
    "quantity": 650,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 650,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "CCI",
    "productLine": "Mini Mag",
    "grainWeight": 40,
    "bulletType": "CPRN",
    "quantity": 90,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 90,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "CCI",
    "productLine": "Clean-22 High Velocity",
    "grainWeight": 40,
    "bulletType": "PC-RN",
    "quantity": 90,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 90,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "CCI",
    "productLine": "Shotshell Pest Control",
    "grainWeight": 31,
    "bulletType": "#12 Shot",
    "quantity": 80,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 80,
    "advertisedFPS": 1750,
    "muzzleEnergy": 211
  },
  {
    "caliber": ".22 LR",
    "brand": "Eley",
    "productLine": "Bullseye Pistol X",
    "grainWeight": 40,
    "bulletType": "RN",
    "quantity": 90,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 90,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "Eley",
    "productLine": "Tenex",
    "grainWeight": 40,
    "bulletType": "FN",
    "quantity": 90,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 90,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "Federal",
    "productLine": "AutoMatch",
    "grainWeight": 40,
    "bulletType": "LRN",
    "quantity": 2763,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 2763,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "Norma",
    "productLine": "TAC-22",
    "grainWeight": 40,
    "bulletType": "LRN",
    "quantity": 90,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 90,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "RWS",
    "productLine": "Rifle Match Pro Line",
    "grainWeight": 40,
    "bulletType": "LRN",
    "quantity": 190,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 190,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "SK",
    "productLine": "Standard Plus",
    "grainWeight": 40,
    "bulletType": "—",
    "quantity": 821,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 821,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "SK",
    "productLine": "High Velocity Match",
    "grainWeight": 40,
    "bulletType": "—",
    "quantity": 490,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 490,
    "advertisedFPS": 1200,
    "muzzleEnergy": 128
  },
  {
    "caliber": ".22 LR",
    "brand": "Winchester",
    "productLine": "Power-Point",
    "grainWeight": 42,
    "bulletType": "CPMHP",
    "quantity": 2000,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 2000,
    "advertisedFPS": 1255,
    "muzzleEnergy": 147
  },
  {
    "caliber": ".30-06 Springfield",
    "brand": "Hornady",
    "productLine": "Superformance",
    "grainWeight": 165,
    "bulletType": "SST",
    "quantity": 60,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 60,
    "advertisedFPS": 2800,
    "muzzleEnergy": 2873
  },
  {
    "caliber": ".30-06 Springfield",
    "brand": "Sellier & Bellot",
    "productLine": "M1 Garand Load",
    "grainWeight": 150,
    "bulletType": "FMJ",
    "quantity": 122,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 122,
    "advertisedFPS": 2910,
    "muzzleEnergy": 2821
  },
  {
    "caliber": ".30-06 Springfield",
    "brand": "Sellier & Bellot",
    "productLine": "Precision Rifle",
    "grainWeight": 168,
    "bulletType": "HPBT",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 2710,
    "muzzleEnergy": 2740
  },
  {
    "caliber": ".30-06 Springfield",
    "brand": "Sellier & Bellot",
    "productLine": "M1 Garand Load (SB3006M2A)",
    "grainWeight": 150,
    "bulletType": "FMJ",
    "quantity": 400,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 400,
    "advertisedFPS": 2910,
    "muzzleEnergy": 2821
  },
  {
    "caliber": ".30-30 Win",
    "brand": "Norma",
    "productLine": "Whitetail",
    "grainWeight": 150,
    "bulletType": "SP",
    "quantity": 20,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 20,
    "advertisedFPS": 2390,
    "muzzleEnergy": 1903
  },
  {
    "caliber": ".30-40 Krag",
    "brand": "HSM",
    "productLine": "—",
    "grainWeight": 180,
    "bulletType": "Sierra GameKing",
    "quantity": 260,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 260,
    "advertisedFPS": 2430,
    "muzzleEnergy": 2361
  },
  {
    "caliber": ".30-40 Krag",
    "brand": "HSM",
    "productLine": "—",
    "grainWeight": 150,
    "bulletType": "SBT GameKing",
    "quantity": 80,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 80,
    "advertisedFPS": 2430,
    "muzzleEnergy": 1967
  },
  {
    "caliber": ".300 AAC Blackout",
    "brand": "Sellier & Bellot",
    "productLine": "SB300BLKB",
    "grainWeight": 147,
    "bulletType": "FMJ",
    "quantity": 20,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 20,
    "advertisedFPS": 1900,
    "muzzleEnergy": 1179
  },
  {
    "caliber": ".303 British",
    "brand": "Hornady",
    "productLine": "Custom",
    "grainWeight": 150,
    "bulletType": "InterLock SP",
    "quantity": 60,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 60,
    "advertisedFPS": 2685,
    "muzzleEnergy": 2402
  },
  {
    "caliber": ".303 British",
    "brand": "PPU",
    "productLine": "Rifle Line",
    "grainWeight": 174,
    "bulletType": "FMJ-BT",
    "quantity": 120,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 120,
    "advertisedFPS": 2440,
    "muzzleEnergy": 2301
  },
  {
    "caliber": ".303 British",
    "brand": "Sellier & Bellot",
    "productLine": "—",
    "grainWeight": 180,
    "bulletType": "FMJ",
    "quantity": 160,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 160,
    "advertisedFPS": 2460,
    "muzzleEnergy": 2419
  },
  {
    "caliber": ".303 British",
    "brand": "Sellier & Bellot",
    "productLine": "—",
    "grainWeight": 180,
    "bulletType": "SP",
    "quantity": 80,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 80,
    "advertisedFPS": 2460,
    "muzzleEnergy": 2419
  },
  {
    "caliber": ".308 Win",
    "brand": "MKE",
    "productLine": "Battle Pack",
    "grainWeight": 147,
    "bulletType": "FMJ",
    "quantity": 200,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 200,
    "advertisedFPS": 2800,
    "muzzleEnergy": 2560
  },
  {
    "caliber": ".308 Win",
    "brand": "PPU",
    "productLine": "Match Line",
    "grainWeight": 155,
    "bulletType": "HPBT",
    "quantity": 60,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 60,
    "advertisedFPS": 2775,
    "muzzleEnergy": 2651
  },
  {
    "caliber": ".308 Win",
    "brand": "PPU",
    "productLine": "Rifle Line",
    "grainWeight": 165,
    "bulletType": "PSP-BT",
    "quantity": 126,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 126,
    "advertisedFPS": 2650,
    "muzzleEnergy": 2574
  },
  {
    "caliber": ".308 Win",
    "brand": "Sellier & Bellot",
    "productLine": "—",
    "grainWeight": 147,
    "bulletType": "FMJ",
    "quantity": 500,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 500,
    "advertisedFPS": 2800,
    "muzzleEnergy": 2560
  },
  {
    "caliber": ".308 Win",
    "brand": "Sellier & Bellot",
    "productLine": "SB308G",
    "grainWeight": 168,
    "bulletType": "HPBT",
    "quantity": 60,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 60,
    "advertisedFPS": 2650,
    "muzzleEnergy": 2620
  },
  {
    "caliber": ".308 Win",
    "brand": "SwissAA (Saltech)",
    "productLine": "Range",
    "grainWeight": 147,
    "bulletType": "FMJ",
    "quantity": 80,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 80,
    "advertisedFPS": 2800,
    "muzzleEnergy": 2560
  },
  {
    "caliber": ".32 Auto",
    "brand": "PPU",
    "productLine": "Defense Line",
    "grainWeight": 71,
    "bulletType": "JHP",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 905,
    "muzzleEnergy": 129
  },
  {
    "caliber": ".32 S&W",
    "brand": "Remington",
    "productLine": "Performance WheelGun",
    "grainWeight": 88,
    "bulletType": "LRN",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 680,
    "muzzleEnergy": 90
  },
  {
    "caliber": ".357 Magnum",
    "brand": "Armscor USA",
    "productLine": "—",
    "grainWeight": 158,
    "bulletType": "FMJ",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 1250,
    "muzzleEnergy": 548
  },
  {
    "caliber": ".357 Magnum",
    "brand": "Magtech",
    "productLine": "—",
    "grainWeight": 125,
    "bulletType": "FMJ-Flat",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 1500,
    "muzzleEnergy": 625
  },
  {
    "caliber": ".357 Magnum",
    "brand": "New Republic",
    "productLine": "Training & Range",
    "grainWeight": 158,
    "bulletType": "FMJ-FP",
    "quantity": 278,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 278,
    "advertisedFPS": 1250,
    "muzzleEnergy": 548
  },
  {
    "caliber": ".357 Magnum",
    "brand": "PMC",
    "productLine": "Bronze",
    "grainWeight": 158,
    "bulletType": "JSP",
    "quantity": 400,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 400,
    "advertisedFPS": 1250,
    "muzzleEnergy": 548
  },
  {
    "caliber": ".357 SIG",
    "brand": "Winchester",
    "productLine": "—",
    "grainWeight": 125,
    "bulletType": "FMJ",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 1450,
    "muzzleEnergy": 584
  },
  {
    "caliber": ".375 H&H Mag",
    "brand": "Barnes",
    "productLine": "—",
    "grainWeight": 300,
    "bulletType": "Banded Solid RN",
    "quantity": 60,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 60,
    "advertisedFPS": 2530,
    "muzzleEnergy": 4265
  },
  {
    "caliber": ".375 H&H Mag",
    "brand": "Barnes",
    "productLine": "—",
    "grainWeight": 300,
    "bulletType": "TSX FB",
    "quantity": 40,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 40,
    "advertisedFPS": 2530,
    "muzzleEnergy": 4265
  },
  {
    "caliber": ".375 H&H Mag",
    "brand": "Federal",
    "productLine": "Power-Shok",
    "grainWeight": 270,
    "bulletType": "JSP",
    "quantity": 20,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 20,
    "advertisedFPS": 2690,
    "muzzleEnergy": 4339
  },
  {
    "caliber": ".375 H&H Mag",
    "brand": "Hornady",
    "productLine": "Outfitter",
    "grainWeight": 250,
    "bulletType": "CX",
    "quantity": 20,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 20,
    "advertisedFPS": 2690,
    "muzzleEnergy": 4018
  },
  {
    "caliber": ".375 H&H Mag",
    "brand": "PPU",
    "productLine": "Rifle Line",
    "grainWeight": 300,
    "bulletType": "FMJ-RN",
    "quantity": 130,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 130,
    "advertisedFPS": 2530,
    "muzzleEnergy": 4265
  },
  {
    "caliber": ".38 Special",
    "brand": "Precision One",
    "productLine": "Target Reman",
    "grainWeight": 125,
    "bulletType": "FMJ",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 945,
    "muzzleEnergy": 248
  },
  {
    "caliber": ".380 Auto",
    "brand": "Armscor USA",
    "productLine": "—",
    "grainWeight": 95,
    "bulletType": "FMJ",
    "quantity": 150,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 150,
    "advertisedFPS": 960,
    "muzzleEnergy": 194
  },
  {
    "caliber": ".380 Auto",
    "brand": "Federal",
    "productLine": "Premium LE HST",
    "grainWeight": 99,
    "bulletType": "HST",
    "quantity": 50,
    "category": "Self Defense",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 950,
    "muzzleEnergy": 198
  },
  {
    "caliber": ".380 Auto",
    "brand": "Sellier & Bellot",
    "productLine": "SB380A",
    "grainWeight": 92,
    "bulletType": "FMJ",
    "quantity": 400,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 400,
    "advertisedFPS": 1000,
    "muzzleEnergy": 204
  },
  {
    "caliber": ".40 S&W",
    "brand": "Federal",
    "productLine": "BallistiClean",
    "grainWeight": 125,
    "bulletType": "Frangible",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 1140,
    "muzzleEnergy": 361
  },
  {
    "caliber": ".410 Bore",
    "brand": "Sellier & Bellot",
    "productLine": "Spherical Bullet",
    "grainWeight": 109,
    "bulletType": "000 Buck 3-pellet",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 1775,
    "muzzleEnergy": 763
  },
  {
    "caliber": ".44 Magnum",
    "brand": "PPU",
    "productLine": "Handgun Line",
    "grainWeight": 240,
    "bulletType": "JHP",
    "quantity": 150,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 150,
    "advertisedFPS": 1350,
    "muzzleEnergy": 971
  },
  {
    "caliber": ".44 Magnum",
    "brand": "Precision One",
    "productLine": "Target",
    "grainWeight": 200,
    "bulletType": "FMJ",
    "quantity": 192,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 192,
    "advertisedFPS": 1610,
    "muzzleEnergy": 1151
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Federal",
    "productLine": "Syntech Training Match",
    "grainWeight": 230,
    "bulletType": "TSJ",
    "quantity": 50,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 850,
    "muzzleEnergy": 369
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Federal",
    "productLine": "Syntech (AE45SJ2)",
    "grainWeight": 230,
    "bulletType": "TSJ",
    "quantity": 500,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 500,
    "advertisedFPS": 850,
    "muzzleEnergy": 369
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Federal",
    "productLine": "American Eagle",
    "grainWeight": 230,
    "bulletType": "TSJ",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 850,
    "muzzleEnergy": 369
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Federal",
    "productLine": "Personal Defense Punch",
    "grainWeight": 230,
    "bulletType": "JHP",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 850,
    "muzzleEnergy": 369
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Fenix Ammunition",
    "productLine": "—",
    "grainWeight": 230,
    "bulletType": "FMJ",
    "quantity": 990,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 990,
    "advertisedFPS": 850,
    "muzzleEnergy": 369
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Hornady",
    "productLine": "Critical Duty",
    "grainWeight": 220,
    "bulletType": "FlexLock +P",
    "quantity": 40,
    "category": "Self Defense",
    "isHandload": false,
    "quantityPurchased": 40,
    "advertisedFPS": 850,
    "muzzleEnergy": 353
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Sellier & Bellot",
    "productLine": "SB45A",
    "grainWeight": 230,
    "bulletType": "FMJ",
    "quantity": 25,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 25,
    "advertisedFPS": 850,
    "muzzleEnergy": 369
  },
  {
    "caliber": ".45 ACP / .45 Auto",
    "brand": "Speer",
    "productLine": "Lawman",
    "grainWeight": 230,
    "bulletType": "TMJ",
    "quantity": 170,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 170,
    "advertisedFPS": 850,
    "muzzleEnergy": 369
  },
  {
    "caliber": ".45 Colt",
    "brand": "HSM",
    "productLine": "Cowboy Action",
    "grainWeight": 250,
    "bulletType": "RNFP Lead",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 900,
    "muzzleEnergy": 450
  },
  {
    "caliber": ".45-70 Gov't",
    "brand": "HSM",
    "productLine": "Cowboy Action",
    "grainWeight": 405,
    "bulletType": "RNFP Lead",
    "quantity": 60,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 60,
    "advertisedFPS": 1330,
    "muzzleEnergy": 1591
  },
  {
    "caliber": ".45-70 Gov't",
    "brand": "HSM",
    "productLine": "Bear Load +P",
    "grainWeight": 430,
    "bulletType": "RNFP GC",
    "quantity": 120,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 120,
    "advertisedFPS": 1330,
    "muzzleEnergy": 1689
  },
  {
    "caliber": ".45-70 Gov't",
    "brand": "Sellier & Bellot",
    "productLine": "—",
    "grainWeight": 405,
    "bulletType": "SP",
    "quantity": 80,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 80,
    "advertisedFPS": 1330,
    "muzzleEnergy": 1591
  },
  {
    "caliber": ".50 BMG",
    "brand": "PMC",
    "productLine": "X-TAC Match",
    "grainWeight": 740,
    "bulletType": "Solid Brass",
    "quantity": 10,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 10,
    "advertisedFPS": 2820,
    "muzzleEnergy": 13070
  },
  {
    "caliber": "10mm Auto",
    "brand": "Blazer",
    "productLine": "Brass Case",
    "grainWeight": 180,
    "bulletType": "FMJ-FN",
    "quantity": 240,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 240,
    "advertisedFPS": 1180,
    "muzzleEnergy": 557
  },
  {
    "caliber": "10mm Auto",
    "brand": "Fenix Ammunition",
    "productLine": "—",
    "grainWeight": 180,
    "bulletType": "FMJ",
    "quantity": 250,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 250,
    "advertisedFPS": 1180,
    "muzzleEnergy": 557
  },
  {
    "caliber": "10mm Auto",
    "brand": "Sellier & Bellot",
    "productLine": "SB10A",
    "grainWeight": 180,
    "bulletType": "FMJ",
    "quantity": 225,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 225,
    "advertisedFPS": 1180,
    "muzzleEnergy": 557
  },
  {
    "caliber": "10mm Auto",
    "brand": "Speer",
    "productLine": "Gold Dot Personal Protection",
    "grainWeight": 200,
    "bulletType": "GDHP",
    "quantity": 40,
    "category": "Self Defense",
    "isHandload": false,
    "quantityPurchased": 40,
    "advertisedFPS": 1050,
    "muzzleEnergy": 490
  },
  {
    "caliber": "12 Gauge",
    "brand": "American Tactical",
    "productLine": "Defense & Hunting",
    "grainWeight": 437,
    "bulletType": "00 Buck 9-pellet",
    "quantity": 90,
    "category": "Hunting",
    "isHandload": false,
    "quantityPurchased": 90,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Brenneke",
    "productLine": "Special Forces MBP Magnum",
    "grainWeight": 437,
    "bulletType": "Slug",
    "quantity": 5,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 5,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Brenneke",
    "productLine": "Super Sabot",
    "grainWeight": 437,
    "bulletType": "Slug",
    "quantity": 5,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 5,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Captor",
    "productLine": "Premium Rounds",
    "grainWeight": 437,
    "bulletType": "00 Buck",
    "quantity": 130,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 130,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Captor",
    "productLine": "Premium Rounds",
    "grainWeight": 437,
    "bulletType": "1oz Slug",
    "quantity": 40,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 40,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Federal",
    "productLine": "—",
    "grainWeight": 437,
    "bulletType": "1oz Slug",
    "quantity": 15,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 15,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Federal",
    "productLine": "Premium LE TruBall Tactical",
    "grainWeight": 438,
    "bulletType": "HP Rifled Slug",
    "quantity": 10,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 10,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1644
  },
  {
    "caliber": "12 Gauge",
    "brand": "Federal",
    "productLine": "Top Gun",
    "grainWeight": 437,
    "bulletType": "#8 Shot 1oz",
    "quantity": 241,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 241,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Fetter",
    "productLine": "Power Rifled Slug",
    "grainWeight": 437,
    "bulletType": "1⅛oz Slug",
    "quantity": 202,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 202,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Fiocchi",
    "productLine": "Defense Dynamics",
    "grainWeight": 437,
    "bulletType": "00 Buck 9-pellet",
    "quantity": 11,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 11,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Fiocchi",
    "productLine": "Less Lethal Line",
    "grainWeight": 437,
    "bulletType": "Rubber Baton",
    "quantity": 10,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 10,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "New Republic",
    "productLine": "Training & Range",
    "grainWeight": 437,
    "bulletType": "00 Buck",
    "quantity": 276,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 276,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Panzer Defense",
    "productLine": "Lequian Special HV",
    "grainWeight": 437,
    "bulletType": "1oz Rifled Slug",
    "quantity": 25,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 25,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Sellier & Bellot",
    "productLine": "Breaching",
    "grainWeight": 437,
    "bulletType": "½oz Polymer Shot",
    "quantity": 10,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 10,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Unknown",
    "productLine": "Dragon's Breath",
    "grainWeight": 437,
    "bulletType": "Dragon's Breath",
    "quantity": 12,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 12,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Unknown",
    "productLine": "Ball & Chain",
    "grainWeight": 437,
    "bulletType": "Ball & Chain",
    "quantity": 6,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 6,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Unknown",
    "productLine": "AP Discarding Sabot",
    "grainWeight": 437,
    "bulletType": "AP Discarding Sabot",
    "quantity": 6,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 6,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Unknown",
    "productLine": "Bean Bag",
    "grainWeight": 437,
    "bulletType": "Bean Bag",
    "quantity": 3,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 3,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "Winchester",
    "productLine": "Super-Target USA 250 Ltd Ed",
    "grainWeight": 437,
    "bulletType": "#7½ Shot 1oz",
    "quantity": 75,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 75,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "12 Gauge",
    "brand": "YTR",
    "productLine": "Slug Storm",
    "grainWeight": 437,
    "bulletType": "1oz Slug",
    "quantity": 800,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 800,
    "advertisedFPS": 1300,
    "muzzleEnergy": 1640
  },
  {
    "caliber": "5.56x45mm",
    "brand": "Hornady",
    "productLine": "Frontier FR200",
    "grainWeight": 55,
    "bulletType": "FMJ",
    "quantity": 500,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 500,
    "advertisedFPS": 3240,
    "muzzleEnergy": 1282
  },
  {
    "caliber": "5.56x45mm",
    "brand": "PMC",
    "productLine": "X-TAC XP193",
    "grainWeight": 55,
    "bulletType": "FMJ-BT",
    "quantity": 7102,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 7102,
    "advertisedFPS": 3240,
    "muzzleEnergy": 1282
  },
  {
    "caliber": "5.56x45mm",
    "brand": "PMC",
    "productLine": "X-TAC M855 Green Tip",
    "grainWeight": 62,
    "bulletType": "FMJ Green Tip",
    "quantity": 2000,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 2000,
    "advertisedFPS": 3100,
    "muzzleEnergy": 1323
  },
  {
    "caliber": "5.56x45mm",
    "brand": "PPU",
    "productLine": "Rangemaster Line",
    "grainWeight": 55,
    "bulletType": "FMJ-BT",
    "quantity": 2000,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 2000,
    "advertisedFPS": 3240,
    "muzzleEnergy": 1282
  },
  {
    "caliber": "5.7x28mm",
    "brand": "Fiocchi",
    "productLine": "Range Dynamics",
    "grainWeight": 40,
    "bulletType": "FMJ-FN",
    "quantity": 750,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 750,
    "advertisedFPS": 1800,
    "muzzleEnergy": 288
  },
  {
    "caliber": "6.5 Creedmoor",
    "brand": "Hornady",
    "productLine": "Match",
    "grainWeight": 120,
    "bulletType": "ELD Match",
    "quantity": 60,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 60,
    "advertisedFPS": 3000,
    "muzzleEnergy": 2399
  },
  {
    "caliber": "6.5 Creedmoor",
    "brand": "Norma",
    "productLine": "Golden Target",
    "grainWeight": 143,
    "bulletType": "GT",
    "quantity": 400,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 400,
    "advertisedFPS": 2700,
    "muzzleEnergy": 2315
  },
  {
    "caliber": "6.5 Creedmoor",
    "brand": "Norma",
    "productLine": "Range & Training",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 3000,
    "muzzleEnergy": 2479
  },
  {
    "caliber": "6.5 Creedmoor",
    "brand": "Winchester",
    "productLine": "USA Ready",
    "grainWeight": 140,
    "bulletType": "Open Tip",
    "quantity": 92,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 92,
    "advertisedFPS": 2710,
    "muzzleEnergy": 2284
  },
  {
    "caliber": "6.5 Grendel",
    "brand": "Nemo",
    "productLine": "Range + Training",
    "grainWeight": 120,
    "bulletType": "FMJ-BT",
    "quantity": 390,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 390,
    "advertisedFPS": 2600,
    "muzzleEnergy": 1802
  },
  {
    "caliber": "6.5 Grendel",
    "brand": "Sellier & Bellot",
    "productLine": "SB665GA",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 400,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 400,
    "advertisedFPS": 2580,
    "muzzleEnergy": 1833
  },
  {
    "caliber": "6.5x55 SE",
    "brand": "Sellier & Bellot",
    "productLine": "SB6555C",
    "grainWeight": 140,
    "bulletType": "FMJBT",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 2735,
    "muzzleEnergy": 2326
  },
  {
    "caliber": "7.5x55 Swiss",
    "brand": "Sellier & Bellot",
    "productLine": "SB7555A",
    "grainWeight": 174,
    "bulletType": "FMJ",
    "quantity": 134,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 134,
    "advertisedFPS": 2560,
    "muzzleEnergy": 2533
  },
  {
    "caliber": "7.62x39mm",
    "brand": "Igman",
    "productLine": "—",
    "grainWeight": 123,
    "bulletType": "FMJ",
    "quantity": 150,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 150,
    "advertisedFPS": 2350,
    "muzzleEnergy": 1509
  },
  {
    "caliber": "7.62x39mm",
    "brand": "Wolf",
    "productLine": "Military Classic",
    "grainWeight": 124,
    "bulletType": "SP",
    "quantity": 120,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 120,
    "advertisedFPS": 2350,
    "muzzleEnergy": 1521
  },
  {
    "caliber": "7.62x54R",
    "brand": "Wolf",
    "productLine": "Military Classic",
    "grainWeight": 148,
    "bulletType": "FMJ",
    "quantity": 300,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 300,
    "advertisedFPS": 2800,
    "muzzleEnergy": 2577
  },
  {
    "caliber": "8mm Mauser",
    "brand": "Turkish Milsurp",
    "productLine": "1938",
    "grainWeight": 196,
    "bulletType": "FMJ",
    "quantity": 200,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 200,
    "advertisedFPS": 2500,
    "muzzleEnergy": 2721
  },
  {
    "caliber": "9mm Luger",
    "brand": "Blazer",
    "productLine": "Brass Case",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "Blazer",
    "productLine": "Brass Case",
    "grainWeight": 147,
    "bulletType": "FMJ",
    "quantity": 1000,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 1000,
    "advertisedFPS": 990,
    "muzzleEnergy": 320
  },
  {
    "caliber": "9mm Luger",
    "brand": "Federal",
    "productLine": "American Eagle AE9AP",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 2000,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 2000,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "Federal",
    "productLine": "Syntech Range",
    "grainWeight": 124,
    "bulletType": "TSJ",
    "quantity": 150,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 150,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "Federal",
    "productLine": "Syntech Action Pistol",
    "grainWeight": 150,
    "bulletType": "TSJ",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 950,
    "muzzleEnergy": 301
  },
  {
    "caliber": "9mm Luger",
    "brand": "Federal",
    "productLine": "Syntech Training Match",
    "grainWeight": 124,
    "bulletType": "TSJ",
    "quantity": 50,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "Federal",
    "productLine": "Syntech Training Match",
    "grainWeight": 147,
    "bulletType": "TSJ",
    "quantity": 25,
    "category": "Match",
    "isHandload": false,
    "quantityPurchased": 25,
    "advertisedFPS": 990,
    "muzzleEnergy": 320
  },
  {
    "caliber": "9mm Luger",
    "brand": "Fenix Ammunition",
    "productLine": "—",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 700,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 700,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "Fenix Ammunition",
    "productLine": "—",
    "grainWeight": 147,
    "bulletType": "FMJ",
    "quantity": 2400,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 2400,
    "advertisedFPS": 990,
    "muzzleEnergy": 320
  },
  {
    "caliber": "9mm Luger",
    "brand": "Fiocchi",
    "productLine": "Range Dynamics",
    "grainWeight": 115,
    "bulletType": "FMJ",
    "quantity": 700,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 700,
    "advertisedFPS": 1180,
    "muzzleEnergy": 356
  },
  {
    "caliber": "9mm Luger",
    "brand": "MAXXTech",
    "productLine": "by GH Ammunition",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 100,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 100,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "PMC",
    "productLine": "Bronze",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 1000,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 1000,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "PPU",
    "productLine": "Rangemaster Line",
    "grainWeight": 124,
    "bulletType": "FMJ",
    "quantity": 250,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 250,
    "advertisedFPS": 1150,
    "muzzleEnergy": 364
  },
  {
    "caliber": "9mm Luger",
    "brand": "Sellier & Bellot",
    "productLine": "SB9A",
    "grainWeight": 115,
    "bulletType": "FMJ",
    "quantity": 1000,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 1000,
    "advertisedFPS": 1180,
    "muzzleEnergy": 356
  },
  {
    "caliber": "9mm Luger",
    "brand": "Speer",
    "productLine": "Gold Dot G2 Carry Gun",
    "grainWeight": 135,
    "bulletType": "HP",
    "quantity": 20,
    "category": "Self Defense",
    "isHandload": false,
    "quantityPurchased": 20,
    "advertisedFPS": 1050,
    "muzzleEnergy": 331
  },
  {
    "caliber": "9mm Luger +P",
    "brand": "Hornady",
    "productLine": "Critical Duty",
    "grainWeight": 135,
    "bulletType": "FlexLock",
    "quantity": 50,
    "category": "Self Defense",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 1200,
    "muzzleEnergy": 432
  },
  {
    "caliber": "9mm Luger +P",
    "brand": "Hornady",
    "productLine": "Backcountry Defense",
    "grainWeight": 138,
    "bulletType": "DGH",
    "quantity": 50,
    "category": "Practice",
    "isHandload": false,
    "quantityPurchased": 50,
    "advertisedFPS": 1050,
    "muzzleEnergy": 338
  }
];
