[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/calibers"
  to = "/cartridge-library"
  status = 301
  force = true

[[redirects]]
  from = "/powder"
  to = "/powder-library"
  status = 301
  force = true
