-- ============================================================
-- manufacturers v3 — Phase 3: New manufacturer rows
-- ~80 new entries: missing US makers, niche/premium, international,
-- historic, military arsenals
-- Idempotent: ON CONFLICT (name) DO NOTHING
-- ============================================================

INSERT INTO public.manufacturers
  (name, alternate_names, country_of_origin, founded_year, active, entity_type,
   categories, parent_company, subsidiaries, description, notable_models,
   known_for, notable_designers, has_military_contract, military_notes,
   price_tier_entry_usd, market_segment, ownership_type, volume_tier,
   us_import_status, production_country, trivia, website, headquarters)
VALUES

-- ═══════════════════════════════════════════════════════════════
-- MISSING US MANUFACTURERS
-- ═══════════════════════════════════════════════════════════════

('Ed Brown Products',
 ARRAY['Ed Brown','EBP'],
 'USA', 1988, true, 'Manufacturer',
 ARRAY['Handgun'],
 NULL, NULL,
 'American custom 1911 manufacturer founded by Ed Brown in Perry, Missouri. Produces some of the finest production 1911 pistols in the country, with the Kobra Carry and Special Forces models widely regarded as benchmarks. Every pistol is hand-fitted, test-fired, and guaranteed to shoot 1-inch groups at 25 yards. Ed Brown completes the premium 1911 triumvirate alongside Nighthawk Custom and Les Baer.',
 ARRAY['Kobra Carry','Special Forces','Classic Custom','Executive Carry'],
 ARRAY['Premium 1911 pistols'],
 NULL, false, NULL,
 3200, 'ultra-premium', 'Independent', 'Boutique',
 'Domestic', 'USA',
 'Ed Brown''s 1911 pistols are hand-fitted one at a time in Perry, Missouri. Each gun ships with a test target proving sub-1-inch accuracy at 25 yards — a guarantee few production manufacturers can match.',
 'edbrown.com', 'Perry, MO'),

('Volquartsen Firearms',
 ARRAY['Volquartsen','VF'],
 'USA', 1974, true, 'Manufacturer',
 ARRAY['Rifle','Handgun'],
 NULL, NULL,
 'Iowa manufacturer of semi-automatic rimfire rifles and pistols, founded by Tom Volquartsen in Carroll, Iowa. Dominant in NRL22 and rimfire precision rifle competition, producing the Summit, Ultralite, and Superlite series. Volquartsen began by making custom parts for Ruger 10/22 rifles before transitioning to complete firearms. Their triggers and barrels are also sold separately and are the de facto standard upgrade for Ruger rimfire platforms.',
 ARRAY['Summit','Ultralite','Superlite','Scorpion','VF-19'],
 ARRAY['Rimfire precision rifles','Competition rimfire','Rimfire pistols'],
 NULL, false, NULL,
 1300, 'premium', 'Independent', 'Boutique',
 'Domestic', 'USA',
 'Volquartsen''s 10/22 custom parts business grew so large that the company now makes complete rifles that outperform virtually every factory rimfire on the market. Their triggers are the first upgrade most competitive rimfire shooters make.',
 'volquartsen.com', 'Carroll, IA'),

('McMillan Firearms',
 ARRAY['McMillan','McMillan Group'],
 'USA', 1973, true, 'Manufacturer',
 ARRAY['Rifle'],
 'McMillan Group International', NULL,
 'Arizona manufacturer of precision rifle stocks and complete custom rifles, founded by Gale McMillan in Phoenix. The McMillan stock is used on the US M40 sniper rifle and dozens of military and police sniper platforms worldwide. Their TAC-50 anti-materiel rifle was the platform used for the longest confirmed sniper kill in history (2017, Iraq, 3,540 meters by a Canadian JTF2 operator). McMillan also produces the CS5 and TAC-338.',
 ARRAY['TAC-50','TAC-338','CS5','A5','A3-5'],
 ARRAY['Precision sniper rifles','Military sniper stocks'],
 NULL, true, 'US M40 sniper rifle stock (USMC); TAC-50 (Canadian military, various special forces)',
 4500, 'ultra-premium', 'Independent', 'Boutique',
 'Domestic', 'USA',
 'A McMillan TAC-50 was the platform used for the longest confirmed sniper kill in recorded history — 3,540 meters in Iraq in 2017, set by a Canadian JTF2 operator. The shot took approximately 10 seconds of flight time.',
 'mcmillanfirearms.com', 'Phoenix, AZ'),

('Heritage Manufacturing',
 ARRAY['Heritage','Heritage Rough Rider'],
 'USA', 1992, true, 'Brand',
 ARRAY['Handgun'],
 'Taurus Armas S.A.', NULL,
 'Florida manufacturer of the Rough Rider single-action revolver, owned by Taurus Armas S.A. Now the highest-volume single-action revolver producer in the United States by a wide margin, selling hundreds of thousands of units annually at under $200. The Rough Rider is likely the most commonly purchased first firearm for budget-conscious buyers and youth shooters. Originally founded in Opa-locka, Florida, now operating under the Taurus umbrella.',
 ARRAY['Rough Rider','Barkeep'],
 ARRAY['Budget single-action revolvers','Youth revolvers'],
 NULL, false, NULL,
 110, 'mass', 'Subsidiary', 'High',
 'Domestic', 'USA',
 'Heritage Manufacturing sells more single-action revolvers than any other company in the US — by a significant margin. The Rough Rider, priced under $200, is often cited as the most common entry-level firearm purchase in America.',
 'heritagemanufacturing.com', 'Opa-locka, FL'),

('Cooper Firearms of Montana',
 ARRAY['Cooper Firearms','Cooper'],
 'USA', 1990, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Stevensville, Montana manufacturer of premium bolt-action rifles in uncommon and wildcat cartridges, founded by Dan Cooper. Known for the Model 52, Model 54, and Model 57 series, with sub-MOA accuracy guarantees and exotic caliber options most major manufacturers do not offer. Cooper rifles are built one at a time by craftsmen in the Bitterroot Valley and are prized by hunters pursuing dangerous or thin-margin game at extended range.',
 ARRAY['Model 52','Model 54','Model 57','Model 22','Model 92'],
 ARRAY['Precision bolt-action rifles','Wildcat calibers'],
 NULL, false, NULL,
 1800, 'ultra-premium', 'Independent', 'Micro',
 'Domestic', 'USA',
 'Cooper Firearms chambers rifles in calibers most manufacturers won''t touch — wildcats, obsolete cartridges, and proprietary rounds that have no commercial source. Every rifle ships with a signed accuracy guarantee tested at the factory.',
 'cooperfirearms.com', 'Stevensville, MT'),

('Nosler',
 ARRAY['Nosler Inc.'],
 'USA', 1948, true, 'Manufacturer',
 ARRAY['Rifle','Ammunition'],
 NULL, NULL,
 'Oregon company founded by John Nosler in 1948, initially producing the Partition bullet — the first controlled-expansion hunting bullet designed to prevent core separation. The Partition is still considered the gold standard of hunting bullets. Nosler expanded into complete bolt-action rifles (Model 21, Model 48), brass, and loaded ammunition. The company remains family-owned and headquartered in Bend, Oregon.',
 ARRAY['Model 21','Model 48','Liberty','Patriot'],
 ARRAY['Precision hunting rifles','Premium bullets','Ammunition'],
 ARRAY['John Nosler'], false, NULL,
 1800, 'premium', 'Independent', 'Boutique',
 'Domestic', 'USA',
 'John Nosler invented the Partition bullet in 1948 after his standard bullets failed on a moose at close range in British Columbia. The Partition''s dual-core design — which prevents the front core from separating while allowing controlled expansion — remains in production 75 years later.',
 'nosler.com', 'Bend, OR'),

('Standard Manufacturing',
 ARRAY['Standard Mfg','Standard Manufacturing Company'],
 'USA', 2012, true, 'Manufacturer',
 ARRAY['Shotgun','Handgun'],
 NULL, NULL,
 'Connecticut manufacturer of genuinely innovative firearm designs, founded in 2012. Known for the DP-12 double-barrel pump shotgun, the SKO series semi-automatic shotguns, and the Switch-Gun folding derringer. Standard Manufacturing pursues original engineering solutions rather than conventional platforms, producing Made-in-USA firearms with an emphasis on novel operating mechanisms.',
 ARRAY['DP-12','Switch-Gun','SKO-12','S333 Volleyfire'],
 ARRAY['Innovative designs','Double-barrel pump shotguns'],
 NULL, false, NULL,
 350, 'mass', 'Independent', 'Mid',
 'Domestic', 'USA',
 'The Standard Manufacturing DP-12 holds 16 rounds of 12-gauge ammunition in two independent tube magazines and fires two rounds per trigger pull — making it the highest-capacity pump shotgun in production. It weighs nearly 9 pounds empty.',
 'standardmfg.com', 'New Britain, CT'),

('Cimarron Firearms',
 ARRAY['Cimarron','Cimarron Arms'],
 'USA', 1984, true, 'Importer',
 ARRAY['Handgun','Rifle','Shotgun'],
 NULL, NULL,
 'Texas-based importer and customizer of Italian-made reproduction firearms, primarily from Uberti and Pedersoli, founded by Mike Harvey in Fredericksburg, Texas. The largest and most historically significant US importer in the cowboy action and reproduction niche. Cimarron offers historically accurate Single Action Army reproductions, cartridge conversions, and period-correct lever-action rifles for reenactors, cowboy action shooters, and collectors.',
 ARRAY['Model P (SAA reproduction)','1873 Winchester reproduction','1858 conversion','Doc Holiday'],
 ARRAY['Cowboy action revolvers','Lever-action reproductions','Historical reproductions'],
 NULL, false, NULL,
 399, 'premium', 'Independent', 'Mid',
 'Active Import', 'Italy',
 'Cimarron Firearms was founded because Mike Harvey believed American consumers deserved historically accurate reproduction firearms, not the simplified imports then available. He worked directly with Uberti to achieve period-correct details that even major museums find acceptable for display.',
 'cimarron-firearms.com', 'Fredericksburg, TX'),

('Taylor''s & Company',
 ARRAY['Taylors','Taylor''s & Co'],
 'USA', 1988, true, 'Importer',
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Virginia-based importer of Italian reproduction firearms, primarily from Uberti, founded in 1988. Taylor''s is one of the two primary US importers for Uberti-manufactured Single Action Army reproductions and 1873 Winchester lever-action copies, alongside Cimarron Firearms. Known for competitive pricing and a broad catalog of historical variations including the 1873 Cattleman and 1866 Yellowboy series.',
 ARRAY['1873 Cattleman','1866 Yellowboy','Smoke Wagon','1858 Army'],
 ARRAY['Cowboy action revolvers','Lever-action reproductions','Historical reproductions'],
 NULL, false, NULL,
 349, 'mass', 'Independent', 'Mid',
 'Active Import', 'Italy',
 'Taylor''s & Company and Cimarron together account for the majority of Uberti''s US sales. The competition between them has pushed historical accuracy and quality to levels that would have been unimaginable in the era of cheap Italian imports of the 1960s and 70s.',
 'taylorsfirearms.com', 'Winchester, VA'),

('AAC (Advanced Armament Corporation)',
 ARRAY['AAC','Advanced Armament'],
 'USA', 1994, true, 'Manufacturer',
 ARRAY['Suppressor','Rifle'],
 'SIG Sauer', NULL,
 'American suppressor manufacturer founded by Kevin Brittingham in Atlanta, Georgia in 1994. AAC effectively legitimized and popularized civilian suppressor ownership through products like the M4-2000 and 762-SDN-6, and through Brittingham''s aggressive marketing of the suppressor lifestyle. Acquired by Remington''s Freedom Group in 2010; Brittingham departed in 2011. Acquired by SIG Sauer in 2021 and now operates as SIG''s suppressor division.',
 ARRAY['M4-2000','762-SDN-6','Cyclone','Illusion 9','Aviator 2'],
 ARRAY['Suppressors','Suppressor culture'],
 ARRAY['Kevin Brittingham'], true, 'US military and SOCOM suppressor contracts',
 800, 'premium', 'Subsidiary', 'Mid',
 'Domestic', 'USA',
 'Kevin Brittingham and AAC are largely responsible for normalizing civilian suppressor ownership in the United States. Their marketing campaigns in the mid-2000s reframed suppressors as hearing protection rather than spy equipment, helping drive a 10x increase in civilian NFA registrations over the following decade.',
 'advanced-armament.com', 'Lawrenceville, GA'),

-- ═══════════════════════════════════════════════════════════════
-- PREMIUM / NICHE US MAKERS
-- ═══════════════════════════════════════════════════════════════

('Vudoo Gun Works',
 ARRAY['Vudoo'],
 'USA', 2017, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Utah precision rimfire manufacturer founded in 2017, producing the V-22 bolt-action rimfire rifle — widely considered the finest production rimfire platform for NRL22 and precision rimfire competition. The V-22 uses a proprietary repeating action designed around .22 LR precision and accepts standard Remington 700 footprint stocks. Built in small batches with exceptional quality control.',
 ARRAY['V-22'],
 ARRAY['Rimfire precision rifles'],
 NULL, false, NULL,
 4200, 'ultra-premium', 'Independent', 'Micro',
 'Domestic', 'USA',
 'The Vudoo V-22 is built around a single obsessive goal: make the most accurate production .22 LR bolt-action rifle possible. In NRL22 competition, it has become the dominant platform at the highest levels — the equivalent of a Formula 1 car in a rimfire stock class.',
 'vudoogunworks.com', 'St. George, UT'),

('Seekins Precision',
 ARRAY['Seekins'],
 'USA', 2009, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Lewiston, Idaho manufacturer of precision AR-platform rifles and billet components, founded by Steve Seekins. Known for beautifully machined billet upper and lower receivers, the Havak bolt-action rifle series, and the SP10 and SP15 AR platforms. Seekins occupies the upper-mid tier of the precision AR market alongside Noveske, LaRue, and JP Enterprises.',
 ARRAY['Havak Pro','SP10','SP15','SP223'],
 ARRAY['Precision AR rifles','Billet receivers','Precision bolt-action rifles'],
 NULL, false, NULL,
 1999, 'premium', 'Independent', 'Boutique',
 'Domestic', 'USA',
 'Seekins Precision started as a CNC machining shop making components for other rifle manufacturers. The quality of their billet receivers was so recognized in the industry that building complete rifles was the natural next step.',
 'seekinsprecision.com', 'Lewiston, ID'),

('Sharps Rifle Company',
 ARRAY['Shiloh Sharps','Sharps'],
 'USA', 1983, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Modern Montana manufacturer of Sharps-pattern single-shot rifles, based in Big Timber. The original Sharps Rifle Manufacturing Company (1848–1881) produced the dominant single-shot rifle of the Civil War era and the Great Plains buffalo trade. The modern Shiloh Sharps produces the most accurate and historically respected Sharps reproductions made today, chambered in original blackpowder calibers. Used extensively by long-range blackpowder competition shooters.',
 ARRAY['Model 1874','Model 1863'],
 ARRAY['Sharps reproductions','Blackpowder single-shot rifles'],
 ARRAY['Christian Sharps (original)'], false, NULL,
 1800, 'ultra-premium', 'Independent', 'Micro',
 'Domestic', 'USA',
 'The original Sharps rifle was so accurate that Civil War sharpshooters could hit targets at 1,000 yards — a feat considered impossible with the muskets of the era. The word "sharpshooter" derives from the reputation of Sharps rifle users, not from the act of accurate shooting itself.',
 'shilohrifle.com', 'Big Timber, MT'),

-- ═══════════════════════════════════════════════════════════════
-- INTERNATIONAL — EUROPE
-- ═══════════════════════════════════════════════════════════════

('Holland & Holland',
 ARRAY['H&H','Holland Holland'],
 'United Kingdom', 1835, true, 'Manufacturer',
 ARRAY['Rifle','Shotgun'],
 'Richemont Group', NULL,
 'London''s most prestigious gunmaker, founded by Harris Holland in 1835 in Oxford Street. The .375 H&H Magnum (1912) and .300 H&H Magnum (1925) cartridges bear the company name and remain globally significant hunting cartridges. H&H produces bespoke bolt-action rifles and side-by-side shotguns for royalty, heads of state, and serious big-game hunters. Now owned by the Richemont Group (same parent as Cartier and IWC). Entry price for a Royal side-by-side exceeds £150,000.',
 ARRAY['Royal','Paradox','Deluxe','Sporting'],
 ARRAY['Bespoke double rifles','Side-by-side shotguns','Dangerous game rifles'],
 ARRAY['Frederick Beesley'], true, 'British Royal Warrant holder; historical British military adoption of .303 H&H wildcat',
 45000, 'ultra-premium', 'Subsidiary', 'Micro',
 'Active Import', 'United Kingdom',
 'A matched pair of Holland & Holland Royal side-by-side shotguns requires over 800 hours of hand labor and costs upward of £150,000. H&H also invented the .375 H&H Magnum in 1912 — still the most widely used African dangerous game cartridge and the minimum caliber legally required for elephant in most countries.',
 'hollandandholland.com', 'London, UK'),

('James Purdey & Sons',
 ARRAY['Purdey','Purdeys'],
 'United Kingdom', 1814, true, 'Manufacturer',
 ARRAY['Shotgun','Rifle'],
 'Richemont Group', NULL,
 'Arguably the most prestigious name in British gunmaking, founded by James Purdey in London in 1814. "A matched pair of Purdeys" is synonymous with the absolute pinnacle of side-by-side and over/under shotgun craft. Purdey has held the Royal Warrant continuously and supplied firearms to nearly every British monarch since George IV. Now owned by the Richemont Group (same parent as Cartier). Waiting list for bespoke guns runs multiple years.',
 ARRAY['Best Gun side-by-side','Over & Under','Sporter','Rifle'],
 ARRAY['Bespoke side-by-side shotguns','Over/under shotguns'],
 ARRAY['James Purdey'], false, NULL,
 55000, 'ultra-premium', 'Subsidiary', 'Micro',
 'Active Import', 'United Kingdom',
 'Purdey has held a Royal Warrant from every British monarch since George IV. The company''s South Audley Street shop in Mayfair has operated continuously since 1881 and is itself a listed building. A Purdey Best Gun takes two craftsmen approximately 2,000 hours to build.',
 'purdey.com', 'London, UK'),

('John Rigby & Co.',
 ARRAY['Rigby','J. Rigby'],
 'United Kingdom', 1775, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'British gunmaker founded in Dublin in 1775, maker of the .416 Rigby and .450 Nitro Express cartridges — both significant in African dangerous game hunting. Rigby rifles were the standard for dangerous game hunting in Africa and India for over a century. Churchill, Hemingway, and numerous maharajas were clients. Currently owned by a private group since 2012, operating from London and producing bespoke and catalog bolt-action and double rifles.',
 ARRAY['Highland Stalker','Rising Bite Double Rifle','Big Game','Standard Rimless'],
 ARRAY['Dangerous game rifles','.416 Rigby','Double rifles'],
 ARRAY['John Rigby'], false, NULL,
 12000, 'ultra-premium', 'Independent', 'Micro',
 'Active Import', 'United Kingdom',
 'John Rigby & Co. introduced the .416 Rigby cartridge in 1911 specifically for the thick-skinned dangerous game of Africa. It remains one of the most respected dangerous game cartridges — and the minimum caliber for elephant in several African nations. The cartridge was also the basis for the .416 Remington Magnum.',
 'johnrigbyandco.com', 'London, UK'),

('Merkel',
 ARRAY['Merkel Jagd- und Sportwaffen'],
 'Germany', 1898, true, 'Manufacturer',
 ARRAY['Shotgun','Rifle'],
 'Heym (since 2022 under same ownership group)', NULL,
 'German firearms manufacturer based in Suhl, Thuringia, founded in 1898. Produces premium over/under shotguns, side-by-side shotguns, double rifles, and Drilling combination guns. Merkel is the surviving prestige German firearms brand from the Suhl gunmaking tradition, which survived both World Wars and the DDR era largely intact. The Merkel 140 double rifle is a benchmark in the African hunting market. Known for the distinctive Kersten lock and robust double rifle actions.',
 ARRAY['140','160','2000EL','K3','RX Helix'],
 ARRAY['Over/under shotguns','Double rifles','Drilling combination guns'],
 NULL, false, NULL,
 3500, 'ultra-premium', 'Independent', 'Boutique',
 'Active Import', 'Germany',
 'Merkel survived the DDR era as a state-controlled manufacturer, producing guns for East German export currency. After reunification, the Suhl factory was privatized and retained all its master craftsmen — giving Merkel an unbroken tradition of hand-fitted German gunmaking stretching back to 1898.',
 'merkel-hunting.com', 'Suhl, Germany'),

('Heym',
 ARRAY['F.W. Heym'],
 'Germany', 1865, true, 'Manufacturer',
 ARRAY['Rifle','Shotgun'],
 NULL, NULL,
 'Bavarian manufacturer of fine bolt-action rifles, double rifles, and combination guns, founded by Friedrich Wilhelm Heym in Gleichamberg in 1865. Now based in Münnerstadt. Known for the SR30 straight-pull bolt-action, the 89B double rifle, and a range of express-style bolt rifles for dangerous game. With Blaser, Sauer, and Merkel, Heym completes the picture of German prestige firearms manufacturing.',
 ARRAY['SR30','89B','Express','Magnum Express'],
 ARRAY['Double rifles','Bolt-action rifles','Combination guns'],
 NULL, false, NULL,
 4500, 'ultra-premium', 'Independent', 'Micro',
 'Active Import', 'Germany',
 'Heym''s SR30 straight-pull bolt-action allows the shooter to cycle without breaking the cheekweld — a design philosophy from German driven-hunt tradition where multiple rapid shots at driven game are common. The action is so smooth it''s compared to a lever gun in terms of cycling speed.',
 'heym-waffenfabrik.de', 'Münnerstadt, Germany'),

('Manurhin',
 ARRAY['Manufacture de Machines du Haut-Rhin','MR73'],
 'France', 1952, true, 'Manufacturer',
 ARRAY['Handgun'],
 NULL, NULL,
 'French precision manufacturer founded in Mulhouse, Alsace in 1952. Produces the MR73 revolver — widely considered the finest production revolver ever made and the standard sidearm of France''s GIGN counter-terrorism unit since its founding in 1974. The MR73 is built to tighter tolerances than any other production revolver, with a double-action trigger pull of extraordinary smoothness. Also produced Walther PP/PPK pistols under license during the 1950s–80s.',
 ARRAY['MR73','MR88'],
 ARRAY['MR73 revolver'],
 NULL, true, 'GIGN (French counter-terrorism, 1974–present); French Gendarmerie',
 3000, 'ultra-premium', 'Independent', 'Micro',
 'Active Import', 'France',
 'The Manurhin MR73 is the only production revolver designed to fire Magnum rounds continuously through a sustained firefight without degradation. French GIGN operators train with it firing thousands of rounds in qualification — a test that destroys most revolvers. The MR73 passes.',
 'manurhin.fr', 'Mulhouse, France'),

('Chapuis Armes',
 ARRAY['Chapuis'],
 'France', 1938, true, 'Manufacturer',
 ARRAY['Rifle','Shotgun'],
 NULL, NULL,
 'French manufacturer of high-quality double rifles and combination guns based in Saint-Bonnet-le-Château, Loire, founded in 1938. The Chapuis RGEX Express double rifle is used by French professional hunters in Africa and is respected in European and African dangerous game circles. Produces over/under and side-by-side shotguns alongside its double rifle line. Less known in the US than British makers but significant in France, Belgium, and Francophone Africa.',
 ARRAY['RGEX Express','Artisan','Brousse','Progress'],
 ARRAY['Double rifles','Over/under shotguns'],
 NULL, false, NULL,
 5000, 'ultra-premium', 'Independent', 'Micro',
 'Active Import', 'France',
 'Chapuis double rifles are the preferred choice of French professional hunters in Africa — chasseurs professionnels — where the ability to place two instant shots on a charging animal is not theoretical. The Loire Valley workshop produces under 1,000 guns per year.',
 'chapuis-armes.com', 'Saint-Bonnet-le-Château, France'),

('Fabryka Broni Radom',
 ARRAY['FB Radom','Radom'],
 'Poland', 1922, true, 'Military Arsenal',
 ARRAY['Handgun','Rifle'],
 'Polish State Treasury', NULL,
 'Polish state arms manufacturer founded in 1922 in Radom. The WW2-era VIS/P35 pistol is a celebrated design praised by both Allied and German forces who captured them. The modern Beryl assault rifle has been Poland''s standard service rifle since the 1990s, and the MSBS Grot is the current-generation Polish service rifle. FB Radom is the most significant Eastern European military manufacturer outside Russia not yet widely represented in firearms reference databases.',
 ARRAY['VIS/P35','Beryl','MSBS Grot','Radom 9mm'],
 ARRAY['Military service rifles','Semi-automatic pistols'],
 NULL, true, 'Polish Armed Forces primary rifle and pistol supplier; NATO member standardization',
 800, 'military', 'State-owned', 'High',
 'Active Import', 'Poland',
 'The Polish VIS/P35 pistol was so highly regarded that German forces, after occupying Poland in 1939, continued production for their own use under the designation P35(p). Captured Radom pistols became prized trophies among German soldiers. This is one of the highest backhanded compliments in firearms history.',
 'fabrykabroni.pl', 'Radom, Poland'),

-- ═══════════════════════════════════════════════════════════════
-- INTERNATIONAL — REST OF WORLD
-- ═══════════════════════════════════════════════════════════════

('CZ',
 ARRAY['CZ-USA','Česká zbrojovka','Czech Arms'],
 'Czech Republic', 1936, true, 'Manufacturer',
 ARRAY['Handgun','Rifle','Shotgun'],
 'CZ Group SE', ARRAY['Colt''s Manufacturing','Dan Wesson'],
 'Czech firearms manufacturer founded in 1936 in Uherský Brod. Produces the CZ 75 — one of the most copied semi-automatic pistol designs in history — along with the Shadow 2 competition pistol, Scorpion Evo carbine, and a full line of bolt-action hunting rifles. CZ Group SE acquired Colt''s Manufacturing in 2021, making CZ one of the most significant firearms conglomerates in the world. The CZ 75 has been produced in greater numbers than almost any other centerfire semi-automatic pistol.',
 ARRAY['CZ 75','Shadow 2','P-10','Scorpion Evo','CZ 457','CZ 600'],
 ARRAY['Semi-automatic pistols','Competition pistols','Bolt-action rifles'],
 NULL, true, 'Czech Armed Forces; numerous law enforcement agencies worldwide',
 500, 'premium', 'Subsidiary', 'High',
 'Active Import', 'Czech Republic',
 'The CZ 75 has been copied by more manufacturers than virtually any other pistol design — imitated by ITM, Tanfoglio, Springfield (EAA Witness), BUL, and dozens of others. It is said that imitation is the sincerest form of flattery. The original remains the standard against which all copies are measured.',
 'cz-usa.com', 'Uherský Brod, Czech Republic'),

('Tikka',
 ARRAY['Tikka Rifles'],
 'Finland', 1918, true, 'Brand',
 ARRAY['Rifle'],
 'Sako', NULL,
 'Finnish rifle brand owned by Sako (which is in turn owned by Beretta Holding). Tikka produces the T3x and T1x bolt-action rifle lines — known for exceptional accuracy at a mid-premium price point. The Tikka T3x is widely regarded as the best sub-$1,000 precision hunting rifle available, with a legendary smooth action and consistent sub-MOA accuracy out of the box. Tikka rifles are manufactured in the Sako factory in Riihimäki, Finland.',
 ARRAY['T3x','T1x','T3x CTR','T3x Compact Tactical Rifle'],
 ARRAY['Precision bolt-action rifles','Hunting rifles'],
 NULL, false, NULL,
 700, 'premium', 'Subsidiary', 'High',
 'Active Import', 'Finland',
 'Tikka T3x rifles routinely outshoot rifles costing two to three times more in independent accuracy testing. The smooth-as-glass Tikka action has become the basis for countless custom rifle builds — gunsmiths blueprint and rebarrel it because the action itself is genuinely excellent.',
 'tikka.fi', 'Riihimäki, Finland'),

('Sako',
 ARRAY['Sako Oy'],
 'Finland', 1921, true, 'Manufacturer',
 ARRAY['Rifle','Ammunition'],
 'Beretta Holding', ARRAY['Tikka'],
 'Finnish precision rifle manufacturer founded in 1921 in Helsinki. Produces the 85 and 90 series bolt-action rifles — among the most accurate factory rifles in the world — along with the TRG sniper rifle series. The TRG-42 is a standard Finnish military sniper rifle and is used by special forces in multiple countries. Sako also produces premium rifle ammunition. Owned by Beretta Holding since 2000.',
 ARRAY['85 Hunter','90 Adventure','TRG-22','TRG-42','Carbonlight'],
 ARRAY['Precision bolt-action rifles','Military sniper rifles'],
 NULL, true, 'Finnish Defence Forces TRG sniper rifle; multiple NATO special operations forces',
 1800, 'ultra-premium', 'Subsidiary', 'Boutique',
 'Active Import', 'Finland',
 'Sako''s TRG-42 has been used to set multiple long-range accuracy records and is the issued sniper rifle of the Finnish military — a country with a sniping tradition dating to the legendary Simo Häyhä, who killed over 500 Soviet soldiers in the Winter War using a Finnish-made rifle.',
 'sako.fi', 'Riihimäki, Finland'),

('Canik',
 ARRAY['Canik Arms','TP9'],
 'Turkey', 2006, true, 'Manufacturer',
 ARRAY['Handgun'],
 'Samsun Yurt Savunma (SARSILMAZ group)', NULL,
 'Turkish firearms manufacturer producing the TP9 series of polymer-frame striker-fired pistols, founded in 2006 in Samsun. Canik has achieved remarkable penetration in the US market as a value-premium option — offering features found on $800 pistols at $350–$450 price points. The TP9 Elite Combat and SFx Rival have gained traction in competition shooting. Imported by Century Arms International.',
 ARRAY['TP9SF','TP9 Elite Combat','SFx Rival','MC9'],
 ARRAY['Polymer pistols','Competition pistols','Budget pistols'],
 NULL, true, 'Turkish Armed Forces and law enforcement',
 350, 'mass', 'Subsidiary', 'High',
 'Active Import', 'Turkey',
 'Canik''s SFx Rival was designed in direct collaboration with competitive shooters and ships with features — adjustable trigger, optic-ready slide, flared magwell — that cost $300+ as upgrades on Glock-pattern pistols. It retails for under $500 complete.',
 'canikusa.com', 'Samsun, Turkey'),

('IWI',
 ARRAY['Israel Weapon Industries','IWI US'],
 'Israel', 2005, true, 'Manufacturer',
 ARRAY['Rifle','Handgun'],
 NULL, ARRAY['IWI US'],
 'Israel Weapon Industries (IWI) is a private Israeli firearms manufacturer spun off from IMI (Israel Military Industries) in 2005, when the Israeli government privatized its small arms division. IMI itself traces to 1933 as part of the pre-state Haganah defense infrastructure. IWI produces the Tavor, Galil, Jericho, and Negev platforms. IWI US, Inc. operates from Middletown, Pennsylvania, manufacturing US-legal versions of IWI designs for the American civilian and law enforcement market.',
 ARRAY['Tavor SAR','X95','Galil ACE','Jericho 941','Negev LMG'],
 ARRAY['Tavor bullpup','Galil','Jericho pistol','Military rifles'],
 NULL, true, 'IDF standard service rifle (Tavor); Negev LMG (IDF); Jericho pistol (IDF)',
 999, 'premium', 'Independent', 'Mid',
 'Active Import', 'Israel',
 'The Tavor SAR became the first bullpup rifle adopted as a primary service rifle by a Western military (IDF, 2009) since the British SA80 in 1985. The bullpup layout gives the Tavor carbine-length maneuverability with a full 16-inch barrel — a combination no conventional-layout rifle can match.',
 'iwi.us', 'Middletown, PA'),

('Zastava Arms',
 ARRAY['Zastava','Zastava Oruzje','ZPAP'],
 'Serbia', 1853, true, 'Manufacturer',
 ARRAY['Rifle','Handgun'],
 'Serbian state (partial)', NULL,
 'Serbian arms manufacturer founded in Kragujevac in 1853 as the Royal Serbian Factory of Artillery. Zastava produced Yugoslav-pattern AK rifles (the M70, M92) and the CZ99/EZ9 pistol family during the Yugoslav era. Post-dissolution, Zastava became a major exporter, with the ZPAP M70 AK-pattern rifle becoming one of the most popular AK variants imported into the United States. Also produces the EZ9 and CZ999 pistol series.',
 ARRAY['ZPAP M70','ZPAP M92','EZ9','CZ999'],
 ARRAY['AK-pattern rifles','Semi-automatic pistols'],
 NULL, true, 'Serbian Armed Forces; former Yugoslav military',
 699, 'mass', 'State-owned', 'High',
 'Active Import', 'Serbia',
 'Zastava''s Kragujevac factory has been producing weapons for over 170 years — through the Ottoman Empire''s decline, both World Wars, the Kingdom of Yugoslavia, Communist Yugoslavia, the civil war of the 1990s, and the modern Serbian state. The continuity of manufacturing on the same site is remarkable.',
 'zastava-arms.rs', 'Kragujevac, Serbia'),

('Bersa',
 ARRAY['Bersa Argentina'],
 'Argentina', 1958, true, 'Manufacturer',
 ARRAY['Handgun'],
 'Industrias de Armas Bersa S.A.', NULL,
 'Argentine firearms manufacturer founded in 1958 in Ramos Mejía, Buenos Aires. Known for the Thunder series — .380 ACP, 9mm, and .45 ACP semi-automatic pistols — which sold hundreds of thousands of units in the US as budget compact carry guns before import complications arose. The Thunder 380 occupies the same market as the Walther PPK but at a fraction of the price. Still widely available in South America.',
 ARRAY['Thunder 380','Thunder 9','Thunder 45','BP9CC'],
 ARRAY['Budget compact pistols','Concealed carry pistols'],
 NULL, false, NULL,
 250, 'mass', 'Independent', 'Mid',
 'Active Import', 'Argentina',
 'The Bersa Thunder 380 was for years the most affordable blowback .380 pistol available in the US that wasn''t a pot-metal Saturday night special. For buyers who wanted PPK aesthetics and reliability at a fraction of the cost, the Bersa was the answer.',
 'bersa.com', 'Ramos Mejía, Argentina'),

('Taurus',
 ARRAY['Taurus Armas','Taurus USA','Forjas Taurus'],
 'Brazil', 1939, true, 'Manufacturer',
 ARRAY['Handgun','Rifle'],
 'Taurus Armas S.A.', ARRAY['Rossi','Heritage Manufacturing'],
 'Brazilian firearms manufacturer founded in 1939 in Porto Alegre, Rio Grande do Sul. Taurus Armas is one of the largest firearms manufacturers in the Western Hemisphere by volume. Best known for the Judge (combination .45 LC/.410 shotshell revolver), G2C and G3 polymer pistols, and an extensive revolver line. Owns Rossi and Heritage Manufacturing. The G2C is consistently one of the top-selling pistols in the United States by unit volume.',
 ARRAY['Judge','G2C','G3','TX22','692 Revolver','Spectrum'],
 ARRAY['Budget revolvers','Budget pistols','Polymer pistols'],
 NULL, true, 'Brazilian Federal Police and military contracts; various South American law enforcement',
 200, 'mass', 'Public', 'Mass',
 'Active Import', 'Brazil',
 'The Taurus Judge fires both .45 Colt revolver cartridges and .410 bore shotshells from the same cylinder. When introduced in 2006, it became Taurus''s best-selling product almost immediately — a reminder that the American market has an enduring fascination with combination firearms.',
 'taurususa.com', 'Bainbridge, GA'),

('Norinco',
 ARRAY['China North Industries Group','NORINCO','North Industries'],
 'China', 1980, true, 'Military Arsenal',
 ARRAY['Rifle','Handgun','Shotgun'],
 'Chinese state (SASAC)', NULL,
 'Chinese state-owned arms and defense corporation, established in 1980 as a commercial export arm of Chinese military industries. Norinco produced AK-pattern and SKS rifles that flooded the US market at extraordinarily low prices in the 1980s and early 1990s before import restrictions tightened significantly. The Type 54 (TT-33 copy) pistol, Type 56 (AK copy), and Type 81 rifle were among their most widely imported products. Now primarily a defense contractor with limited US civilian presence.',
 ARRAY['Type 56','Type 81','Type 54 pistol','NHM-91','PolyTech Legend'],
 ARRAY['AK-pattern rifles','Budget military-pattern rifles'],
 NULL, true, 'People''s Liberation Army primary small arms supplier',
 NULL, 'military', 'State-owned', 'Mass',
 'Import Banned', 'China',
 'Norinco AK-pattern rifles imported in the late 1980s — the PolyTech Legend and Milled AK — are now among the most collected AK variants in the US. Their import ban under the 1994 Crime Bill and subsequent executive orders makes surviving pre-ban examples increasingly valuable.',
 'norinco.com', 'Beijing, China'),

('Tula Arms Plant',
 ARRAY['Tula','TOZ','TsKIB SOO'],
 'Russia', 1712, true, 'Military Arsenal',
 ARRAY['Rifle','Handgun','Shotgun'],
 'Russian state (Rostec)', NULL,
 'Russian state arms manufacturer founded by decree of Peter the Great in 1712 in Tula, the historic center of Russian arms production. One of the oldest continuously operating weapons manufacturers in the world. Produces the TOZ shotgun series, Tokarev TT pistol, SVT semi-auto rifle, and is responsible for production of the 7N6 5.45×39 military cartridge. Tula arsenal marks appear on millions of historical Russian firearms.',
 ARRAY['TOZ-34 shotgun','TOZ-17 rimfire','Tokarev TT','SVT-40'],
 ARRAY['Military rifles','Shotguns','Historical Russian arms'],
 NULL, true, 'Russian Armed Forces historical primary supplier; current ammunition production',
 NULL, 'military', 'State-owned', 'Mass',
 'Import Banned', 'Russia',
 'The Tula Arms Plant was founded by order of Peter the Great in 1712, who recognized that Russia''s military expansion required domestic arms production. Over 300 years later, the factory is still operating on the same site — making it one of the oldest continuously operating manufacturers of any kind in the world.',
 NULL, 'Tula, Russia'),

('Steyr Arms',
 ARRAY['Steyr','Steyr Mannlicher','Steyr-Daimler-Puch'],
 'Austria', 1864, true, 'Manufacturer',
 ARRAY['Rifle','Handgun'],
 'Steyr Arms GmbH', NULL,
 'Austrian firearms manufacturer with roots to 1864 in Steyr, Upper Austria. The original Österreichische Waffenfabriksgesellschaft (OWG) produced rifles for the Austro-Hungarian Empire including the Mannlicher-pattern straight-pull rifles. Modern Steyr Arms produces the AUG bullpup assault rifle (Austrian standard service weapon since 1977), the SSG sniper rifle series, and the M-series and L9-A2 pistols. The AUG''s bullpup layout predated and influenced most subsequent military bullpup designs.',
 ARRAY['AUG','SSG 08','SSG 69','M9-A2','Scout'],
 ARRAY['AUG bullpup','Precision sniper rifles','Semi-automatic pistols'],
 NULL, true, 'Austrian Army standard rifle (AUG); SSG sniper rifles used by multiple militaries',
 1500, 'premium', 'Independent', 'Mid',
 'Active Import', 'Austria',
 'The Steyr AUG, adopted by the Austrian Army in 1977, was the world''s first modern bullpup assault rifle to achieve widespread military adoption. Its transparent magazine, integral 1.5x optic, and modular design were all ahead of their time — and are features still being imitated in designs developed decades later.',
 'steyr-arms.com', 'Steyr, Austria'),

-- ═══════════════════════════════════════════════════════════════
-- HISTORIC / DEFUNCT MAKERS
-- ═══════════════════════════════════════════════════════════════

('Parker Brothers',
 ARRAY['Parker','Parker Guns'],
 'USA', 1832, false, 'Defunct Maker',
 ARRAY['Shotgun'],
 'Remington Arms (acquired 1934)', NULL,
 'American shotgun manufacturer founded by Charles Parker in Meriden, Connecticut in 1832. Parker Brothers produced what many consider the finest American double-barrel shotguns ever made — the Parker shotgun was the choice of affluent hunters, wing shooters, and sportsmen for generations. Acquired by Remington in 1934 and eventually discontinued. Parker guns, particularly the rare A-1 Special grade, now command six-figure prices at auction. Winchester produced a replica from 1987–1989.',
 ARRAY['VH Grade','GH Grade','DH Grade','A-1 Special'],
 ARRAY['Side-by-side shotguns','Double-barrel shotguns'],
 NULL, false, NULL,
 NULL, 'collector', 'Subsidiary', 'Micro',
 'Historical', 'USA',
 'A Parker A-1 Special shotgun in pristine condition can fetch $200,000 or more at auction — for a gun manufactured before 1934. Parker''s reputation for quality was so enduring that Winchester attempted a replica in 1987, and modern craftsmen still restore Parkers as a specialized profession.',
 NULL, 'Meriden, CT'),

('L.C. Smith',
 ARRAY['Hunter Arms','LC Smith'],
 'USA', 1878, false, 'Defunct Maker',
 ARRAY['Shotgun'],
 'Marlin (acquired 1945)', NULL,
 'American shotgun manufacturer founded by Lyman Cornelius Smith in Syracuse, New York in 1878. L.C. Smith side-by-side shotguns were among the finest American sporting guns ever produced, known for their fluid steel barrels, tight fitting, and exceptional balance. The company was acquired by Hunter Arms Company in 1890 and by Marlin in 1945. L.C. Smith shotguns with fluid steel barrels are safe to shoot with modern loads and remain prized by collectors.',
 ARRAY['Field Grade','Specialty Grade','Crown Grade'],
 ARRAY['Side-by-side shotguns'],
 ARRAY['Lyman Cornelius Smith'], false, NULL,
 NULL, 'collector', 'Subsidiary', 'Micro',
 'Historical', 'USA',
 'The L.C. Smith was one of the few American shotguns ever made with a true sidelock — rather than a boxlock — action. This made it significantly more expensive to produce and significantly more beautiful in profile. A pristine Crown Grade L.C. Smith is considered the equal of many British guns.',
 NULL, 'Syracuse, NY'),

('Harrington & Richardson',
 ARRAY['H&R','H&R 1871','New England Firearms','NEF'],
 'USA', 1871, false, 'Defunct Maker',
 ARRAY['Rifle','Shotgun','Handgun'],
 'Freedom Group (final owner)', ARRAY['New England Firearms'],
 'American manufacturer founded by Gilbert Harrington and William Richardson in Worcester, Massachusetts in 1871. H&R produced reliable, affordable single-shot rifles, shotguns, and revolvers for over a century, serving the working-class American shooter. The H&R Topper single-shot shotgun was one of the most widely owned firearms in rural America. H&R ceased operations in 1986, was reorganized, acquired New England Firearms in 1991, and finally shut down under Freedom Group in 2015.',
 ARRAY['Topper','Ultra Slug Hunter','Pardner','Handi-Rifle'],
 ARRAY['Single-shot shotguns','Single-shot rifles','Budget firearms'],
 NULL, false, NULL,
 NULL, 'collector', 'Independent', 'Mid',
 'Historical', 'USA',
 'The H&R Topper was the first firearm for millions of rural American kids — an indestructible single-shot shotgun that could be handed down through families, dropped in a muddy ditch, and still harvest a turkey. When H&R closed in 2015, it ended 144 years of making honest, affordable American firearms.',
 NULL, 'Gardner, MA'),

-- ═══════════════════════════════════════════════════════════════
-- ADDITIONAL SIGNIFICANT MAKERS
-- ═══════════════════════════════════════════════════════════════

('Chiappa Firearms',
 ARRAY['Chiappa','Armi Sport'],
 'Italy', 1958, true, 'Manufacturer',
 ARRAY['Rifle','Handgun','Shotgun'],
 NULL, NULL,
 'Italian manufacturer founded by Ezechiele Chiappa in Azzano Mella in 1958 as Armi Sport. Produces an eclectic mix of reproduction revolvers, lever-action rifles, tactical shotguns, and the unique Rhino revolver. The Rhino fires from the bottom chamber of the cylinder rather than the top, dramatically reducing felt recoil and muzzle flip. Also produces M1 Carbine reproductions and 1887 Winchester lever-action shotgun reproductions.',
 ARRAY['Rhino','Little Badger','Triple Threat','1887 Lever Shotgun','M9-22'],
 ARRAY['Rhino revolver','Lever-action shotguns','Innovative designs'],
 NULL, false, NULL,
 200, 'mass', 'Independent', 'Mid',
 'Active Import', 'Italy',
 'The Chiappa Rhino fires from the lowest chamber of the cylinder — directly in line with the shooter''s hand — rather than the top chamber. This eliminates the lever-arm effect that causes conventional revolvers to flip upward during recoil. The design was patented by Emilio Ghisoni, who also designed the Mateba autorevolver.',
 'chiappafirearms.com', 'Azzano Mella, Italy'),

('Stoeger',
 ARRAY['Stoeger Industries'],
 'USA', 1924, true, 'Brand',
 ARRAY['Shotgun','Handgun'],
 'Beretta Holding', NULL,
 'American brand under Beretta Holding, founded in 1924 in New York by A.F. Stoeger as an importer of Luger pistols. Now primarily a value-segment shotgun brand, producing the Condor over/under and Coach Gun side-by-side under its own name while the manufacturing is conducted by Beretta''s supply chain. The Stoeger Luger (an American-made copy of the P08) was produced in the 1990s. Stoeger is the US distributor for several Beretta Holding brands.',
 ARRAY['Condor','Coach Gun','M3000','P3000'],
 ARRAY['Over/under shotguns','Side-by-side shotguns'],
 NULL, false, NULL,
 299, 'mass', 'Subsidiary', 'High',
 'Domestic', 'USA',
 'Stoeger''s original business was importing German Luger pistols to the United States — they were the authorized US Luger distributor for decades. A.F. Stoeger also wrote "The Shooter''s Bible," which became the most widely read firearms catalog in America and is still published annually.',
 'stoegerindustries.com', 'Accokeek, MD'),

('Franchi',
 ARRAY['Luigi Franchi'],
 'Italy', 1868, true, 'Brand',
 ARRAY['Shotgun'],
 'Beretta Holding', NULL,
 'Italian shotgun manufacturer founded by Luigi Franchi in Brescia in 1868. Known for the AL-48 long-recoil semi-automatic shotgun — one of the lightest production shotguns ever made — and the Instinct over/under series. Acquired by Beretta Holding in 1987. The Franchi SPAS-12 combat shotgun, while no longer in production, became iconic through its appearance in Jurassic Park and numerous films of the 1980s–90s.',
 ARRAY['Affinity','Instinct','SPAS-12','AL-48'],
 ARRAY['Semi-automatic shotguns','Over/under shotguns'],
 NULL, true, 'SPAS-12 used by various military and police units',
 799, 'premium', 'Subsidiary', 'Mid',
 'Active Import', 'Italy',
 'The Franchi SPAS-12 appeared in the original Jurassic Park and dozens of action films, becoming the visual shorthand for "serious tactical shotgun" in 1980s and 90s cinema. In reality, its dual pump/semi-auto mechanism was complex and unreliable — but as a movie prop it was perfect.',
 'franchiusa.com', 'Brescia, Italy'),

('Korth',
 ARRAY['Korth Germany','Korth Waffen'],
 'Germany', 1955, true, 'Manufacturer',
 ARRAY['Handgun'],
 NULL, NULL,
 'German precision manufacturer of handguns, founded by Willi Korth in Ratzeburg in 1955. Produces what are widely considered the finest production revolvers in the world — machined to tolerances that make most revolvers look crude by comparison. The Korth NXS and Combat revolver are hand-fitted by master craftsmen and priced accordingly ($4,000–$10,000). Also produces the Sky Marshal and PRS semi-automatic pistol.',
 ARRAY['NXS','Classic','Combat','Sky Marshal'],
 ARRAY['Ultra-premium revolvers'],
 ARRAY['Willi Korth'], false, NULL,
 4500, 'ultra-premium', 'Independent', 'Micro',
 'Active Import', 'Germany',
 'Korth revolvers are machined to tolerances tighter than most precision rifles. The cylinder gap — the space between cylinder and barrel — on a Korth is typically measured in tenths of a thousandth of an inch. Smith & Wesson considers 0.006" acceptable; Korth considers 0.001" the standard.',
 'korth-waffen.de', 'Ratzeburg, Germany'),

('Daniel Defense',
 ARRAY['DD'],
 'USA', 2000, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'American AR-platform manufacturer founded by Marty Daniel in Black Creek, Georgia in 2000. Daniel Defense began making rail systems and handguards for military and law enforcement before transitioning to complete rifles. The DD M4V7 is one of the most respected mil-spec AR-15 platforms in the market. Daniel Defense rifles are issued to various US special operations units and are used by competitive 3-gun shooters.',
 ARRAY['M4V7','DDM4 V11','Delta 5 Pro','DD5V4'],
 ARRAY['AR-platform rifles','Military-grade rifles'],
 NULL, true, 'Various US SOCOM units; law enforcement contracts',
 1800, 'premium', 'Independent', 'Mid',
 'Domestic', 'USA',
 'Daniel Defense started making rail systems because Marty Daniel couldn''t find the handguard he wanted for his own AR-15. That handguard ended up being adopted by US Special Operations Forces — the same customer he had originally hoped to impress.',
 'danieldefense.com', 'Black Creek, GA'),

('Aero Precision',
 ARRAY['Aero'],
 'USA', 1994, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Tacoma, Washington manufacturer of AR-15 and AR-10 platform components and complete rifles, founded in 1994 as an aerospace precision machining company. Aero Precision is the dominant supplier of stripped AR receivers to the build-it-yourself market and produces complete rifles under the M4E1 and M5 lines. Known for exceptional quality-to-price ratio — their receivers are used as the baseline for countless custom builds.',
 ARRAY['M4E1','M5','EPC-9','SOLUS Competition'],
 ARRAY['AR-platform components','Precision receivers'],
 NULL, false, NULL,
 999, 'mass', 'Independent', 'High',
 'Domestic', 'USA',
 'Aero Precision started as an aerospace machining contractor — the precision tolerances required for aircraft components translated directly to firearm receivers. Their aerospace background is why Aero receivers are considered the quality baseline against which all other stripped AR lowers are measured.',
 'aeroprecisionusa.com', 'Tacoma, WA'),

('Bravo Company (BCM)',
 ARRAY['BCM','Bravo Company USA'],
 'USA', 2005, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Wisconsin AR-platform manufacturer founded by Paul Buffoni in 2005. BCM occupies the professional tier of the AR market — not the custom boutique level, but purpose-built for professional users. BCM rifles are used by military, law enforcement, and serious competition shooters. Known for their commitment to mil-spec manufacturing, the BCMGUNFIGHTER line of furniture, and the Recce series carbines.',
 ARRAY['Recce-16','Recce-14','Recce-11','MCMR'],
 ARRAY['Professional AR rifles','Mil-spec AR components'],
 NULL, true, 'Various law enforcement and military training units',
 1400, 'premium', 'Independent', 'Mid',
 'Domestic', 'USA',
 'BCM was founded on the observation that most AR-15 manufacturers were building to a price, not a standard. Paul Buffoni set out to build every rifle as if a professional''s life depended on it — which for law enforcement and military customers, it does.',
 'bravocompanyusa.com', 'Hartland, WI'),

('SilencerCo',
 ARRAY['SilencerCo Sparrow','SilencerCo Omega'],
 'USA', 2008, true, 'Manufacturer',
 ARRAY['Suppressor'],
 NULL, NULL,
 'Utah suppressor manufacturer founded by Joshua Waldron and Cameron Hopkins in West Valley City in 2008. SilencerCo has become the dominant civilian suppressor brand in the United States through innovative designs like the Omega 300, Salvo 12 shotgun suppressor, and Maxim 9 integrally suppressed pistol. Their marketing and design have done more to normalize civilian suppressor ownership than any other company except AAC.',
 ARRAY['Omega 300','Omega 45K','Salvo 12','Maxim 9','Hybrid 46'],
 ARRAY['Suppressors','Integrally suppressed pistols'],
 NULL, true, 'Various law enforcement suppressor contracts',
 700, 'premium', 'Independent', 'Mid',
 'Domestic', 'USA',
 'SilencerCo''s Maxim 9 is the world''s first commercially produced integrally suppressed 9mm pistol — the entire suppressor is built into the slide, making it no longer than a conventional full-size pistol. It sounds like a Hollywood suppressor and looks like nothing else on the market.',
 'silencerco.com', 'West Valley City, UT'),

('Christensen Arms',
 ARRAY['Christensen'],
 'USA', 1995, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Utah manufacturer of carbon fiber-wrapped rifle barrels and complete bolt-action rifles, founded by Roland Christensen in 1995. Pioneered the use of carbon fiber in rifle barrels for hunting — producing barrels that are lighter than steel but nearly equivalent in stiffness. The Mesa, Ridgeline, and Modern Precision Rifle lines have become the dominant choices in the lightweight precision hunting market. Manufactured in Gunnison, Utah.',
 ARRAY['Mesa','Ridgeline','MPR','Modern Precision Rifle','ELR'],
 ARRAY['Carbon fiber barrels','Lightweight hunting rifles','Precision rifles'],
 NULL, false, NULL,
 1500, 'premium', 'Independent', 'Mid',
 'Domestic', 'USA',
 'Christensen Arms proved that carbon fiber-wrapped rifle barrels could hold match-grade accuracy while weighing significantly less than steel equivalents. A carbon-fiber barrel on a chassis stock cut 2 pounds from traditional mountain rifles — enough to matter over 10 miles of elk country.',
 'christensenarms.com', 'Gunnison, UT'),

('Proof Research',
 ARRAY['PROOF Research'],
 'USA', 2012, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Montana manufacturer of ultra-premium carbon fiber rifle barrels and complete precision rifles, founded in Columbia Falls in 2012. Proof Research barrels are used by military and law enforcement snipers and are the industry standard for combination of light weight and match-grade accuracy. Their Summit and Glacier Ti titanium-actioned rifles are among the most technically sophisticated production rifles available.',
 ARRAY['Summit','Glacier Ti','Elevation MTR','Tundra Ti'],
 ARRAY['Carbon fiber barrels','Precision rifles','Military sniper barrels'],
 NULL, true, 'Various US military and SOCOM sniper barrel contracts',
 3500, 'ultra-premium', 'Independent', 'Micro',
 'Domestic', 'USA',
 'Proof Research carbon fiber barrels are issued to US military snipers who need accuracy without the weight penalty of steel — critical in mountain warfare where every pound matters over hundreds of miles of patrol. Their barrels have been confirmed in use by Delta Force and other SOCOM units.',
 'proofresearch.com', 'Columbia Falls, MT'),

('CMMG',
 ARRAY['CMMG Inc'],
 'USA', 2002, true, 'Manufacturer',
 ARRAY['Rifle','Handgun'],
 NULL, NULL,
 'Missouri AR-platform and pistol-caliber carbine manufacturer, founded in 2002 in Fayette, Missouri. Best known as the innovator of the Radial Delayed Blowback (RDB) operating system — which allows 9mm, .45 ACP, and other pistol cartridges to be fired reliably in an AR-pattern action without a buffer tube. The Banshee series pistol-caliber carbines using this system are among the most popular PCCs in the market.',
 ARRAY['Banshee 9mm','Resolute','Mk47 Mutant','Mk57'],
 ARRAY['Pistol-caliber carbines','AR-platform rifles'],
 NULL, false, NULL,
 1000, 'premium', 'Independent', 'Mid',
 'Domestic', 'USA',
 'CMMG''s Radial Delayed Blowback system solved the fundamental problem of pistol-caliber AR carbines: uncontrolled blowback in an AR action produces a brutal, unreliable cycling behavior. By adding a rotating delay to the bolt, CMMG made the 9mm AR platform genuinely reliable and pleasant to shoot.',
 'cmmginc.com', 'Fayette, MO'),

('Weatherby',
 ARRAY['Weatherby Inc'],
 'USA', 1945, true, 'Manufacturer',
 ARRAY['Rifle','Shotgun'],
 NULL, NULL,
 'American firearms manufacturer founded by Roy Weatherby in 1945 in South Gate, California, now headquartered in Sheridan, Wyoming. Weatherby created and commercialized the magnum hunting rifle concept — the .300 Weatherby Magnum, .340 Weatherby, and .460 Weatherby remain among the most powerful hunting cartridges available. Known for distinctive high-gloss stocks, Monte Carlo cheekpieces, and the Mark V bolt action with nine locking lugs. Rifles were historically manufactured in Germany (Sauer) and Japan (Howa).',
 ARRAY['Mark V','Vanguard','Camilla','307'],
 ARRAY['Magnum hunting rifles','Precision bolt-action rifles'],
 ARRAY['Roy Weatherby'], false, NULL,
 1000, 'premium', 'Independent', 'Mid',
 'Domestic', 'USA',
 'Roy Weatherby believed that faster was always better — and spent his career proving it by designing cartridges that pushed bullets 300–500 fps faster than anything else available. His .460 Weatherby Magnum remains the most powerful commercially loaded cartridge capable of being fired from a bolt-action rifle.',
 'weatherby.com', 'Sheridan, WY'),

('LaRue Tactical',
 ARRAY['LaRue','LaRue Precision'],
 'USA', 1993, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Texas AR-platform manufacturer founded by Mark LaRue in Leander, Texas in 1993. Known for exceptional quality AR-15 and AR-10 rifles, the PredatAR series, and the Optimized Battle Rifle (OBR). LaRue pioneered the use of quick-detach (QD) optic mounts — the LaRue LT Trijicon mount became the standard against which all QD mounts are measured. LaRue became famous for shipping free bumper stickers with every order, building one of the most loyal customer followings in the AR market.',
 ARRAY['OBR 5.56','OBR 7.62','PredatAR','Stealth'],
 ARRAY['Precision AR rifles','QD optic mounts'],
 NULL, true, 'US SOCOM optic mounts; various military rifle contracts',
 2400, 'ultra-premium', 'Independent', 'Boutique',
 'Domestic', 'USA',
 'LaRue Tactical''s QD optic mounts are so trusted by US special operations forces that they have been standard issue for some SOCOM units. Mark LaRue also became famous for his "We the People" policies during various ammunition shortages — limiting sales to civilians when law enforcement and military had purchased what they needed.',
 'larue.com', 'Leander, TX'),

('JP Enterprises',
 ARRAY['JP','JP Rifles'],
 'USA', 1995, true, 'Manufacturer',
 ARRAY['Rifle'],
 NULL, NULL,
 'Minnesota precision AR and competition rifle manufacturer founded by John Paul in Hugo, Minnesota in 1995. JP Enterprises produces some of the most refined competition-grade AR-15 and AR-10 rifles in the market, including the SCR-11 and LRP-07 series. Known for the JP adjustable gas system, Silent Captured Spring buffer system, and the JP Enterprises trigger — components that define the performance upper tier of the AR platform.',
 ARRAY['SCR-11','LRP-07','GMR-15','PSC-12'],
 ARRAY['Competition AR rifles','Precision AR components'],
 NULL, false, NULL,
 2200, 'ultra-premium', 'Independent', 'Micro',
 'Domestic', 'USA',
 'JP Enterprises'' Silent Captured Spring system eliminated the characteristic "sproing" sound of the standard AR buffer spring that has irritated shooters since Eugene Stoner''s original design. It is now standard on virtually every serious competition AR build.',
 'jprifles.com', 'Hugo, MN')

ON CONFLICT (name) DO NOTHING;
