-- Gun models for manufacturers F through K (batch 2 of 3)

INSERT INTO public.gun_models (
  make, model, caliber, type, action, capacity, year_introduced,
  discontinued, country_of_origin, description, msrp_usd,
  weight_oz_unloaded, overall_length_in, military_use, law_enforcement_use,
  notable_variants, production_status, platform_family, caliber_options,
  model_aliases, era, trigger_type, intended_use, trivia,
  country_of_manufacture, is_collectible, collector_notes
) VALUES

-- FABARM
('Fabarm', 'L4S', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 2014, false, 'Italy',
 'Gas-operated semi-auto shotgun with PULSE PISTON system for reduced recoil.',
 1699, 74.0, 48.0, false, false,
 ARRAY['L4S Initial Hunter', 'L4S Sporting'],
 'Active', 'Fabarm L4S', ARRAY['12 Gauge'],
 ARRAY['l4s', 'fabarm l4s'], 'Modern', 'Trigger', ARRAY['hunting', 'sport'],
 'The Pulse Piston system vents gas earlier than competitors, reducing felt recoil.', 'Italy', false, NULL),

('Fabarm', 'SDASS', '12 Gauge', 'Shotgun', 'Semi-Auto', 5, 1995, false, 'Italy',
 'Tactical semi-auto shotgun for law enforcement and home defense. Pistol grip, ghost ring sights.',
 899, 80.0, 40.0, false, true,
 ARRAY['SDASS Tactical', 'SDASS Martial'],
 'Active', 'Fabarm SDASS', ARRAY['12 Gauge'],
 ARRAY['sdass', 'fabarm tactical'], 'Post-Cold War', 'Trigger', ARRAY['home defense', 'law enforcement'],
 NULL, 'Italy', false, NULL),

('Fabarm', 'XLR5', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 2018, false, 'Italy',
 'Premium sporting clays semi-auto with Tribore HP barrel and Ergal aluminum receiver.',
 2099, 78.0, 50.5, false, false,
 ARRAY['XLR5 Sporting', 'XLR5 Waterfowler'],
 'Active', 'Fabarm XLR5', ARRAY['12 Gauge'],
 ARRAY['xlr5', 'fabarm xlr'], 'Modern', 'Trigger', ARRAY['sport', 'hunting'],
 NULL, 'Italy', false, NULL),

-- FABRYKA BRONI RADOM
('Fabryka Broni Radom', 'MSBS Grot', '5.56x45mm NATO', 'Rifle', 'Semi-Auto', 30, 2017, false, 'Poland',
 'Modular assault rifle system adopted by the Polish Armed Forces. Replaces the Beryl.',
 NULL, 87.0, 35.0, true, true,
 ARRAY['Grot-S', 'Grot-B', 'Grot-K'],
 'Active', 'MSBS Grot', ARRAY['5.56x45mm NATO'],
 ARRAY['grot', 'msbs', 'fb radom grot'], 'Modern', 'Trigger', ARRAY['military', 'law enforcement'],
 'The Grot replaced the Soviet-era Beryl as Poland''s standard service rifle.', 'Poland', false, NULL),

('Fabryka Broni Radom', 'Beryl', '5.56x45mm NATO', 'Rifle', 'Semi-Auto', 30, 1997, false, 'Poland',
 'Polish AKM-derived assault rifle in 5.56mm NATO. Polish Army standard rifle for two decades.',
 NULL, 77.0, 37.0, true, true,
 ARRAY['Beryl M1', 'Mini-Beryl', 'Beryl M762'],
 'Active', 'Beryl', ARRAY['5.56x45mm NATO', '7.62x39mm'],
 ARRAY['beryl', 'kbs beryl', 'wz.96'], 'Post-Cold War', 'Trigger', ARRAY['military'],
 NULL, 'Poland', false, NULL),

('Fabryka Broni Radom', 'P-64', '9x18mm Makarov', 'Pistol', 'Semi-Auto', 6, 1965, true, 'Poland',
 'Polish military pistol based on the Walther PPK, standard sidearm through the Cold War.',
 300, 21.4, 6.3, true, true,
 ARRAY['P-64 commercial'],
 'Discontinued', 'P-64', ARRAY['9x18mm Makarov'],
 ARRAY['p64', 'czak', 'polish ppk'], 'Cold War', 'Double-Action', ARRAY['military', 'collector'],
 'The P-64 DA trigger pull exceeds 25 lbs — notorious among surplus buyers.', 'Poland', true,
 'Surplus imports popular as budget CCW. Heavy DA pull is the main complaint.'),

-- FEG
('FEG', 'PA-63', '9x18mm Makarov', 'Pistol', 'Semi-Auto', 7, 1963, true, 'Hungary',
 'Hungarian Walther PP copy in 9x18 Makarov. Standard Hungarian military sidearm through the Cold War.',
 250, 19.8, 6.9, true, true,
 ARRAY['PA-63 commercial'],
 'Discontinued', 'PA-63', ARRAY['9x18mm Makarov'],
 ARRAY['pa63', 'feg pa63', 'hungarian pp'], 'Cold War', 'Double-Action', ARRAY['military', 'collector'],
 NULL, 'Hungary', true, 'Popular budget import. Aluminum frame cracks under heavy use.'),

('FEG', 'P9R', '9mm Luger', 'Pistol', 'Semi-Auto', 14, 1984, true, 'Hungary',
 'Hungarian Browning Hi-Power copy. Used by the Hungarian military, exported commercially.',
 350, 32.0, 7.8, true, false,
 ARRAY['P9RK (compact)'],
 'Discontinued', 'FEG P9', ARRAY['9mm Luger'],
 ARRAY['p9r', 'feg hi-power', 'hungarian hi-power'], 'Cold War', 'Single-Action', ARRAY['military', 'collector'],
 NULL, 'Hungary', true, 'Mechanically similar to the BHP but inferior fit and finish. Very affordable.'),

('FEG', 'SMC-918', '9mm Short (.380 ACP)', 'Pistol', 'Semi-Auto', 7, 1990, true, 'Hungary',
 'Compact FEG pistol based on the Walther PPK, imported to the US in the 1990s.',
 200, 18.0, 6.5, false, false,
 ARRAY['SMC-380'],
 'Discontinued', 'FEG SMC', ARRAY['9mm Short (.380 ACP)'],
 ARRAY['smc918', 'feg smc'], 'Post-Cold War', 'Double-Action', ARRAY['concealed carry', 'collector'],
 NULL, 'Hungary', false, NULL),

-- FRANCHI
('Franchi', 'SPAS-12', '12 Gauge', 'Shotgun', 'Pump/Semi-Auto', 8, 1979, true, 'Italy',
 'Dual-mode pump/semi-auto tactical shotgun, iconic in film and TV. Now banned from import.',
 NULL, 97.0, 41.0, false, true,
 ARRAY['SPAS-12 folding stock', 'SPAS-12 fixed stock'],
 'Discontinued', 'Franchi SPAS', ARRAY['12 Gauge'],
 ARRAY['spas12', 'spas 12'], 'Cold War', 'Trigger', ARRAY['law enforcement', 'collector'],
 'Appeared in Jurassic Park and Terminator 2. The folding hook stock allows one-handed racking.',
 'Italy', true, 'Desirable collector piece. Folding stock variants command premiums.'),

('Franchi', 'AL-48', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 1948, false, 'Italy',
 'Long-recoil semi-auto shotgun with 70+ year production history.',
 849, 49.0, 45.0, false, false,
 ARRAY['AL-48 20 Gauge', 'AL-48 28 Gauge'],
 'Active', 'Franchi AL-48', ARRAY['12 Gauge', '20 Gauge', '28 Gauge'],
 ARRAY['al48', 'franchi al48'], 'Post-Cold War', 'Trigger', ARRAY['hunting', 'sport'],
 'Long-recoil: both barrel and bolt travel rearward together — one of the oldest semi-auto mechanisms still made.',
 'Italy', false, NULL),

('Franchi', 'Affinity', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 2013, false, 'Italy',
 'Inertia-operated semi-auto hunting shotgun with TSA recoil reducer in stock.',
 849, 71.0, 49.0, false, false,
 ARRAY['Affinity 3', 'Affinity 3.5', 'Affinity Catalyst'],
 'Active', 'Franchi Affinity', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['affinity', 'franchi affinity'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Italy', false, NULL),

-- GALESI
('Galesi', 'Model 9', '.32 ACP', 'Pistol', 'Semi-Auto', 8, 1930, true, 'Italy',
 'Small Italian semi-auto pocket pistol popular in the pre-WWII era.',
 NULL, 14.0, 5.0, false, false,
 ARRAY['Model 6', 'Model 12'],
 'Discontinued', 'Galesi Model', ARRAY['.32 ACP', '.25 ACP'],
 ARRAY['galesi 9', 'industria armi galesi'], 'World War II', 'Single-Action', ARRAY['collector'],
 NULL, 'Italy', true, 'Compact Italian pocket pistols. Fit and finish varies by era.'),

('Galesi', 'Model 6', '.25 ACP', 'Pistol', 'Semi-Auto', 6, 1920, true, 'Italy',
 'Pocket pistol in .25 ACP, common prewar Italian production.',
 NULL, 10.0, 4.5, false, false, ARRAY['Model 6 commercial'],
 'Discontinued', 'Galesi Model', ARRAY['.25 ACP'],
 ARRAY['galesi 6', 'galesi 25'], 'Interwar', 'Single-Action', ARRAY['collector'],
 NULL, 'Italy', true, NULL),

('Galesi', 'Model 12', '9mm Luger', 'Pistol', 'Semi-Auto', 8, 1950, true, 'Italy',
 'Postwar Galesi pistol in 9mm — last major model before the company ceased operations.',
 NULL, 26.0, 6.8, false, false, ARRAY['Model 12 commercial'],
 'Discontinued', 'Galesi Model', ARRAY['9mm Luger'],
 ARRAY['galesi 12', 'galesi 9mm'], 'Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'Italy', true, NULL),

-- GIRSAN
('Girsan', 'MC9', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2018, false, 'Turkey',
 'Full-size polymer striker-fired pistol imported by EAA Corporation.',
 399, 27.5, 7.6, false, false,
 ARRAY['MC9 Match', 'MC9 T'],
 'Active', 'Girsan MC9', ARRAY['9mm Luger'],
 ARRAY['mc9', 'girsan mc9', 'eaa mc9'], 'Modern', 'Striker-Fired', ARRAY['home defense', 'concealed carry'],
 NULL, 'Turkey', false, NULL),

('Girsan', 'MC1911', '.45 ACP', 'Pistol', 'Semi-Auto', 8, 2010, false, 'Turkey',
 'Budget 1911-pattern pistol imported via EAA. Good value for the price.',
 499, 38.0, 8.5, false, false,
 ARRAY['MC1911 S', 'MC1911 C', 'MC1911 SC'],
 'Active', 'Girsan MC1911', ARRAY['.45 ACP', '9mm Luger'],
 ARRAY['mc1911', 'girsan 1911'], 'Modern', 'Single-Action', ARRAY['home defense', 'competition'],
 NULL, 'Turkey', false, NULL),

('Girsan', 'Regard MC', '9mm Luger', 'Pistol', 'Semi-Auto', 15, 2010, false, 'Turkey',
 'Browning Hi-Power-inspired double-stack pistol imported by EAA.',
 449, 34.0, 7.8, false, false,
 ARRAY['Regard MC Gen 3'],
 'Active', 'Girsan Regard', ARRAY['9mm Luger'],
 ARRAY['regard', 'girsan regard', 'eaa regard'], 'Modern', 'Single-Action', ARRAY['home defense'],
 NULL, 'Turkey', false, NULL),

-- GRAND POWER
('Grand Power', 'P1 Mk7', '9mm Luger', 'Pistol', 'Semi-Auto', 15, 2010, false, 'Slovakia',
 'Rotating barrel polymer pistol. Rotating barrel delays the action and reduces felt recoil.',
 599, 26.5, 7.4, false, false,
 ARRAY['P1 Mk12', 'P1 Ultra'],
 'Active', 'Grand Power P1', ARRAY['9mm Luger'],
 ARRAY['p1', 'grand power p1'], 'Modern', 'Double-Action', ARRAY['home defense', 'competition'],
 'Grand Power''s rotating barrel is one of the smoothest-shooting 9mms in its class.',
 'Slovakia', false, NULL),

('Grand Power', 'K100 Mk7', '9mm Luger', 'Pistol', 'Semi-Auto', 15, 2000, false, 'Slovakia',
 'Original Grand Power rotating barrel pistol, predecessor to the P1.',
 549, 27.0, 7.6, false, false,
 ARRAY['K100 Mk9', 'K100 Match'],
 'Active', 'Grand Power K100', ARRAY['9mm Luger'],
 ARRAY['k100', 'grand power k100'], 'Modern', 'Double-Action', ARRAY['home defense', 'competition'],
 NULL, 'Slovakia', false, NULL),

('Grand Power', 'T12', '9mm Luger', 'Pistol', 'Semi-Auto', 15, 2016, false, 'Slovakia',
 'Compact rotating barrel carry pistol with polymer frame.',
 549, 24.0, 6.8, false, false, ARRAY['T12F'],
 'Active', 'Grand Power T12', ARRAY['9mm Luger'],
 ARRAY['t12', 'grand power t12'], 'Modern', 'Double-Action', ARRAY['concealed carry'],
 NULL, 'Slovakia', false, NULL),

-- HARRINGTON & RICHARDSON
('Harrington & Richardson', 'Topper', '12 Gauge', 'Shotgun', 'Break-Action', 1, 1946, false, 'United States',
 'Single-shot break-action shotgun — one of the most affordable and reliable entry guns ever made.',
 199, 46.0, 43.0, false, false,
 ARRAY['Topper Deluxe', 'Topper Jr.', 'Topper 098'],
 'Active', 'H&R Topper', ARRAY['12 Gauge', '20 Gauge', '.410 Bore'],
 ARRAY['topper', 'h&r topper'], 'Post-Cold War', 'Trigger', ARRAY['hunting', 'home defense'],
 'The H&R Topper has been a staple first shotgun and farm gun for generations of American shooters.',
 'United States', false, NULL),

('Harrington & Richardson', '999 Sportsman', '.22 LR', 'Revolver', 'Double-Action', 9, 1932, true, 'United States',
 'Top-break 9-shot revolver in .22 LR. Beloved target and small game revolver.',
 NULL, 30.0, 10.5, false, false,
 ARRAY['999 Deluxe', '999 Premier'],
 'Discontinued', 'H&R 999', ARRAY['.22 LR'],
 ARRAY['999', 'h&r 999', 'sportsman'], 'Post-Cold War', 'Double-Action', ARRAY['hunting', 'collector'],
 'Top-break action ejects all 9 spent cases simultaneously.',
 'United States', true, 'Well-made target revolvers at budget prices. Highly collectible.'),

('Harrington & Richardson', 'Handi-Rifle', '.223 Remington', 'Rifle', 'Break-Action', 1, 1989, false, 'United States',
 'Single-shot break-action rifle with interchangeable barrels across many calibers.',
 279, 52.0, 42.0, false, false,
 ARRAY['Handi-Rifle Ultra', 'Handi-Rifle Youth'],
 'Active', 'H&R Handi', ARRAY['.223 Remington', '.243 Winchester', '.30-06 Springfield', '.308 Winchester'],
 ARRAY['handi rifle', 'h&r handi'], 'Modern', 'Trigger', ARRAY['hunting'],
 'Barrels are interchangeable — one receiver can serve many calibers.', 'United States', false, NULL),

-- HATSAN
('Hatsan', 'Escort', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 2000, false, 'Turkey',
 'Gas-operated semi-auto hunting and home defense shotgun. Popular budget Turkish import.',
 349, 73.0, 46.0, false, false,
 ARRAY['Escort PS', 'Escort AS', 'Escort MP', 'Escort Tactical'],
 'Active', 'Hatsan Escort', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['escort', 'hatsan escort'], 'Modern', 'Trigger', ARRAY['hunting', 'home defense'],
 NULL, 'Turkey', false, NULL),

('Hatsan', 'Optima', '12 Gauge', 'Shotgun', 'Over-Under', 2, 2010, false, 'Turkey',
 'Budget over-under for hunting and sporting clays.',
 499, 78.0, 45.0, false, false,
 ARRAY['Optima Field', 'Optima Sporting'],
 'Active', 'Hatsan Optima', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['optima', 'hatsan optima'], 'Modern', 'Trigger', ARRAY['hunting', 'sport'],
 NULL, 'Turkey', false, NULL),

('Hatsan', 'Veyron', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 2015, false, 'Turkey',
 'Inertia-operated semi-auto in a bullpup configuration.',
 499, 65.0, 39.0, false, false, ARRAY['Veyron 20'],
 'Active', 'Hatsan Veyron', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['veyron', 'hatsan veyron'], 'Modern', 'Trigger', ARRAY['hunting', 'home defense'],
 'One of the only bullpup semi-auto shotguns in its price range.', 'Turkey', false, NULL),

-- HERITAGE MANUFACTURING
('Heritage Manufacturing', 'Rough Rider', '.22 LR', 'Revolver', 'Single-Action', 6, 1993, false, 'United States',
 'Single-action revolver styled after the Colt SAA. Available in .22 LR / .22 WMR combo.',
 169, 31.0, 9.5, false, false,
 ARRAY['Rough Rider .22 WMR', 'Rough Rider Tactical', 'Rough Rider Big Bore'],
 'Active', 'Heritage Rough Rider', ARRAY['.22 LR', '.22 WMR', '.357 Magnum'],
 ARRAY['rough rider', 'heritage rough rider', 'rr22'], 'Modern', 'Single-Action', ARRAY['plinking', 'hunting'],
 'Best-selling single-action revolver in the US by unit volume.',
 'United States', false, NULL),

('Heritage Manufacturing', 'Barkeep', '.22 LR', 'Revolver', 'Single-Action', 6, 2021, false, 'United States',
 'Snub-nose 2" single-action revolver styled after Old West growing guns.',
 199, 23.0, 6.5, false, false, ARRAY['Barkeep Boot'],
 'Active', 'Heritage Barkeep', ARRAY['.22 LR', '.22 WMR'],
 ARRAY['barkeep', 'heritage barkeep'], 'Modern', 'Single-Action', ARRAY['plinking'],
 NULL, 'United States', false, NULL),

('Heritage Manufacturing', 'Rancher Carbine', '.22 LR', 'Rifle', 'Semi-Auto', 12, 2020, false, 'United States',
 'Lever-action style .22 LR carbine designed to match the Rough Rider aesthetically.',
 299, 47.0, 34.0, false, false, ARRAY['Rancher Carbine .22 WMR'],
 'Active', 'Heritage Rancher', ARRAY['.22 LR', '.22 WMR'],
 ARRAY['rancher', 'heritage rancher'], 'Modern', 'Trigger', ARRAY['plinking', 'hunting'],
 NULL, 'United States', false, NULL),

-- HEYM
('Heym', 'SR 30', '.30-06 Springfield', 'Rifle', 'Bolt-Action', 4, 1994, false, 'Germany',
 'Premium German bolt-action with straight-pull bolt for faster follow-up shots.',
 3500, 96.0, 44.0, false, false,
 ARRAY['SR 30 Left-Hand', 'SR 30 Alpine'],
 'Active', 'Heym SR 30', ARRAY['.30-06 Springfield', '.308 Winchester', '9.3x62mm'],
 ARRAY['sr30', 'heym sr30'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Germany', false, NULL),

('Heym', 'Express', '.375 H&H Magnum', 'Rifle', 'Double', 2, 1950, false, 'Germany',
 'Premium German double rifle for dangerous game. Hand-fitted sidelocks.',
 15000, 128.0, 44.0, false, false,
 ARRAY['Express Magnum', 'Express Safari'],
 'Active', 'Heym Express', ARRAY['.375 H&H Magnum', '.470 NE', '.500 NE', '.458 Win Mag'],
 ARRAY['heym express double', 'heym double rifle'], 'Modern', 'Single-Action', ARRAY['hunting', 'collector'],
 'Hand-built Heym double rifles take years to produce and are among the finest in the world.',
 'Germany', true, 'Significant collector value. Hand-engraved examples command very high premiums.'),

('Heym', 'Model 88B', '.375 H&H Magnum', 'Rifle', 'Bolt-Action', 4, 1988, false, 'Germany',
 'Premium Mauser-98 based bolt-action in dangerous game calibers.',
 5000, 112.0, 46.0, false, false,
 ARRAY['88B Safari', 'Magnum'],
 'Active', 'Heym 88B', ARRAY['.375 H&H Magnum', '.416 Rigby', '.458 Win Mag'],
 ARRAY['88b', 'heym 88b'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Germany', false, NULL),

-- HI-POINT FIREARMS
('Hi-Point Firearms', 'C9', '9mm Luger', 'Pistol', 'Semi-Auto', 8, 1995, false, 'United States',
 'Budget blowback 9mm pistol. Heaviest in class but extremely affordable. Lifetime warranty.',
 179, 29.0, 6.7, false, false, ARRAY['C9 Comp'],
 'Active', 'Hi-Point C', ARRAY['9mm Luger'],
 ARRAY['c9', 'hi point c9', 'hipoint 9mm'], 'Modern', 'Trigger', ARRAY['home defense'],
 'Hi-Point''s lifetime warranty covers all repairs or replacements regardless of ownership history.',
 'United States', false, NULL),

('Hi-Point Firearms', 'CF380', '.380 ACP', 'Pistol', 'Semi-Auto', 8, 1993, false, 'United States',
 'Budget .380 blowback pistol — among the heaviest and largest .380s made.',
 150, 28.0, 6.7, false, false, ARRAY['CF380 Comp'],
 'Active', 'Hi-Point CF', ARRAY['.380 ACP'],
 ARRAY['cf380', 'hi point 380'], 'Modern', 'Trigger', ARRAY['home defense'],
 NULL, 'United States', false, NULL),

('Hi-Point Firearms', '995 Carbine', '9mm Luger', 'Rifle', 'Semi-Auto', 10, 1996, false, 'United States',
 'Blowback 9mm carbine with polymer stock. Budget home defense carbine accepting pistol magazines.',
 349, 72.0, 31.5, false, false,
 ARRAY['995 TS', '4095 TS (.40 S&W)', '4595 TS (.45 ACP)'],
 'Active', 'Hi-Point Carbine', ARRAY['9mm Luger', '.40 S&W', '.45 ACP'],
 ARRAY['995', '995ts', 'hi point carbine'], 'Modern', 'Trigger', ARRAY['home defense'],
 NULL, 'United States', false, NULL),

-- HIGH STANDARD MANUFACTURING
('High Standard Manufacturing', 'Supermatic Trophy', '.22 LR', 'Pistol', 'Semi-Auto', 10, 1958, true, 'United States',
 'Premium .22 LR target pistol that dominated American bullseye competition in the 1960s–70s.',
 NULL, 44.0, 9.5, false, false,
 ARRAY['Supermatic Citation', 'Supermatic Tournament'],
 'Discontinued', 'High Standard Supermatic', ARRAY['.22 LR'],
 ARRAY['trophy', 'supermatic trophy', 'hs trophy'], 'Cold War', 'Single-Action', ARRAY['competition', 'collector'],
 'High Standard pistols won more NRA National Championships in the 1960s than any other brand.',
 'United States', true, 'Highly collectible. Post-1984 Houston-era guns are lower quality than Hamden-era.'),

('High Standard Manufacturing', 'Sentinel', '.22 LR', 'Revolver', 'Double-Action', 9, 1955, true, 'United States',
 'Aluminum-frame double-action revolver in .22 LR with swing-out cylinder.',
 NULL, 23.0, 9.0, false, false,
 ARRAY['Sentinel Deluxe', 'Sentinel Snub'],
 'Discontinued', 'High Standard Sentinel', ARRAY['.22 LR'],
 ARRAY['sentinel', 'hs sentinel'], 'Cold War', 'Double-Action', ARRAY['plinking', 'collector'],
 NULL, 'United States', true, NULL),

('High Standard Manufacturing', 'Flite King', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 1960, true, 'United States',
 'Pump-action shotgun from High Standard''s peak manufacturing years.',
 NULL, 58.0, 43.0, false, false,
 ARRAY['Flite King Deluxe', 'Flite King Brush'],
 'Discontinued', 'High Standard Flite King', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['flite king', 'hs flite king'], 'Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'United States', true, NULL),

-- HOLLAND & HOLLAND
('Holland & Holland', 'Royal Deluxe', '.375 H&H Magnum', 'Rifle', 'Double', 2, 1885, false, 'United Kingdom',
 'The pinnacle of British double rifle craftsmanship. Each takes 2+ years to hand-build.',
 80000, 132.0, 45.0, false, false,
 ARRAY['Royal Double Rifle', 'Royal Deluxe Sidelock'],
 'Active', 'H&H Royal', ARRAY['.375 H&H Magnum', '.470 NE', '.500 NE', '.700 NE'],
 ARRAY['royal', 'h&h royal', 'holland royal'], 'Modern', 'Single-Action', ARRAY['hunting', 'collector'],
 'H&H invented the .375 H&H Magnum cartridge in 1912 — still the world standard for dangerous game.',
 'United Kingdom', true, 'Among the most valuable sporting firearms in the world.'),

('Holland & Holland', 'Sporting Over-Under', '12 Gauge', 'Shotgun', 'Over-Under', 2, 1993, false, 'United Kingdom',
 'Premium hand-built British over-under for sporting clays and game shooting.',
 45000, 82.0, 46.0, false, false,
 ARRAY['Sporting Deluxe', 'Round Action'],
 'Active', 'H&H Sporting', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['h&h sporting', 'holland sporting'], 'Modern', 'Trigger', ARRAY['hunting', 'sport', 'collector'],
 NULL, 'United Kingdom', true, NULL),

('Holland & Holland', 'Paradox', '12 Gauge', 'Shotgun', 'Double', 2, 1885, true, 'United Kingdom',
 'Original "gun-rifle" — a shotgun with rifled chokes that could accurately fire slugs. Revolutionary in 1885.',
 NULL, 84.0, 44.0, false, false,
 ARRAY['Paradox 10 Bore', 'Paradox 8 Bore'],
 'Discontinued', 'H&H Paradox', ARRAY['12 Gauge', '8 Bore', '10 Bore'],
 ARRAY['paradox', 'h&h paradox'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['hunting', 'collector'],
 'H&H coined "Paradox" — paradoxical that a smooth bore could produce rifle accuracy.',
 'United Kingdom', true, 'Extremely collectible. Fine examples sell for $10,000–50,000+.'),

-- HOPKINS & ALLEN
('Hopkins & Allen', 'Safety Police', '.32 S&W', 'Revolver', 'Double-Action', 5, 1890, true, 'United States',
 'Top-break double-action revolver popular in the late 19th century.',
 NULL, 18.0, 7.0, false, false, ARRAY['Safety Police .38 S&W'],
 'Discontinued', 'Hopkins Allen Safety Police', ARRAY['.32 S&W', '.38 S&W'],
 ARRAY['h&a safety police', 'hopkins allen revolver'], 'Pre-WWI / Old West', 'Double-Action', ARRAY['collector'],
 NULL, 'United States', true, 'Affordable antique revolvers. Mostly of historical interest.'),

('Hopkins & Allen', 'XL Bulldog', '.32 S&W', 'Revolver', 'Double-Action', 5, 1880, true, 'United States',
 'Compact pocket revolver from the late 19th century.',
 NULL, 12.0, 5.5, false, false, ARRAY['XL Navy'],
 'Discontinued', 'Hopkins Allen XL', ARRAY['.32 S&W', '.38 S&W'],
 ARRAY['xl bulldog', 'hopkins allen bulldog'], 'Pre-WWI / Old West', 'Double-Action', ARRAY['collector'],
 NULL, 'United States', true, NULL),

('Hopkins & Allen', 'Falling Block Rifle', '.22 LR', 'Rifle', 'Single-Shot', 1, 1902, true, 'United States',
 'Simple falling-block single-shot .22 rifle sold through Sears and hardware stores.',
 NULL, 42.0, 38.0, false, false, ARRAY['No. 922', 'No. 925'],
 'Discontinued', 'Hopkins Allen Falling Block', ARRAY['.22 LR', '.22 Short'],
 ARRAY['h&a rifle', 'hopkins allen 22'], 'Pre-WWI / Old West', 'Trigger', ARRAY['collector'],
 NULL, 'United States', true, NULL),

-- HOWA
('Howa Machinery', '1500', '.308 Winchester', 'Rifle', 'Bolt-Action', 5, 1978, false, 'Japan',
 'Japanese bolt-action known for accuracy and quality. Basis for the Weatherby Vanguard series.',
 599, 85.0, 42.5, false, false,
 ARRAY['1500 Mini Action', '1500 Super Lite', '1500 HCR'],
 'Active', 'Howa 1500', ARRAY['.308 Winchester', '.243 Winchester', '.30-06 Springfield', '6.5 Creedmoor', '.223 Remington'],
 ARRAY['howa 1500', 'weatherby vanguard', 'mossberg 1500'], 'Modern', 'Trigger', ARRAY['hunting', 'competition'],
 'The Howa 1500 action is sold under the Weatherby Vanguard name — same rifle, two brands.',
 'Japan', false, NULL),

('Howa Machinery', 'HCR', '.308 Winchester', 'Rifle', 'Bolt-Action', 10, 2017, false, 'Japan',
 'Heavy Chassis Rifle — 1500 action in aluminum chassis with folding stock and AICS magazine.',
 999, 132.0, 46.0, false, false,
 ARRAY['HCR Bravo', 'HCR Wildcat'],
 'Active', 'Howa HCR', ARRAY['.308 Winchester', '6.5 Creedmoor', '.300 Win Mag'],
 ARRAY['hcr', 'howa hcr'], 'Modern', 'Trigger', ARRAY['competition', 'hunting'],
 NULL, 'Japan', false, NULL),

('Howa Machinery', 'M1100', '.22 LR', 'Rifle', 'Semi-Auto', 10, 1965, true, 'Japan',
 'Semi-auto .22 LR rifle from Howa''s early production years.',
 NULL, 56.0, 40.0, false, false, ARRAY['M1100 Deluxe'],
 'Discontinued', 'Howa M1100', ARRAY['.22 LR'],
 ARRAY['m1100', 'howa 22'], 'Cold War', 'Trigger', ARRAY['plinking', 'collector'],
 NULL, 'Japan', false, NULL),

-- IBM CORPORATION
('IBM Corporation', 'M1 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 15, 1943, true, 'United States',
 'WWII M1 Carbine manufactured by IBM under government contract. ~346,000 units produced.',
 NULL, 51.0, 35.6, true, false,
 ARRAY['IBM M1 Carbine (1943)', 'IBM M1 Carbine (1944)'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['ibm carbine', 'ibm m1', 'ibm m1 carbine'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 'IBM pivoted from typewriters and calculators to manufacturing rifles during WWII.',
 'United States', true, 'IBM-marked M1 Carbines sought by collectors. Good condition examples command premiums.'),

('IBM Corporation', 'M1A1 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 30, 1944, true, 'United States',
 'IBM-produced M1A1 folding-stock paratrooper carbine variant.',
 NULL, 51.0, 35.6, true, false, ARRAY['M1A1 folding stock'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['ibm m1a1', 'ibm paratrooper carbine'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

('IBM Corporation', 'M2 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 30, 1945, true, 'United States',
 'Arsenal-converted IBM carbines to M2 select-fire configuration.',
 NULL, 51.0, 35.6, true, false, ARRAY['IBM M2 conversion'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['ibm m2', 'ibm select fire carbine'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

-- ISSC AUSTRIA
('ISSC Austria', 'M22', '.22 LR', 'Pistol', 'Semi-Auto', 10, 2007, false, 'Austria',
 'Glock-lookalike .22 LR pistol — identical ergonomics and controls to the Glock 17.',
 299, 22.0, 7.2, false, false,
 ARRAY['M22 SD (suppressor-ready)', 'M22 Flat Dark Earth'],
 'Active', 'ISSC M22', ARRAY['.22 LR'],
 ARRAY['m22', 'issc m22', 'glock 22 trainer'], 'Modern', 'Striker-Fired', ARRAY['training', 'plinking'],
 'Allows Glock owners to train with identical controls at .22 LR cost.',
 'Austria', false, NULL),

('ISSC Austria', 'SPA', '.22 LR', 'Rifle', 'Semi-Auto', 22, 2010, false, 'Austria',
 'AR-15 pattern .22 LR training rifle from Austria.',
 499, 62.0, 34.0, false, false, ARRAY['SPA Fixed Stock', 'SPA Folding Stock'],
 'Active', 'ISSC SPA', ARRAY['.22 LR'],
 ARRAY['spa', 'issc spa'], 'Modern', 'Trigger', ARRAY['training', 'plinking'],
 NULL, 'Austria', false, NULL),

('ISSC Austria', 'MK22', '.22 LR', 'Rifle', 'Semi-Auto', 10, 2012, false, 'Austria',
 'AK-47 pattern .22 LR training rifle.',
 399, 58.0, 35.0, false, false, ARRAY['MK22 Folding Stock'],
 'Active', 'ISSC MK22', ARRAY['.22 LR'],
 ARRAY['mk22', 'issc mk22'], 'Modern', 'Trigger', ARRAY['training', 'plinking'],
 NULL, 'Austria', false, NULL),

-- INLAND MANUFACTURING
('Inland Manufacturing', 'M1 1945 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 15, 1943, true, 'United States',
 'Original WWII Inland M1 Carbine — largest single producer with 2.6M+ units made.',
 NULL, 51.0, 35.6, true, false,
 ARRAY['M1A1 (folding stock)', 'M2 (select-fire)'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['inland m1', 'inland carbine', 'original inland'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 'Inland (a GM division) produced 2,632,097 M1 Carbines — more than any other manufacturer.',
 'United States', true, 'Highly collectible. The modern Inland Mfg. Co. reproduces them.'),

('Inland Manufacturing', 'M1 Carbine (reproduction)', '.30 Carbine', 'Rifle', 'Semi-Auto', 15, 2015, false, 'United States',
 'Modern reproduction of the WWII M1 Carbine by the modern Inland Manufacturing company.',
 979, 51.0, 35.6, false, false,
 ARRAY['M1 1945', 'M1A1 Paratrooper', 'T30 Carbine'],
 'Active', 'Inland M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['inland reproduction', 'modern inland m1'], 'Modern', 'Trigger', ARRAY['collector', 'hunting'],
 NULL, 'United States', false, NULL),

('Inland Manufacturing', 'M1A1 Paratrooper', '.30 Carbine', 'Rifle', 'Semi-Auto', 15, 2016, false, 'United States',
 'Modern reproduction of the WWII M1A1 folding-stock paratrooper carbine.',
 1099, 51.0, 35.6, false, false, ARRAY['M1A1 reproduction'],
 'Active', 'Inland M1A1', ARRAY['.30 Carbine'],
 ARRAY['m1a1 paratrooper', 'inland paratrooper'], 'Modern', 'Trigger', ARRAY['collector'],
 NULL, 'United States', false, NULL),

-- INTRATEC
('Intratec', 'TEC-9', '9mm Luger', 'Pistol', 'Semi-Auto', 32, 1984, true, 'United States',
 'Open-bolt semi-auto pistol banned by name under the 1994 federal Assault Weapons Ban.',
 NULL, 50.0, 12.4, false, false,
 ARRAY['TEC-22 (.22 LR)', 'KG-9 (pre-ban)', 'AB-10 (post-ban)'],
 'Discontinued', 'Intratec TEC', ARRAY['9mm Luger'],
 ARRAY['tec9', 'tec 9', 'kg9'], 'Post-Cold War', 'Trigger', ARRAY['collector'],
 'Specifically named in the 1994 AWB. Continued production post-ban as the AB-10.',
 'United States', true, 'Pre-ban features command collector premiums. Notoriously unreliable.'),

('Intratec', 'TEC-22', '.22 LR', 'Pistol', 'Semi-Auto', 30, 1988, true, 'United States',
 '.22 LR variant of the TEC-9 design.',
 NULL, 40.0, 11.0, false, false, ARRAY['TEC-22 Scorpion'],
 'Discontinued', 'Intratec TEC', ARRAY['.22 LR'],
 ARRAY['tec22', 'tec 22'], 'Post-Cold War', 'Trigger', ARRAY['collector'],
 NULL, 'United States', true, NULL),

('Intratec', 'CAT-9', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 1991, true, 'United States',
 'Post-ban redesigned pistol with closed bolt and reduced capacity.',
 NULL, 44.0, 11.0, false, false, ARRAY['CAT-9 standard'],
 'Discontinued', 'Intratec CAT', ARRAY['9mm Luger'],
 ARRAY['cat9', 'intratec cat'], 'Post-Cold War', 'Trigger', ARRAY['collector'],
 NULL, 'United States', true, NULL),

-- ITHACA GUN COMPANY
('Ithaca Gun Company', 'Model 37', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 1937, false, 'United States',
 'Bottom-ejecting pump shotgun with 80+ year production history. Bottom ejection allows ambidextrous use.',
 649, 64.0, 40.0, false, true,
 ARRAY['Model 37 Defense', 'Model 37 Featherlight', 'Model 37 DSPS'],
 'Active', 'Ithaca 37', ARRAY['12 Gauge', '20 Gauge', '16 Gauge', '28 Gauge'],
 ARRAY['model 37', 'ithaca 37', 'featherlight'], 'Cold War', 'Trigger', ARRAY['hunting', 'home defense', 'law enforcement'],
 'Bottom ejection means no hot case hits the side — a key reason the Model 37 was popular as a police gun.',
 'United States', false, NULL),

('Ithaca Gun Company', 'Model 51', '12 Gauge', 'Shotgun', 'Semi-Auto', 3, 1970, true, 'United States',
 'Gas-operated semi-auto shotgun — first Ithaca semi-auto.',
 NULL, 74.0, 47.0, false, false,
 ARRAY['Model 51 Featherlight', 'Model 51 Magnum'],
 'Discontinued', 'Ithaca 51', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['model 51', 'ithaca 51'], 'Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'United States', true, NULL),

('Ithaca Gun Company', 'Model 1911-A1', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1943, true, 'United States',
 'WWII M1911A1 manufactured by Ithaca under government contract (~369,000 units).',
 NULL, 38.5, 8.6, true, false,
 ARRAY['Ithaca 1943', 'Ithaca 1944', 'Ithaca 1945'],
 'Discontinued', 'M1911A1', ARRAY['.45 ACP'],
 ARRAY['ithaca 1911', 'ithaca 45'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 'Ithaca-made 1911s are identifiable by their unique slide markings.',
 'United States', true, 'WWII Ithaca 1911s in original condition with matching parts command strong premiums.'),

-- IVER JOHNSON ARMS
('Iver Johnson Arms', 'Safety Hammerless', '.38 S&W', 'Revolver', 'Double-Action', 5, 1887, true, 'United States',
 'Top-break revolver with hammerless design and transfer bar safety — revolutionary in 1887.',
 NULL, 16.0, 6.5, false, false,
 ARRAY['Safety Hammerless 2nd Model', '3rd Model', '4th Model'],
 'Discontinued', 'IJ Safety Hammerless', ARRAY['.38 S&W', '.32 S&W'],
 ARRAY['safety hammerless', 'iver johnson hammerless', 'ij owl head'], 'Pre-WWI / Old West', 'Double-Action', ARRAY['collector'],
 '"Hammer the Hammer" advertising: the gun cannot fire if dropped, due to the transfer bar safety — revolutionary in 1887.',
 'United States', true, 'Widely collected "Owl Head" top-break revolvers.'),

('Iver Johnson Arms', 'Cadet', '.22 LR', 'Revolver', 'Double-Action', 8, 1955, true, 'United States',
 'Small-frame DA revolver in .22 LR. Common plinker and first gun for generations.',
 NULL, 20.0, 8.5, false, false,
 ARRAY['Cadet Model 55', 'Cadet Model 55-S'],
 'Discontinued', 'Iver Johnson Cadet', ARRAY['.22 LR'],
 ARRAY['cadet', 'ij cadet', 'iver johnson 22'], 'Cold War', 'Double-Action', ARRAY['plinking', 'collector'],
 NULL, 'United States', true, NULL),

('Iver Johnson Arms', 'Champion', '.410 Bore', 'Shotgun', 'Break-Action', 1, 1909, true, 'United States',
 'Single-barrel break-action shotgun — the original affordable farm and small game gun.',
 NULL, 46.0, 44.0, false, false,
 ARRAY['Champion Grade', 'Champion Matted Rib'],
 'Discontinued', 'Iver Johnson Champion', ARRAY['.410 Bore', '12 Gauge', '20 Gauge'],
 ARRAY['champion', 'ij champion'], 'Pre-WWI / Old West', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'United States', true, NULL),

-- JP ENTERPRISES
('JP Enterprises', 'JP-15', '5.56x45mm NATO', 'Rifle', 'Semi-Auto', 30, 1995, false, 'United States',
 'Premium match-grade AR-15 with JP Silent Captured Spring and tuned trigger.',
 2000, 58.0, 32.0, false, false,
 ARRAY['JP-15 Competition', 'JP-15 Tactical', 'JP-15 Short Action'],
 'Active', 'JP-15', ARRAY['5.56x45mm NATO', '.223 Wylde', '6.5 Grendel'],
 ARRAY['jp15', 'jp enterprises ar15'], 'Modern', 'Single-Stage', ARRAY['competition', 'hunting'],
 'The Silent Captured Spring replaces the AR buffer, eliminating spring noise and reducing felt recoil.',
 'United States', false, NULL),

('JP Enterprises', 'GMR-15', '9mm Luger', 'Rifle', 'Semi-Auto', 17, 2015, false, 'United States',
 'Glock-magazine PCC built for 3-Gun and PCC competition.',
 1799, 52.0, 32.0, false, false, ARRAY['GMR-15 Competition'],
 'Active', 'JP GMR-15', ARRAY['9mm Luger'],
 ARRAY['gmr15', 'jp pcc', 'jp 9mm'], 'Modern', 'Single-Stage', ARRAY['competition'],
 NULL, 'United States', false, NULL),

('JP Enterprises', 'SCR-11', '.308 Winchester', 'Rifle', 'Semi-Auto', 20, 2005, false, 'United States',
 'Precision AR-10 pattern rifle for long-range competition.',
 2500, 102.0, 40.0, false, false,
 ARRAY['SCR-11 LRP', 'SCR-11 Tactical'],
 'Active', 'JP SCR-11', ARRAY['.308 Winchester', '6.5 Creedmoor'],
 ARRAY['scr11', 'jp ar10'], 'Modern', 'Single-Stage', ARRAY['competition', 'hunting'],
 NULL, 'United States', false, NULL),

-- JAMES PURDEY & SONS
('James Purdey & Sons', 'Best Quality Shotgun', '12 Gauge', 'Shotgun', 'Side-by-Side', 2, 1814, false, 'United Kingdom',
 'Gold standard of English best-quality shotguns. Fully bespoke, hand-built, 18–24 months to complete.',
 100000, 68.0, 46.0, false, false,
 ARRAY['Best SxS Game Gun', 'Best O/U', 'Self-Opener'],
 'Active', 'Purdey Best', ARRAY['12 Gauge', '20 Gauge', '28 Gauge', '.410 Bore'],
 ARRAY['purdey best', 'purdey sxs', 'best gun'], 'Modern', 'Trigger', ARRAY['hunting', 'collector'],
 'A new Purdey Best starts at ~£100,000 and takes up to two years to complete.',
 'United Kingdom', true, 'Among the most prestigious firearms in the world. Strong second-hand value.'),

('James Purdey & Sons', 'Over-Under', '12 Gauge', 'Shotgun', 'Over-Under', 2, 1925, false, 'United Kingdom',
 'Purdey best-quality over-under for sporting clays and game.',
 95000, 74.0, 46.0, false, false,
 ARRAY['Purdey O/U Sporting', 'Purdey O/U Game'],
 'Active', 'Purdey O/U', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['purdey ou', 'purdey over under'], 'Modern', 'Trigger', ARRAY['hunting', 'sport', 'collector'],
 NULL, 'United Kingdom', true, NULL),

('James Purdey & Sons', 'Hammerless Ejector', '12 Gauge', 'Shotgun', 'Side-by-Side', 2, 1880, false, 'United Kingdom',
 'The classic Purdey hammerless ejector SxS — basis of all modern Purdey best guns.',
 95000, 66.0, 45.0, false, false,
 ARRAY['Self-Opener', 'Non-Ejector'],
 'Active', 'Purdey Hammerless Ejector', ARRAY['12 Gauge', '20 Gauge', '28 Gauge'],
 ARRAY['purdey hammerless', 'purdey ejector'], 'Modern', 'Trigger', ARRAY['hunting', 'collector'],
 'Purdey''s self-opening mechanism is powered by the mainsprings — the gun opens automatically after firing.',
 'United Kingdom', true, NULL),

-- JENNINGS FIREARMS
('Jennings Firearms', 'J-22', '.22 LR', 'Pistol', 'Semi-Auto', 6, 1978, true, 'United States',
 'Inexpensive zinc alloy pocket pistol. Original "Ring of Fire" SNS gun.',
 NULL, 13.0, 5.4, false, false, ARRAY['J-22 standard'],
 'Discontinued', 'Jennings J', ARRAY['.22 LR'],
 ARRAY['j22', 'jennings 22'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 'Jennings was part of the California "Ring of Fire" SNS manufacturer cluster.',
 'United States', false, NULL),

('Jennings Firearms', 'Nine', '9mm Luger', 'Pistol', 'Semi-Auto', 8, 1991, true, 'United States',
 'Budget 9mm pocket pistol from Jennings.',
 NULL, 18.0, 5.9, false, false, ARRAY['Nine standard'],
 'Discontinued', 'Jennings Nine', ARRAY['9mm Luger'],
 ARRAY['jennings nine', 'jennings 9mm'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

('Jennings Firearms', 'Bryco 38', '.380 ACP', 'Pistol', 'Semi-Auto', 6, 1985, true, 'United States',
 'Budget .380 pistol sold under the Bryco and Jennings names.',
 NULL, 15.0, 5.3, false, false, ARRAY['Bryco 380'],
 'Discontinued', 'Jennings Bryco', ARRAY['.380 ACP', '.32 ACP'],
 ARRAY['bryco 38', 'jennings 380'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

-- JIMENEZ ARMS
('Jimenez Arms', 'JA-9', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 2004, true, 'United States',
 'Successor to the Bryco Arms pocket pistol line.',
 NULL, 22.0, 6.0, false, false, ARRAY['JA-9 standard'],
 'Discontinued', 'Jimenez JA', ARRAY['9mm Luger'],
 ARRAY['ja9', 'jimenez 9mm'], 'Modern', 'Single-Action', ARRAY['collector'],
 'Jimenez took over Bryco Arms production after Bryco''s bankruptcy.',
 'United States', false, NULL),

('Jimenez Arms', 'JA-22', '.22 LR', 'Pistol', 'Semi-Auto', 6, 2004, true, 'United States',
 'Budget .22 LR pocket pistol from Jimenez.',
 NULL, 13.0, 5.4, false, false, ARRAY['JA-22 standard'],
 'Discontinued', 'Jimenez JA', ARRAY['.22 LR'],
 ARRAY['ja22', 'jimenez 22'], 'Modern', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

('Jimenez Arms', 'JA-380', '.380 ACP', 'Pistol', 'Semi-Auto', 6, 2004, true, 'United States',
 'Budget .380 ACP pocket pistol.',
 NULL, 15.0, 5.3, false, false, ARRAY['JA-380 standard'],
 'Discontinued', 'Jimenez JA', ARRAY['.380 ACP'],
 ARRAY['ja380', 'jimenez 380'], 'Modern', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

-- KAHR ARMS
('Kahr Arms', 'CM9', '9mm Luger', 'Pistol', 'Semi-Auto', 6, 2011, false, 'United States',
 'Compact single-stack 9mm DAO for concealed carry. Budget alternative to the PM9.',
 449, 14.0, 5.4, false, false,
 ARRAY['CM9 black', 'CM9 stainless'],
 'Active', 'Kahr CM9', ARRAY['9mm Luger'],
 ARRAY['cm9', 'kahr cm9'], 'Modern', 'DAO', ARRAY['concealed carry'],
 'Functionally identical to the PM9 but uses MIM parts instead of machined.',
 'United States', false, NULL),

('Kahr Arms', 'PM9', '9mm Luger', 'Pistol', 'Semi-Auto', 6, 2000, false, 'United States',
 'Premium compact single-stack 9mm DAO. Ultra-thin for deep concealment.',
 699, 14.0, 5.3, false, false,
 ARRAY['PM9 Covert', 'PM9 Blackout'],
 'Active', 'Kahr PM9', ARRAY['9mm Luger'],
 ARRAY['pm9', 'kahr pm9'], 'Modern', 'DAO', ARRAY['concealed carry'],
 'One of the first subcompact 9mms small enough for pocket carry.',
 'United States', false, NULL),

('Kahr Arms', 'CT380', '.380 ACP', 'Pistol', 'Semi-Auto', 7, 2014, false, 'United States',
 'Compact .380 ACP DAO pistol. Value-tier Kahr.',
 419, 11.2, 5.2, false, false, ARRAY['CT380 standard'],
 'Active', 'Kahr CT380', ARRAY['.380 ACP'],
 ARRAY['ct380', 'kahr 380'], 'Modern', 'DAO', ARRAY['concealed carry'],
 NULL, 'United States', false, NULL),

-- KEL-TEC
('Kel-Tec', 'P-11', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 1995, false, 'United States',
 'Ultra-compact double-stack 9mm DAO. One of the first polymer subcompact 9mms.',
 333, 14.4, 5.6, false, false, ARRAY['P-11 standard', 'P-11 Tungsten'],
 'Active', 'Kel-Tec P-11', ARRAY['9mm Luger'],
 ARRAY['p11', 'kel tec p11'], 'Modern', 'DAO', ARRAY['concealed carry'],
 'The P-11 pioneered the small polymer 9mm category that spawned dozens of imitators.',
 'United States', false, NULL),

('Kel-Tec', 'Sub-2000', '9mm Luger', 'Rifle', 'Semi-Auto', 17, 2001, false, 'United States',
 'Folding PCC that folds in half for transport. Accepts Glock magazines.',
 499, 47.0, 29.9, false, false,
 ARRAY['Sub-2000 G17 Gen 2', 'Sub-2000 G19', 'Sub-2000 Gen 3'],
 'Active', 'Kel-Tec Sub-2000', ARRAY['9mm Luger', '.40 S&W'],
 ARRAY['sub2000', 'sub 2000', 'keltec sub2k'], 'Modern', 'Trigger', ARRAY['home defense', 'travel'],
 'Folds at the ejection port to backpack size. Popular for travel and emergency preparedness.',
 'United States', false, NULL),

('Kel-Tec', 'KSG', '12 Gauge', 'Shotgun', 'Pump-Action', 14, 2011, false, 'United States',
 'Bullpup pump shotgun with dual magazine tubes — 14+1 capacity in a compact package.',
 899, 96.0, 26.1, false, false,
 ARRAY['KSG-25 (extended)', 'KSG-NR'],
 'Active', 'Kel-Tec KSG', ARRAY['12 Gauge'],
 ARRAY['ksg', 'kel tec ksg'], 'Modern', 'Trigger', ARRAY['home defense'],
 'Two magazine tubes can hold different loads — the shooter selects which to feed.',
 'United States', false, NULL),

-- KNIGHT RIFLES
('Knight Rifles', 'Disc Extreme', '.50 Caliber', 'Rifle', 'Single-Shot', 1, 2001, false, 'United States',
 'In-line muzzleloader with 209 primer ignition for reliable all-weather performance.',
 649, 82.0, 45.0, false, false,
 ARRAY['Disc Extreme SS', 'Disc Extreme Thumbhole'],
 'Active', 'Knight Disc', ARRAY['.50 Caliber'],
 ARRAY['disc extreme', 'knight disc'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'United States', false, NULL),

('Knight Rifles', 'Bighorn', '.50 Caliber', 'Rifle', 'Single-Shot', 1, 2014, false, 'United States',
 'Bolt-action in-line muzzleloader.',
 499, 96.0, 44.0, false, false, ARRAY['Bighorn SS', 'Bighorn TT'],
 'Active', 'Knight Bighorn', ARRAY['.50 Caliber', '.52 Caliber'],
 ARRAY['bighorn', 'knight bighorn'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'United States', false, NULL),

('Knight Rifles', 'TK2000', '12 Gauge', 'Shotgun', 'Single-Shot', 1, 2000, false, 'United States',
 'In-line muzzle-loading shotgun for turkey hunting.',
 399, 72.0, 44.0, false, false, ARRAY['TK2000 SS'],
 'Active', 'Knight TK2000', ARRAY['12 Gauge'],
 ARRAY['tk2000', 'knight turkey gun'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'United States', false, NULL),

-- KNIGHTS ARMAMENT
('Knights Armament', 'SR-25', '7.62x51mm NATO', 'Rifle', 'Semi-Auto', 20, 1990, false, 'United States',
 'Semi-auto precision rifle derived from the AR-10. Standard USSOCOM sniper rifle (Mk 11 Mod 0).',
 4499, 102.0, 43.5, true, true,
 ARRAY['SR-25 APC', 'SR-25 ECC', 'Mk 11 Mod 0'],
 'Active', 'KAC SR-25', ARRAY['7.62x51mm NATO', '.308 Winchester'],
 ARRAY['sr25', 'kac sr25', 'mk11'], 'Post-Cold War', 'Trigger', ARRAY['military', 'law enforcement', 'competition'],
 'Co-designed by Eugene Stoner and Reed Knight. Became the US Army and SOCOM standard sniper rifle.',
 'United States', false, NULL),

('Knights Armament', 'SR-15', '5.56x45mm NATO', 'Rifle', 'Semi-Auto', 30, 1995, false, 'United States',
 'Premium AR-15 with URX rail system and match-grade barrel.',
 2700, 62.0, 33.0, false, true,
 ARRAY['SR-15 IWS', 'SR-15 E3 Mod 2', 'SR-15 LPR'],
 'Active', 'KAC SR-15', ARRAY['5.56x45mm NATO'],
 ARRAY['sr15', 'kac sr15', 'knights sr15'], 'Modern', 'Trigger', ARRAY['law enforcement', 'competition', 'hunting'],
 NULL, 'United States', false, NULL),

('Knights Armament', 'PDW', '6x35mm', 'Rifle', 'Semi-Auto', 20, 2003, false, 'United States',
 'Personal Defense Weapon in proprietary 6x35mm cartridge designed for SOCOM PDW requirements.',
 NULL, 60.0, 22.0, true, true, ARRAY['PDW military', 'PDW semi-auto'],
 'Active', 'KAC PDW', ARRAY['6x35mm'],
 ARRAY['kac pdw', 'knights pdw'], 'Modern', 'Trigger', ARRAY['military'],
 'The 6x35mm cartridge was designed to penetrate body armor at close range.',
 'United States', false, NULL),

-- KORTH
('Korth', 'Combat', '.357 Magnum', 'Revolver', 'Double-Action', 6, 1960, false, 'Germany',
 'Hand-built German precision revolver — arguably the finest revolver ever made. Tolerances tighter than a Swiss watch.',
 8000, 40.0, 8.5, false, false,
 ARRAY['Combat Classic', 'Combat Stainless', 'Combat Ti'],
 'Active', 'Korth Combat', ARRAY['.357 Magnum', '9mm Luger', '.22 LR'],
 ARRAY['korth combat', 'korth revolver'], 'Modern', 'Double-Action', ARRAY['competition', 'collector'],
 'Each Korth requires 6 weeks of hand fitting. Tolerances reportedly tighter than most machine tools.',
 'Germany', true, 'Among the most technically accomplished revolvers ever made.'),

('Korth', 'Sky Marshal', '9mm Luger', 'Pistol', 'Semi-Auto', 13, 2015, false, 'Germany',
 'German semi-auto pistol with rotating barrel for reduced felt recoil.',
 2500, 27.5, 7.5, false, false,
 ARRAY['Sky Marshal Stainless', 'Sky Marshal Custom'],
 'Active', 'Korth Sky Marshal', ARRAY['9mm Luger', '.40 S&W'],
 ARRAY['sky marshal', 'korth pistol'], 'Modern', 'Double-Action', ARRAY['home defense', 'collector'],
 NULL, 'Germany', true, NULL),

('Korth', 'PRS', '.357 Magnum', 'Revolver', 'Double-Action', 6, 2019, false, 'Germany',
 'Modern Korth target revolver with interchangeable cylinders and adjustable sights.',
 3500, 44.0, 9.0, false, false,
 ARRAY['PRS 6"', 'PRS 4"'],
 'Active', 'Korth PRS', ARRAY['.357 Magnum', '9mm Luger'],
 ARRAY['prs', 'korth prs'], 'Modern', 'Double-Action', ARRAY['competition', 'collector'],
 NULL, 'Germany', true, NULL),

-- KRIEGHOFF
('Krieghoff', 'K-80', '12 Gauge', 'Shotgun', 'Over-Under', 2, 1980, false, 'Germany',
 'Premium German O/U dominant at Olympic-level trap for decades.',
 10000, 94.0, 47.0, false, false,
 ARRAY['K-80 Trap', 'K-80 Skeet', 'K-80 Sporting', 'K-80 Pro Sporter'],
 'Active', 'Krieghoff K-80', ARRAY['12 Gauge'],
 ARRAY['k80', 'krieghoff k80'], 'Modern', 'Trigger', ARRAY['competition', 'sport'],
 'The K-80 has won more Olympic and World Championship trap medals than any other shotgun.',
 'Germany', false, NULL),

('Krieghoff', 'K-20', '20 Gauge', 'Shotgun', 'Over-Under', 2, 2002, false, 'Germany',
 '20-gauge version of the K-80 for sub-gauge competition.',
 10000, 76.0, 47.0, false, false,
 ARRAY['K-20 Skeet', 'K-20 Sporting'],
 'Active', 'Krieghoff K-20', ARRAY['20 Gauge', '28 Gauge', '.410 Bore'],
 ARRAY['k20', 'krieghoff k20'], 'Modern', 'Trigger', ARRAY['competition', 'sport'],
 NULL, 'Germany', false, NULL),

('Krieghoff', 'Hubertus', '7x57mm R', 'Rifle', 'Single-Shot', 1, 1960, false, 'Germany',
 'German combination gun and single-shot rifle for European hunting.',
 4500, 96.0, 40.0, false, false,
 ARRAY['Hubertus Drilling', 'Hubertus combo'],
 'Active', 'Krieghoff Hubertus', ARRAY['7x57mm R', '7x65mm R', '8x57mm JS'],
 ARRAY['hubertus', 'krieghoff hunting'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Germany', false, NULL),

-- KRISS USA
('Kriss USA', 'Vector', '.45 ACP', 'Rifle', 'Semi-Auto', 13, 2009, false, 'Switzerland',
 'Delayed blowback SMG-pattern firearm with Super V recoil system. Recoil redirected downward.',
 1499, 64.0, 16.0, false, true,
 ARRAY['Vector Gen 2', 'Vector SDP (pistol)', 'Vector Enhanced'],
 'Active', 'Kriss Vector', ARRAY['.45 ACP', '9mm Luger', '10mm Auto', '.40 S&W'],
 ARRAY['vector', 'kriss vector', 'super v'], 'Modern', 'Trigger', ARRAY['home defense', 'law enforcement'],
 'The Super V system drives the bolt at a 45° angle downward, redirecting recoil away from the shooter.',
 'Switzerland', false, NULL),

('Kriss USA', 'Sphinx SDP', '9mm Luger', 'Pistol', 'Semi-Auto', 15, 2014, false, 'Switzerland',
 'Swiss precision CZ 75-derivative pistol with aluminum frame and match barrel.',
 1099, 28.0, 7.7, false, false,
 ARRAY['SDP Alpha', 'SDP Compact', 'SDP Subcompact'],
 'Active', 'Sphinx SDP', ARRAY['9mm Luger', '.40 S&W'],
 ARRAY['sphinx sdp', 'kriss sphinx'], 'Modern', 'Double-Action', ARRAY['competition', 'home defense'],
 NULL, 'Switzerland', false, NULL),

('Kriss USA', 'DMK22', '.22 LR', 'Rifle', 'Semi-Auto', 10, 2016, false, 'Switzerland',
 'AR-15 pattern .22 LR training rifle from Kriss.',
 499, 54.0, 34.0, false, false,
 ARRAY['DMK22C (carbine)', 'DMK22P (pistol)'],
 'Active', 'Kriss DMK22', ARRAY['.22 LR'],
 ARRAY['dmk22', 'kriss 22'], 'Modern', 'Trigger', ARRAY['training', 'plinking'],
 NULL, 'Switzerland', false, NULL)

ON CONFLICT (make, model) DO NOTHING;
