-- ============================================================
-- Powder seed v2 — ~220 additional rows
-- Brings powder_brands to ~320+ total entries
-- Run after: 20260415_powder_brands.sql + 20260415_powder_brands_v2.sql
--            + 20260423_powders_phase2.sql
-- Idempotent: ON CONFLICT (brand, product_name) DO NOTHING
-- ============================================================

INSERT INTO public.powder_brands
  (brand, product_name, burn_rate_rank, powder_type, best_use, recommended_calibers,
   temperature_sensitivity, discontinued, country_of_origin, description,
   metering_grade, muzzle_flash_rating, parent_company, manufacturer, distributor)
VALUES

-- ═══════════════════════════════════════════════════════════════
-- HODGDON (additional)
-- ═══════════════════════════════════════════════════════════════

('Hodgdon','Trail Boss',
 22,'Disc',ARRAY['Pistol','Rifle'],
 ARRAY['9mm','.45 ACP','.38 Special','.357 Magnum','.30-30 Win','.45-70 Govt'],
 'Low',false,'USA',
 'Unique disc-shaped powder designed for cowboy action shooting and cast bullet rifle loads. Extremely bulky — low charge weights prevent double-charging. Produces mild velocity with soft-shooting loads in lever-action and revolver cartridges.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','HP-38',
 18,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.45 ACP','.40 S&W','.357 Magnum'],
 'Moderate',false,'USA',
 'Hodgdon''s version of Winchester 231 — identical ball powder formula. Clean-burning, excellent metering, one of the most popular pistol powders in America. Well-documented in every major loading manual.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','HS-7',
 32,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Magnum','.45 Colt','12 Gauge (heavy buckshot)'],
 'Moderate',false,'USA',
 'Slightly slower than HS-6. Designed for heavy magnum handgun loads and maximum 12-gauge buckshot and magnum loads. Excellent metering through progressive reloading equipment.',
 'Excellent','Moderate',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','Longshot',
 26,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['12 Gauge (3.5")','12 Gauge (3")','.357 Magnum','.44 Magnum','10mm','9mm (major)'],
 'Moderate',false,'USA',
 'Long-range shotshell and heavy magnum pistol ball powder. Outstanding for 3" and 3.5" 12-gauge magnum waterfowl loads. Also used by IPSC Open division shooters for major power factor 9mm and .357 Magnum loads.',
 'Excellent','Moderate',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H322',
 37,'Extruded',ARRAY['Rifle'],
 ARRAY['.222 Rem','.223 Rem','.22 PPC','.222 Rem Mag','.17 Rem'],
 'Low',false,'USA',
 'Temperature-insensitive extruded powder for small rifle cases. Long favored for benchrest competition in .222 Rem and .223 Rem. Produces extremely consistent extreme spreads in small-capacity cases across temperature ranges.',
 'Good','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H335',
 44,'Ball',ARRAY['Rifle'],
 ARRAY['5.56 NATO','.223 Rem','6mm PPC','.22-250'],
 'Moderate',false,'USA',
 'Classic ball powder originally developed for military 5.56 NATO ammunition. Excellent accuracy in .223 Rem and 5.56 NATO with 52-77gr bullets. Popular for high-volume AR-15 reloading due to ball powder''s superior metering.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','BL-C(2)',
 42,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem','7.62 NATO'],
 'Moderate',false,'USA',
 'A classic ball powder developed for the 7.62 NATO military cartridge. Long production history and well-documented in every major loading manual. Popular with military surplus case reloaders and AR-10 shooters.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H380',
 53,'Ball',ARRAY['Rifle'],
 ARRAY['.22-250','.220 Swift','.243 Win','.308 Win'],
 'Moderate',false,'USA',
 'Named for its 38-grain charge in .22-250 Rem. Ideal for varmint rifles with .22-250 and .220 Swift. Ball powder that meters precisely and burns clean. One of the best powders for maximum velocity in fast 22-caliber varmint cartridges.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H414',
 56,'Ball',ARRAY['Rifle'],
 ARRAY['.270 Win','.30-06','.243 Win','.308 Win','.25-06'],
 'Moderate',false,'USA',
 'Versatile medium-speed ball powder covering the .270 Win to .30-06 application range. Excellent metering in progressive reloading. Competes with IMR 4350 but offers superior consistency through powder measures.',
 'Excellent','Moderate',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','Superperformance',
 58,'Ball',ARRAY['Rifle'],
 ARRAY['.30-06','.308 Win','.270 Win','7mm Rem Mag','.300 Win Mag'],
 'Moderate',false,'USA',
 'Optimized for the Hornady Superperformance load line. Produces 100-200 fps more velocity than standard powders in .30-06 and similar cases. Works well in hunting applications where maximum velocity is the priority.',
 'Excellent','Moderate',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','Leverevolution',
 47,'Ball',ARRAY['Rifle'],
 ARRAY['.30-30 Win','.35 Rem','.308 Marlin Express','.338 Marlin Express','.444 Marlin'],
 'Moderate',false,'USA',
 'Developed specifically for Hornady Leverevolution ammunition in lever-action cartridges. Optimal for .30-30 Win, .35 Rem, and Marlin Express calibers. Ball powder formula provides excellent metering for tube-magazine cartridge reloading.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H4227',
 34,'Extruded',ARRAY['Pistol','Rifle'],
 ARRAY['.357 Magnum','.44 Magnum','.454 Casull','.22 Hornet','.30-30 Win (cast)'],
 'Moderate',false,'USA',
 'Fast-burning extruded powder straddling the magnum handgun and small rifle boundary. Excellent for .357 Magnum with heavy cast bullets and .22 Hornet rifle loads. Popular with Contender and XP-100 single-shot pistol silhouette shooters.',
 'Fair','High',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H1000',
 73,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Lapua','.30-06 (heavy)','.280 Rem','7mm Rem Mag'],
 'Low',false,'USA',
 'Ultra-slow extruded powder for large magnum cases. Temperature-insensitive formula — a major advantage at this burn rate. Dominant choice for long-range precision .300 Win Mag loads. Low ES across wide temperature swings makes it a PRS and hunting favorite.',
 'Fair','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H50BMG',
 88,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.50 BMG','.50 DTC'],
 'Moderate',false,'USA',
 'Purpose-built for the .50 BMG cartridge. Optimized for maximum energy extraction in this extreme-capacity case. Used by both competitive .50 BMG benchrest shooters and long-range precision enthusiasts. No other standard Hodgdon powder is appropriate for this application.',
 'Poor','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','International Clays',
 10,'Flake',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge','20 Gauge','.38 Special','.45 ACP'],
 'Low',false,'USA',
 'Slightly slower than Clays, optimized for 28-gram international target shotshell loads and ISSF competition. Also excellent in light pistol target loads. Clean-burning with very low flash signature.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','TiteWad',
 4,'Flake',ARRAY['Shotgun'],
 ARRAY['12 Gauge (light target)','20 Gauge (light target)'],
 'Low',false,'USA',
 'Extremely fast flake powder designed specifically for light 12-gauge and 20-gauge target loads. Produces minimal felt recoil. Among the cleanest-burning shotgun powders available. Named for its ability to produce compact, tight wads at low charge weights.',
 'Good','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','700X',
 6,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light)','20 Gauge','.38 Special','.45 ACP'],
 'Low',false,'USA',
 'One of the oldest ball powders in continuous production. Primarily a shotshell powder but useful for light pistol target loads. Very clean and consistent. The Hodgdon-distributed version of this classic fast-burning powder.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H870',
 83,'Ball',ARRAY['Magnum Rifle'],
 ARRAY['.378 Wby','.416 Wby','.460 Wby'],
 'Moderate',true,'USA',
 'Discontinued ultra-slow ball powder that was the only Hodgdon option for Weatherby Magnum cases before Retumbo. Replaced by Retumbo and H1000 for most applications. Historical reference only — not currently available.',
 'Fair','Low',NULL,NULL,'Hodgdon Powder Company'),

('Hodgdon','H205',
 48,'Ball',ARRAY['Rifle'],
 ARRAY['.30-06','.308 Win'],
 'Moderate',true,'USA',
 'Discontinued Hodgdon ball powder in the medium rifle burn rate range. Replaced by H414 in most applications. No longer in production. Still appears in older loading manuals from the 1970s-80s.',
 'Excellent','Low',NULL,NULL,'Hodgdon Powder Company'),

-- ═══════════════════════════════════════════════════════════════
-- IMR (additional)
-- ═══════════════════════════════════════════════════════════════

('IMR','IMR 4227',
 34,'Extruded',ARRAY['Pistol','Rifle'],
 ARRAY['.22 Hornet','.357 Magnum','.44 Magnum','.454 Casull','.30 Carbine'],
 'Moderate',false,'USA',
 'Classic IMR fast rifle/magnum pistol extruded powder. Identical application range to H4227. Excellent for .22 Hornet and magnum revolver cartridges. Long production history dating to the original Du Pont IMR family.',
 'Fair','High','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR 4320',
 48,'Extruded',ARRAY['Rifle'],
 ARRAY['.22-250','.243 Win','.308 Win','.30-06'],
 'Moderate',false,'USA',
 'Classic medium-speed IMR extruded powder from the original Du Pont family. Excellent in .22-250 and medium rifle cases. Well-documented in every major loading manual. Slightly faster than IMR 4350.',
 'Fair','Moderate','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR 4007 SSC',
 44,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.22-250','.308 Win','5.56 NATO'],
 'Low',false,'USA',
 'Ball powder from IMR — unusual as IMR is primarily an extruded line. Temperature-insensitive. The SSC designation indicates suitability for service rifle competition. Excellent metering through progressive presses despite IMR branding.',
 'Excellent','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR 8208 XBR',
 47,'Extruded',ARRAY['Rifle'],
 ARRAY['.223 Rem','6mm PPC','.308 Win','6mm BR','.22-250'],
 'Low',false,'USA',
 'Temperature-insensitive extruded powder purpose-built for benchrest competition. XBR stands for "extra benchrest." Exceptional lot-to-lot consistency. Top choice for 6mm BR, 6mm PPC, and .223 Rem benchrest and F-Class Open competition.',
 'Good','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR 4831',
 68,'Extruded',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.270 Win','.30-06 (heavy)','.300 Win Mag','7mm Rem Mag'],
 'Moderate',false,'USA',
 'Classic slow IMR extruded powder from the original Du Pont family. Near-identical to Hodgdon H4831 in application. One of the most referenced powders in loading history. Excellent for .270 Win and 7mm Rem Mag with full-weight hunting bullets.',
 'Fair','Moderate','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR 4955',
 65,'Extruded',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.30-06','.270 Win','6.5 Creedmoor','7mm Rem Mag'],
 'Low',false,'USA',
 'Enduron-series temperature-insensitive extruded powder with a copper fouling reducer additive. Fills the gap between IMR 4451 and IMR 7977 in the Enduron lineup. Excellent for standard magnum cases with full-weight hunting bullets.',
 'Good','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR 5010',
 79,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.378 Wby','.460 Wby','.375 H&H (heavy)'],
 'Moderate',false,'USA',
 'One of IMR''s slowest extruded powders. Designed for the largest belted magnum cases. Indispensable for maximum loads in Weatherby large magnums and .375 H&H with heavy bullets. Niche application but irreplaceable in those cases.',
 'Poor','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR 8133',
 83,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.338 Lapua','.375 H&H','.300 Norma Mag','28 Nosler','.416 Rigby'],
 'Low',false,'USA',
 'Enduron series ultra-slow temperature-insensitive powder for the largest magnum rifle cartridges. Copper fouling reducer additive. Produces low extreme spread in .338 Lapua and similar case capacities. The slowest powder in the IMR Enduron line.',
 'Good','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR SR-4756',
 22,'Flake',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.45 ACP','.357 Magnum'],
 'Moderate',true,'USA',
 'Discontinued IMR flake powder popular for pistol calibers in the Unique burn rate zone. No longer manufactured. Replaced by newer Hodgdon/IMR ball powders. Still referenced in loading manuals from the 1980s-90s.',
 'Good','Moderate','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('IMR','IMR SR-4759',
 29,'Extruded',ARRAY['Pistol','Rifle'],
 ARRAY['.30-30 Win (reduced)','.45-70 Govt (cast)','.357 Magnum (heavy)'],
 'Moderate',true,'USA',
 'Discontinued IMR extruded powder designed for cast bullet loads and reduced rifle charges. Excellent for cowboy-action-type velocity ranges in rifle cases. Replaced by Trail Boss for most applications. Prized by cast bullet shooters when found as old stock.',
 'Fair','Moderate','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

-- ═══════════════════════════════════════════════════════════════
-- ALLIANT (additional)
-- ═══════════════════════════════════════════════════════════════

('Alliant','Bull''s-Eye',
 4,'Flake',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special','.45 ACP','9mm','12 Gauge (light)'],
 'Low',false,'USA',
 'One of the fastest pistol powders and one of the oldest in continuous production. Classic Hercules/Alliant flake with lineage going back over a century. Extremely popular for .38 Special target loads. Very clean-burning at recommended charge weights.',
 'Good','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','e3',
 7,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special','.45 ACP','9mm','12 Gauge'],
 'Low',false,'USA',
 'Modern ball powder positioned in the fast pistol/shotgun range. Developed as an alternative to Red Dot with superior metering characteristics of ball powder. Very clean-burning. The "e3" name references its environmental performance profile.',
 'Excellent','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Power Pro 110',
 18,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.40 S&W','.45 ACP'],
 'Low',false,'USA',
 'Clean-burning ball powder optimized for 9mm, .40 S&W, and .45 ACP. Consistent performance for high-volume competition reloading. Temperature-insensitive across typical shooting conditions. Excellent metering for progressive press reloading.',
 'Excellent','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Reloader 25',
 74,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.338 Win Mag','.300 Win Mag','.375 H&H','.30-378 Wby','7mm STW'],
 'Moderate',false,'USA',
 'Very slow extruded powder for large magnum cases. Fills the gap between Reloader 22 and the ultra-slow Reloader 33. Excellent for .338 Win Mag and overbore cartridges. Preferred by hunters seeking maximum velocity from large belted magnums.',
 'Poor','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Reloader 26',
 74,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Lapua','7mm Rem Mag','.300 WSM'],
 'Low',false,'USA',
 'Temperature-stable version in the Reloader 22-25 burn rate zone. Formulated specifically for thermal stability — a critical advantage for hunters who encounter wide temperature swings between sighting-in and field conditions.',
 'Fair','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Reloader 33',
 85,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.338 Lapua','.300 Norma Mag','33 Nosler','338 Edge'],
 'Low',false,'USA',
 'Alliant''s slowest powder. Purpose-built for .338 Lapua with heavy bullets and similar ultra-high-capacity cases. Exceptional temperature stability for ELR (extreme long range) competition. Low ES across extreme temperature ranges is its defining characteristic.',
 'Poor','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Reloader 50',
 90,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.50 BMG'],
 'Low',false,'USA',
 'Alliant''s answer to Hodgdon H50BMG. Purpose-built for the .50 BMG cartridge. Temperature-stable formulation for consistent performance across conditions encountered in .50 caliber competition. Not suitable for any other standard cartridge.',
 'Poor','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Power Pro 2000-MR',
 20,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Magnum','12 Gauge (magnum)','.45 Colt'],
 'Moderate',false,'USA',
 'Medium-burn-rate ball powder for magnum handgun and heavy shotshell applications. Superior metering for progressive reloading. Consistent performance in .357 Magnum major power factor competition loads.',
 'Excellent','Moderate','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Power Pro 300-MP',
 23,'Ball',ARRAY['Pistol'],
 ARRAY['9mm (major)','.38 Super','10mm','.40 S&W (heavy)'],
 'Low',false,'USA',
 'Competition-optimized ball powder for USPSA Open and Limited division major power factor loads. Clean-burning with low temperature sensitivity. Growing adoption among competitive shooters who need consistent major PF across ambient temperature ranges.',
 'Excellent','Low','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Power Pro 4000-MR',
 56,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.270 Win'],
 'Moderate',false,'USA',
 'Slow-burning ball rifle powder from Alliant''s Power Pro competition line. Excellent metering for high-volume rifle reloading. Alternative to H4350 class powders with ball powder''s metering advantages. Used in service rifle and high-volume bolt-action reloading.',
 'Excellent','Moderate','Vista Outdoor',NULL,'Alliant Powder'),

('Alliant','Power Pro Varmint',
 40,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.22-250','.220 Swift','.204 Ruger'],
 'Low',false,'USA',
 'Varmint-optimized ball powder from Alliant''s Power Pro series. Temperature-insensitive formulation ideal for varmint hunters shooting in varying conditions. Excellent metering for high-round-count prairie dog and ground squirrel seasons.',
 'Excellent','Low','Vista Outdoor',NULL,'Alliant Powder'),

-- ═══════════════════════════════════════════════════════════════
-- VIHTAVUORI (additional)
-- ═══════════════════════════════════════════════════════════════

('Vihtavuori','N110',
 28,'Extruded',ARRAY['Pistol','Rifle'],
 ARRAY['.22 Hornet','.357 Magnum','.454 Casull','.30 Carbine'],
 'Low',false,'Finland',
 'Fastest powder in the Vihtavuori N1xx extruded series. Designed for small-capacity rifle cases and magnum handguns. The Finnish standard for .22 Hornet loading. Exceptional consistency and lot-to-lot uniformity characteristic of the entire VV N-series.',
 'Good','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N120',
 32,'Extruded',ARRAY['Rifle'],
 ARRAY['.22 Hornet','.222 Rem','.223 Rem (light)','.17 Remington'],
 'Low',false,'Finland',
 'Second-fastest N1xx extruded powder. Bridges the gap between N110 and N130. Excellent for small-capacity rimmed rifle cases and .17 caliber varmint cartridges. Temperature-stable Vihtavuori chemistry with low lot-to-lot variation.',
 'Good','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N130',
 36,'Extruded',ARRAY['Rifle'],
 ARRAY['.222 Rem','.223 Rem','.17 Remington','.221 Fireball'],
 'Low',false,'Finland',
 'Fast extruded powder from the Vihtavuori N1xx series. Standard Finnish military rifle powder equivalent. Excellent in .222 Rem and .223 Rem with lighter bullets. Consistent burn characteristics across temperature ranges.',
 'Good','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N105',
 87,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.338 Lapua','.300 Norma Mag'],
 'Low',false,'Finland',
 'Vihtavuori''s slowest powder. Ultra-slow extruded formula for .338 Lapua and similar large-capacity precision rifle cases. Low temperature sensitivity throughout the temperature ranges encountered in European and Arctic competition.',
 'Fair','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N530',
 46,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)','.243 Win'],
 'Low',false,'Finland',
 'First ball powder in the Vihtavuori N500 competition series. Designed as a temperature-stable alternative to N135 for AR-platform rifles and service rifle competition. Ball granules provide superior metering compared to N-series extruded counterparts.',
 'Excellent','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N550',
 57,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win (F-Class)','.30-06','6.5 Creedmoor','.260 Rem'],
 'Low',false,'Finland',
 'Competition ball powder from VV''s N500 series at the H4350 burn rate. Temperature-stable alternative to N150 for precision competition. Outstanding for 6.5 Creedmoor and .308 Win in F-Class. Superior metering compared to extruded equivalents.',
 'Excellent','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N560',
 65,'Ball',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['7mm Rem Mag','.300 Win Mag','.30-06 (heavy)','.270 Win (heavy)'],
 'Low',false,'Finland',
 'Slow competition ball powder from VV''s N500 series. The ball-powder equivalent of N160 in burn rate. Designed for magnum rifle cases requiring the precision consistency of Vihtavuori chemistry. Excellent for long-range hunting and competition in 7mm Rem Mag.',
 'Excellent','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N570',
 73,'Ball',ARRAY['Magnum Rifle'],
 ARRAY['.338 Lapua','.300 Win Mag (heavy)','7mm STW','.30-378 Wby'],
 'Low',false,'Finland',
 'Vihtavuori''s slowest N500 competition ball powder. Designed for maximum velocity in large magnum cases. Superior metering advantage over equivalent extruded powders N165/N170. Outstanding for precision long-range hunting where consistent velocity is essential.',
 'Excellent','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','3N37',
 14,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.40 S&W','.45 ACP'],
 'Low',false,'Finland',
 'Competition pistol ball powder from VV''s 3N series. Extremely popular among IPSC Production and ISSF sport pistol competitors. Low temperature sensitivity is the key differentiator versus domestic ball powders. Finnish national competition standard.',
 'Excellent','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','3N38',
 17,'Ball',ARRAY['Pistol'],
 ARRAY['9mm (major)','.38 Super','.40 S&W (major)','10mm'],
 'Low',false,'Finland',
 'Slightly slower than 3N37 for IPSC Open division major power factor loads. The European standard for 9mm Major and .38 Super competition. Low temperature sensitivity enables consistent power factors across summer and winter matches.',
 'Excellent','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

('Vihtavuori','N310',
 2,'Flake',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light)','20 Gauge','.38 Special (light)','.45 ACP (light)'],
 'Low',false,'Finland',
 'Fastest Vihtavuori powder — the benchmark for light target shotshell loads and minimum-charge pistol work. Standard for ISU/ISSF light target 12-gauge loads throughout Europe. Exceptionally clean, consistent, and temperature-stable.',
 'Excellent','Low','Nammo','Nammo Vihtavuori Oy','Capstone Precision Group'),

-- ═══════════════════════════════════════════════════════════════
-- ACCURATE (additional)
-- ═══════════════════════════════════════════════════════════════

('Accurate','No. 1',
 3,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light target)','20 Gauge','.38 Special (light)','.45 ACP (light)'],
 'Moderate',false,'Belgium',
 'Fastest Accurate powder. Ball formulation for light shotshell and target pistol loads. Consistent metering for high-volume target shooting. One of the fastest ball powders available for light target applications.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','No. 2',
 7,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special','.45 ACP','9mm','12 Gauge'],
 'Moderate',false,'Belgium',
 'Fast ball pistol powder in the Red Dot burn rate zone. Excellent metering for USPSA Production and IDPA target loads. One of the most popular Accurate pistol powders for light to medium handgun charges.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','No. 4',
 11,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['9mm','.38 Special','.45 ACP','.40 S&W'],
 'Moderate',false,'Belgium',
 'Ball powder positioned between No. 2 and No. 5 in the Accurate pistol lineup. Clean-burning and consistent across a wide range of pistol calibers. Excellent metering for progressive reloading presses.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','No. 5',
 13,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.357 Magnum','.45 ACP'],
 'Moderate',false,'Belgium',
 'Versatile ball pistol powder covering a wide caliber range. Similar application to Unique but with superior metering due to ball granules. Popular for all handgun calibers from light target to medium power factor.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','No. 7',
 20,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Special','.45 Colt','12 Gauge (target)','.38 Super'],
 'Moderate',false,'Belgium',
 'Medium-burn ball powder bridging the gap between pistol and magnum pistol applications. The go-to Accurate powder for .357 Magnum and .44 Special full-power loads. Consistent performance across temperature ranges.',
 'Excellent','Moderate','Western Powders','PB Clermont','Western Powders'),

('Accurate','No. 9',
 25,'Ball',ARRAY['Pistol'],
 ARRAY['.357 Magnum','.44 Magnum','.45 Colt','.454 Casull','10mm'],
 'Moderate',false,'Belgium',
 'Slowest of the Accurate numbered pistol series. Purpose-built for maximum-velocity loads in magnum handgun cartridges. Excellent for .44 Magnum and .454 Casull full-house loads. Ball powder metering is a significant advantage over flake or extruded alternatives.',
 'Excellent','High','Western Powders','PB Clermont','Western Powders'),

('Accurate','1680',
 31,'Ball',ARRAY['Rifle','Pistol'],
 ARRAY['.22 Hornet','.221 Fireball','7.62x39','.300 Blackout (subsonic)'],
 'Moderate',false,'Belgium',
 'Purpose-designed for small-capacity rifle cases and subsonic applications. The definitive Accurate powder for .300 Blackout subsonic loads. Also excellent for 7.62x39 in AK-pattern rifles. Low metering variance due to ball construction critical for consistent subsonic loads.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','2015',
 38,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.22-250','.17 Remington','.222 Rem'],
 'Moderate',false,'Belgium',
 'Accurate''s fast rifle ball powder for small and medium rifle cases. Popular for .223 Rem varmint and target loads. Competes with H335 and BL-C(2) in application. Uniform density in ball formulation minimizes charge variation in progressive reloaders.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','2230',
 43,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','5.56 NATO','.308 Win (mid-range)'],
 'Moderate',false,'Belgium',
 'One of Accurate''s most popular rifle powders. Primarily used for .223 Rem and 5.56 NATO. Excellent metering for AR-15 reloading. Consistent velocities with military-specification case volumes.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','2460',
 47,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)','.243 Win'],
 'Moderate',false,'Belgium',
 'Medium-speed Accurate ball powder bridging .223 Rem heavy bullet and .308 Win applications. Excellent metering for both varmint and deer rifles. One of the most versatile ball powders in the Accurate rifle series.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','2495',
 52,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.243 Win','.223 Rem (heavy)'],
 'Moderate',false,'Belgium',
 'Classic Accurate ball rifle powder in the Varget burn rate range. Long history in .308 Win competition and service rifle shooting. Consistent lot-to-lot performance. Ball powder construction provides superior metering compared to extruded alternatives.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','2520',
 48,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem','.243 Win'],
 'Moderate',false,'Belgium',
 'Accurate''s medium ball powder optimized for the .308 Win service rifle cartridge. Slightly faster than 2495. Excellent metering for high-volume .308 reloading. Among the most referenced Accurate powders in NRA High Power loading data.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','2700',
 58,'Ball',ARRAY['Rifle'],
 ARRAY['.30-06','.270 Win','.308 Win (heavy)','.25-06'],
 'Moderate',false,'Belgium',
 'Slower ball powder from Accurate''s rifle series. Application range similar to H4350 and IMR 4350. Ball granules provide superior metering over extruded counterparts. Useful for medium-magnum and larger standard rifle cases.',
 'Excellent','Moderate','Western Powders','PB Clermont','Western Powders'),

('Accurate','4350',
 62,'Ball',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.30-06','.270 Win','7mm Rem Mag','.338 Win Mag'],
 'Moderate',false,'Belgium',
 'Accurate''s ball powder equivalent of H4350. Competes directly with Hodgdon H4350 in application but offers superior metering due to ball construction. Well-documented in major loading manuals. Popular as an out-of-stock substitute for H4350.',
 'Excellent','Moderate','Western Powders','PB Clermont','Western Powders'),

('Accurate','5744',
 31,'Extruded',ARRAY['Rifle','Pistol'],
 ARRAY['.45-70 Govt','.450 Marlin','.444 Marlin','7.62x39 (reduced)','.30-06 (reduced)'],
 'Low',false,'Belgium',
 'Unique fast extruded powder designed for low-velocity cast bullet loads and reduced rifle charges. The standard powder for accurate, mild .45-70 Government loads. Also excellent for the .444 Marlin and other large-bore lever-action calibers.',
 'Fair','Low','Western Powders','PB Clermont','Western Powders'),

('Accurate','MagPro',
 76,'Ball',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Win Mag','7mm Rem Mag','.338 Lapua'],
 'Moderate',false,'Belgium',
 'Accurate''s magnum ball powder for large-capacity rifle cases. Excellent metering advantage over extruded competitors at this burn rate. Popular as a substitute for H1000 when stock is unavailable. Used in .300 Win Mag and 7mm Rem Mag full-power hunting loads.',
 'Good','Low','Western Powders','PB Clermont','Western Powders'),

-- ═══════════════════════════════════════════════════════════════
-- RAMSHOT (additional)
-- ═══════════════════════════════════════════════════════════════

('Ramshot','Competition',
 4,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light target)','20 Gauge','.38 Special (light)','.45 ACP (light)'],
 'Low',false,'Belgium',
 'Fastest Ramshot powder. Clean-burning ball powder for light target shotshell and pistol loads. Designed for sporting clays and USPSA target-power loads. Superior metering to flake alternatives for high-volume progressive reloading.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Ramshot','True Blue',
 15,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.357 Magnum','.45 ACP'],
 'Low',false,'Belgium',
 'Medium-fast ball pistol powder bridging the target and medium-power pistol range. Excellent for 9mm Power Factor competition loads and medium .38 Special charges. Ball construction provides superior metering over Unique-class flake powders.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Ramshot','Silhouette',
 18,'Ball',ARRAY['Pistol'],
 ARRAY['.357 Magnum','.44 Magnum','10mm','.45 Colt'],
 'Low',false,'Belgium',
 'Named for IHMSA metallic silhouette competition. Designed specifically for extended-range magnum revolver loads requiring consistent velocity. Excellent for 180gr .357 Mag and full-power .44 Magnum silhouette loads.',
 'Excellent','Moderate','Western Powders','PB Clermont','Western Powders'),

('Ramshot','X-Terminator',
 40,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.22-250','.204 Ruger','.220 Swift'],
 'Low',false,'Belgium',
 'Varmint-specific ball powder optimized for .223 Rem and fast 22-caliber cartridges. Temperature stable for year-round prairie dog and ground squirrel shooting. Excellent metering for high-round-count varmint reloading.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Ramshot','TAC',
 44,'Ball',ARRAY['Rifle'],
 ARRAY['5.56 NATO','.223 Rem','.308 Win (mid-range)','7.62 NATO'],
 'Low',false,'Belgium',
 'Purpose-built for AR-15 and AR-10 tactical applications. Clean-burning with excellent temperature stability profile. The name reflects its tactical/military application focus. Excellent metering for semi-auto rifle reloading.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Ramshot','Hunter',
 61,'Ball',ARRAY['Rifle'],
 ARRAY['.270 Win','.30-06','.308 Win (heavy)','.25-06'],
 'Low',false,'Belgium',
 'Hunting-optimized ball powder at the H4350 burn rate. Temperature-stable for consistent hunting performance across seasons. Popular substitute for H4350 with superior metering. Designed specifically for hunting applications where shot opportunities cannot be wasted.',
 'Excellent','Moderate','Western Powders','PB Clermont','Western Powders'),

('Ramshot','Big Game',
 68,'Ball',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.300 Win Mag','7mm Rem Mag','.338 Win Mag','.30-06 (heavy)'],
 'Low',false,'Belgium',
 'Slow-burning hunting ball powder for large game. Temperature stable for hunting conditions from Alaska to Africa. Application range similar to IMR 4831. Ball construction provides significant metering advantage for reloaders who hunt in remote areas.',
 'Excellent','Low','Western Powders','PB Clermont','Western Powders'),

('Ramshot','Magnum',
 76,'Ball',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Lapua','7mm Rem Mag','.338 Win Mag'],
 'Low',false,'Belgium',
 'Ramshot''s ultra-slow ball powder for the largest magnum cases. Excellent temperature stability for ELR and dangerous game hunting. Superior metering to competitive extruded powders at this burn rate makes it popular with hunters and precision shooters.',
 'Good','Low','Western Powders','PB Clermont','Western Powders'),

('Ramshot','Enforcer',
 23,'Ball',ARRAY['Pistol'],
 ARRAY['.357 Magnum','.44 Magnum','10mm','.41 Magnum'],
 'Low',false,'Belgium',
 'Medium-speed ball powder designed for full-power revolver magnum loads. Excellent for IHMSA metallic silhouette and hunting revolver applications. Clean-burning and consistent in magnum-capacity cases.',
 'Excellent','Moderate','Western Powders','PB Clermont','Western Powders'),

-- ═══════════════════════════════════════════════════════════════
-- WINCHESTER (additional)
-- ═══════════════════════════════════════════════════════════════

('Winchester','WST',
 6,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special (target)','.45 ACP (light)','12 Gauge (light target)','9mm (light)'],
 'Low',false,'USA',
 'Winchester Super Target — fast ball powder designed for light target loads. Very clean-burning. One of the most popular choices for USPSA and IDPA target power factor loads. Low recoil impulse for faster target reacquisition in competition.',
 'Excellent','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('Winchester','AutoComp',
 11,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['9mm','.40 S&W','.38 Super','.45 ACP','12 Gauge'],
 'Low',false,'USA',
 'Originally developed for autoloading pistol and shotgun competition. Clean-burning with excellent temperature stability. Works across a wide range of calibers. Named for its autoloading competition heritage.',
 'Excellent','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('Winchester','WSF',
 17,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Super','9mm','.40 S&W','12 Gauge (target)','.45 ACP'],
 'Low',false,'USA',
 'Winchester Super Field — medium-fast ball powder for the pistol/shotgun crossover zone. Versatile across shotshell and handgun applications. Popular for standard velocity 9mm and .40 S&W target loads. Consistent performance in both pistol and 12-gauge applications.',
 'Excellent','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('Winchester','748',
 44,'Ball',ARRAY['Rifle'],
 ARRAY['5.56 NATO','.223 Rem','.308 Win','.30-06'],
 'Moderate',false,'USA',
 'Classic Winchester medium ball rifle powder with decades of service rifle history. Originally developed for military 5.56 NATO production. Outstanding metering for AR-15 and service rifle reloading. One of the most well-documented ball rifle powders in existence.',
 'Excellent','Low','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('Winchester','760',
 55,'Ball',ARRAY['Rifle'],
 ARRAY['.270 Win','.30-06','.308 Win (heavy)','.25-06'],
 'Moderate',false,'USA',
 'Classic Winchester medium-slow ball powder in the H414/IMR 4350 burn rate range. Outstanding for .270 Win and .30-06 with standard hunting bullets. Consistently ranks among the most accurate powders for these cartridges in published loading data.',
 'Excellent','Moderate','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('Winchester','540',
 19,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Magnum','12 Gauge (target)','.38 Super'],
 'Moderate',false,'USA',
 'Medium-speed Winchester ball powder for the magnum pistol and target shotshell zone. Clean-burning alternative to flake magnum pistol powders. Good metering consistency across powder measures.',
 'Excellent','Moderate','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

('Winchester','572',
 21,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Magnum','12 Gauge (magnum)','.45 Colt'],
 'Moderate',false,'USA',
 'Winchester medium-slow pistol/shotgun ball powder. Designed for the upper magnum handgun range and heavy shotshell applications. Fills the gap between WSF and 296 in the Winchester lineup.',
 'Excellent','Moderate','Hodgdon Powder Company',NULL,'Hodgdon Powder Company'),

-- ═══════════════════════════════════════════════════════════════
-- NORMA (additional)
-- ═══════════════════════════════════════════════════════════════

('Norma','Norma 200',
 53,'Extruded',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.243 Win','.260 Rem'],
 'Moderate',false,'Sweden',
 'Norma''s medium extruded rifle powder in the Varget/H4895 burn rate range. Classic Swedish precision rifle powder with excellent lot-to-lot consistency. Standard in Scandinavian .308 Win precision shooting. Clean-burning with tight extreme spreads.',
 'Good',NULL,'RUAG Ammotec','Norma Precision AB','RUAG Ammotec USA'),

('Norma','Norma 201',
 50,'Extruded',ARRAY['Rifle'],
 ARRAY['.308 Win','.223 Rem (heavy)','.243 Win','.30-06'],
 'Moderate',false,'Sweden',
 'Slightly faster than Norma 200. Bridges the gap between medium and fast extruded rifle powders in the Norma line. Well-documented in Norma reloading data. Complement to the 200 series for slightly smaller case capacities.',
 'Good',NULL,'RUAG Ammotec','Norma Precision AB','RUAG Ammotec USA'),

('Norma','Norma 202',
 58,'Extruded',ARRAY['Rifle'],
 ARRAY['.30-06','.270 Win','.308 Win (heavy)','6.5x55 Swedish'],
 'Moderate',false,'Sweden',
 'Classic Norma extruded rifle powder with outstanding heritage in 6.5x55 Swedish and .30-06 Springfield. Long the standard in Scandinavian moose and big game hunting loads. Clean-burning and consistent across wide temperature ranges.',
 'Good',NULL,'RUAG Ammotec','Norma Precision AB','RUAG Ammotec USA'),

('Norma','Norma 204',
 65,'Extruded',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.300 Win Mag','7mm Rem Mag','.270 Win (heavy)'],
 'Moderate',false,'Sweden',
 'Slow-medium Norma extruded powder for standard and short magnum cases. Application similar to IMR 4831. Heritage in European .300 Win Mag and 7mm Rem Mag loading data. Standard in the Norma loading manual for large-capacity standard cases.',
 'Fair',NULL,'RUAG Ammotec','Norma Precision AB','RUAG Ammotec USA'),

('Norma','MRP',
 66,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Win Mag','7mm Rem Mag','.375 H&H'],
 'Moderate',false,'Sweden',
 'Magnum Rifle Powder — Norma''s primary slow magnum extruded powder. Long history as the Swedish standard for dangerous game and large magnum cartridges. Excellent for .375 H&H and .338 Win Mag. Still heavily referenced in European dangerous game loading data.',
 'Fair',NULL,'RUAG Ammotec','Norma Precision AB','RUAG Ammotec USA'),

('Norma','MRP2',
 70,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Lapua','7mm STW','.375 H&H (heavy)'],
 'Moderate',false,'Sweden',
 'Slower than MRP — Norma''s answer to the need for slower magnum powders as larger belted magnums and overbore cartridges grew in popularity. Excellent for maximum loads in .300 Win Mag and .338 Lapua.',
 'Poor',NULL,'RUAG Ammotec','Norma Precision AB','RUAG Ammotec USA'),

('Norma','Norma R1',
 40,'Extruded',ARRAY['Rifle'],
 ARRAY['.223 Rem','.222 Rem','5.56 NATO','.22 PPC'],
 'Moderate',false,'Sweden',
 'Fast extruded rifle powder from Norma for small rifle cases. Standard for .222 Rem and .223 Rem in the Norma European tradition. Not as widely available in North America as other Norma powders but well-documented in European loading references.',
 'Good',NULL,'RUAG Ammotec','Norma Precision AB','RUAG Ammotec USA'),

-- ═══════════════════════════════════════════════════════════════
-- SHOOTERS WORLD (additional)
-- ═══════════════════════════════════════════════════════════════

('Shooters World','Action Pistol',
 10,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.40 S&W','.45 ACP','.38 Special'],
 'Low',false,'Czech Republic',
 'Clean-burning, temperature-stable ball powder for target pistol applications. Growing adoption in USPSA Production and IDPA. Very consistent chronograph readings across temperature ranges — a defining advantage over domestic competitors.',
 'Excellent','Low','Shooters World','Explosia','Shooters World'),

('Shooters World','Economy Rifle',
 42,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','5.56 NATO','.308 Win'],
 'Low',false,'Czech Republic',
 'High-volume rifle ball powder designed for cost-effective .223 Rem and 5.56 NATO reloading. As the name implies, optimized for the economics of bulk rifle reloading. Consistent and clean. Significant market growth as an alternative to Hodgdon ball powders.',
 'Excellent','Low','Shooters World','Explosia','Shooters World'),

('Shooters World','Match Rifle',
 48,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)'],
 'Low',false,'Czech Republic',
 'Competition-grade ball powder optimized for .308 Win match reloading. Temperature-stable Explosia chemistry. Gaining adoption in NRA High Power and F-Class competition as a consistent and available alternative to Varget.',
 'Excellent','Low','Shooters World','Explosia','Shooters World'),

('Shooters World','Long Rifle',
 60,'Extruded',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.270 Win','.30-06','6.5 Creedmoor','.308 Win (heavy)'],
 'Low',false,'Czech Republic',
 'Slow extruded rifle powder positioned in the H4350 application zone. Temperature-stable chemistry. Growing use in precision rifle competition as an alternative to Hodgdon H4350 during availability shortages.',
 'Fair','Low','Shooters World','Explosia','Shooters World'),

('Shooters World','Precision Rifle',
 54,'Extruded',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.243 Win','.223 Rem (heavy)'],
 'Low',false,'Czech Republic',
 'Precision-grade extruded rifle powder in the Varget burn rate zone. Temperature-stable for consistent performance across seasons. Positioned as a competition-viable alternative to Varget. The Shooters World choice for precision rifle reloaders seeking temperature stability.',
 'Fair','Low','Shooters World','Explosia','Shooters World'),

('Shooters World','Magnum Rifle',
 73,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Lapua','7mm Rem Mag'],
 'Low',false,'Czech Republic',
 'Ultra-slow extruded powder for large magnum cases. Temperature-stable Explosia chemistry designed for consistent performance from Scandinavian winters to desert summers. Growing presence in ELR competition and long-range hunting as an H1000 alternative.',
 'Poor','Low','Shooters World','Explosia','Shooters World'),

('Shooters World','Multi-Purpose Pistol',
 14,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.357 Magnum','.45 ACP'],
 'Low',false,'Czech Republic',
 'Versatile medium-speed pistol ball powder covering a broad caliber range. The Shooters World general-purpose handgun powder. Excellent temperature stability distinguishes it from domestic competitors in the Unique burn rate range.',
 'Excellent','Low','Shooters World','Explosia','Shooters World'),

-- ═══════════════════════════════════════════════════════════════
-- ADI (Australian Defence Industries)
-- ═══════════════════════════════════════════════════════════════

('ADI','AR 2205',
 37,'Extruded',ARRAY['Rifle'],
 ARRAY['.222 Rem','.223 Rem','.22 PPC'],
 'Low',false,'Australia',
 'ADI equivalent of Hodgdon H322. Manufactured at the Mulwala facility in New South Wales. The standard Australian .222 Rem and .223 Rem competition powder. Widely available in Australian retail channels. Lot-to-lot consistency meets Australian Defence standards.',
 'Good','Low',NULL,'ADI','ADI'),

('ADI','AR 2206H',
 53,'Extruded',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)','.243 Win'],
 'Low',false,'Australia',
 'Near-equivalent to Hodgdon H4895 with slightly improved temperature stability. The standard Australian .308 Win competition and service rifle powder. Dominant in Australian F-Class and NRA-style service rifle competition. Manufactured at Mulwala under Australian defence specifications.',
 'Good','Low',NULL,'ADI','ADI'),

('ADI','AR 2207',
 53,'Extruded',ARRAY['Rifle'],
 ARRAY['.22-250','.220 Swift','.243 Win','.308 Win'],
 'Low',false,'Australia',
 'Equivalent to Hodgdon H380 in application. Popular Australian varmint powder for fast .22-caliber and .24-caliber cartridges. Standard in the Australian reloading market for .22-250 and .220 Swift maximum velocity loads.',
 'Good','Low',NULL,'ADI','ADI'),

('ADI','AR 2208',
 55,'Extruded',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)','.243 Win'],
 'Low',false,'Australia',
 'The primary ADI source powder for Hodgdon Varget. Near-identical formula and application. Standard Australian precision rifle powder. AR 2208 and Varget are functionally interchangeable and data is cross-referenced between brands in Australian loading manuals.',
 'Good','Low',NULL,'ADI','ADI'),

('ADI','AR 2209',
 62,'Extruded',ARRAY['Rifle'],
 ARRAY['.270 Win','.30-06','6.5 Creedmoor','7mm Rem Mag'],
 'Low',false,'Australia',
 'The ADI equivalent of Hodgdon H4350. Standard Australian big game and precision powder. Dominant in Australian long-range competition and hunting. Cross-referenced with H4350 in Australian loading manuals. Temperature-stable as required by Australian Defence specifications.',
 'Fair','Low',NULL,'ADI','ADI'),

('ADI','AR 2213SC',
 70,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['7mm Rem Mag','.300 Win Mag','.338 Win Mag','.30-06 (heavy)'],
 'Low',false,'Australia',
 'Short-cut formulation equivalent to Hodgdon H4831SC. The SC designation reflects the improved metering of the short-cut kernels. Standard Australian slow magnum powder. Dominant for .300 Win Mag and 7mm Rem Mag in Australian hunting and competition.',
 'Good','Low',NULL,'ADI','ADI'),

('ADI','AR 2217',
 73,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.338 Lapua','.300 Norma Mag'],
 'Low',false,'Australia',
 'ADI equivalent of Hodgdon H1000. Among the slowest of the ADI extruded powders. Used for maximum-velocity loads in large magnum cases. Temperature-stable as required for Australian Defence use. Standard for .300 Win Mag and .338 Lapua in Australian long-range competition.',
 'Fair','Low',NULL,'ADI','ADI'),

('ADI','AR 2218',
 78,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.338 Lapua','.300 RUM','.30-378 Wby'],
 'Low',false,'Australia',
 'ADI''s slowest powder — the equivalent of Hodgdon Retumbo. Designed for ultra-high-capacity magnum cases. Available in Australia for extreme long range .338 Lapua reloading. Meets Australian Defence Industry manufacturing standards for consistent lot production.',
 'Poor','Low',NULL,'ADI','ADI'),

-- ═══════════════════════════════════════════════════════════════
-- RELOAD SWISS
-- ═══════════════════════════════════════════════════════════════

('Reload Swiss','RS10',
 4,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light)','.38 Special (light)','.45 ACP (light)'],
 'Low',false,'Switzerland',
 'Fastest Reload Swiss ball powder. Optimized for light target shotshell and minimum-charge pistol loads. Swiss manufacturing precision results in exceptional lot-to-lot consistency. Growing adoption in European and North American ISSF competition.',
 'Excellent','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS12',
 6,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (target)','20 Gauge','.38 Special','.45 ACP'],
 'Low',false,'Switzerland',
 'Fast ball powder for target shotshell and light pistol applications. Swiss precision manufacturing ensures minimal lot-to-lot variation. Excellent clean-burning characteristics for indoor range use.',
 'Excellent','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS20',
 11,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.40 S&W','.38 Special','.45 ACP'],
 'Low',false,'Switzerland',
 'Medium-fast ball pistol powder. Growing use in European IPSC competition for target and minor power factor loads. Excellent temperature stability across the Swiss alpine climate range. Clean-burning, low flash signature.',
 'Excellent','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS24',
 15,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.357 Magnum','.40 S&W','.38 Super'],
 'Low',false,'Switzerland',
 'Medium ball pistol powder similar in application to True Blue and Silhouette. Standard Swiss competition powder for 9mm and .40 S&W. Exceptional temperature stability is the hallmark of the Reload Swiss line.',
 'Excellent','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS36',
 19,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Magnum','12 Gauge (magnum)'],
 'Low',false,'Switzerland',
 'Medium-speed ball powder for magnum pistol and heavy shotshell applications. Swiss precision manufacturing ensures consistent burning characteristics. Excellent for .357 Magnum IPSC major power factor loads.',
 'Excellent','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS40',
 40,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.222 Rem','.22-250'],
 'Low',false,'Switzerland',
 'Varmint-range ball rifle powder from Reload Swiss. Excellent temperature stability for year-round varmint shooting. Clean-burning with consistent ignition across cold Swiss alpine winters. Growing adoption among European .223 Rem varmint shooters.',
 'Excellent','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS50',
 48,'Extruded',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)'],
 'Low',false,'Switzerland',
 'Medium extruded rifle powder in the Varget burn rate zone. Swiss precision manufacturing with excellent temperature stability. Standard European option for .308 Win precision competition where VV or Hodgdon powders are unavailable.',
 'Good','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS52',
 50,'Extruded',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.243 Win'],
 'Low',false,'Switzerland',
 'Slightly slower than RS50. Comprehensive coverage of the medium rifle burn rate zone. Same Nitrochemie AG base with exceptional consistency. Alternative to Accurate 2495 or Varget for European precision rifle reloading.',
 'Good','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS60',
 55,'Extruded',ARRAY['Rifle'],
 ARRAY['.30-06','.270 Win','.308 Win (heavy)','6.5x55 Swedish'],
 'Low',false,'Switzerland',
 'Medium-slow extruded rifle powder from Reload Swiss. Application range similar to IMR 4350. Standard Swiss choice for 6.5x55 Swedish and .30-06 precision loads. Nitrochemie''s temperature-stable chemistry is especially valued in Alpine hunting conditions.',
 'Good','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS62',
 62,'Extruded',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.270 Win','.30-06 (heavy)','7mm Rem Mag'],
 'Low',false,'Switzerland',
 'Slow extruded powder for larger standard and short magnum cases. The Reload Swiss equivalent of H4350. Excellent for 6.5 Creedmoor with heavy bullets. Temperature-stable performance across the temperature range encountered in European mountain hunting.',
 'Good','Low',NULL,'Nitrochemie AG',NULL),

('Reload Swiss','RS70',
 70,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','7mm Rem Mag','.338 Win Mag'],
 'Low',false,'Switzerland',
 'Slow extruded powder for magnum rifle applications. Application similar to H4831 and IMR 4831. Swiss precision manufacturing ensures consistent performance. Standard Reload Swiss option for large magnum hunting and precision rifle applications.',
 'Fair','Low',NULL,'Nitrochemie AG',NULL),

-- ═══════════════════════════════════════════════════════════════
-- VECTAN
-- ═══════════════════════════════════════════════════════════════

('Vectan','BA10',
 3,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light target)','20 Gauge','.38 Special (light)'],
 'Low',false,'France',
 'Fastest Vectan powder. Ultra-fast ball powder for light target shotshell loads. Standard French competitive clay target powder. The benchmark for minimum-weight 12-gauge and 20-gauge target charges in European ISSF competition.',
 'Excellent','Low',NULL,'Nobel Sport',NULL),

('Vectan','BA9.5',
 5,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (target)','20 Gauge','.38 Special'],
 'Low',false,'France',
 'Slightly slower than BA10 with broader caliber coverage. Primary French powder for international ISSF clay target competition. Clean-burning and consistent under European competition conditions.',
 'Excellent','Low',NULL,'Nobel Sport',NULL),

('Vectan','BA9',
 7,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge','20 Gauge','.38 Special','.45 ACP'],
 'Low',false,'France',
 'Fast ball powder for target shotshell and light pistol. One of the most widely used French sporting powders. Popular throughout European IPSC target-power reloading. Good temperature stability across the French climate range.',
 'Excellent','Low',NULL,'Nobel Sport',NULL),

('Vectan','AS',
 12,'Flake',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special','.45 ACP','9mm','12 Gauge'],
 'Low',false,'France',
 'Versatile Vectan flake powder covering the Unique application zone. One of the most documented French pistol and shotgun powders. Standard in French reloading manuals for medium-velocity pistol loads. Comparable to Alliant Unique in application.',
 'Good',NULL,NULL,'Nobel Sport',NULL),

('Vectan','SP2',
 16,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.357 Magnum','.40 S&W'],
 'Low',false,'France',
 'Medium-speed ball pistol powder. The standard Vectan choice for 9mm and .38 Special competition loads. Clean-burning with good temperature stability. Growing adoption among European IPSC Production reloaders.',
 'Excellent','Low',NULL,'Nobel Sport',NULL),

('Vectan','SP3',
 19,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Magnum','12 Gauge (magnum)'],
 'Low',false,'France',
 'Medium-slow ball powder for magnum pistol and heavy shotshell. Standard Vectan powder for .357 Magnum full-power loads. Excellent metering through progressive equipment. Growing North American adoption as availability from importers improves.',
 'Excellent','Low',NULL,'Nobel Sport',NULL),

('Vectan','GM3',
 22,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.357 Magnum','.44 Magnum','12 Gauge (heavy)'],
 'Low',false,'France',
 'Vectan''s medium magnum ball powder. One of the more popular Vectan powders in North America due to its versatility across magnum pistol and heavy shotshell applications. Consistent performance in both revolver and semi-auto magnum cartridges.',
 'Excellent','Moderate',NULL,'Nobel Sport',NULL),

('Vectan','A0',
 39,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','7.62x39','.30-30 Win'],
 'Low',false,'France',
 'Vectan''s fast rifle ball powder. Standard French military-equivalent small rifle powder. Application similar to H335. Clean-burning for high-volume .223 Rem reloading. Growing adoption in North America as an H335 substitute.',
 'Excellent','Low',NULL,'Nobel Sport',NULL),

('Vectan','A1',
 44,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.223 Rem (heavy)','5.56 NATO'],
 'Low',false,'France',
 'Medium-speed Vectan rifle ball powder at the BL-C(2)/H335 burn rate. Standard for French 7.62 NATO service rifle reloading. Growing North American presence as an alternative to domestic ball rifle powders in periods of supply constraint.',
 'Excellent','Low',NULL,'Nobel Sport',NULL),

('Vectan','Tubal 7000',
 72,'Ball',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','7mm Rem Mag','.338 Win Mag','.375 H&H'],
 'Moderate',false,'France',
 'Vectan''s ultra-slow ball powder for large magnum rifle cases. Application similar to H4831 and Ramshot Big Game. Ball construction provides metering advantages over extruded alternatives. One of the few very-slow ball powders available for magnum hunting.',
 'Good','Low',NULL,'Nobel Sport',NULL),

-- ═══════════════════════════════════════════════════════════════
-- LOVEX / EXPLOSIA
-- ═══════════════════════════════════════════════════════════════

('Lovex','S065',
 4,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light)','.38 Special (light)','.45 ACP (light)'],
 'Low',false,'Czech Republic',
 'Fast Lovex ball powder for light shotshell and target pistol applications. Manufactured to Czech defence-grade specifications at Explosia''s Pardubice facility. Consistent lot-to-lot performance. Growing adoption as Shooters World expands US distribution.',
 'Excellent','Low',NULL,'Explosia a.s.',NULL),

('Lovex','S070',
 6,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special','9mm','.45 ACP','12 Gauge'],
 'Low',false,'Czech Republic',
 'Fast clean-burning Lovex ball powder. Application similar to Clays/International Clays. Manufactured at Explosia for both military and civilian markets. Temperature-stable Czech chemistry.',
 'Excellent','Low',NULL,'Explosia a.s.',NULL),

('Lovex','D060.5',
 15,'Ball',ARRAY['Pistol'],
 ARRAY['9mm','.38 Special','.357 Magnum'],
 'Low',false,'Czech Republic',
 'Medium-speed Lovex ball pistol powder. Standard Explosia competition pistol powder. Clean-burning, temperature-stable. Growing European IPSC presence as the Lovex brand expands.',
 'Excellent','Low',NULL,'Explosia a.s.',NULL),

('Lovex','D036.3',
 26,'Ball',ARRAY['Pistol','Magnum Pistol'],
 ARRAY['.357 Magnum','.44 Magnum','.38 Super','9mm (major)'],
 'Low',false,'Czech Republic',
 'Lovex''s medium-slow competition pistol powder. Used in IPSC Open and Limited division major power factor loads throughout Europe. Explosia''s competition-grade ball powder with excellent temperature stability.',
 'Excellent','Low',NULL,'Explosia a.s.',NULL),

('Lovex','D073.3',
 23,'Ball',ARRAY['Pistol'],
 ARRAY['.357 Magnum','.40 S&W (major)','10mm'],
 'Low',false,'Czech Republic',
 'Medium Lovex competition ball powder. Clean-burning with excellent temperature stability. Primarily used for IPSC Open division major power factor loads in Europe. Explosia defence-grade consistency.',
 'Excellent','Low',NULL,'Explosia a.s.',NULL),

('Lovex','S010',
 42,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','5.56 NATO','7.62x39'],
 'Low',false,'Czech Republic',
 'Lovex rifle ball powder for small to medium rifle cases. Application similar to BL-C(2). Czech military equivalent small rifle powder. Consistent across the temperature ranges encountered in Central European conditions.',
 'Excellent','Low',NULL,'Explosia a.s.',NULL),

('Lovex','D032.5',
 48,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)'],
 'Low',false,'Czech Republic',
 'Lovex medium rifle ball powder in the Varget/4895 burn rate zone. Standard Czech medium rifle powder. Application similar to IMR 4895. Temperature-stable for consistent competition performance across seasons.',
 'Excellent','Low',NULL,'Explosia a.s.',NULL),

('Lovex','D072.5',
 58,'Ball',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.30-06','.270 Win','.308 Win (heavy)','7mm Rem Mag'],
 'Low',false,'Czech Republic',
 'Slow Lovex ball powder for larger rifle and short magnum cases. Application in the H4350 burn rate zone. Ball construction provides metering advantages. Temperature-stable for hunting applications in varying conditions.',
 'Excellent','Moderate',NULL,'Explosia a.s.',NULL),

-- ═══════════════════════════════════════════════════════════════
-- MAXAM (Spanish)
-- ═══════════════════════════════════════════════════════════════

('Maxam','CSB1',
 3,'Ball',ARRAY['Shotgun','Pistol'],
 ARRAY['12 Gauge (light target)','20 Gauge','.38 Special'],
 'Low',false,'Spain',
 'Fast Maxam ball powder for light target shotshell and pistol applications. Standard Spanish competition clay target powder. Consistent production from Maxam''s Burgos facility. Growing North American availability through specialty importers.',
 'Excellent','Low',NULL,'Maxam',NULL),

('Maxam','CSB2',
 7,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special','9mm','12 Gauge (target)'],
 'Low',false,'Spain',
 'Medium-fast Maxam ball powder. One of the most common Spanish competition pistol powders. Reliable and clean-burning. Standard for IPSC Minor power factor loads in Spanish and Portuguese competition.',
 'Excellent','Low',NULL,'Maxam',NULL),

('Maxam','CSB3',
 12,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['9mm','.38 Special','12 Gauge','.357 Magnum'],
 'Low',false,'Spain',
 'Medium Maxam ball powder in the Unique application zone. Standard for medium-velocity pistol and shotgun loads in Spanish competition. Consistent performance across Iberian climate conditions.',
 'Excellent','Low',NULL,'Maxam',NULL),

('Maxam','CSP1',
 19,'Ball',ARRAY['Pistol'],
 ARRAY['.357 Magnum','9mm (major)','.38 Super'],
 'Low',false,'Spain',
 'Medium-slow Maxam pistol ball powder. Application similar to HS-6 and Power Pro 300-MP. Standard for .357 Magnum and major power factor 9mm in Iberian IPSC competition.',
 'Excellent','Low',NULL,'Maxam',NULL),

('Maxam','CSP2',
 25,'Ball',ARRAY['Pistol'],
 ARRAY['.357 Magnum','.44 Magnum','10mm'],
 'Low',false,'Spain',
 'Slower Maxam magnum pistol powder. Application in the 2400 burn rate zone. Standard for heavy .44 Magnum loads in Spanish competition. Consistent and clean-burning.',
 'Excellent','Moderate',NULL,'Maxam',NULL),

('Maxam','CSP3',
 32,'Ball',ARRAY['Pistol','Rifle'],
 ARRAY['.44 Magnum','.454 Casull','.22 Hornet'],
 'Low',false,'Spain',
 'Slowest Maxam pistol ball powder. Bridges the magnum pistol and small rifle boundary. Application similar to H110 and H4227. Specialized use in very heavy magnum loads and small rifle cases.',
 'Excellent','High',NULL,'Maxam',NULL),

('Maxam','CSRB1',
 46,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.308 Win','5.56 NATO'],
 'Low',false,'Spain',
 'Maxam''s fast ball rifle powder. Application equivalent to BL-C(2) and H335. Standard Spanish military equivalent rifle powder. Consistent for high-volume military-specification reloading.',
 'Excellent','Low',NULL,'Maxam',NULL),

('Maxam','CSRB2',
 58,'Ball',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.30-06','.270 Win','.308 Win (heavy)'],
 'Low',false,'Spain',
 'Slow Maxam ball rifle powder for larger standard rifle cases. Application in the H414/H4350 zone. Standard Spanish powder for hunting loads in .30-06 and .270 Win. Ball construction ensures consistent metering for hunting reloads.',
 'Excellent','Moderate',NULL,'Maxam',NULL),

-- ═══════════════════════════════════════════════════════════════
-- SOMCHEM (South Africa)
-- ═══════════════════════════════════════════════════════════════

('Somchem','S121',
 12,'Ball',ARRAY['Pistol','Shotgun'],
 ARRAY['.38 Special','9mm','.45 ACP','12 Gauge'],
 'Low',false,'South Africa',
 'Fast Somchem ball pistol/shotgun powder. Standard South African competition pistol powder. Consistent performance under Southern Hemisphere climate conditions. Limited North American availability but well-documented in South African loading data.',
 'Excellent','Low',NULL,'PMP/Denel',NULL),

('Somchem','S123',
 22,'Ball',ARRAY['Pistol'],
 ARRAY['.357 Magnum','.38 Super','9mm','.45 Colt'],
 'Low',false,'South Africa',
 'Medium Somchem pistol ball powder. Standard for South African IPSC and biathlon competition. Good temperature stability across sub-Saharan conditions. Application similar to Unique and HS-6.',
 'Excellent','Low',NULL,'PMP/Denel',NULL),

('Somchem','S130',
 34,'Ball',ARRAY['Pistol','Rifle'],
 ARRAY['.357 Magnum','.44 Magnum','.22 Hornet'],
 'Low',false,'South Africa',
 'Medium-slow Somchem ball powder bridging the magnum pistol and small rifle boundary. Standard South African powder for full-power revolver loads and some small rifle applications.',
 'Excellent','High',NULL,'PMP/Denel',NULL),

('Somchem','S133',
 40,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.22-250','5.56 NATO'],
 'Low',false,'South Africa',
 'Fast Somchem rifle ball powder. South African military equivalent for 5.56 NATO. Standard in South African NRA-style service rifle competition. Consistent performance across sub-Saharan temperature ranges.',
 'Excellent','Low',NULL,'PMP/Denel',NULL),

('Somchem','S135',
 44,'Ball',ARRAY['Rifle'],
 ARRAY['.223 Rem','.308 Win','5.56 NATO'],
 'Low',false,'South Africa',
 'Medium-fast Somchem rifle ball powder. Application similar to BL-C(2) and TAC. Standard South African .308 Win service rifle powder. Used in South African NDF-specification ammunition production.',
 'Excellent','Low',NULL,'PMP/Denel',NULL),

('Somchem','S243',
 55,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.270 Win'],
 'Low',false,'South Africa',
 'Medium-slow Somchem ball rifle powder. Application in the Varget/H4895 burn rate zone. Standard South African hunting powder for medium rifle cases. Consistent across the temperature extremes of Southern African hunting conditions.',
 'Excellent','Low',NULL,'PMP/Denel',NULL),

('Somchem','S353',
 62,'Extruded',ARRAY['Rifle','Magnum Rifle'],
 ARRAY['.30-06','.270 Win','7mm Rem Mag'],
 'Low',false,'South Africa',
 'Slow extruded Somchem powder for large standard and short magnum rifle cases. Standard South African choice for .30-06 and .270 Win hunting loads with heavy bullets. Application similar to H4350 and IMR 4350.',
 'Fair','Low',NULL,'PMP/Denel',NULL),

('Somchem','S355',
 68,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','7mm Rem Mag','.338 Win Mag'],
 'Low',false,'South Africa',
 'Very slow extruded Somchem powder for magnum rifle cases. Standard South African dangerous game powder for .300 Win Mag and similar. Application similar to IMR 4831. Used in South African ammunition for dangerous game hunting.',
 'Fair','Low',NULL,'PMP/Denel',NULL),

('Somchem','S365',
 73,'Extruded',ARRAY['Magnum Rifle'],
 ARRAY['.300 Win Mag','.375 H&H','.338 Lapua'],
 'Low',false,'South Africa',
 'Ultra-slow extruded Somchem powder for the largest magnum cases. The South African equivalent of H1000. Standard for maximum .375 H&H and similar dangerous game hunting loads. Excellent temperature stability in tropical African conditions.',
 'Poor','Low',NULL,'PMP/Denel',NULL),

('Somchem','MS200',
 48,'Ball',ARRAY['Rifle'],
 ARRAY['.308 Win','.30-06','.223 Rem (heavy)'],
 'Low',false,'South Africa',
 'Somchem military specification ball powder. Designed for South African National Defence Force 7.62 NATO and 5.56 NATO production. Available to civilian reloaders through South African channels. Consistent military-specification quality.',
 'Excellent','Low',NULL,'PMP/Denel',NULL)

ON CONFLICT (brand, product_name) DO NOTHING;
