-- ============================================================
-- Missing Manufacturers Batch 1 — 55 manufacturers
-- US historical, SNS era, Spanish, European, Italian, black
-- powder, WWII M1 Carbine contractors
-- ============================================================

INSERT INTO public.manufacturers (
  name, alternate_names, country_of_origin, founded_year, active,
  categories, parent_company, subsidiaries, description,
  notable_models, website, headquarters,
  production_country, us_import_status, volume_tier,
  market_segment, ownership_type, low_confidence,
  entity_type, known_for, notable_designers,
  price_tier_entry_usd, has_military_contract, military_notes, trivia,
  production_countries, collector_prestige_tier, signature_model
) VALUES

-- ── US HISTORICAL / NOTABLE ──────────────────────────────────

(
  'Iver Johnson Arms',
  ARRAY['Iver Johnson', 'Iver Johnson Arms & Cycle Works'],
  'United States', 1871, false,
  ARRAY['Pistol', 'Revolver', 'Rifle', 'Shotgun'],
  NULL, NULL,
  'Iver Johnson Arms & Cycle Works was an American manufacturer founded in 1871 in Fitchburg, Massachusetts by Norwegian immigrant Iver Johnson. The company became one of the largest American handgun manufacturers of the late 19th and early 20th centuries, producing affordable revolvers, break-action shotguns, and later semi-automatic pistols. Their Safety Automatic Revolver introduced the hammer-the-frame transfer bar — a genuine safety innovation that became standard across the industry. Iver Johnson revolvers were ubiquitous in American homes from the 1880s through the 1950s. The original company went through several ownership changes and a final closure; the brand was revived in 2006 as Iver Johnson Arms Inc. making AR-pattern rifles and 1911s.',
  ARRAY['Safety Automatic Revolver', '1900 Revolver', 'Champion Shotgun', 'TP22', 'TP25'],
  'https://www.iverjohnsonarms.com', 'Rockledge, Florida, USA (revived)',
  'United States', 'Domestic', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['transfer bar safety revolver', 'break-action shotguns', 'affordable revolvers'],
  ARRAY['Iver Johnson'],
  299, false, NULL,
  'An Iver Johnson revolver was the weapon used in the assassination of President William McKinley in 1901. This notoriety, combined with widespread distribution, made the Iver Johnson Safety Automatic Revolver one of the most historically documented handguns in American history.',
  ARRAY['United States'], 'Medium', 'Safety Automatic Revolver'
),

(
  'Stevens Arms',
  ARRAY['J. Stevens Arms', 'J. Stevens Arms & Tool Co.', 'Stevens'],
  'United States', 1864, true,
  ARRAY['Rifle', 'Shotgun', 'Pistol'],
  'Savage Arms', NULL,
  'J. Stevens Arms was founded in 1864 in Chicopee Falls, Massachusetts by Joshua Stevens. The company became one of the most prolific American firearms manufacturers of the late 19th and early 20th centuries, producing single-shot pistols, .22 rifles, and a vast range of shotguns. Stevens merged with Savage Arms in 1920 and the Stevens name has been used as a budget sub-brand of Savage ever since. The Stevens Model 311 side-by-side and Model 520/620 pump shotguns were widely used by US military and police in both World Wars. The brand remains active today on entry-level Savage shotguns.',
  ARRAY['Model 311', 'Model 520', 'Model 67', 'Model 320', 'Model 200'],
  NULL, 'Chicopee Falls, Massachusetts (historical); Westfield, Massachusetts (current)',
  'United States', 'Domestic', 'High', 'mass', 'Subsidiary', false,
  'Manufacturer',
  ARRAY['pump-action shotguns', 'side-by-side shotguns', '.22 rifles', 'single-shot rifles'],
  ARRAY['Joshua Stevens'],
  199, true, 'Stevens Model 520/620 pump shotguns were issued to US military and Navy personnel in WWI and WWII as trench and riot guns.',
  'At its peak in the early 1900s, Stevens was the largest producer of sporting arms in the United States by unit volume — selling more guns than Winchester, Remington, and Colt combined.',
  ARRAY['United States'], 'Low', 'Model 311'
),

(
  'High Standard Manufacturing',
  ARRAY['High Standard', 'Hartford Arms', 'High Standard Mfg. Co.'],
  'United States', 1926, false,
  ARRAY['Pistol', 'Revolver', 'Rifle', 'Shotgun'],
  NULL, NULL,
  'High Standard Manufacturing Company was an American firearms maker founded in 1926 in New Haven, Connecticut. The company built its reputation on high-quality .22 LR target pistols that dominated American pistol competition from the 1940s through the 1970s. High Standard pistols won Olympic gold medals, national championships, and set numerous accuracy records. Their Supermatic Trophy, Citation, and Victor pistols are still regarded as among the finest production .22 target pistols ever made in the United States. The company also made a popular line of pump and semi-auto shotguns. High Standard went out of business in 1984; the brand was revived in 1993 and operated until 2018.',
  ARRAY['Supermatic Trophy', 'Citation', 'Victor', 'Sport King', 'Sentinel', 'Flite King'],
  NULL, 'Houston, Texas (final location)',
  'United States', 'Domestic', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['.22 LR target pistols', 'Olympic target shooting', 'pump shotguns', 'semi-auto shotguns'],
  NULL,
  NULL, false, NULL,
  'High Standard pistols were the official sidearms of the CIA from the late 1940s through the 1960s — the suppressed .22 Model B and HD Military were used for clandestine operations where a subsonic .22 with an integral suppressor was preferred over larger calibers.',
  ARRAY['United States'], 'High', 'Supermatic Trophy'
),

(
  'Para Ordnance',
  ARRAY['Para-Ordnance', 'Para USA', 'Para'],
  'Canada', 1985, false,
  ARRAY['Pistol'],
  'Remington Arms', NULL,
  'Para Ordnance was a Canadian firearms manufacturer founded in 1985 in Toronto, Ontario, originally making paintball equipment before pivoting to firearms. The company''s landmark achievement was the P14-45 — the first commercially successful double-stack .45 ACP 1911, holding 14 rounds versus the standard 7. This innovation fundamentally expanded what the 1911 platform could do and spawned a generation of imitators. Para also developed the LDA (Light Double Action) trigger, offering a DAO option on the 1911 platform. Para Ordnance relocated manufacturing to the US after import restrictions and was acquired by Remington Arms / Freedom Group in 2012. The brand was subsequently discontinued.',
  ARRAY['P14-45', 'P13-45', 'P12-45', 'LDA Carry', 'SSP', 'Black Ops'],
  NULL, 'Pineville, North Carolina, USA (final)',
  'United States', 'Domestic', 'Boutique', 'premium', 'Subsidiary', false,
  'Manufacturer',
  ARRAY['double-stack .45 ACP 1911', 'LDA trigger', 'high-capacity 1911'],
  NULL,
  799, false, NULL,
  'The Para P14-45 was the first production pistol to put 14 rounds of .45 ACP in a 1911 frame. Before Para, double-stack .45 ACP was a gunsmith-only modification. Para made it available off the shelf.',
  ARRAY['Canada', 'United States'], 'Medium', 'P14-45'
),

(
  'Remington Rand',
  ARRAY['Remington Rand Inc.'],
  'United States', 1927, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Remington Rand Inc. was an American business machinery company (typewriters, early computers) that was contracted by the US government to manufacture M1911A1 pistols during World War II. Between 1942 and 1945, Remington Rand produced approximately 1,086,624 M1911A1 pistols — more than any other WWII contractor, including Colt. The company had no prior firearms manufacturing experience; the contract was awarded to increase industrial production capacity. Remington Rand pistols are among the most commonly encountered WWII-era 1911s in collector circles.',
  ARRAY['M1911A1'],
  NULL, 'Syracuse, New York, USA',
  'United States', 'Historical', 'Micro', 'military', 'Independent', false,
  'Manufacturer',
  ARRAY['M1911A1 (WWII contract)', 'WWII military production'],
  NULL,
  NULL, true, 'Produced 1,086,624 M1911A1 pistols for the US military between 1942 and 1945 — the highest production total of any WWII 1911 contractor.',
  'Remington Rand was a typewriter and adding machine company. The irony of the largest 1911 producer being an office equipment maker is one of the stranger facts of WWII industrial history.',
  ARRAY['United States'], 'Medium', 'M1911A1'
),

(
  'Cobray',
  ARRAY['S.W.D. Inc.', 'SWD', 'Cobray Company', 'Sylvia & Wayne Daniel'],
  'United States', 1982, false,
  ARRAY['Pistol', 'Shotgun'],
  NULL, NULL,
  'S.W.D. Inc. (Cobray) was an American firearms manufacturer founded in 1982 in Atlanta, Georgia by Wayne Daniel after acquiring rights to the Military Armament Corporation MAC designs. Cobray produced MAC-pattern semi-automatic pistols and carbines under the Cobray brand name — most notably the M11/Nine (9mm semi-auto MAC-11 pattern) and the M12 (.380 ACP). They also made the notorious Cobray Terminator, a single-shot 12-gauge shotgun made from a piece of pipe with a simple striker mechanism. Cobray/SWD is widely associated with the "assault weapon" debates of the early 1990s and their products were frequently cited in crime statistics. The company ceased operations in the late 1990s after the 1994 Assault Weapons Ban.',
  ARRAY['M11/Nine', 'M12', 'Terminator', 'PM11'],
  NULL, 'Atlanta, Georgia, USA',
  'United States', 'Historical', 'Micro', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['MAC-pattern semi-autos', 'M11/Nine', 'Terminator shotgun'],
  ARRAY['Wayne Daniel'],
  NULL, false, NULL,
  'The Cobray Terminator — a crude single-shot 12-gauge made from a piece of pipe — retailed for approximately $70 new and was frequently cited by legislators as an example of the cheap, dangerous firearms flooding the market. It became a symbol of the debate that led to the 1994 Assault Weapons Ban.',
  ARRAY['United States'], 'Low', 'M11/Nine'
),

(
  'Intratec',
  ARRAY['Intratec USA', 'TEC'],
  'United States', 1984, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Intratec was an American firearms manufacturer founded in 1984 in Miami, Florida as a subsidiary of Interdynamic AB of Sweden. Best known for the TEC-9 and TEC-DC9 — a semi-automatic 9mm pistol with a distinctive appearance that made it a focal point of the assault weapons debate in the early 1990s. Despite its menacing appearance, the TEC-9 was mechanically unreliable; however, its cheap price and high-capacity magazines made it widely available. The TEC-9 was specifically named in the 1994 Federal Assault Weapons Ban. Intratec subsequently redesigned the pistol as the AB-10 (removing threaded barrel and top charging handle). The company closed around 2001.',
  ARRAY['TEC-9', 'TEC-DC9', 'AB-10', 'CAT-9', 'TEC-22'],
  NULL, 'Miami, Florida, USA',
  'United States', 'Historical', 'Micro', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['TEC-9 semi-auto pistol', 'high-capacity 9mm pistols'],
  NULL,
  NULL, false, NULL,
  'The TEC-9 was singled out by name in the 1994 Federal Assault Weapons Ban along with a small list of specific firearms. Intratec''s response was to slightly modify the design and sell it as the AB-10 — technically compliant but functionally identical.',
  ARRAY['United States', 'Sweden'], 'Low', 'TEC-9'
),

(
  'Olympic Arms',
  ARRAY['Olympic Arms Inc.', 'Schuetzen Pistol Works', 'SGW'],
  'United States', 1975, false,
  ARRAY['Rifle', 'Pistol'],
  NULL, NULL,
  'Olympic Arms was an American AR-15 manufacturer founded in 1975 in Olympia, Washington as Safari Arms / Schuetzen Pistol Works. One of the earliest independent AR-15 manufacturers after Colt''s patents expired, Olympic Arms produced a wide range of AR-15 pattern rifles and pistols including early small-caliber variants (.223 Wylde, .45 ACP, 9mm carbines) and the first commercially produced AR pistols. Known for the K8 series lightweight rifles and the OA-93/OA-96 pistols. The company closed in 2017 after the death of founder Robert Schuetz.',
  ARRAY['K8', 'OA-93', 'OA-96', 'PCR', 'CAR97'],
  NULL, 'Olympia, Washington, USA',
  'United States', 'Historical', 'Boutique', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['AR-15 rifles and pistols', 'small-caliber AR variants', 'AR pistols'],
  ARRAY['Robert Schuetz'],
  NULL, false, NULL,
  'Olympic Arms was among the first manufacturers to produce AR-15 pistols commercially. Their OA-93 was specifically named in the 1994 Federal Assault Weapons Ban due to its lack of a conventional stock — making it one of the few AR pistols commercially available at the time.',
  ARRAY['United States'], 'Low', 'K8'
),

(
  'USFA',
  ARRAY['United States Firearms', 'USFA Manufacturing', 'United States Firearms Manufacturing Company'],
  'United States', 1992, false,
  ARRAY['Revolver', 'Rifle'],
  NULL, NULL,
  'United States Firearms Manufacturing Company (USFA) was founded in 1992 in Hartford, Connecticut in the original Colt factory complex. USFA specialized in historically accurate reproductions of Colt Single Action Army revolvers and other 19th century firearms, machined on period-correct tooling to exacting specifications. Their SAA reproductions are considered superior to Italian imports and competitive with Colt''s own production for historical fidelity. USFA also made the ZIP .22 pistol — one of the most unusual and universally criticized firearm designs in modern history. The company closed around 2012.',
  ARRAY['Single Action Army', 'Rodeo', 'ZIP .22'],
  NULL, 'Hartford, Connecticut, USA',
  'United States', 'Historical', 'Micro', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['SAA revolver reproductions', 'historical Colt reproductions'],
  NULL,
  NULL, false, NULL,
  'USFA operated inside the original Colt factory in Hartford — making SAA reproductions on the same shop floor where Colt had made the originals. This historical continuity was central to their marketing and collector appeal.',
  ARRAY['United States'], 'High', 'Single Action Army'
),

(
  'AMT',
  ARRAY['Arcadia Machine & Tool', 'AMT Inc.', 'Irwindale Arms'],
  'United States', 1977, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Arcadia Machine & Tool (AMT) was an American firearms manufacturer founded in 1977 in Irwindale, California. Known for producing all-stainless steel pistols at a time when stainless was uncommon in production handguns. The AMT Hardballer was a long-slide .45 ACP 1911 in stainless steel — made famous by Arnold Schwarzenegger''s character in The Terminator (1984). The Backup series offered compact .380 and .45 ACP pocket pistols in stainless. The Automag II and III offered .22 Magnum and .30 Carbine semi-auto pistols. AMT went through several name changes and ownership transitions before finally closing.',
  ARRAY['Hardballer', 'Backup', 'Automag II', 'Automag III', 'Lightning', 'On Duty'],
  NULL, 'Irwindale, California, USA',
  'United States', 'Historical', 'Boutique', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['stainless steel pistols', 'long-slide 1911', '.22 Magnum semi-auto', 'Backup pocket pistol'],
  NULL,
  NULL, false, NULL,
  'The AMT Hardballer long-slide .45 ACP was used as the T-800''s weapon of choice in The Terminator (1984). The film''s worldwide success made the Hardballer one of the most recognizable pistols in popular culture, despite its mixed reputation for reliability.',
  ARRAY['United States'], 'Medium', 'Hardballer'
),

(
  'Maverick Arms',
  ARRAY['Maverick'],
  'United States', 1991, true,
  ARRAY['Shotgun'],
  'Mossberg', NULL,
  'Maverick Arms is a subsidiary of O.F. Mossberg & Sons, established in 1991 to produce budget-priced shotguns manufactured in Eagle Pass, Texas. The Maverick 88 is a simplified, less-expensive version of the Mossberg 500 — sharing the same barrel, choke, and basic action but with a cross-bolt safety instead of the Mossberg''s tang safety. The Maverick 88 has become one of the best-selling budget home defense shotguns in the United States, offering solid Mossberg reliability at a significantly lower price point.',
  ARRAY['88', '91', '88 Slug'],
  NULL, 'Eagle Pass, Texas, USA',
  'United States', 'Domestic', 'High', 'mass', 'Subsidiary', false,
  'Manufacturer',
  ARRAY['budget pump-action shotguns', 'home defense shotguns'],
  NULL,
  199, false, NULL,
  'The Maverick 88 shares its barrel with the Mossberg 500 — a Mossberg 500 barrel fits the Maverick 88. This compatibility allows Maverick owners to access the full range of Mossberg 500 barrel options including rifled slug barrels and extended tubes.',
  ARRAY['United States'], 'Low', '88'
),

(
  'Del-Ton',
  ARRAY['Del-Ton Inc.'],
  'United States', 2003, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'Del-Ton Inc. is an American AR-15 manufacturer founded in 2003 in Elizabethtown, North Carolina. The company produces complete AR-15 rifles and carbines as well as parts and build kits at budget price points. Del-Ton became popular during the AR-15 parts kit era of the 2000s-2010s as a source of affordable, mil-spec-ish components. Their complete rifles are positioned at the entry level of the AR-15 market.',
  ARRAY['Echo 316', 'Sierra 316', 'Lima 316', 'Sport'],
  'https://www.del-ton.com', 'Elizabethtown, North Carolina, USA',
  'United States', 'Domestic', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['budget AR-15 rifles', 'AR-15 parts kits'],
  NULL,
  499, false, NULL,
  NULL,
  ARRAY['United States'], 'Low', 'Echo 316'
),

(
  'PTR Industries',
  ARRAY['PTR 91', 'JLD Enterprises'],
  'United States', 2000, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'PTR Industries is an American manufacturer of HK91/G3-pattern semi-automatic rifles, originally founded as JLD Enterprises in Connecticut before relocating to South Carolina. PTR purchased original HK tooling and machinery from Portugal, enabling them to produce rifles to CETME/G3 specifications rather than licensed copies. Their PTR 91 series is widely regarded as the closest American-made equivalent to an original HK91. Also produces the PTR 32 in 7.62x39mm.',
  ARRAY['PTR 91', 'PTR 91F', 'PTR 32', 'PTR MSG91', 'GI R'],
  'https://www.ptr91.com', 'Aynor, South Carolina, USA',
  'United States', 'Domestic', 'Boutique', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['HK91/G3-pattern rifles', 'roller-delayed blowback rifles', '.308 semi-auto carbines'],
  NULL,
  999, false, NULL,
  'PTR acquired original HK machinery from Portugal when Portugal updated their military rifles. This means PTR rifles are made on the actual tooling that produced military G3s — not reverse-engineered copies, but genuine HK-spec production.',
  ARRAY['United States'], 'Medium', 'PTR 91'
),

(
  'DS Arms',
  ARRAY['DSA', 'David Selvaggio Arms'],
  'United States', 1987, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'DS Arms is an American firearms manufacturer founded in 1987 in Barrington, Illinois, specializing in FAL (FN-pattern) semi-automatic rifles and components. DS Arms obtained original FN tooling and produces the SA58 FAL to original Belgian specifications — one of the most faithful American FAL reproductions available. Also makes M240 and M249 machine gun components for US military contracts. The SA58 series is the flagship product.',
  ARRAY['SA58', 'SA58 Congo', 'SA58 OSW', 'ZM4 (AR-15)'],
  'https://www.dsarms.com', 'Lake Barrington, Illinois, USA',
  'United States', 'Domestic', 'Boutique', 'premium', 'Independent', false,
  'Manufacturer',
  ARRAY['FAL-pattern rifles', 'SA58 FN FAL reproductions', 'military parts contracts'],
  NULL,
  1299, true, 'DS Arms holds US military contracts for M240 and M249 machine gun components.',
  'DS Arms is one of a small number of US manufacturers that produces FAL-pattern rifles using original FN specifications and tooling — a significant difference from most FAL importers who assemble foreign parts kits on domestic receivers.',
  ARRAY['United States'], 'Medium', 'SA58'
),

(
  'Knight Rifles',
  ARRAY['Knight Muzzleloading', 'Knight Manufacturing'],
  'United States', 1985, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'Knight Rifles is an American inline muzzleloader manufacturer founded in 1985 in Centerville, Iowa by William "Tony" Knight. Knight is credited with inventing and popularizing the modern inline muzzleloader — a percussion muzzle-loading rifle with the nipple and hammer inline with the barrel rather than on the side, dramatically improving ignition reliability. This innovation opened muzzleloader hunting to millions of hunters who had avoided traditional sidelocks. Knight''s Revolution, Disc, and Vision rifles dominated the inline muzzleloader market in the 1990s and 2000s.',
  ARRAY['Revolution', 'Disc Extreme', 'Vision', 'Bighorn', 'Mountaineer'],
  'https://www.knightrifles.com', 'Centerville, Iowa, USA',
  'United States', 'Domestic', 'Boutique', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['inline muzzleloaders', 'modern percussion muzzle-loading rifles'],
  ARRAY['William Tony Knight'],
  299, false, NULL,
  'Tony Knight''s inline muzzleloader patent, issued in the mid-1980s, created an entirely new category of firearm. Before Knight, serious muzzleloader hunting required traditional sidelock knowledge; the inline made muzzleloader hunting as simple as a bolt-action.',
  ARRAY['United States'], 'Low', 'Revolution'
),

(
  'SKB Arms',
  ARRAY['SKB', 'SKB Shotguns', 'Suminoe Keiki Boeki'],
  'Japan', 1855, true,
  ARRAY['Shotgun'],
  NULL, NULL,
  'SKB Arms Company is a Japanese shotgun manufacturer with roots going back to 1855. SKB produced shotguns under their own name and as OEM manufacturer for other brands including Ithaca (the Ithaca SKB line) and early Winchester O/U models. SKB shotguns are known for excellent fit and finish, smooth actions, and competitive pricing against Italian counterparts. Their current lineup includes the 85TSS trap and sporting clays models. SKB shotguns are imported into the US by GU Inc.',
  ARRAY['85TSS', '90TSS', '505', '585', '700', '800', 'Model 200E'],
  'https://www.skbshotguns.com', 'Japan',
  'Japan', 'Active Import', 'Boutique', 'premium', 'Independent', false,
  'Manufacturer',
  ARRAY['over-and-under shotguns', 'trap shotguns', 'sporting clays shotguns'],
  NULL,
  999, false, NULL,
  'SKB was the actual manufacturer behind the Ithaca SKB line sold in the US through the 1970s — a partnership so successful that many shooters did not realize their "Ithaca" over-and-under was made in Japan.',
  ARRAY['Japan'], 'Medium', '85TSS'
),

(
  'American Derringer',
  ARRAY['American Derringer Corporation', 'ADC'],
  'United States', 1980, true,
  ARRAY['Pistol'],
  NULL, NULL,
  'American Derringer Corporation was founded in 1980 in Waco, Texas, reviving the classic Remington-style over-under derringer in modern calibers. American Derringer produces the Model 1 in over 50 calibers — from .22 LR to .45-70 Government — making them the most diverse derringer line in the world. The Lady Derringer features an engraved frame and rosewood grips. Popular as backup firearms, collection pieces, and for historical reenactment.',
  ARRAY['Model 1', 'Lady Derringer', 'Model 4', 'LM5', 'DA38'],
  NULL, 'Waco, Texas, USA',
  'United States', 'Domestic', 'Micro', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['over-under derringers', 'derringers in exotic calibers', 'Lady Derringer'],
  NULL,
  320, false, NULL,
  'American Derringer offers the Model 1 in more calibers than virtually any other production handgun — including .45-70 Government, a caliber more commonly associated with rifles. A two-shot .45-70 derringer delivers more energy per shot than most handgun calibers.',
  ARRAY['United States'], 'Low', 'Model 1'
),

(
  'Navy Arms',
  ARRAY['Navy Arms Company', 'Val Forgett Navy Arms'],
  'United States', 1957, false,
  ARRAY['Rifle', 'Revolver', 'Pistol', 'Shotgun'],
  NULL, NULL,
  'Navy Arms Company was an American importer of replica and historically accurate firearms founded in 1957 in Ridgefield, New Jersey by Val Forgett. Navy Arms pioneered the importation of Italian-made Colt, Winchester, and blackpowder replicas to the US market, creating the replica firearms industry. They imported revolvers from Uberti, rifles from Pedersoli and others, and were the primary US distributor for blackpowder replicas for decades. Navy Arms helped fuel the Civil War reenactment and Western cowboy shooting boom. The company closed around 2011.',
  ARRAY['1858 Remington', '1860 Army', 'Henry Rifle replica', 'Model 1873 replica'],
  NULL, 'Martinsburg, West Virginia, USA (final)',
  'United States', 'Historical', 'Micro', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['replica firearms importer', 'blackpowder revolvers', 'Winchester replicas', 'Civil War replicas'],
  ARRAY['Val Forgett'],
  NULL, false, NULL,
  'Val Forgett''s Navy Arms essentially created the American replica firearms market. Before Navy Arms, shooters who wanted a Civil War-era revolver had to find an original. After Navy Arms, high-quality Italian replicas were available through any gun shop.',
  ARRAY['United States', 'Italy'], 'Medium', '1860 Army'
),

(
  'Hopkins & Allen',
  ARRAY['Hopkins & Allen Arms', 'Meriden Arms'],
  'United States', 1868, false,
  ARRAY['Revolver', 'Rifle', 'Shotgun'],
  NULL, NULL,
  'Hopkins & Allen was an American firearms manufacturer founded in 1868 in Norwich, Connecticut. The company produced inexpensive revolvers, single-shot rifles, and shotguns for the mass market throughout the late 19th and early 20th centuries. Their revolvers were sold under numerous trade names through hardware stores and mail-order catalogs. Hopkins & Allen went bankrupt in 1916, and their factory and equipment were purchased by Marlin.',
  ARRAY['XL Double Action', 'Safety Police', 'Forehand & Wadsworth'],
  NULL, 'Norwich, Connecticut, USA',
  'United States', 'Historical', 'Micro', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['inexpensive revolvers', 'single-shot rifles', 'trade brand firearms'],
  NULL,
  NULL, false, NULL,
  'Hopkins & Allen sold revolvers under dozens of trade names through Sears, Montgomery Ward, and hardware stores — making it nearly impossible to count their actual production. Many guns marked with names like "Forehand & Wadsworth" or "Aetna" trace back to the Hopkins & Allen factory.',
  ARRAY['United States'], 'Low', 'Safety Police'
),

-- ── SATURDAY NIGHT SPECIAL ERA ───────────────────────────────

(
  'Lorcin Engineering',
  ARRAY['Lorcin'],
  'United States', 1989, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Lorcin Engineering Company was an American manufacturer of low-cost semi-automatic pistols founded in 1989 in Mira Loma, California. Lorcin was one of the "Ring of Fire" companies — a group of Southern California firearms manufacturers that produced inexpensive handguns that dominated the lower end of the US market in the early 1990s. Lorcin was briefly the largest-selling handgun manufacturer in the United States by unit volume in 1993-1994. Their L-series pistols in .25 ACP, .32 ACP, .380 ACP, and 9mm were notorious for inconsistent quality. The company went bankrupt in 1999 following multiple product liability lawsuits.',
  ARRAY['L-25', 'L-32', 'L-380', 'L-9MM'],
  NULL, 'Mira Loma, California, USA',
  'United States', 'Historical', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['low-cost semi-auto pistols', 'Ring of Fire manufacturer'],
  NULL,
  NULL, false, NULL,
  'At its peak in 1993-1994, Lorcin Engineering was manufacturing and selling more handguns per year by unit count than Smith & Wesson, Ruger, or Colt. The L-380 was the single best-selling handgun model in the United States in 1993 — outselling any individual Glock, SIG, or S&W model.',
  ARRAY['United States'], 'Low', 'L-380'
),

(
  'Raven Arms',
  ARRAY['Raven Industries'],
  'United States', 1970, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Raven Arms was a Southern California firearms manufacturer founded around 1970 by George Jennings in Industry, California. Raven produced the Model P-25, a simple .25 ACP semi-automatic pistol that became one of the best-selling handguns in the United States through the 1970s and 1980s. The P-25 was inexpensive, lightweight, and while functional, was not known for quality or accuracy. Raven Arms is considered the founding company of the "Ring of Fire" cluster of related manufacturers. The company closed in 1991 when founder George Jennings sold to his son Bruce Jennings, who founded Jennings Firearms.',
  ARRAY['P-25'],
  NULL, 'Industry, California, USA',
  'United States', 'Historical', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['.25 ACP pocket pistol', 'Ring of Fire founding company'],
  ARRAY['George Jennings'],
  NULL, false, NULL,
  'The Raven P-25 was priced as low as $25-$50 retail in the 1970s and 1980s — literally the cheapest new handgun available in America. This pricing made it extremely accessible and contributed to its notoriety in crime statistics.',
  ARRAY['United States'], 'Low', 'P-25'
),

(
  'Davis Industries',
  ARRAY['Davis'],
  'United States', 1987, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Davis Industries was an American manufacturer of low-cost pistols and derringers founded in 1987 in Chino, California by Jim Davis (formerly of Ring of Fire). Davis produced the D-series semi-automatic pistols in .22 LR, .25 ACP, .32 ACP, and .380 ACP, and the P-series semi-autos in .32 and .380. After Davis Industries closed in 1999, the designs were continued by Cobra Enterprises.',
  ARRAY['D-22', 'D-25', 'D-32', 'D-380', 'P-32', 'P-380'],
  NULL, 'Chino, California, USA',
  'United States', 'Historical', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['low-cost semi-auto pistols', 'Ring of Fire manufacturer'],
  ARRAY['Jim Davis'],
  NULL, false, NULL,
  NULL,
  ARRAY['United States'], 'Low', 'P-380'
),

(
  'Jennings Firearms',
  ARRAY['Jennings', 'Bryco Arms', 'Jennings / Bryco'],
  'United States', 1978, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Jennings Firearms was founded in 1978 by Bruce Jennings in Industry, California, continuing the Raven Arms tradition of inexpensive small-caliber pistols. Bryco Arms was a related company under the same ownership producing slightly larger pistols. The Jennings J-22 and J-25 were the primary models. Jennings / Bryco went bankrupt in 2003 following a major product liability lawsuit; the company was purchased out of bankruptcy and re-established as Jimenez Arms.',
  ARRAY['J-22', 'J-25', 'Model 38', 'Model 48', 'Model 59'],
  NULL, 'Industry, California, USA',
  'United States', 'Historical', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['low-cost semi-auto pistols', 'Ring of Fire manufacturer'],
  ARRAY['Bruce Jennings'],
  NULL, false, NULL,
  'The Bryco / Jennings product liability case that ended the company involved a child who was shot when a loaded pistol''s safety was engaged — the design required the trigger to be pulled to engage the safety. The resulting lawsuit judgment contributed to the company''s bankruptcy.',
  ARRAY['United States'], 'Low', 'J-22'
),

(
  'Stallard Arms',
  ARRAY['Stallard'],
  'United States', 1991, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Stallard Arms was a small Ohio-based manufacturer founded in 1991 that produced the JS-9mm pistol, a cheap semi-automatic handgun. Stallard is notable primarily as the direct predecessor to Hi-Point Firearms — the company and its designs were acquired and restructured into Hi-Point in 1992-1993. The Stallard JS-9mm design evolved into the Hi-Point C9.',
  ARRAY['JS-9mm'],
  NULL, 'Mansfield, Ohio, USA',
  'United States', 'Historical', 'Micro', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['budget 9mm semi-auto', 'Hi-Point predecessor'],
  NULL,
  NULL, false, NULL,
  'Without Stallard Arms, there would be no Hi-Point Firearms. The Stallard JS-9mm''s basic design DNA — heavy polymer over a steel frame, blowback operation, single-stack magazine — carried directly into the Hi-Point product line.',
  ARRAY['United States'], 'Low', 'JS-9mm'
),

(
  'Phoenix Arms',
  ARRAY['Phoenix'],
  'United States', 1992, true,
  ARRAY['Pistol'],
  NULL, NULL,
  'Phoenix Arms is an American manufacturer of low-cost semi-automatic pistols founded in 1992 in Ontario, California, continuing the Ring of Fire tradition after buying rights from Raven Arms. Their HP22A and HP25A are simple, inexpensive .22 LR and .25 ACP semi-automatic pistols popular as first handguns and plinkers. Unlike most Ring of Fire predecessors, Phoenix Arms remains in business and has a relatively better reputation for quality consistency.',
  ARRAY['HP22A', 'HP25A', 'Raven MP25'],
  NULL, 'Ontario, California, USA',
  'United States', 'Domestic', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['budget .22 LR pistols', '.25 ACP pocket pistols'],
  NULL,
  99, false, NULL,
  'Phoenix Arms HP22A regularly sells for under $130 new — making it one of the least expensive centerfire-rimfire semi-auto pistols in the US market. Its longevity (30+ years of production) distinguishes it from most Ring of Fire contemporaries that closed in the 1990s.',
  ARRAY['United States'], 'Low', 'HP22A'
),

(
  'Cobra Enterprises',
  ARRAY['Cobra Firearms', 'Cobra'],
  'United States', 2001, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Cobra Enterprises was an American firearms manufacturer founded in 2001 in Salt Lake City, Utah, acquiring the designs and tooling from Davis Industries after its 1999 closure. Cobra produced semi-automatic pistols and derringers continuing the Davis P-series and D-series lineage, plus a Patriot series derringer. While similar in price to Davis products, Cobra introduced minor quality improvements. The company closed around 2019.',
  ARRAY['CA380', 'CB38', 'FS380', 'Patriot', 'Denali'],
  NULL, 'Salt Lake City, Utah, USA',
  'United States', 'Historical', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['low-cost semi-auto pistols', 'derringers'],
  NULL,
  NULL, false, NULL,
  NULL,
  ARRAY['United States'], 'Low', 'CA380'
),

(
  'Jimenez Arms',
  ARRAY['Jimenez', 'JA'],
  'United States', 2004, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Jimenez Arms was an American manufacturer of budget semi-automatic pistols founded in 2004 in Henderson, Nevada by Paul Jimenez, who purchased the Bryco Arms designs and tooling from bankruptcy. Jimenez produced the JA-series pistols in .22 LR, .25 ACP, .32 ACP, .380 ACP, and 9mm — direct successors to the Bryco/Jennings lineup. The company closed in 2019 after relocating to Henderson, Nevada.',
  ARRAY['JA-22', 'JA-25', 'JA-32', 'JA-380', 'JA-9'],
  NULL, 'Henderson, Nevada, USA',
  'United States', 'Historical', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['budget semi-auto pistols'],
  NULL,
  NULL, false, NULL,
  'Jimenez Arms represented the fourth generation of the same basic design lineage: Raven Arms → Jennings/Bryco → Jimenez. Each company was founded by someone associated with the predecessor, carrying the same basic .22/.25/.32/.380 pistol designs forward through multiple bankruptcies.',
  ARRAY['United States'], 'Low', 'JA-380'
),

(
  'Sundance Industries',
  ARRAY['Sundance'],
  'United States', 1989, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Sundance Industries was a small California-based manufacturer of inexpensive .25 ACP pistols active from approximately 1989 to 1995. Their primary product was the Model A-25, a simple blowback semi-automatic pocket pistol. Sundance was among the smallest of the Ring of Fire companies and is the least documented. The company closed mid-decade as product liability pressure increased across the category.',
  ARRAY['Model A-25', 'Point Blank'],
  NULL, 'Valencia, California, USA',
  'United States', 'Historical', 'Micro', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['budget .25 ACP pocket pistols'],
  NULL,
  NULL, false, NULL,
  NULL,
  ARRAY['United States'], 'Low', 'Model A-25'
),

-- ── SPANISH ──────────────────────────────────────────────────

(
  'Astra',
  ARRAY['Astra-Unceta', 'Astra-Unceta y Cia', 'Unceta & Company'],
  'Spain', 1908, false,
  ARRAY['Pistol', 'Revolver'],
  NULL, NULL,
  'Astra-Unceta y Cia was a Spanish firearms manufacturer founded in 1908 in Eibar (later Guernica), Basque Country. Astra was one of the most significant Spanish pistol makers of the 20th century, producing military pistols for Spain, Germany, and numerous other nations. The Astra 400 chambered in 9mm Largo was the standard Spanish military pistol for decades. The Astra 600 in 9mm Parabellum was produced for Germany in WWII. The Model 900 was a Broomhandle Mauser copy. Post-war Astra produced modern DA revolvers and the Constable and A-75 semi-autos that sold well in the US market. Astra closed in 1997.',
  ARRAY['Model 400', 'Model 600', 'Model 900', 'Constable', 'A-75', 'Cub', 'Falcon'],
  NULL, 'Guernica, Basque Country, Spain',
  'Spain', 'Historical', 'Mid', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['Spanish military pistols', '9mm Largo pistols', 'DA revolvers', 'WWII German contracts'],
  NULL,
  NULL, true, 'Supplied the Astra 400 as the standard Spanish Army sidearm and produced the Astra 600 under contract for Germany during WWII.',
  'The Astra Model 900 was a remarkably faithful copy of the Mauser C96 Broomhandle, made under license (and sometimes without license) in Spain. During the Spanish Civil War, both Nationalist and Republican forces used Astra Broomhandle copies.',
  ARRAY['Spain'], 'High', 'Model 400'
),

(
  'Star Firearms',
  ARRAY['Star', 'Star Bonifacio Echeverria', 'Bonifacio Echeverria'],
  'Spain', 1905, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Star Bonifacio Echeverria, S.A. was a Spanish firearms manufacturer founded in 1905 in Eibar, Basque Country. Star produced a long series of semi-automatic pistols modeled closely on the Colt 1911 but with their own improvements — external extractors, loaded chamber indicators, and simplified field-stripping. The Star Model B in 9mm Parabellum became the standard Spanish military pistol from the 1940s through the 1990s. The Star Model 30M and 28 were modern DA/SA service pistols. The compact Star BM in 9mm was widely used by Spanish police and sold well in the US market. Star closed in 1997 amid the same economic pressures that shuttered Astra.',
  ARRAY['Model B', 'BM', 'PD', 'Model 30M', 'Model 28', 'Megastar'],
  NULL, 'Eibar, Basque Country, Spain',
  'Spain', 'Historical', 'Mid', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['1911-pattern pistols', 'Spanish military pistols', '9mm service pistols'],
  NULL,
  NULL, true, 'The Star Model B series served as the standard sidearm of the Spanish Armed Forces and Guardia Civil for approximately five decades. Star also had contracts with multiple South American militaries.',
  'The Star PD was the first .45 ACP compact pistol — a genuine all-steel .45 weighing under 25 ounces — produced several years before American manufacturers developed comparable designs. It found a dedicated following among concealed carry shooters in the 1970s and 1980s.',
  ARRAY['Spain'], 'Medium', 'Model B'
),

(
  'Llama',
  ARRAY['Llama-Gabilondo', 'Gabilondo y Cia', 'Llama-Gabilondo y Cia'],
  'Spain', 1904, false,
  ARRAY['Pistol', 'Revolver'],
  NULL, NULL,
  'Llama-Gabilondo y Cia was a Spanish firearms manufacturer founded in 1904 in Vitoria, Basque Country. Llama produced 1911-pattern semi-automatic pistols and revolvers for the Spanish and export markets. The Llama pistol line closely followed the Colt 1911 design but in a range of calibers from .22 LR to .45 ACP. Llama revolvers were DA copies of Smith & Wesson designs. The company sold significant quantities to the US market through importers. Llama closed in 2005.',
  ARRAY['IXA', 'Especial', 'Minimax', 'Max-1', 'Micro Max', 'Comanche'],
  NULL, 'Vitoria, Basque Country, Spain',
  'Spain', 'Historical', 'Mid', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['1911-pattern pistols', 'DA revolvers', 'Spanish military pistols'],
  NULL,
  NULL, false, NULL,
  'Llama''s name translates to "flame" in Spanish. The company''s full name, Gabilondo y Cia, is rarely seen on the pistols — most are simply marked "Llama" with the country of origin.',
  ARRAY['Spain'], 'Low', 'IXA'
),

-- ── EUROPEAN ─────────────────────────────────────────────────

(
  'FEG',
  ARRAY['Fegyver és Gázkészülékgyár', 'FEG Budapest', 'Femaru'],
  'Hungary', 1891, true,
  ARRAY['Pistol', 'Rifle'],
  NULL, NULL,
  'Fegyver és Gázkészülékgyár (FEG) is a Hungarian state firearms manufacturer founded in 1891 in Budapest. FEG produced military and police sidearms for Hungary and Warsaw Pact allies throughout the Cold War. Their PA-63 was the standard Hungarian military pistol, chambered in 9mm Makarov. The FEG Hi-Power clones (PJK-9HP, GKK-45) are widely regarded as excellent copies of the Browning Hi-Power. FEG also produced the AP-MBP pistol for export. Cold War-era FEG pistols imported to the US before the import bans are moderately collectible. The company continues as part of the Hungarian defense industry.',
  ARRAY['PA-63', 'P9M', 'P9R', 'GKK-45', 'AP-MBP', 'AK-63'],
  NULL, 'Budapest, Hungary',
  'Hungary', 'Import Banned', 'Boutique', 'collector', 'State-owned', false,
  'Manufacturer',
  ARRAY['Hungarian military pistols', 'Browning Hi-Power clones', 'PA-63', 'Cold War Warsaw Pact pistols'],
  NULL,
  NULL, true, 'Primary manufacturer of Hungarian military and police sidearms; supplied Warsaw Pact allies.',
  'FEG''s P9M Browning Hi-Power clone was so faithfully produced that many parts interchange with original FN Hi-Power pistols. Experienced Hi-Power shooters debate whether a well-fitted FEG P9M is distinguishable from the original in shooting performance.',
  ARRAY['Hungary'], 'Medium', 'PA-63'
),

(
  'Arminius',
  ARRAY['Arminius Waffenfabrik', 'Friedrich Pickert', 'Weihrauch Arminius'],
  'Germany', 1904, false,
  ARRAY['Revolver'],
  NULL, NULL,
  'Arminius Waffenfabrik (Friedrich Pickert) was a German revolver manufacturer founded in 1904 in Zella-Mehlis, Thuringia. Arminius produced inexpensive DA revolvers sold under the Arminius and other trade names throughout Europe and exported to the US. Their revolvers were inexpensive but functional. After WWII, the Arminius name and some designs were continued by Weihrauch (HW-Arminius). Arminius revolvers were among those targeted by the Gun Control Act of 1968 import restrictions.',
  ARRAY['HW3', 'HW5', 'HW7', 'HW38'],
  NULL, 'Zella-Mehlis, Germany (historical)',
  'Germany', 'Import Banned', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['inexpensive DA revolvers', 'European trade brand revolvers'],
  NULL,
  NULL, false, NULL,
  'Arminius revolvers were among the "Saturday Night Specials" imported from Europe that the Gun Control Act of 1968 was specifically designed to restrict. The GCA''s sporting purposes test effectively banned most Arminius imports.',
  ARRAY['Germany'], 'Low', 'HW38'
),

(
  'Rohm',
  ARRAY['Röhm GmbH', 'Rohm Gesellschaft', 'RG Industries'],
  'Germany', 1948, true,
  ARRAY['Revolver', 'Pistol'],
  NULL, NULL,
  'Röhm GmbH is a German company founded in 1948 in Sontheim an der Brenz, primarily a tool manufacturer that also produced inexpensive revolvers under the RG designation. RG revolvers (imported to the US by RG Industries of Miami) were extremely cheap, low-quality firearms that became synonymous with the "Saturday Night Special" debate. The RG-14 in .22 LR and RG-38 in .38 Special were widely sold in the US in the 1960s-1980s. An RG-14 revolver was used in the assassination attempt on President Ronald Reagan in 1981. Rohm''s firearms division has since ceased, though the company continues as a cutting tools manufacturer.',
  ARRAY['RG-14', 'RG-38', 'RG-31', 'RG-40', 'RG-42'],
  NULL, 'Sontheim an der Brenz, Germany',
  'Germany', 'Import Banned', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['cheap DA revolvers', 'RG revolvers', 'Saturday Night Special revolvers'],
  NULL,
  NULL, false, NULL,
  'An RG-14 .22 LR revolver — retailing for approximately $47 at the time — was used by John Hinckley Jr. in the 1981 assassination attempt on President Reagan. The incident reignited the Saturday Night Special debate and contributed directly to handgun control legislation.',
  ARRAY['Germany'], 'Low', 'RG-14'
),

(
  'ISSC Austria',
  ARRAY['ISSC', 'Innovative Solutions & Services Corp', 'ISSC Handels GmbH'],
  'Austria', 2001, true,
  ARRAY['Rifle', 'Pistol'],
  NULL, NULL,
  'ISSC Austria (Innovative Solutions & Services Corp) is an Austrian manufacturer founded in 2001, best known for the M22 — a .22 LR semi-automatic pistol styled to closely resemble the Glock 17. The M22 is marketed as a training tool for Glock users and as an affordable target/plinking pistol. ISSC also produced the MK22, an AR-15-style .22 LR rifle. Products are imported into the US by Legacy Sports International.',
  ARRAY['M22', 'MK22'],
  NULL, 'Austria',
  'Austria', 'Active Import', 'Boutique', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['Glock-replica .22 LR pistols', '.22 LR training pistols', 'AR-style .22 rifles'],
  NULL,
  299, false, NULL,
  'The ISSC M22 is dimensionally very similar to the Glock 17, allowing Glock-trained shooters to practice trigger manipulation, draw stroke, and malfunction drills with cheaper .22 LR ammunition before transitioning to their actual carry gun.',
  ARRAY['Austria'], 'Low', 'M22'
),

(
  'Daewoo Precision Industries',
  ARRAY['Daewoo', 'S&T Motiv', 'Daewoo Arms'],
  'South Korea', 1968, true,
  ARRAY['Pistol', 'Rifle'],
  NULL, NULL,
  'Daewoo Precision Industries was a South Korean firearms manufacturer established in 1968 as part of the Daewoo conglomerate. The company produced the K2 assault rifle (the standard South Korean military rifle) and the DP51 semi-automatic pistol. The DP51 in 9mm was notable for its "Fast Action" (FA) trigger — a unique system combining DA/SA and DAO characteristics. Daewoo precision was restructured into S&T Motiv following the Daewoo conglomerate collapse. Limited quantities of DP51 pistols and AR-100/110C rifles were imported to the US in the 1990s before import restrictions.',
  ARRAY['DP51', 'DP52', 'K2', 'AR-100', 'AR-110C'],
  NULL, 'Seoul, South Korea',
  'South Korea', 'Import Banned', 'Mid', 'mass', 'State-owned', false,
  'Manufacturer',
  ARRAY['DP51 9mm pistol', 'K2 assault rifle', 'Fast Action trigger system'],
  NULL,
  NULL, true, 'Primary manufacturer of the K2 rifle and K5 pistol — standard-issue South Korean military weapons.',
  'The Daewoo DP51''s "Fast Action" trigger is mechanically unique: the hammer partially resets on the rearward slide travel, giving it a trigger pull between DA and SA weight. No other production pistol shares this exact system.',
  ARRAY['South Korea'], 'Medium', 'DP51'
),

(
  'MKE',
  ARRAY['Makina ve Kimya Endüstrisi', 'MKE Ateşli Silahlar ve Av Malzemeleri', 'MKEK'],
  'Turkey', 1950, true,
  ARRAY['Pistol', 'Rifle'],
  NULL, NULL,
  'MKE (Makina ve Kimya Endüstrisi Kurumu) is a Turkish state enterprise and arms manufacturer founded in 1950. MKE produces firearms for Turkish military and police forces and also exports. Their AT-4 pistol is a Turkish-manufactured copy of the Walther P1/P38. The T94 is a Turkish copy of the HK MP5. MKE also produces the Kirrikale pistol (Walther PP pattern) and various other military weapons. Limited quantities of MKE firearms have been imported to the US.',
  ARRAY['AT-4', 'Kirrikale', 'T94', 'MPT-76'],
  NULL, 'Ankara, Turkey',
  'Turkey', 'Active Import', 'Mid', 'military', 'State-owned', false,
  'Manufacturer',
  ARRAY['Turkish military firearms', 'Walther P1 pattern pistols', 'MP5 pattern rifles'],
  NULL,
  NULL, true, 'Primary manufacturer of firearms for Turkish Armed Forces; produces standard-issue Turkish military pistols and rifles.',
  'MKE is one of the few state arms manufacturers that produces licensed copies of both German (Walther, HK) and domestic designs for active military service. The AT-4 has been standard Turkish military issue for decades.',
  ARRAY['Turkey'], 'Low', 'AT-4'
),

(
  'Yildiz',
  ARRAY['Yildiz Silah', 'Yildiz Arms'],
  'Turkey', 1992, true,
  ARRAY['Shotgun'],
  NULL, NULL,
  'Yildiz Arms (Yildiz Silah Sanayi) is a Turkish shotgun manufacturer founded in 1992 in Konya, Turkey. Yildiz produces side-by-side and over-and-under shotguns at budget to mid-range price points, exported worldwide. They are best known in the US market for affordable O/U and SxS shotguns imported under the Yildiz brand and as OEM shotguns for other US importers. Quality is generally competitive for the price tier.',
  ARRAY['SPZ-M', 'TK36', 'TK37', 'A36'],
  NULL, 'Konya, Turkey',
  'Turkey', 'Active Import', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['budget over-and-under shotguns', 'side-by-side shotguns'],
  NULL,
  349, false, NULL,
  NULL,
  ARRAY['Turkey'], 'Low', 'SPZ-M'
),

(
  'Hatsan',
  ARRAY['Hatsan Arms', 'Hatsan Arms Company', 'Escort'],
  'Turkey', 1976, true,
  ARRAY['Shotgun', 'Rifle'],
  NULL, NULL,
  'Hatsan Arms Company is a Turkish manufacturer founded in 1976 in Izmir, Turkey. Hatsan produces a broad range of shotguns and air rifles. Their Escort brand covers semi-automatic and pump-action shotguns exported worldwide, with a strong presence in the US market. Escort semi-auto shotguns are gas-operated and available at competitive price points. Hatsan also produces a wide range of air rifles and air pistols under the Hatsan name.',
  ARRAY['Escort Field Hunter', 'Escort 12 Gauge', 'Escort PS', 'Escort MAG', 'Escort MPA'],
  'https://www.hatsan.com.tr', 'Izmir, Turkey',
  'Turkey', 'Active Import', 'High', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['semi-auto shotguns', 'pump shotguns', 'air rifles'],
  NULL,
  299, false, NULL,
  'Hatsan''s Escort brand has become one of the most widely distributed Turkish shotgun labels in the US, UK, and Australia. The gas-operated Escort semi-auto is frequently recommended as a budget alternative to Beretta and Browning gas guns for clay target shooting.',
  ARRAY['Turkey'], 'Low', 'Escort Field Hunter'
),

(
  'Husqvarna',
  ARRAY['Husqvarna Vapenfabriks', 'Husqvarna Vapenfabriks AB', 'HVA'],
  'Sweden', 1689, false,
  ARRAY['Rifle', 'Pistol'],
  NULL, NULL,
  'Husqvarna Vapenfabriks AB was the firearms division of the Swedish Husqvarna company, with firearm production dating to 1689. Husqvarna produced Swedish military Mauser rifles (M96, M38) under license and also made commercial sporting rifles on Mauser actions. Swedish Mauser rifles manufactured by Husqvarna are among the most collectible WWII-era military bolt-actions due to their superb metallurgy and fit. Husqvarna ended firearms production in 1970 when the division was spun off; the parent company now makes power tools and outdoor equipment.',
  ARRAY['M96 Mauser', 'M38 Mauser', 'Crown Grade'],
  NULL, 'Huskvarna, Sweden',
  'Sweden', 'Historical', 'Mid', 'collector', 'Public', false,
  'Manufacturer',
  ARRAY['Swedish Mauser rifles', 'M96 6.5x55 Mauser', 'Swedish military rifles'],
  NULL,
  NULL, true, 'Primary manufacturer of Swedish military Mauser rifles including the m/96 and m/38 in 6.5x55mm Swedish.',
  'Swedish Mauser rifles by Husqvarna were produced to exceptionally tight tolerances — the 6.5x55mm Swedish cartridge was specifically designed for the Swedish-Norwegian climate, and Husqvarna''s metallurgical standards produced actions that are still trusted for conversion to magnum calibers today.',
  ARRAY['Sweden'], 'High', 'M96 Mauser'
),

(
  'Voere',
  ARRAY['Voere GmbH', 'Voere Kufstein', 'Tiroler Jagd und Sportwaffen'],
  'Austria', 1948, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'Voere is an Austrian rifle manufacturer founded in 1948 in Kufstein, Tyrol. Voere produces bolt-action sporting and hunting rifles sold primarily in the German-speaking European market. Their M2185 caseless ammunition experimental rifle was a notable Cold War-era development — a rifle designed to fire ammunition with no brass cartridge case, using an electrically-ignited propellant block. The caseless project was abandoned but demonstrated advanced engineering capability. Current Voere rifles are conventional bolt-actions.',
  ARRAY['M2185', 'LBW', 'Titan II', '2115 Luxus'],
  NULL, 'Kufstein, Tyrol, Austria',
  'Austria', 'Active Import', 'Boutique', 'premium', 'Independent', false,
  'Manufacturer',
  ARRAY['bolt-action hunting rifles', 'caseless ammunition research', 'Austrian sporting rifles'],
  NULL,
  1800, false, NULL,
  'The Voere M2185 caseless ammunition rifle was one of only two production firearms ever built to fire caseless ammunition — the other being the German H&K G11. Unlike the G11 (military only), the M2185 was a civilian sporting rifle. Both were commercial failures for the same reason: proprietary ammunition that was difficult to source.',
  ARRAY['Austria'], 'Medium', 'M2185'
),

-- ── ITALIAN HISTORICAL ───────────────────────────────────────

(
  'Bernardelli',
  ARRAY['Vincenzo Bernardelli', 'Fabbrica Italiana di Armi V. Bernardelli'],
  'Italy', 1865, false,
  ARRAY['Pistol', 'Revolver', 'Shotgun'],
  NULL, NULL,
  'Vincenzo Bernardelli was an Italian firearms manufacturer founded in 1865 in Gardone Val Trompia, Brescia. The company produced a range of semi-automatic pistols, revolvers, and shotguns sold in Europe and exported to the US. The Model 60 .22 LR target pistol and P-018 9mm DA semi-auto were their primary handguns. Bernardelli also made a well-regarded line of O/U and SxS shotguns. The company closed in 1997 amid the collapse of several mid-tier Italian manufacturers.',
  ARRAY['Model 60', 'Practical VB', 'P-018', 'P1', 'USA Model'],
  NULL, 'Gardone Val Trompia, Brescia, Italy',
  'Italy', 'Historical', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['Italian semi-auto pistols', '.22 LR target pistols', 'Italian shotguns'],
  ARRAY['Vincenzo Bernardelli'],
  NULL, false, NULL,
  'Bernardelli was one of the last independent mid-tier manufacturers in the Val Trompia gunmaking valley before the consolidation of the Italian firearms industry in the 1990s-2000s. Their closure left a gap in the Italian .22 target pistol segment that was not filled domestically.',
  ARRAY['Italy'], 'Medium', 'P-018'
),

(
  'Mateba',
  ARRAY['Macchine Termo Balistiche', 'Mateba Arms'],
  'Italy', 1994, false,
  ARRAY['Revolver', 'Pistol'],
  NULL, NULL,
  'Mateba (Macchine Termo Balistiche) was an Italian firearms manufacturer founded in 1994 by Emilio Ghisoni in Pavia. Mateba is best known for the Autorevolver — the only production semi-automatic revolver in history. The Mateba 2006M fires from the bottom chamber of the cylinder rather than the top, lowering the bore axis to reduce muzzle rise. The cylinder and frame reciprocate rearward with each shot, rotating the cylinder for the next round semi-automatically. A handful of these extraordinary pistols were made; they are among the most distinctive and collectible revolvers ever manufactured. Mateba closed around 2005 when Ghisoni died.',
  ARRAY['Autorevolver 2006M', 'Unica 6', 'MTR-8'],
  NULL, 'Pavia, Italy',
  'Italy', 'Historical', 'Micro', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['semi-automatic revolvers', 'Autorevolver', 'bottom-firing revolvers'],
  ARRAY['Emilio Ghisoni'],
  NULL, false, NULL,
  'The Mateba Autorevolver is the only production firearm ever made where the cylinder chamber that fires is at the 6 o''clock position (bottom) rather than the 12 o''clock position (top). By firing from the bottom, the bore axis is as low as possible, minimizing muzzle flip — the same principle as the Chiappa Rhino, designed by the same engineer.',
  ARRAY['Italy'], 'High', 'Autorevolver 2006M'
),

(
  'Galesi',
  ARRAY['Industria Armi Galesi', 'Rino Galesi'],
  'Italy', 1910, false,
  ARRAY['Pistol'],
  NULL, NULL,
  'Industria Armi Galesi was an Italian manufacturer founded around 1910 in Collebeato, Brescia. Galesi produced pocket semi-automatic pistols in .25 ACP and .32 ACP — inexpensive, flat, and reliable enough for the European and South American export market. The Galesi Model 6 and Model 9 were their primary products. Galesi pistols were imported to the US in quantity before the GCA 1968 import restrictions ended most cheap Italian pistol imports.',
  ARRAY['Model 6', 'Model 9'],
  NULL, 'Collebeato, Brescia, Italy',
  'Italy', 'Historical', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['Italian pocket pistols', '.25 ACP semi-autos', '.32 ACP pocket pistols'],
  NULL,
  NULL, false, NULL,
  NULL,
  ARRAY['Italy'], 'Low', 'Model 9'
),

(
  'Armi Sport',
  ARRAY['Armi Sport di Chiappa', 'Armi Sport Italy'],
  'Italy', 1958, true,
  ARRAY['Rifle', 'Revolver', 'Pistol'],
  NULL, NULL,
  'Armi Sport is an Italian manufacturer of reproduction historic firearms founded in 1958 in Brescia. Specializing in accurate reproductions of 19th century firearms — particularly Sharps, Springfield, and Enfield rifles, plus Remington and Colt revolver patterns — Armi Sport products are used in SASS Cowboy Action Shooting, Civil War reenactment, and historical collecting. The company has a manufacturing relationship with Chiappa Firearms (Chiappa Armi). Their Sharps rifle reproductions are widely regarded as among the best available.',
  ARRAY['Sharps 1874', '1863 Springfield', 'Remington 1858', 'Colt 1851 Navy'],
  NULL, 'Brescia, Italy',
  'Italy', 'Active Import', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['Sharps reproduction rifles', 'Civil War reproduction firearms', '19th century revolver reproductions'],
  NULL,
  699, false, NULL,
  NULL,
  ARRAY['Italy'], 'Medium', 'Sharps 1874'
),

-- ── BLACK POWDER / MUZZLELOADERS ─────────────────────────────

(
  'CVA',
  ARRAY['Connecticut Valley Arms', 'CVA Muzzleloaders', 'BPI Outdoors'],
  'United States', 1971, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'Connecticut Valley Arms (CVA) was founded in 1971 in Haddam Neck, Connecticut, and is now owned by BPI Outdoors. CVA pioneered the affordable inline muzzleloader market and today offers one of the widest ranges of muzzle-loading rifles in the industry. Their Optima, Accura, and Wolf series inline muzzleloaders are popular hunting rifles known for reliability and accuracy at competitive prices. CVA also offers traditional sidelock kits and completed guns. The Scout pistol is their single-shot muzzleloader handgun. CVA is currently headquartered in Atlanta, Georgia.',
  ARRAY['Optima V2', 'Accura MR-X', 'Wolf', 'Paramount', 'Scout Pistol'],
  'https://www.cva.com', 'Atlanta, Georgia, USA',
  'United States', 'Domestic', 'Mid', 'mass', 'Independent', false,
  'Manufacturer',
  ARRAY['inline muzzleloaders', 'traditional muzzleloaders', 'muzzleloader rifles'],
  NULL,
  299, false, NULL,
  'CVA''s Paramount series was the first production muzzleloader designed specifically for long-range hunting accuracy — capable of consistent accuracy at 300 yards with appropriate loads. It effectively created the "long-range muzzleloader" niche category.',
  ARRAY['United States', 'Spain'], 'Low', 'Accura MR-X'
),

(
  'Pedersoli',
  ARRAY['Davide Pedersoli', 'Davide Pedersoli & C.', 'Pedersoli Arms'],
  'Italy', 1957, true,
  ARRAY['Rifle', 'Pistol', 'Shotgun'],
  NULL, NULL,
  'Davide Pedersoli & C. is an Italian manufacturer of reproduction historic firearms founded in 1957 in Gardone Val Trompia, Brescia. Pedersoli is considered the gold standard for historically accurate reproduction firearms — their Sharps, Rolling Block, Hawken, Kentucky, and Springfield reproductions are used at the highest levels of black powder competition and by serious collectors worldwide. CAS (Cowboy Action Shooting), BPCR (Black Powder Cartridge Rifle) silhouette competition, and NSSA (North-South Skirmish Association) shooters all rely heavily on Pedersoli products. Accuracy and finish quality are exceptional.',
  ARRAY['Sharps 1874', 'Remington Rolling Block', 'Kodiak', 'Creedmoor', 'Gibbs', 'Alamo'],
  'https://www.davide-pedersoli.com', 'Gardone Val Trompia, Brescia, Italy',
  'Italy', 'Active Import', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['Sharps rifle reproductions', 'Rolling Block reproductions', 'black powder competition rifles', 'Hawken rifles'],
  NULL,
  799, false, NULL,
  'Pedersoli''s Sharps 1874 Quigley Down Under model was the specific prop replica used in the 1990 film "Quigley Down Under" — the film that introduced modern audiences to the concept of extreme-range black powder shooting and sparked a revival of interest in Sharps rifles.',
  ARRAY['Italy'], 'High', 'Sharps 1874'
),

(
  'Euroarms',
  ARRAY['Euroarms of America', 'Euroarms Italia'],
  'Italy', 1970, true,
  ARRAY['Rifle', 'Revolver', 'Pistol'],
  NULL, NULL,
  'Euroarms is an Italian manufacturer and US importer of reproduction black powder and early cartridge firearms, operating since approximately 1970. Euroarms Italia produces reproductions of Civil War-era rifles (1853 Enfield, 1861 Springfield), revolvers (Rogers & Spencer, Remington Army), and early breechloaders. Euroarms of America is the US import and distribution company. Products are sold to reenactors, collectors, and competitive shooters.',
  ARRAY['1853 Enfield', '1861 Springfield', 'Rogers & Spencer', 'Cook & Brother', 'Remington Army'],
  NULL, 'Concord, North Carolina, USA (importer)',
  'Italy', 'Active Import', 'Boutique', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['Civil War rifle reproductions', 'Enfield reproductions', 'blackpowder revolvers'],
  NULL,
  499, false, NULL,
  NULL,
  ARRAY['Italy'], 'Low', '1853 Enfield'
),

(
  'Sharps Rifle Company',
  ARRAY['Sharps Rifle Co.', 'SRC'],
  'United States', 2011, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'Sharps Rifle Company is an American manufacturer founded in 2011 in Chamberlain, South Dakota, producing modern Sharps-influenced single-shot rifles. Unlike reproduction makers (Pedersoli, Shiloh), Sharps Rifle Company makes contemporary rifles with modern steel and manufacturing while using the Sharps falling-block action design. Their rifles are chambered in both traditional (45-70, 40-65) and modern calibers.',
  ARRAY['Model 1874', 'Classic', 'Carbine'],
  'https://www.sharpsrifle.com', 'Chamberlain, South Dakota, USA',
  'United States', 'Domestic', 'Micro', 'collector', 'Independent', false,
  'Manufacturer',
  ARRAY['falling-block single-shot rifles', 'Sharps-action rifles', 'modern single-shot rifles'],
  NULL,
  1299, false, NULL,
  NULL,
  ARRAY['United States'], 'Low', 'Model 1874'
),

-- ── WWII M1 CARBINE CONTRACTORS ──────────────────────────────

(
  'Underwood Typewriter',
  ARRAY['Underwood Typewriter Company', 'Underwood', 'Underwood-Elliot-Fisher'],
  'United States', 1895, false,
  ARRAY['Rifle'],
  NULL, NULL,
  'Underwood Typewriter Company was an American typewriter manufacturer that received a WWII government contract to produce M1 Carbines. Between 1942 and 1944, Underwood produced approximately 545,616 M1 Carbines at their Hartford, Connecticut facility. Like other non-firearms contractors (IBM, Rock-Ola), Underwood had to retool their manufacturing lines entirely for firearms production. Underwood-marked M1 Carbines are among the more collectible WWII carbine variants.',
  ARRAY['M1 Carbine'],
  NULL, 'Hartford, Connecticut, USA',
  'United States', 'Historical', 'Micro', 'military', 'Independent', false,
  'Manufacturer',
  ARRAY['M1 Carbine (WWII contract)'],
  NULL,
  NULL, true, 'Produced ~545,616 M1 Carbines for the US military under WWII government contract.',
  'The choice of typewriter companies to manufacture carbines was deliberate — typewriter manufacturers had precision machining capabilities, stamping presses, and assembly-line experience that transferred directly to firearms production at scale.',
  ARRAY['United States'], 'Medium', 'M1 Carbine'
),

(
  'IBM Corporation',
  ARRAY['IBM', 'International Business Machines'],
  'United States', 1911, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'IBM Corporation (International Business Machines) received a WWII government contract to manufacture M1 Carbines between 1942 and 1944. IBM produced approximately 346,500 M1 Carbines at their Poughkeepsie, New York facility. IBM is the most famous non-firearms M1 Carbine contractor due to the company''s subsequent history as a technology giant. IBM-marked M1 Carbines command premium prices in the collector market due to name recognition.',
  ARRAY['M1 Carbine'],
  NULL, 'Poughkeepsie, New York, USA',
  'United States', 'Historical', 'Micro', 'military', 'Public', false,
  'Manufacturer',
  ARRAY['M1 Carbine (WWII contract)'],
  NULL,
  NULL, true, 'Produced ~346,500 M1 Carbines for the US military under WWII government contract.',
  'IBM M1 Carbines regularly command 20-30% premiums over equivalent carbines from other contractors in the collector market, purely due to IBM''s name recognition as one of history''s most famous technology companies.',
  ARRAY['United States'], 'High', 'M1 Carbine'
),

(
  'Quality Hardware & Machine',
  ARRAY['Quality Hardware', 'Quality Hardware & Machine Co.', 'QHM'],
  'United States', 1935, false,
  ARRAY['Rifle'],
  NULL, NULL,
  'Quality Hardware & Machine Company was an American industrial manufacturer that produced M1 Carbines under WWII government contract. Between 1942 and 1944, Quality Hardware produced approximately 359,666 M1 Carbines. Quality Hardware carbines are identified by the "QHM" cartouche and are considered to be of uniformly good quality. The company dissolved after WWII.',
  ARRAY['M1 Carbine'],
  NULL, 'Chicago, Illinois, USA',
  'United States', 'Historical', 'Micro', 'military', 'Independent', false,
  'Manufacturer',
  ARRAY['M1 Carbine (WWII contract)'],
  NULL,
  NULL, true, 'Produced ~359,666 M1 Carbines for the US military under WWII government contract.',
  NULL,
  ARRAY['United States'], 'Medium', 'M1 Carbine'
),

(
  'National Postal Meter',
  ARRAY['National Postal Meter Co.', 'NPM'],
  'United States', 1930, false,
  ARRAY['Rifle'],
  NULL, NULL,
  'National Postal Meter Company was an American postage meter manufacturer that received a WWII contract to produce M1 Carbines. Between 1943 and 1944, National Postal Meter produced approximately 413,017 M1 Carbines at their Rochester, New York facility. NPM carbines are noted for their consistent quality and are identified by the "NPM" cartouche. The company returned to postage equipment after the war.',
  ARRAY['M1 Carbine'],
  NULL, 'Rochester, New York, USA',
  'United States', 'Historical', 'Micro', 'military', 'Independent', false,
  'Manufacturer',
  ARRAY['M1 Carbine (WWII contract)'],
  NULL,
  NULL, true, 'Produced ~413,017 M1 Carbines for the US military under WWII government contract.',
  NULL,
  ARRAY['United States'], 'Medium', 'M1 Carbine'
),

(
  'Standard Products',
  ARRAY['Standard Products Co.', 'Standard Products Company'],
  'United States', 1930, false,
  ARRAY['Rifle'],
  NULL, NULL,
  'Standard Products Company was an American automotive parts manufacturer that received a WWII contract to produce M1 Carbines. Between 1942 and 1944, Standard Products produced approximately 247,000 M1 Carbines at their Port Clinton, Ohio facility. Standard Products carbines are among the less common WWII contractor carbines, making them moderately collectible.',
  ARRAY['M1 Carbine'],
  NULL, 'Port Clinton, Ohio, USA',
  'United States', 'Historical', 'Micro', 'military', 'Independent', false,
  'Manufacturer',
  ARRAY['M1 Carbine (WWII contract)'],
  NULL,
  NULL, true, 'Produced ~247,000 M1 Carbines for the US military under WWII government contract.',
  NULL,
  ARRAY['United States'], 'Medium', 'M1 Carbine'
),

(
  'Smith Enterprise',
  ARRAY['Smith Enterprise Inc.', 'SEI'],
  'United States', 1989, true,
  ARRAY['Rifle'],
  NULL, NULL,
  'Smith Enterprise Inc. (SEI) is an American small-batch custom rifle manufacturer founded in 1989 in Tempe, Arizona by Ron Smith. SEI specializes in M14/M1A-pattern semi-automatic rifles — accurizing, upgrading, and building complete rifles on US Rifle M14 actions. Their Mk 14 Mod 0-pattern Crazy Horse and M21 Sniper Counterpart are among the highest-quality M14-pattern semi-autos available. SEI also produces the Vortex flash hider/suppressor mount, which became standard on US Army designated marksman rifles. Very small production volumes.',
  ARRAY['Crazy Horse', 'M21 Sniper Counterpart', 'Mk14 Mod 0'],
  NULL, 'Tempe, Arizona, USA',
  'United States', 'Domestic', 'Micro', 'premium', 'Independent', false,
  'Manufacturer',
  ARRAY['M14/M1A custom rifles', 'M21 sniper rifles', 'Vortex flash hider'],
  ARRAY['Ron Smith'],
  2500, false, NULL,
  'Smith Enterprise''s Vortex flash hider was adopted by the US Army as the standard flash suppressor for M14-based designated marksman rifles. It is one of the few commercially designed accessories to see official military standardization.',
  ARRAY['United States'], 'Medium', 'Crazy Horse'
)

ON CONFLICT (name) DO NOTHING;
