-- ============================================================
-- powders v1 seed — ~80 rows, all 14 Phase 1 manufacturers
-- Run AFTER 20260429_powders_v1_schema.sql
-- Idempotent: ON CONFLICT (id) DO NOTHING
-- Columns: id, name, manufacturer, brand_family, alternate_names,
--   country_of_origin, grain_shape, meters_well,
--   burn_rate_rank, burn_rate_category, burn_rate_normalized,
--   temperature_sensitivity, extreme_series, flash_suppressed,
--   fouling_level, primary_application,
--   suitable_for_pistol, suitable_for_rifle, suitable_for_shotgun,
--   suitable_for_precision, suitable_for_bulk_plinking,
--   typical_calibers, double_charge_visible,
--   availability_us, shortage_prone, classification, description
-- ============================================================

INSERT INTO public.powders (
  id, name, manufacturer, brand_family, alternate_names,
  country_of_origin, grain_shape, meters_well,
  burn_rate_rank, burn_rate_category, burn_rate_normalized,
  temperature_sensitivity, extreme_series, flash_suppressed,
  fouling_level, primary_application,
  suitable_for_pistol, suitable_for_rifle, suitable_for_shotgun,
  suitable_for_precision, suitable_for_bulk_plinking,
  typical_calibers, double_charge_visible,
  availability_us, shortage_prone, classification, description
) VALUES

-- ═══════════════════════════════════════════════════════════════
-- HODGDON (13 rows)
-- ═══════════════════════════════════════════════════════════════

('hodgdon-varget','Varget','Hodgdon','Hodgdon Family',
 ARRAY['ADI AR2208'],'USA','Stick',true,
 61,'Rifle Medium',43.3,
 'Low',true,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','6.5 Creedmoor','.223 Rem','6mm Creedmoor','.30-06 Springfield','.243 Win'],
 true,
 'Common',true,'Smokeless',
 'The most popular precision rifle powder in the world. Temperature-insensitive extruded powder that delivers exceptional accuracy and consistent extreme spreads in .308 Win and 6.5 Creedmoor. Dominant in NRA High Power, F-Class, and PRS competition. Part of the Hodgdon Extreme series.'),

('hodgdon-h4350','H4350','Hodgdon','Hodgdon Family',
 ARRAY['ADI AR2209'],'USA','Stick',false,
 66,'Rifle Medium',40.0,
 'Low',true,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['6.5 Creedmoor','.308 Win','.30-06 Springfield','7mm-08 Rem','.270 Win','.243 Win'],
 true,
 'Common',true,'Smokeless',
 'Second only to Varget in popularity among precision rifle competitors. Temperature-insensitive Extreme series powder that excels in 6.5 Creedmoor and .308 Win. Notorious for inconsistent metering through volumetric measures — weigh each charge for precision work.'),

('hodgdon-h4895','H4895','Hodgdon','Hodgdon Family',
 ARRAY['ADI AR2206H','IMR 4895 (near-identical)'],'USA','Stick',true,
 57,'Rifle Medium',36.7,
 'Low',true,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.243 Win','7.62x51 NATO','.30-40 Krag'],
 true,
 'Common',false,'Smokeless',
 'Classic Extreme series medium-burn stick powder with a unique reduced-load capability — the "minimum recommended charge" rule makes it one of the safest powders for experimenting with light loads. Excellent .308 Win benchmark powder with consistent, tight extreme spreads.'),

('hodgdon-h4831sc','H4831SC','Hodgdon','Hodgdon Family',
 ARRAY['ADI AR2213SC'],'USA','Stick',true,
 69,'Rifle Slow',23.3,
 'Low',true,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['.270 Win','.30-06 Springfield','7mm Rem Mag','.300 Win Mag','.338 Win Mag'],
 true,
 'Common',false,'Smokeless',
 'Short-Cut version of H4831 with shorter kernels for improved metering through powder measures. Same Extreme series temperature stability as H4831. Excellent for standard to medium magnum rifle cartridges and a top choice for .270 Win hunting loads.'),

('hodgdon-h1000','H1000','Hodgdon','Hodgdon Family',
 ARRAY['ADI AR2217'],'USA','Stick',false,
 76,'Magnum Rifle',15.6,
 'Low',true,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['7mm Rem Mag','.300 Win Mag','.30-378 Wby','.338 Lapua'],
 true,
 'Common',false,'Smokeless',
 'Very slow Extreme series extruded powder for large magnum rifle cases. Temperature-insensitive — a critical advantage at this burn rate where temperature swings significantly impact other powders. Top choice for long-range hunters using .300 Win Mag with heavy bullets.'),

('hodgdon-retumbo','Retumbo','Hodgdon','Hodgdon Family',
 NULL,'USA','Stick',false,
 78,'Magnum Rifle',13.3,
 'Moderate',false,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['.300 Win Mag','.338 Lapua','.300 RUM','.30-378 Wby','7mm Rem Mag'],
 true,
 'Common',false,'Smokeless',
 'Ultra-slow extruded powder for large magnum rifle cases. Produces maximum velocities from .300 Win Mag, .338 Lapua, and Remington Ultra Mag cases. Dominant choice for long-range hunters using large magnums. Fills the gap between H1000 and the ultra-slow competition powders.'),

('hodgdon-titegroup','Titegroup','Hodgdon','Hodgdon Family',
 NULL,'USA','Ball',true,
 10,'Pistol Fast',88.9,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.38 Special','.40 S&W','.45 ACP','.357 Magnum'],
 false,
 'Common',false,'Smokeless',
 'Very fast ball powder ideal for high-volume target pistol reloading. Low charge weights mean more rounds per pound and lower recoil. Clean-burning and consistent — one of the most popular target pistol powders for 9mm and .45 ACP. WARNING: Double-charging not visually detectable in typical pistol cases.'),

('hodgdon-trail-boss','Trail Boss','Hodgdon','Hodgdon Family',
 NULL,'USA','Disc',false,
 22,'Pistol Medium',75.6,
 'Low',false,false,
 'Low','Pistol',
 true,true,false,false,false,
 ARRAY['9mm Luger','.45 ACP','.38 Special','.357 Magnum','.30-30 Win','.45-70 Govt'],
 true,
 'Common',false,'Smokeless',
 'Unique disc-shaped powder designed for cowboy action shooting and cast bullet rifle loads. The bulky disc geometry physically prevents double-charging in most cases — a built-in safety feature. Produces mild velocity with very soft-shooting loads in lever-action and revolver cartridges.'),

('hodgdon-h110','H110','Hodgdon','Hodgdon Family',
 ARRAY['Winchester 296 (identical)'],'USA','Ball',true,
 38,'Pistol Slow',57.8,
 'Moderate',false,false,
 'Moderate','Pistol',
 true,false,false,false,false,
 ARRAY['.44 Magnum','.357 Magnum','.454 Casull','.460 S&W','.300 Blackout'],
 false,
 'Common',false,'Smokeless',
 'Slow-burning ball powder for maximum magnum revolver velocities. Identical formulation to Winchester 296. Produces top velocities in .44 Magnum with heavy bullets and is the preferred powder for .300 Blackout supersonic loads. Not suitable for reduced loads — minimum charge rules must be followed.'),

('hodgdon-cfe-223','CFE 223','Hodgdon','Hodgdon Family',
 NULL,'USA','Ball',true,
 56,'Rifle Medium',37.8,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.223 Rem','5.56 NATO','.308 Win','.243 Win'],
 false,
 'Common',false,'Smokeless',
 'Copper Fouling Eraser (CFE) ball powder that dramatically reduces copper fouling in the bore. Temperature-insensitive with excellent metering for high-volume AR-15 reloading. Very popular for bulk .223 Rem plinking and competition AR loads.'),

('hodgdon-cfe-pistol','CFE Pistol','Hodgdon','Hodgdon Family',
 NULL,'USA','Ball',true,
 15,'Pistol Fast',83.3,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.40 S&W','.45 ACP','.38 Super','10mm Auto'],
 false,
 'Common',false,'Smokeless',
 'CFE (Copper Fouling Eraser) technology in a fast pistol ball powder. Clean-burning with reduced copper fouling. Temperature-insensitive. Consistent across a wide temperature range — excellent for competition shooters who reload year-round.'),

('hodgdon-blc2','BL-C(2)','Hodgdon','Hodgdon Family',
 NULL,'USA','Ball',true,
 54,'Rifle Medium',40.0,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.308 Win','.30-06 Springfield','.223 Rem','7.62 NATO'],
 false,
 'Common',false,'Smokeless',
 'Classic ball powder developed for 7.62 NATO military ammunition production. Long production history with well-documented loading data in every major manual. Popular with military surplus case reloaders and AR-10 shooters due to its superior metering.'),

('hodgdon-clays','Clays','Hodgdon','Hodgdon Family',
 NULL,'USA','Flake',true,
 7,'Pistol Fast',92.2,
 'Low',false,false,
 'Low','Shotgun',
 true,false,true,false,true,
 ARRAY['12 Gauge (light target)','20 Gauge','28 Gauge','.45 ACP (light)','.40 S&W (light)'],
 false,
 'Common',false,'Smokeless',
 'The benchmark fast flake powder for light target shotshell and pistol loads. Extremely clean-burning. Produces consistent, soft-shooting loads for sporting clays, trap, skeet, and target pistol work. One of the most widely used powders in competitive clay target shooting.'),

-- ═══════════════════════════════════════════════════════════════
-- IMR (7 rows)
-- ═══════════════════════════════════════════════════════════════

('imr-4064','IMR 4064','IMR','Hodgdon Family',
 NULL,'USA','Stick',true,
 62,'Rifle Medium',31.1,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.243 Win','.30-40 Krag','7.62x54R'],
 true,
 'Common',false,'Smokeless',
 'A classic medium burn rate IMR stick powder in production since the Du Pont era. Excellent in .308 Win and .30-06 with a long record of precision accuracy. One of the most well-documented powders in American reloading history — found in every major manual published since 1950.'),

('imr-4166','IMR 4166','IMR','Hodgdon Family',
 NULL,'USA','Stick',true,
 63,'Rifle Medium',30.0,
 'Low',true,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','6.5 Creedmoor','.30-06 Springfield','.243 Win'],
 true,
 'Common',false,'Smokeless',
 'Enduron series temperature-insensitive extruded powder with a copper fouling reducer additive. Burn rate close to Varget. Consistent performance across extreme temperatures — the IMR Enduron answer to Hodgdon Varget. Excellent for precision rifle competition where temperature stability matters.'),

('imr-4350','IMR 4350','IMR','Hodgdon Family',
 NULL,'USA','Stick',false,
 67,'Rifle Medium',25.6,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.270 Win','.30-06 Springfield','.308 Win','7mm-08 Rem','.243 Win'],
 true,
 'Common',false,'Smokeless',
 'Classic slow-medium IMR extruded powder from the original Du Pont family. One of the most referenced powders in American reloading history. Works excellently in medium to medium-large rifle cases. A traditional benchmark for .270 Win and .30-06 with hunting-weight bullets.'),

('imr-4451','IMR 4451','IMR','Hodgdon Family',
 NULL,'USA','Stick',true,
 68,'Rifle Medium',24.4,
 'Low',true,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['6.5 Creedmoor','.308 Win','.30-06 Springfield','.270 Win'],
 true,
 'Common',false,'Smokeless',
 'Enduron series temperature-insensitive IMR powder in the H4350 burn rate range. Copper fouling reducer included. The IMR Enduron answer to Hodgdon H4350 — same application range with superior temperature stability. Excellent for precision rifle competition across diverse climates.'),

('imr-4895','IMR 4895','IMR','Hodgdon Family',
 ARRAY['Hodgdon H4895 (near-identical)'],'USA','Stick',true,
 57,'Rifle Medium',36.7,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.243 Win','.30-40 Krag'],
 true,
 'Common',false,'Smokeless',
 'Classic IMR stick powder derived from surplus WWII military powder. Near-identical to Hodgdon H4895 in application. Excellent in .308 Win and .30-06 with a reduced-load capability similar to H4895. One of the most referenced powders in American loading history.'),

('imr-7977','IMR 7977','IMR','Hodgdon Family',
 NULL,'USA','Stick',true,
 80,'Magnum Rifle',11.1,
 'Low',true,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['7mm Rem Mag','.300 Win Mag','.338 Lapua','28 Nosler'],
 true,
 'Common',false,'Smokeless',
 'Enduron series very slow magnum IMR powder. Temperature-insensitive with copper fouling reducer. Excellent for large belted magnums requiring the slowest burn rates. Low ES and SD in precision applications across wide temperature swings. One of the slowest IMR Enduron options.'),

('imr-4198','IMR 4198','IMR','Hodgdon Family',
 NULL,'USA','Stick',true,
 41,'Rifle Fast',54.4,
 'Moderate',false,false,
 'Moderate','Rifle',
 false,true,false,false,false,
 ARRAY['.222 Rem','.22 Hornet','.223 Rem','.30-30 Win','.45-70 Govt'],
 true,
 'Common',false,'Smokeless',
 'Classic fast-burning IMR extruded powder in continuous production since 1960. One of the original Du Pont IMR family. Excellent for .222 Rem, .22 Hornet, and other small-capacity rifle cases. Also useful for cast bullet rifle loads and reduced loads in larger cases. A staple of every major loading manual.'),

-- ═══════════════════════════════════════════════════════════════
-- WINCHESTER (5 rows)
-- ═══════════════════════════════════════════════════════════════

('winchester-231','Winchester 231','Winchester','Hodgdon Family',
 ARRAY['Hodgdon HP-38 (identical)'],'USA','Ball',true,
 17,'Pistol Fast',81.1,
 'Moderate',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.38 Special','.40 S&W','.45 ACP','.380 ACP'],
 false,
 'Abundant',false,'Smokeless',
 'The most widely used pistol powder in America. Classic ball powder identical to Hodgdon HP-38 — the same formulation under different labels. Consistent, clean-burning, and excellent metering. Well-documented in every major loading manual for five decades. WARNING: Double-charging not visually detectable in standard pistol cases.'),

('winchester-296','Winchester 296','Winchester','Hodgdon Family',
 ARRAY['Hodgdon H110 (identical)'],'USA','Ball',true,
 37,'Pistol Slow',58.9,
 'Moderate',false,false,
 'Moderate','Pistol',
 true,false,false,false,false,
 ARRAY['.44 Magnum','.357 Magnum','.454 Casull','.410 Bore'],
 false,
 'Common',false,'Smokeless',
 'Identical to Hodgdon H110 — same formulation, different label. Slow-burning ball powder for maximum magnum revolver velocities and .410 shotshell. Not suitable for reduced loads — minimum charge rules must be strictly followed to avoid dangerous pressure spikes.'),

('winchester-748','Winchester 748','Winchester','Hodgdon Family',
 NULL,'USA','Ball',true,
 44,'Rifle Medium',51.1,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.223 Rem','5.56 NATO','.308 Win','.30-06 Springfield'],
 false,
 'Common',false,'Smokeless',
 'Classic Winchester ball rifle powder with decades of service rifle history. Originally developed for military 5.56 NATO production. Outstanding metering for AR-15 and service rifle reloading. One of the most well-documented ball rifle powders — found in every major loading manual.'),

('winchester-760','Winchester 760','Winchester','Hodgdon Family',
 NULL,'USA','Ball',true,
 55,'Rifle Medium',38.9,
 'Moderate',false,false,
 'Moderate','Rifle',
 false,true,false,false,false,
 ARRAY['.270 Win','.30-06 Springfield','.308 Win','.25-06 Rem'],
 false,
 'Common',false,'Smokeless',
 'Classic Winchester medium-slow ball powder in the H414/IMR 4350 burn rate range. Outstanding for .270 Win and .30-06 with standard hunting bullets. Ball construction provides excellent metering for hunting reloads. Consistently ranks among the most accurate powders for these cartridges in published loading data.'),

('winchester-staball-65','Winchester StaBALL 6.5','Winchester','Hodgdon Family',
 NULL,'USA','Ball',true,
 65,'Rifle Medium',27.8,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['6.5 Creedmoor','.308 Win','.260 Rem'],
 true,
 'Common',false,'Smokeless',
 'Temperature-stable ball powder specifically optimized for the 6.5 Creedmoor cartridge. Copper fouling reducer in the formulation. Low temperature sensitivity enables consistent performance in competition from summer to winter. Superior metering compared to H4350 for progressive press reloading.'),

-- ═══════════════════════════════════════════════════════════════
-- ALLIANT (8 rows)
-- ═══════════════════════════════════════════════════════════════

('alliant-unique','Alliant Unique','Alliant','Vista Outdoor',
 NULL,'USA','Flake',true,
 20,'Pistol Medium',77.8,
 'Moderate',false,false,
 'Moderate','Pistol',
 true,false,true,false,true,
 ARRAY['9mm Luger','.38 Special','.357 Magnum','.45 ACP','12 Gauge','.223 Rem'],
 false,
 'Abundant',false,'Smokeless',
 'The most versatile powder ever produced — in continuous production since 1898. Works across a remarkable range of calibers from pistol to light rifle and shotshell. Tends to produce visible fouling but delivers consistent results. The benchmark against which all multi-purpose powders are measured.'),

('alliant-sport-pistol','Alliant Sport Pistol','Alliant','Vista Outdoor',
 NULL,'USA','Ball',true,
 28,'Pistol Medium',68.9,
 'Low',false,true,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.40 S&W','.45 ACP'],
 false,
 'Common',false,'Smokeless',
 'Temperature-stable ball powder designed for USPSA and IPSC competition. Flash-suppressed formula for indoor and low-light competition. Low temperature sensitivity ensures consistent power factors from summer outdoor matches to winter indoor competition.'),

('alliant-power-pistol','Alliant Power Pistol','Alliant','Vista Outdoor',
 NULL,'USA','Ball',true,
 35,'Pistol Slow',61.1,
 'Moderate',false,false,
 'High','Pistol',
 true,false,false,false,false,
 ARRAY['9mm Luger','.40 S&W','.357 SIG','.45 ACP','.357 Magnum','10mm Auto'],
 false,
 'Common',false,'Smokeless',
 'High-energy ball powder for semi-automatic pistol calibers. Achieves high velocity with heavy bullets — the preferred powder for 10mm Auto and +P loads. Produces significant muzzle flash; not ideal for low-light or indoor competition. Excellent for defensive and hunting handgun loads.'),

('alliant-reloader-15','Alliant Reloader 15','Alliant','Vista Outdoor',
 NULL,'USA','Stick',true,
 58,'Rifle Medium',35.6,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.243 Win','7mm-08 Rem','6.5 Creedmoor'],
 true,
 'Common',false,'Smokeless',
 'Extremely versatile medium rifle powder with excellent performance in .308 Win and similar capacity cases. Consistent metering and accuracy across a wide range of bullet weights. One of the most popular precision rifle powders for .308 Win High Power and F-Class competition.'),

('alliant-reloader-16','Alliant Reloader 16','Alliant','Vista Outdoor',
 NULL,'USA','Stick',true,
 60,'Rifle Medium',33.3,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['6.5 Creedmoor','.308 Win','.300 WSM','.270 WSM'],
 true,
 'Common',false,'Smokeless',
 'Temperature-stable medium rifle powder delivering low extreme spreads for precision work. Excellent in 6.5 Creedmoor across a wide temperature range. Low ES and SD performance that rivals the Hodgdon Extreme series without the metering challenges of H4350.'),

('alliant-reloader-22','Alliant Reloader 22','Alliant','Vista Outdoor',
 NULL,'USA','Stick',false,
 73,'Magnum Rifle',18.9,
 'Moderate',false,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['7mm Rem Mag','.300 Win Mag','.300 Wby Mag','.338 Win Mag'],
 true,
 'Common',false,'Smokeless',
 'The benchmark slow-burning powder for .300 Win Mag and 7mm Rem Mag accuracy loads. Decades of proven accuracy data in major loading manuals. Excellent for hunters and precision shooters who need maximum performance from standard magnum cases.'),

('alliant-ar-comp','Alliant AR-Comp','Alliant','Vista Outdoor',
 NULL,'USA','Ball',true,
 55,'Rifle Medium',38.9,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['5.56 NATO','.223 Rem','.300 Blackout'],
 false,
 'Common',false,'Smokeless',
 'Temperature-stable ball powder optimized for AR-platform rifles. Designed for consistent performance from -65°F to 165°F — ideal for military and law enforcement applications. Excellent metering for high-volume AR-15 reloading. The Alliant choice for tactical rifle reloaders.'),

('alliant-2400','Alliant 2400','Alliant','Vista Outdoor',
 NULL,'USA','Flake',true,
 40,'Pistol Slow',55.6,
 'Moderate',false,false,
 'High','Pistol',
 true,true,false,false,false,
 ARRAY['.44 Magnum','.357 Magnum','.41 Magnum','.22 Hornet','7.62x39'],
 false,
 'Common',false,'Smokeless',
 'Classic slow-burning pistol powder in production since the 1930s. Excellent for magnum handgun cartridges and small rifle cases like .22 Hornet. Produces significant muzzle flash — not ideal for indoor or low-light use. A traditional choice for handgun hunting loads.'),

-- ═══════════════════════════════════════════════════════════════
-- VIHTAVUORI (8 rows)
-- ═══════════════════════════════════════════════════════════════

('vihtavuori-n133','Vihtavuori N133','Vihtavuori','Nammo Group',
 NULL,'Finland','Stick',true,
 53,'Rifle Fast',41.1,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['5.56 NATO','.223 Rem','6mm PPC','.300 Blackout'],
 true,
 'Common',false,'Smokeless',
 'Benchmark Vihtavuori powder for .223 Rem and benchrest cartridges. Exceptionally consistent lot-to-lot. Very low temperature sensitivity — the defining characteristic of the entire N-series. Top choice for 6mm PPC and .223 Rem benchrest and F-Class Open competition.'),

('vihtavuori-n140','Vihtavuori N140','Vihtavuori','Nammo Group',
 NULL,'Finland','Stick',true,
 61,'Rifle Medium',32.2,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','6.5 Creedmoor','.30-06 Springfield','.243 Win','7mm-08 Rem'],
 true,
 'Common',false,'Smokeless',
 'The most popular Vihtavuori powder globally. Excellent in .308 Win and 6.5 Creedmoor with very low temperature sensitivity. Standard choice for European precision rifle competition. Consistent lot-to-lot performance enables reloaders to buy in bulk without rechronographing.'),

('vihtavuori-n150','Vihtavuori N150','Vihtavuori','Nammo Group',
 NULL,'Finland','Stick',false,
 66,'Rifle Medium',26.7,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.30-06 Springfield','.270 Win','7mm-08 Rem','.308 Win'],
 true,
 'Common',false,'Smokeless',
 'Medium-slow Vihtavuori rifle powder between N140 and N160. Excellent for .30-06 with standard bullet weights and .270 Win hunting loads. Very consistent with tight extreme spreads characteristic of all N-series powders.'),

('vihtavuori-n160','Vihtavuori N160','Vihtavuori','Nammo Group',
 NULL,'Finland','Stick',false,
 70,'Magnum Rifle',22.2,
 'Low',false,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['.270 Win','.30-06 Springfield','7mm Rem Mag','.300 Win Mag','.338 Win Mag'],
 true,
 'Common',false,'Smokeless',
 'Slow N-series Vihtavuori powder for medium to large capacity rifle cases. Excellent in 7mm Rem Mag and .300 Win Mag with hunting-weight bullets. Very low temperature sensitivity makes it ideal for hunting in cold-weather environments.'),

('vihtavuori-n320','Vihtavuori N320','Vihtavuori','Nammo Group',
 NULL,'Finland','Flake',true,
 8,'Pistol Fast',91.1,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.38 Special','.40 S&W','.45 ACP'],
 false,
 'Common',false,'Smokeless',
 'Popular competition handgun powder used by IPSC and USPSA competitors worldwide. Clean-burning, consistent, and excellent metering. Very low temperature sensitivity distinguishes it from domestic alternatives. Preferred by European and international competition shooters.'),

('vihtavuori-n340','Vihtavuori N340','Vihtavuori','Nammo Group',
 NULL,'Finland','Flake',true,
 17,'Pistol Medium',81.1,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.40 S&W','.357 Magnum','.45 ACP'],
 false,
 'Common',false,'Smokeless',
 'Medium handgun powder excellent for 9mm major power factor loads and .40 S&W IPSC competition. Vihtavuori''s consistent N-series chemistry with very low temperature sensitivity. Popular with Open and Limited division competitors in USPSA/IPSC.'),

('vihtavuori-3n37','Vihtavuori 3N37','Vihtavuori','Nammo Group',
 NULL,'Finland','Ball',true,
 33,'Pistol Slow',63.3,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,false,
 ARRAY['9mm Luger (+P/Major)','.38 Super','.357 SIG','.40 S&W (Major)'],
 false,
 'Moderate',false,'Smokeless',
 'Competition handgun powder for major power factor loads in Open division IPSC/USPSA. Very low temperature sensitivity is the key differentiator versus domestic powders. Finnish national competition standard. Used by world-class Open division competitors for consistent major power factor.'),

('vihtavuori-3n38','Vihtavuori 3N38','Vihtavuori','Nammo Group',
 NULL,'Finland','Ball',true,
 40,'Pistol Slow',55.6,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,false,
 ARRAY['9mm Major','.38 Super Major','.357 SIG'],
 false,
 'Moderate',false,'Smokeless',
 'Slightly slower than 3N37 for IPSC Open division major power factor loads. The European standard for 9mm Major and .38 Super competition. Low temperature sensitivity enables consistent power factors across summer and winter matches without reloading from scratch.'),

-- ═══════════════════════════════════════════════════════════════
-- NORMA (3 rows)
-- ═══════════════════════════════════════════════════════════════

('norma-200','Norma 200','Norma','RUAG Ammotec',
 NULL,'Sweden','Stick',true,
 53,'Rifle Medium',41.1,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.243 Win','.260 Rem'],
 true,
 'Limited',false,'Smokeless',
 'Norma''s medium extruded rifle powder in the Varget/H4895 burn rate range. Classic Swedish precision rifle powder with excellent lot-to-lot consistency. Standard in Scandinavian .308 Win precision shooting. Clean-burning with tight extreme spreads.'),

('norma-202','Norma 202','Norma','RUAG Ammotec',
 NULL,'Sweden','Stick',true,
 58,'Rifle Medium',35.6,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.30-06 Springfield','.270 Win','.308 Win','6.5x55 Swedish'],
 true,
 'Limited',false,'Smokeless',
 'Classic Norma extruded rifle powder with outstanding heritage in 6.5x55 Swedish and .30-06 Springfield. Long the standard in Scandinavian moose and big game hunting loads. Clean-burning and consistent across wide temperature ranges encountered in Nordic hunting conditions.'),

('norma-mrp','Norma MRP','Norma','RUAG Ammotec',
 NULL,'Sweden','Stick',false,
 66,'Magnum Rifle',26.7,
 'Moderate',false,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['.300 Win Mag','.338 Win Mag','7mm Rem Mag','.375 H&H Magnum'],
 true,
 'Limited',false,'Smokeless',
 'Magnum Rifle Powder — Norma''s primary slow magnum extruded powder. Long history as the Swedish standard for dangerous game and large magnum cartridges. Excellent for .375 H&H and .338 Win Mag. Still heavily referenced in European dangerous game loading data.'),

-- ═══════════════════════════════════════════════════════════════
-- ADI (Australian Defence Industries) (5 rows)
-- ═══════════════════════════════════════════════════════════════

('adi-ar2205','ADI AR 2205','ADI',NULL,
 ARRAY['Hodgdon H322 (equivalent)'],'Australia','Stick',true,
 37,'Rifle Fast',58.9,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.222 Rem','.223 Rem','.22 PPC'],
 true,
 'Limited',false,'Smokeless',
 'ADI equivalent of Hodgdon H322. Manufactured at the Mulwala facility in New South Wales under Australian Defence standards. The standard Australian .222 Rem and .223 Rem competition powder. Widely available in Australian retail channels with consistent lot-to-lot performance.'),

('adi-ar2206h','ADI AR 2206H','ADI',NULL,
 ARRAY['Hodgdon H4895 (near-equivalent)'],'Australia','Stick',true,
 53,'Rifle Medium',41.1,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.223 Rem','.243 Win'],
 true,
 'Limited',false,'Smokeless',
 'Near-equivalent to Hodgdon H4895 with slightly improved temperature stability. The standard Australian .308 Win competition and service rifle powder. Dominant in Australian F-Class and NRA-style service rifle competition. Manufactured at Mulwala under Australian defence specifications.'),

('adi-ar2208','ADI AR 2208','ADI',NULL,
 ARRAY['Hodgdon Varget (equivalent — same source powder)'],'Australia','Stick',true,
 55,'Rifle Medium',38.9,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','6.5 Creedmoor','.223 Rem','.30-06 Springfield'],
 true,
 'Limited',false,'Smokeless',
 'The primary ADI source powder for Hodgdon Varget — functionally identical formulation. AR 2208 and Varget are cross-referenced in Australian loading manuals and data is interchangeable. Standard Australian precision rifle powder and one of the most accurate powders for .308 Win.'),

('adi-ar2209','ADI AR 2209','ADI',NULL,
 ARRAY['Hodgdon H4350 (equivalent)'],'Australia','Stick',false,
 62,'Rifle Medium',31.1,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.270 Win','.30-06 Springfield','6.5 Creedmoor','7mm Rem Mag'],
 true,
 'Limited',false,'Smokeless',
 'The ADI equivalent of Hodgdon H4350. Standard Australian big game and precision powder. Dominant in Australian long-range competition and hunting. Cross-referenced with H4350 in Australian loading manuals. Temperature-stable per Australian Defence specifications.'),

('adi-ar2213sc','ADI AR 2213SC','ADI',NULL,
 ARRAY['Hodgdon H4831SC (equivalent)'],'Australia','Stick',true,
 70,'Magnum Rifle',22.2,
 'Low',false,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['7mm Rem Mag','.300 Win Mag','.338 Win Mag'],
 true,
 'Limited',false,'Smokeless',
 'Short-cut formulation equivalent to Hodgdon H4831SC. The SC designation reflects improved metering of the short-cut kernels versus full-length AR2213. Standard Australian slow magnum powder. Dominant for .300 Win Mag and 7mm Rem Mag in Australian hunting and competition.'),

-- ═══════════════════════════════════════════════════════════════
-- ACCURATE (7 rows)
-- ═══════════════════════════════════════════════════════════════

('accurate-no5','Accurate No. 5','Accurate','Western Powders',
 NULL,'Belgium','Ball',true,
 18,'Pistol Fast',80.0,
 'Moderate',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.38 Special','.357 Magnum','.45 ACP'],
 false,
 'Common',false,'Smokeless',
 'Versatile Accurate ball pistol powder covering a wide caliber range. Similar application to Alliant Unique but with superior metering due to ball granules. Popular for all handgun calibers from light target to medium power factor. One of the most multi-purpose pistol powders in the Accurate line.'),

('accurate-1680','Accurate 1680','Accurate','Western Powders',
 NULL,'Belgium','Ball',true,
 31,'Pistol Slow',65.6,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,false,false,
 ARRAY['.22 Hornet','.221 Fireball','7.62x39','.300 Blackout (subsonic)'],
 false,
 'Common',false,'Smokeless',
 'Purpose-designed for small-capacity rifle cases and subsonic applications. The definitive Accurate powder for .300 Blackout subsonic loads — fills the case volume correctly for consistent ignition at sub-sonic pressures. Also excellent for 7.62x39 in AK-pattern rifles.'),

('accurate-2230','Accurate 2230','Accurate','Western Powders',
 NULL,'Belgium','Ball',true,
 43,'Rifle Fast',52.2,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.223 Rem','5.56 NATO','.308 Win (mid-range)'],
 false,
 'Common',false,'Smokeless',
 'One of Accurate''s most popular rifle powders. Primarily used for .223 Rem and 5.56 NATO. Excellent metering for AR-15 reloading. Consistent velocities with military-specification case volumes. Ball construction provides superior metering compared to extruded alternatives.'),

('accurate-2520','Accurate 2520','Accurate','Western Powders',
 NULL,'Belgium','Ball',true,
 48,'Rifle Medium',46.7,
 'Moderate',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.308 Win','.30-06 Springfield','.223 Rem (heavy)','.243 Win'],
 false,
 'Common',false,'Smokeless',
 'Accurate''s medium ball powder optimized for the .308 Win service rifle cartridge. Among the most referenced Accurate powders in NRA High Power loading data. Ball construction provides significant metering advantage for progressive press reloading.'),

('accurate-4350','Accurate 4350','Accurate','Western Powders',
 NULL,'Belgium','Ball',true,
 62,'Rifle Medium',31.1,
 'Moderate',false,false,
 'Moderate','Rifle',
 false,true,false,false,false,
 ARRAY['.30-06 Springfield','.270 Win','7mm Rem Mag','.338 Win Mag'],
 false,
 'Common',false,'Smokeless',
 'Accurate''s ball powder equivalent of H4350. Competes directly with Hodgdon H4350 in application but offers superior metering due to ball construction. Popular as an out-of-stock substitute for H4350 during shortage cycles.'),

('accurate-lt32','Accurate LT-32','Accurate','Western Powders',
 NULL,'USA','Stick',true,
 61,'Rifle Medium',32.2,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.223 Rem','6mm Creedmoor','6.5 Creedmoor'],
 true,
 'Common',false,'Smokeless',
 'Temperature-stable extruded powder for small to medium rifle cases. Similar to Varget in application range. Low temperature sensitivity makes it an excellent Varget alternative when stock is unavailable. Growing adoption in precision rifle competition.'),

('accurate-magpro','Accurate MagPro','Accurate','Western Powders',
 NULL,'Belgium','Ball',true,
 76,'Magnum Rifle',15.6,
 'Moderate',false,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['.300 Win Mag','.338 Win Mag','7mm Rem Mag','.338 Lapua'],
 true,
 'Common',false,'Smokeless',
 'Accurate''s very slow magnum ball powder for large-capacity rifle cases. Excellent metering advantage over extruded competitors at this burn rate. Popular as an H1000 substitute during shortage cycles. Used in .300 Win Mag and 7mm Rem Mag full-power hunting and competition loads.'),

-- ═══════════════════════════════════════════════════════════════
-- RAMSHOT (6 rows)
-- ═══════════════════════════════════════════════════════════════

('ramshot-tac','Ramshot TAC','Ramshot','Western Powders',
 NULL,'Belgium','Ball',true,
 44,'Rifle Medium',51.1,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['5.56 NATO','.223 Rem','.308 Win (mid-range)','7.62 NATO'],
 false,
 'Common',false,'Smokeless',
 'Purpose-built for AR-15 and AR-10 tactical applications. Clean-burning with excellent temperature stability. The name reflects its tactical/military application focus. Excellent metering for high-volume semi-auto rifle reloading. Growing adoption as a Ramshot answer to Hodgdon CFE 223.'),

('ramshot-true-blue','Ramshot True Blue','Ramshot','Western Powders',
 NULL,'Belgium','Ball',true,
 15,'Pistol Fast',83.3,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.38 Special','.357 Magnum','.45 ACP'],
 false,
 'Common',false,'Smokeless',
 'Medium-fast ball pistol powder bridging the target and medium-power pistol range. Excellent for 9mm competition loads and medium .38 Special charges. Ball construction provides superior metering over Unique-class flake powders for high-volume progressive reloading.'),

('ramshot-x-terminator','Ramshot X-Terminator','Ramshot','Western Powders',
 NULL,'Belgium','Ball',true,
 40,'Rifle Fast',55.6,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,false,
 ARRAY['.223 Rem','.22-250 Rem','.204 Ruger','.220 Swift'],
 false,
 'Common',false,'Smokeless',
 'Varmint-specific ball powder optimized for .223 Rem and fast 22-caliber cartridges. Temperature-stable for year-round prairie dog and ground squirrel shooting. Excellent metering for high-round-count varmint reloading where consistency matters over many hundreds of rounds.'),

('ramshot-hunter','Ramshot Hunter','Ramshot','Western Powders',
 NULL,'Belgium','Ball',true,
 61,'Rifle Medium',32.2,
 'Low',false,false,
 'Moderate','Rifle',
 false,true,false,false,false,
 ARRAY['.270 Win','.30-06 Springfield','.308 Win (heavy)','.25-06 Rem'],
 false,
 'Common',false,'Smokeless',
 'Hunting-optimized ball powder at the H4350 burn rate. Temperature-stable for consistent performance across seasons. Popular substitute for H4350 with superior metering. Designed specifically for hunting applications where conditions may be diverse.'),

('ramshot-big-game','Ramshot Big Game','Ramshot','Western Powders',
 NULL,'Belgium','Ball',true,
 68,'Magnum Rifle',24.4,
 'Low',false,false,
 'Low','Magnum Rifle',
 false,true,false,false,false,
 ARRAY['.300 Win Mag','7mm Rem Mag','.338 Win Mag','.30-06 Springfield (heavy)'],
 false,
 'Common',false,'Smokeless',
 'Slow-burning hunting ball powder for large game. Temperature-stable for hunting conditions from Alaska to Africa. Application similar to IMR 4831. Ball construction provides significant metering advantage for reloaders who hunt in remote areas and load in the field.'),

('ramshot-magnum','Ramshot Magnum','Ramshot','Western Powders',
 NULL,'Belgium','Ball',true,
 76,'Magnum Rifle',15.6,
 'Low',false,false,
 'Low','Magnum Rifle',
 false,true,false,true,false,
 ARRAY['.300 Win Mag','.338 Lapua','7mm Rem Mag','.338 Win Mag'],
 true,
 'Common',false,'Smokeless',
 'Ramshot''s ultra-slow ball powder for the largest magnum cases. Excellent temperature stability for ELR and dangerous game hunting. Superior metering advantage over extruded powders at this burn rate makes it popular with hunters and precision shooters who value consistency.'),

-- ═══════════════════════════════════════════════════════════════
-- RELOAD SWISS (3 rows)
-- ═══════════════════════════════════════════════════════════════

('reload-swiss-rs50','Reload Swiss RS50','Reload Swiss',NULL,
 NULL,'Switzerland','Stick',true,
 48,'Rifle Medium',46.7,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.223 Rem (heavy)'],
 true,
 'Limited',false,'Smokeless',
 'Medium extruded rifle powder in the Varget burn rate zone. Swiss precision manufacturing by Nitrochemie AG ensures exceptional lot-to-lot consistency. Temperature-stable across the Alpine climate range. Standard European option for .308 Win precision competition.'),

('reload-swiss-rs60','Reload Swiss RS60','Reload Swiss',NULL,
 NULL,'Switzerland','Stick',true,
 55,'Rifle Medium',38.9,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.30-06 Springfield','.270 Win','.308 Win (heavy)','6.5x55 Swedish'],
 true,
 'Limited',false,'Smokeless',
 'Medium-slow extruded rifle powder from Reload Swiss. Application range similar to IMR 4350. Standard Swiss choice for 6.5x55 Swedish and .30-06 precision loads. Nitrochemie''s temperature-stable chemistry is especially valued in Alpine hunting conditions.'),

('reload-swiss-rs62','Reload Swiss RS62','Reload Swiss',NULL,
 NULL,'Switzerland','Stick',true,
 62,'Rifle Medium',31.1,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.270 Win','.30-06 Springfield (heavy)','7mm Rem Mag','6.5 Creedmoor (heavy)'],
 true,
 'Limited',false,'Smokeless',
 'Slow extruded powder for larger standard and short magnum cases. The Reload Swiss equivalent of H4350. Excellent for 6.5 Creedmoor with heavy bullets. Temperature-stable performance across the temperature range encountered in European mountain hunting.'),

-- ═══════════════════════════════════════════════════════════════
-- LOVEX / EXPLOSIA (3 rows)
-- ═══════════════════════════════════════════════════════════════

('lovex-d060-5','Lovex D060.5','Lovex','Explosia',
 NULL,'Czech Republic','Ball',true,
 15,'Pistol Fast',83.3,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.38 Special','.357 Magnum'],
 false,
 'Limited',false,'Smokeless',
 'Medium-speed Lovex ball pistol powder. Standard Explosia competition pistol powder. Clean-burning, temperature-stable, and excellent metering. Growing European IPSC presence as the Lovex brand expands into North American markets through Shooters World distribution.'),

('lovex-s010','Lovex S010','Lovex','Explosia',
 NULL,'Czech Republic','Ball',true,
 42,'Rifle Fast',53.3,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.223 Rem','5.56 NATO','7.62x39'],
 false,
 'Limited',false,'Smokeless',
 'Lovex rifle ball powder for small to medium rifle cases. Application similar to BL-C(2). Czech military equivalent small rifle powder. Consistent across the temperature ranges encountered in Central European conditions. Available in North America through specialty distributors.'),

('lovex-d032-5','Lovex D032.5','Lovex','Explosia',
 NULL,'Czech Republic','Ball',true,
 48,'Rifle Medium',46.7,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.223 Rem (heavy)'],
 true,
 'Limited',false,'Smokeless',
 'Lovex medium rifle ball powder in the Varget/4895 burn rate zone. Standard Czech medium rifle powder. Application similar to IMR 4895. Temperature-stable for consistent competition performance. Alternative source for .308 Win precision reloaders seeking diversity beyond Hodgdon/Alliant.'),

-- ═══════════════════════════════════════════════════════════════
-- NOBEL SPORT / VECTAN (4 rows — manufacturer = Nobel Sport)
-- ═══════════════════════════════════════════════════════════════

('nobel-sport-ba10','Vectan BA10','Nobel Sport',NULL,
 ARRAY['Vectan BA10'],'France','Ball',true,
 3,'Pistol Fast',96.7,
 'Low',false,false,
 'Low','Shotgun',
 false,false,true,false,true,
 ARRAY['12 Gauge (light target)','20 Gauge','28 Gauge'],
 false,
 'Limited',false,'Smokeless',
 'Fastest Vectan powder and the benchmark for light target shotshell loads. Standard French competitive clay target powder. The benchmark for minimum-weight 12-gauge and 20-gauge target charges in European ISSF competition. Very clean-burning.'),

('nobel-sport-sp2','Vectan SP2','Nobel Sport',NULL,
 ARRAY['Vectan SP2'],'France','Ball',true,
 16,'Pistol Medium',82.2,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.38 Special','.357 Magnum','.40 S&W'],
 false,
 'Limited',false,'Smokeless',
 'Medium-speed ball pistol powder. The standard Vectan choice for 9mm and .38 Special competition loads. Clean-burning with good temperature stability. Growing adoption among European IPSC Production reloaders. Available in North America through specialty importers.'),

('nobel-sport-a0','Vectan A0','Nobel Sport',NULL,
 ARRAY['Vectan A0'],'France','Ball',true,
 39,'Rifle Fast',56.7,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.223 Rem','7.62x39','.30-30 Win'],
 false,
 'Limited',false,'Smokeless',
 'Vectan''s fast rifle ball powder. Standard French military-equivalent small rifle powder. Application similar to H335. Clean-burning for high-volume .223 Rem reloading. Growing adoption in North America as an H335 substitute during shortage periods.'),

('nobel-sport-a1','Vectan A1','Nobel Sport',NULL,
 ARRAY['Vectan A1'],'France','Ball',true,
 44,'Rifle Medium',51.1,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.308 Win','.223 Rem (heavy)','5.56 NATO'],
 false,
 'Limited',false,'Smokeless',
 'Medium-speed Vectan rifle ball powder at the BL-C(2)/H335 burn rate. Standard for French 7.62 NATO service rifle reloading. Growing North American presence as an alternative to domestic ball rifle powders in periods of supply constraint.'),

-- ═══════════════════════════════════════════════════════════════
-- SHOOTERS WORLD (4 rows)
-- ═══════════════════════════════════════════════════════════════

('shooters-world-action-pistol','Shooters World Action Pistol','Shooters World',NULL,
 NULL,'Czech Republic','Ball',true,
 10,'Pistol Fast',88.9,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,true,
 ARRAY['9mm Luger','.40 S&W','.45 ACP','.38 Special'],
 false,
 'Common',false,'Smokeless',
 'Clean-burning, temperature-stable ball powder for target pistol applications. Manufactured by Explosia at the Pardubice facility. Growing adoption in USPSA Production and IDPA. Very consistent chronograph readings across temperature ranges — a defining advantage over many domestic competitors.'),

('shooters-world-major-pistol','Shooters World Major Pistol','Shooters World',NULL,
 NULL,'Czech Republic','Ball',true,
 27,'Pistol Medium',70.0,
 'Low',false,false,
 'Low','Pistol',
 true,false,false,false,false,
 ARRAY['9mm Luger (Major)','.38 Super','.40 S&W (Major)','10mm Auto'],
 false,
 'Common',false,'Smokeless',
 'Explosia-manufactured ball powder gaining significant adoption in USPSA Open and Limited divisions for major power factor loads. Clean-burning with excellent metering. Temperature-insensitive. Represents the growing Shooters World brand as a serious alternative to established domestic competition powders.'),

('shooters-world-match-rifle','Shooters World Match Rifle','Shooters World',NULL,
 NULL,'Czech Republic','Ball',true,
 48,'Rifle Medium',46.7,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,true,false,
 ARRAY['.308 Win','.30-06 Springfield','.223 Rem (heavy)'],
 true,
 'Common',false,'Smokeless',
 'Competition-grade ball powder optimized for .308 Win match reloading. Temperature-stable Explosia chemistry. Gaining adoption in NRA High Power and F-Class competition as a consistent and available alternative to Varget during shortage cycles.'),

('shooters-world-economy-rifle','Shooters World Economy Rifle','Shooters World',NULL,
 NULL,'Czech Republic','Ball',true,
 42,'Rifle Fast',53.3,
 'Low',false,false,
 'Low','Rifle',
 false,true,false,false,true,
 ARRAY['.223 Rem','5.56 NATO','.308 Win'],
 false,
 'Common',false,'Smokeless',
 'High-volume rifle ball powder designed for cost-effective .223 Rem and 5.56 NATO reloading. As the name implies, optimized for the economics of bulk rifle reloading. Consistent and clean with significant market growth as an alternative to Hodgdon ball powders during shortage periods.'),

-- ═══════════════════════════════════════════════════════════════
-- BLACKHORN 209 (1 row)
-- ═══════════════════════════════════════════════════════════════

('blackhorn-209','Blackhorn 209','Blackhorn',NULL,
 NULL,'USA','Disc',false,
 NULL,'Muzzleloader',NULL,
 'Low',false,false,
 'Low','Muzzleloader',
 false,false,false,false,false,
 ARRAY['50 Cal Muzzleloader','45 Cal Muzzleloader'],
 true,
 'Common',false,'Black Powder Substitute',
 'The most popular non-corrosive, non-hygroscopic black powder substitute for modern inline muzzleloaders. Ignited by 209 shotgun primers. Does not require swabbing between shots. Superior ballistic performance and significantly easier cleanup versus traditional black powder and Pyrodex. Requires 209 primer — not compatible with #11 cap ignition systems.')

ON CONFLICT (id) DO NOTHING;

-- ════════════════════════════════════════════════════════════════
-- POWDER SUBSTITUTIONS — confirmed equivalent pairs
-- Seed after powders are inserted
-- ════════════════════════════════════════════════════════════════

INSERT INTO public.powder_substitutions
  (powder_id, substitute_id, direction, charge_adjustment_notes, confidence, notes)
VALUES

-- Hodgdon H110 = Winchester 296 (identical formulation)
('hodgdon-h110','winchester-296','bidirectional',
 'Identical formulation — same charge weights apply exactly. No adjustment needed.',
 'Manufacturer','Hodgdon and Winchester both confirm these are the same powder.'),

-- Hodgdon Varget ↔ ADI AR2208 (same source powder)
('hodgdon-varget','adi-ar2208','bidirectional',
 'Same source powder, interchangeable data. Work up from published minimum in a different case lot.',
 'Manufacturer','ADI AR2208 is the Australian designation for the same Hodgdon Varget formulation.'),

-- Hodgdon H4350 ↔ ADI AR2209
('hodgdon-h4350','adi-ar2209','bidirectional',
 'Equivalent formulation. Cross-referenced in Australian loading manuals. Work up from minimum.',
 'Published','ADI AR2209 is the Australian equivalent of H4350.'),

-- Hodgdon H4895 ↔ IMR 4895 (near-identical)
('hodgdon-h4895','imr-4895','bidirectional',
 'Near-identical application — minor lot-level differences possible. Start at published minimum and work up.',
 'Published','Shared military powder heritage. Hodgdon and IMR both document these as interchangeable in most applications.'),

-- Hodgdon H4831SC ↔ ADI AR2213SC
('hodgdon-h4831sc','adi-ar2213sc','bidirectional',
 'Equivalent formulation. Cross-referenced in Australian loading manuals. Work up from minimum.',
 'Published','ADI AR2213SC is the Australian short-cut equivalent of Hodgdon H4831SC.'),

-- Winchester 231 ↔ Hodgdon HP-38 noted via alternate_names; no separate row needed since HP-38 not seeded yet

-- Accurate MagPro — substitute for H1000 class powders
('accurate-magpro','hodgdon-h1000','bidirectional',
 'Similar burn rate. Reduce charge weight 5-8% from published H1000 data and work up. Ball powder may require slightly different seating depth.',
 'Community','Community-confirmed substitute in .300 Win Mag and 7mm Rem Mag applications.'),

-- IMR 4350 ↔ Hodgdon H4350 (very close but not identical)
('imr-4350','hodgdon-h4350','bidirectional',
 'Similar application range but not identical. Start at lowest published charge for the target powder and work up. H4350 tends to be slightly slower.',
 'Published','Both are widely cross-referenced in major loading manuals. Treat as similar, not identical.'),

-- Alliant Reloader 15 ↔ Hodgdon Varget (comparable burn rate, popular substitution)
('alliant-reloader-15','hodgdon-varget','bidirectional',
 'Comparable burn rate. Reduce charge by 3-5% from Varget data and work up. Extruded vs extruded — similar density.',
 'Community','Commonly swapped in .308 Win and 6.5 Creedmoor when one is unavailable. Not identical — always work up.'),

-- Ramshot Hunter ↔ Hodgdon H4350 class
('ramshot-hunter','hodgdon-h4350','bidirectional',
 'Similar burn rate. Ball powder — may achieve slightly higher velocity at same charge weight. Reduce charge by 2-4% from H4350 data and work up.',
 'Community','Commonly used as an H4350 substitute. Ball construction gives metering advantage.'),

-- Shooters World Match Rifle ↔ Hodgdon Varget
('shooters-world-match-rifle','hodgdon-varget','bidirectional',
 'Similar burn rate — positioned as a Varget alternative. Ball powder vs extruded. Reduce charge 3-5% from Varget data and work up from minimum.',
 'Community','Growing competition use as a Varget substitute during shortage periods. Not identical — always work up.'),

-- Vihtavuori N140 ↔ Hodgdon Varget (close burn rate, common swap)
('vihtavuori-n140','hodgdon-varget','bidirectional',
 'Similar burn rate and application range. Reduce charge 2-4% from published Varget data and work up. Extruded vs extruded.',
 'Published','Both documented in .308 Win and 6.5 Creedmoor in major loading manuals. Vihtavuori offers lower temperature sensitivity.')

ON CONFLICT (powder_id, substitute_id) DO NOTHING;
