-- ============================================================
-- manufacturers: public reference table
-- Firearms, optics, ammo, and accessories manufacturers
-- RLS: public SELECT, service_role only for writes
-- ============================================================

CREATE TABLE IF NOT EXISTS public.manufacturers (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text UNIQUE NOT NULL,
  alternate_names     text[],
  country_of_origin   text,
  founded_year        integer,
  active              boolean DEFAULT true,
  categories          text[],   -- ['Handgun','Rifle','Shotgun','Optics','Ammo','Accessories','Suppressors','NFA']
  parent_company      text,
  subsidiaries        text[],
  description         text,
  notable_models      text[],
  website             text,
  headquarters        text,
  created_at          timestamptz DEFAULT now(),
  updated_at          timestamptz DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_manufacturers_name        ON public.manufacturers (name);
CREATE INDEX IF NOT EXISTS idx_manufacturers_country     ON public.manufacturers (country_of_origin);
CREATE INDEX IF NOT EXISTS idx_manufacturers_active      ON public.manufacturers (active);
CREATE INDEX IF NOT EXISTS idx_manufacturers_categories  ON public.manufacturers USING GIN (categories);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_manufacturers_updated_at ON public.manufacturers;
CREATE TRIGGER trg_manufacturers_updated_at
  BEFORE UPDATE ON public.manufacturers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS
ALTER TABLE public.manufacturers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "manufacturers_public_read"   ON public.manufacturers;
DROP POLICY IF EXISTS "manufacturers_service_write" ON public.manufacturers;

CREATE POLICY "manufacturers_public_read"
  ON public.manufacturers FOR SELECT
  USING (true);

CREATE POLICY "manufacturers_service_write"
  ON public.manufacturers FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- SEED DATA
-- ============================================================

INSERT INTO public.manufacturers
  (name, alternate_names, country_of_origin, founded_year, active, categories, parent_company, subsidiaries, description, notable_models, website, headquarters)
VALUES

-- ── HANDGUN MAKERS ─────────────────────────────────────────────────────────────

('Glock',
 ARRAY['Glock Ges.m.b.H.'],
 'Austria', 1963, true,
 ARRAY['Handgun','Accessories'],
 NULL, NULL,
 'Austrian polymer-frame pistol manufacturer. The Glock 17, introduced in 1982, revolutionized the handgun industry with its lightweight polymer frame and striker-fired action.',
 ARRAY['G17','G19','G26','G43','G45'],
 'glock.com', 'Deutsch-Wagram, Austria'),

('Sig Sauer',
 ARRAY['SIG','Sig','SIG SAUER','Schweizerische Industrie-Gesellschaft'],
 'USA', 1985, true,
 ARRAY['Handgun','Rifle','Suppressors','Optics','Accessories'],
 NULL, ARRAY['Electro-Optics'],
 'Originally a Swiss-German partnership (SIG + Sauer & Sohn), the US subsidiary became dominant. Winner of the US Army M17/M18 contract. Full-line firearms and optics manufacturer.',
 ARRAY['P226','P320','P365','MCX','SCAR'],
 'sigsauer.com', 'Newington, NH'),

('Smith & Wesson',
 ARRAY['S&W','Smith and Wesson'],
 'USA', 1852, true,
 ARRAY['Handgun','Rifle','Accessories'],
 'American Outdoor Brands', NULL,
 'One of the oldest American firearms manufacturers, founded by Horace Smith and Daniel B. Wesson. Known for revolvers and the M&P series of polymer pistols.',
 ARRAY['Model 686','Model 29','M&P 9','M&P Shield','Governor'],
 'smith-wesson.com', 'Springfield, MA'),

('Beretta',
 ARRAY['Fabbrica d''Armi Pietro Beretta','Pietro Beretta'],
 'Italy', 1526, true,
 ARRAY['Handgun','Rifle','Shotgun','Accessories'],
 'Beretta Holding', ARRAY['Sako','Tikka','Benelli','Uberti','Franchi','Stoeger'],
 'The world''s oldest active firearms manufacturer, continuously operating since 1526. Supplier of the US military M9 pistol for over 30 years.',
 ARRAY['92FS','M9','APX','PX4 Storm','1301','A400'],
 'beretta.com', 'Brescia, Italy'),

('Ruger',
 ARRAY['Sturm Ruger','Sturm, Ruger & Co.'],
 'USA', 1949, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 NULL, NULL,
 'Major American manufacturer offering one of the broadest product lines in the industry. Founded by William B. Ruger and Alexander McCormick Sturm. Known for value and reliability.',
 ARRAY['10/22','GP100','Mini-14','Precision Rifle','LCP II'],
 'ruger.com', 'Southport, CT'),

('Springfield Armory',
 ARRAY['SA','Springfield'],
 'USA', 1974, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Commercial successor (no government affiliation) to the historic federal Springfield Armory. Known for 1911 pistols, XD series, and the Hellcat micro-compact.',
 ARRAY['1911 Loaded','XD-9','Hellcat','Echelon','Saint'],
 'springfield-armory.com', 'Geneseo, IL'),

('Colt',
 ARRAY['Colt Defense','Colt''s Manufacturing','Colt Patent Firearms'],
 'USA', 1836, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Iconic American firearms manufacturer founded by Samuel Colt. Inventor of the practical revolver and producer of the 1911 pistol and M16/AR-15 rifle family.',
 ARRAY['1911 Government','Python','LE6920','M4','Single Action Army'],
 'colt.com', 'West Hartford, CT'),

('Kimber',
 ARRAY['Kimber Manufacturing','Kimber of America'],
 'USA', 1979, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Premium American manufacturer of 1911-platform pistols and bolt-action rifles. Known for tight tolerances and out-of-the-box accuracy.',
 ARRAY['Custom II','Pro Carry II','Ultra Carry','Micro 9','Raptor'],
 'kimberamerica.com', 'Troy, AL'),

('Taurus',
 ARRAY['Forjas Taurus','Taurus International'],
 'Brazil', 1939, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Brazilian manufacturer offering value-priced handguns for the civilian and law enforcement markets. Known for revolvers and the popular G-series polymer pistols.',
 ARRAY['G2c','G3c','Judge','Model 856','TX22'],
 'taurususa.com', 'Bainbridge, GA'),

('CZ',
 ARRAY['Česká zbrojovka','CZ-USA','Ceska Zbrojovka'],
 'Czech Republic', 1936, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 'Colt CZ Group', ARRAY['Dan Wesson'],
 'Czech state arms manufacturer with a long military and police history. The CZ 75 is one of the most copied pistol designs in the world.',
 ARRAY['CZ 75B','CZ P-10C','Shadow 2','Scorpion EVO','527'],
 'cz-usa.com', 'Uherský Brod, Czech Republic'),

('Walther',
 ARRAY['Carl Walther GmbH','Walther Arms'],
 'Germany', 1886, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'German firearms manufacturer famous for the PPK (carried by James Bond) and innovative trigger designs. Now distributed in the US by PW Arms.',
 ARRAY['PDP','PPQ M2','PPK/S','PPS M2','Creed'],
 'waltherarms.com', 'Fort Smith, AR'),

('H&K',
 ARRAY['Heckler & Koch','HK','Heckler and Koch'],
 'Germany', 1949, true,
 ARRAY['Handgun','Rifle','Accessories','NFA'],
 NULL, NULL,
 'German manufacturer of premium military and law enforcement weapons. Known for the MP5, G3, and USP/VP9 handgun series. Motto: "No Compromise."',
 ARRAY['VP9','USP','P30','HK416','MP5','Mark 23'],
 'hk-usa.com', 'Sterling, VA'),

('FN Herstal',
 ARRAY['FN','Fabrique Nationale','FN America'],
 'Belgium', 1889, true,
 ARRAY['Handgun','Rifle','Accessories'],
 'Herstal Group', ARRAY['Winchester Repeating Arms','Browning'],
 'Belgian arms manufacturer and one of the world''s largest. Manufacturer of the M249 SAW, M240, and M16A2 for US military. Commercial line includes SCAR and Five-seveN.',
 ARRAY['FN 509','SCAR 16S','SCAR 17S','Five-seveN','FAL'],
 'fnamerica.com', 'McLean, VA'),

('Canik',
 ARRAY['TP9','Canik USA','Century Canik'],
 'Turkey', 1998, true,
 ARRAY['Handgun'],
 'MKEK / Samsun Yurt', NULL,
 'Turkish manufacturer producing well-regarded striker-fired pistols at competitive price points. The TP9 series has won multiple value-for-money awards.',
 ARRAY['TP9SF','TP9SFx','TP9SA','METE SFT'],
 'canikusa.com', 'Samsun, Turkey'),

('Staccato',
 ARRAY['STI International','STI'],
 'USA', 1993, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'Texas-based manufacturer of 2011-platform (double-stack 1911) pistols favored by competitive shooters and law enforcement. Rebranded from STI International in 2020.',
 ARRAY['Staccato P','Staccato C2','Staccato XC','Staccato CS'],
 'staccato2011.com', 'Georgetown, TX'),

('Wilson Combat',
 ARRAY['Wilson Combat'],
 'USA', 1977, true,
 ARRAY['Handgun','Rifle','Accessories'],
 NULL, NULL,
 'Arkansas-based custom firearms shop and manufacturer. Known for ultra-premium 1911 and 2011 pistols and custom AR-15/AR-10 rifles.',
 ARRAY['EDC X9','Protector','CQB','SFX9','Tactical AR'],
 'wilsoncombat.com', 'Berryville, AR'),

('Nighthawk Custom',
 ARRAY['Nighthawk'],
 'USA', 2004, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'Premium 1911 manufacturer in Arkansas. Each pistol is built by a single gunsmith from start to finish. Among the highest-quality production 1911s available.',
 ARRAY['Agent 2','GRP','Predator','T4','VIP'],
 'nighthawkcustom.com', 'Berryville, AR'),

('Les Baer',
 ARRAY['Les Baer Custom'],
 'USA', 1993, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Illinois-based custom firearms maker known for extremely accurate 1911-platform pistols and custom AR rifles. Tight tolerances with match-grade components.',
 ARRAY['Premier II','Thunder Ranch Special','Monolith','UTC'],
 'lesbaer.com', 'Hillsdale, IL'),

('Dan Wesson',
 ARRAY['DW'],
 'USA', 1968, true,
 ARRAY['Handgun'],
 'Colt CZ Group', NULL,
 'Originally founded by Dan Wesson (grandson of D.B. Wesson). Now owned by CZ-USA. Known for high-quality, value-priced 1911 pistols and classic revolvers.',
 ARRAY['Valor','Discretion','Specialist','Pointman 9','715'],
 'danwessonfirearms.com', 'Norwich, NY'),

('Kahr Arms',
 ARRAY['Kahr','Auto-Ordnance'],
 'USA', 1995, true,
 ARRAY['Handgun'],
 NULL, ARRAY['Auto-Ordnance','Thompson Center Arms'],
 'American manufacturer of slim, concealable semi-automatic pistols. Also owns Auto-Ordnance (Thompson submachine gun heritage) and Thompson Center Arms.',
 ARRAY['PM9','CW9','K9','P380','CT380'],
 'kahr.com', 'Greeley, PA'),

('Kel-Tec',
 ARRAY['Kel Tec','KelTec'],
 'USA', 1991, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 NULL, NULL,
 'Florida-based manufacturer known for innovative, unconventional designs at budget-friendly prices. Produces the RFB, KSG bullpup shotgun, and popular sub-compacts.',
 ARRAY['P-3AT','P11','PF-9','Sub-2000','KSG','RFB'],
 'keltecweapons.com', 'Cocoa, FL'),

('Diamondback Firearms',
 ARRAY['Diamondback'],
 'USA', 2009, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Florida-based manufacturer producing compact pistols and AR-platform rifles. Known for the DB9 ultra-compact and affordable AR-15 builds.',
 ARRAY['DB9','DB380','DB9 Gen 4','AR-15'],
 'diamondbackfirearms.com', 'Cocoa, FL'),

('Kriss USA',
 ARRAY['KRISS','Kriss Vector'],
 'USA', 2009, true,
 ARRAY['Handgun','Rifle','Accessories'],
 'KRISS Group', NULL,
 'American subsidiary of Swiss-based KRISS Group. Known for the Vector carbine/SMG with its unique Super V recoil mitigation system.',
 ARRAY['Vector CRB','Vector SDP','Sphinx SDP'],
 'kriss-usa.com', 'Virginia Beach, VA'),

('Bond Arms',
 ARRAY['Bond'],
 'USA', 1995, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'Texas-based manufacturer of premium derringer-style pistols in an interchangeable barrel system. The Roughneck and Bullpup9 are popular carry options.',
 ARRAY['Roughneck','Snake Slayer','Texas Defender','Bullpup9'],
 'bondarms.com', 'Granbury, TX'),

('North American Arms',
 ARRAY['NAA'],
 'USA', 1971, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'Utah manufacturer specializing in mini revolvers and small semi-automatic pistols. The .22 LR and .22 Magnum mini revolvers are among the smallest production firearms available.',
 ARRAY['Mini Revolver','Black Widow','Guardian','Earl'],
 'northamericanarms.com', 'Provo, UT'),

('Charter Arms',
 ARRAY['Charter'],
 'USA', 1964, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'Connecticut-based revolver manufacturer known for the Undercover .38 Special and the pink-finished Chic Lady line. Popular for affordable carry revolvers.',
 ARRAY['Undercover','Bulldog','Pathfinder','Off Duty'],
 'charterarms.com', 'Shelton, CT'),

('Chiappa Firearms',
 ARRAY['Chiappa'],
 'Italy', 1958, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 NULL, NULL,
 'Italian manufacturer known for reproduction lever-action rifles, Rhino revolvers with a low bore axis, and novelty/training firearms.',
 ARRAY['Rhino 50DS','Little Badger','1892 Kodiak','Triple Threat'],
 'chiappafirearms.com', 'Azzano Mella, Italy'),

('EAA Corporation',
 ARRAY['EAA','European American Armory'],
 'USA', 1990, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'Florida-based importer of European firearms, primarily Tanfoglio-made pistols sold under the Witness brand and Girsan pistols.',
 ARRAY['Witness','MC 1911','Girsan MC28SA'],
 'eaacorp.com', 'Rockledge, FL'),

('Rock Island Armory',
 ARRAY['RIA','Armscor','Armscor USA'],
 'Philippines', 1980, true,
 ARRAY['Handgun','Rifle'],
 'Armscor', NULL,
 'Philippine manufacturer (Armscor) selling value-priced 1911-platform pistols and AR-pattern rifles in the US under the Rock Island Armory brand.',
 ARRAY['GI Standard','XT22','MAPP','VR60','STK100'],
 'armscor.com', 'Marikina City, Philippines'),

-- ── RIFLE MAKERS ───────────────────────────────────────────────────────────────

('Daniel Defense',
 ARRAY['DD'],
 'USA', 2000, true,
 ARRAY['Rifle','Accessories'],
 NULL, NULL,
 'Georgia-based manufacturer of premium AR-15 and AR-10 platform rifles. Known for the DDM4 series and Delta 5 bolt-action. Mil-spec plus quality at a premium price point.',
 ARRAY['DDM4 V7','DDM4 V11','Delta 5','DDM4 PDW'],
 'danieldefense.com', 'Black Creek, GA'),

('BCM',
 ARRAY['Bravo Company MFG','Bravo Company','Bravo Company USA'],
 'USA', 2005, true,
 ARRAY['Rifle','Accessories'],
 NULL, NULL,
 'Wisconsin manufacturer of mil-spec-plus AR-15 rifles. Known for quality control and "life-saving equipment" philosophy. Popular with law enforcement and serious shooters.',
 ARRAY['RECCE-16','RECCE-14','MK2','BFH 16"'],
 'bravocompanymfg.com', 'Hartland, WI'),

('LaRue Tactical',
 ARRAY['LaRue'],
 'USA', 1992, true,
 ARRAY['Rifle','Accessories'],
 NULL, NULL,
 'Texas-based manufacturer of precision AR-platform rifles and the famous QD scope mount system. Known for exceptional quality and free shipping on everything.',
 ARRAY['OBR 5.56','OBR 7.62','PredatAR','Stealth'],
 'laruetactical.com', 'Leander, TX'),

('LWRC International',
 ARRAY['LWRC','Land Warfare Resources Corp'],
 'USA', 2006, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Maryland manufacturer of short-stroke piston-operated AR-15 pattern rifles. LWRC rifles are used by military and law enforcement worldwide.',
 ARRAY['IC-A5','IC-DI','IC-SPR','Six8','M6IC'],
 'lwrci.com', 'Cambridge, MD'),

('Knights Armament',
 ARRAY['KAC','Knight''s Armament Company'],
 'USA', 1982, true,
 ARRAY['Rifle','Accessories','Suppressors'],
 NULL, NULL,
 'Florida manufacturer of military-grade weapons and accessories. Producer of the SR-25 semi-auto sniper rifle and the M110 SASS used by US military.',
 ARRAY['SR-15','SR-25','PDW','URX Rail'],
 'knightarmco.com', 'Titusville, FL'),

('Barrett',
 ARRAY['Barrett Firearms','Barrett Firearms Manufacturing'],
 'USA', 1982, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Tennessee manufacturer founded by Ronnie Barrett. Created the .50 BMG semi-automatic rifle market with the M82A1. Also produces the MRAD bolt-action and .416 Barrett caliber.',
 ARRAY['M82A1','M107A1','MRAD','M95','REC7'],
 'barrett.net', 'Murfreesboro, TN'),

('Bushmaster',
 ARRAY['Bushmaster Firearms'],
 'USA', 1978, true,
 ARRAY['Rifle'],
 'Cerberus Capital / Remington Outdoor', NULL,
 'American AR-15 manufacturer. Once one of the largest AR-15 producers in the US. Now under new ownership after Remington Outdoor bankruptcy.',
 ARRAY['XM-15','Carbon 15','ACR'],
 'bushmaster.com', 'Ilion, NY'),

('DPMS',
 ARRAY['DPMS Panther Arms','Defense Procurement Manufacturing Services'],
 'USA', 1986, true,
 ARRAY['Rifle'],
 'Remington Outdoor', NULL,
 'Minnesota manufacturer of AR-15 and AR-10/LR-308 platform rifles. Known for value-priced builds and popularizing the AR-10 commercial market.',
 ARRAY['Panther Oracle','G2 RECON','Prairie Panther'],
 'dpmsinc.com', 'St. Cloud, MN'),

('Windham Weaponry',
 ARRAY['WWC'],
 'USA', 2011, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Founded by former Bushmaster employees in Maine after the Cerberus buyout. Produces made-in-Maine AR-15 rifles with a focus on American craftsmanship.',
 ARRAY['SRC','CDI','R16M4FTT'],
 'windhamweaponry.com', 'Windham, ME'),

('Stag Arms',
 ARRAY['Stag'],
 'USA', 2003, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Connecticut manufacturer known for left-handed AR-15 configurations (a specialty not offered by most AR makers). Also produces right-hand models.',
 ARRAY['Stag 15','Stag 10','Pursuit'],
 'stagarms.com', 'New Britain, CT'),

('Palmetto State Armory',
 ARRAY['PSA'],
 'USA', 2008, true,
 ARRAY['Handgun','Rifle','Accessories'],
 NULL, NULL,
 'South Carolina manufacturer and retailer offering budget-friendly AR-15 parts and complete rifles. Known for aggressive pricing and regular sales.',
 ARRAY['PA-15','Dagger','AKV','AR-V'],
 'palmettostatearmory.com', 'Columbia, SC'),

('Aero Precision',
 ARRAY['Aero'],
 'USA', 1994, true,
 ARRAY['Rifle','Accessories'],
 NULL, NULL,
 'Washington state manufacturer of AR-15 and AR-10 components and complete rifles. Popular for quality at mid-tier pricing. Also manufactures for aerospace industry.',
 ARRAY['M4E1','M5','SOLUS','M16A4'],
 'aeroprecisionusa.com', 'Tacoma, WA'),

('CMMG',
 ARRAY['Brownells CMMG'],
 'USA', 2002, true,
 ARRAY['Rifle','Accessories'],
 NULL, NULL,
 'Missouri manufacturer known for the Banshee series of compact AR-pattern pistol caliber carbines and standard AR-15/AR-10 rifles.',
 ARRAY['Banshee 9mm','Resolute','Mk47 Mutant'],
 'cmmginc.com', 'Fayette, MO'),

('Christensen Arms',
 ARRAY['Christensen'],
 'USA', 1995, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Utah manufacturer producing carbon fiber-barreled bolt-action rifles. Known for lightweight hunting and precision rifle competition builds.',
 ARRAY['Mesa','Ridgeline','MPR','Modern Hunting Rifle'],
 'christensenarms.com', 'Gunnison, UT'),

('Proof Research',
 ARRAY['PROOF','Proof'],
 'USA', 2012, true,
 ARRAY['Rifle','Accessories'],
 NULL, NULL,
 'Montana manufacturer of carbon fiber wrapped barrels and complete precision rifles. Barrels are known for exceptional accuracy and light weight.',
 ARRAY['Glacier','Summit','Elevation','Tundra'],
 'proofresearch.com', 'Columbia Falls, MT'),

('Accuracy International',
 ARRAY['AI','AICS'],
 'UK', 1978, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'British manufacturer of the AI Arctic Warfare (AW) series sniper rifles. Standard issue or adopted by military/police forces in over 50 countries.',
 ARRAY['AXMC','AX308','AT','AW','AICS Chassis'],
 'accuracy-international.com', 'Portsmouth, UK'),

('Tikka',
 ARRAY['Tikka Rifles'],
 'Finland', 1893, true,
 ARRAY['Rifle'],
 'Beretta Holding', NULL,
 'Finnish manufacturer of bolt-action hunting and target rifles. Subsidiary of Sako, itself owned by Beretta. Known for exceptional accuracy at competitive prices.',
 ARRAY['T3x Lite','T3x CTR','T3x TAC A1','T1x MTR'],
 'tikka.fi', 'Riihimäki, Finland'),

('Sako',
 ARRAY['Sako Ltd'],
 'Finland', 1921, true,
 ARRAY['Rifle'],
 'Beretta Holding', ARRAY['Tikka'],
 'Finnish premium bolt-action rifle manufacturer owned by Beretta. Known for exceptional quality and the proprietary Sako action design.',
 ARRAY['S20','85 Hunter','TRG 22','TRG 42','Carbonlight'],
 'sako.fi', 'Riihimäki, Finland'),

('Steyr Arms',
 ARRAY['Steyr Mannlicher','Steyr','Steyr-Daimler-Puch'],
 'Austria', 1864, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Historic Austrian manufacturer known for the AUG bullpup rifle and the Steyr Scout bolt-action. Also produces the L9-A2 pistol series.',
 ARRAY['AUG','Scout','Pro Hunter','L9-A2','HS .50'],
 'steyr-arms.com', 'Kleinraming, Austria'),

('Blaser',
 ARRAY['Blaser Jagdwaffen'],
 'Germany', 1957, true,
 ARRAY['Rifle','Shotgun'],
 'Blaser Group', ARRAY['Sauer','Mauser'],
 'German manufacturer of premium hunting and sporting rifles. Known for the R8 straight-pull bolt-action and modular rifle systems.',
 ARRAY['R8','F3','LRS2','HHS 2'],
 'blaser.de', 'Isny im Allgäu, Germany'),

('Sauer',
 ARRAY['J.P. Sauer & Sohn','Sauer & Sohn'],
 'Germany', 1751, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 'Blaser Group', NULL,
 'One of Germany''s oldest firearms makers. The Sauer 100 and 404 bolt rifles are known for precision. Also the historical partner in Sig Sauer (now separate companies).',
 ARRAY['Sauer 100','Sauer 404','S 101'],
 'sauer.de', 'Eckernförde, Germany'),

('Anschutz',
 ARRAY['J.G. Anschütz','Anschutz'],
 'Germany', 1856, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'German manufacturer of Olympic-grade rimfire and centerfire target rifles. The Anschutz 1907 and 2013 are dominant in Olympic biathlon and smallbore competition.',
 ARRAY['1907','1710','2013','1416','64 MP'],
 'anschuetz-sport.com', 'Ulm, Germany'),

('IWI',
 ARRAY['Israel Weapon Industries','IMI','Israeli Military Industries'],
 'Israel', 1933, true,
 ARRAY['Handgun','Rifle','Accessories'],
 NULL, NULL,
 'Israeli manufacturer formerly known as IMI (Israel Military Industries). Produces the Tavor bullpup series, Galil ACE, and Jericho pistols.',
 ARRAY['Tavor X95','Tavor 7','Galil ACE','Zion-15','Masada'],
 'iwi.us', 'Ramat HaSharon, Israel'),

('Desert Tech',
 ARRAY['DT','Desert Technologies'],
 'USA', 2007, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Utah manufacturer of premium bullpup bolt-action and semi-auto rifles. The SRS A2 is a top-tier precision bolt gun favored in PRS competition.',
 ARRAY['SRS A2','MDRX','HTI','SRS A2 Covert'],
 'deserttech.com', 'St. George, UT'),

('Armalite',
 ARRAY['AR','ArmaLite'],
 'USA', 1954, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Original designer of the AR-10 and AR-15 rifles (later sold to Colt). Currently produces AR-10 (AR-10B) and AR-15 pattern rifles.',
 ARRAY['AR-10','AR-15','AR-30','AR-50','M15'],
 'armalite.com', 'Geneseo, IL'),

('Savage Arms',
 ARRAY['Savage','Savage Stevens'],
 'USA', 1894, true,
 ARRAY['Rifle','Shotgun'],
 'Vista Outdoor', NULL,
 'Massachusetts-turned-Connecticut manufacturer known for accurate bolt-action rifles with the AccuTrigger system. Also produces the Axis entry-level series.',
 ARRAY['110','Axis','Mark II','A22','64','Model 12','110 Precision'],
 'savagearms.com', 'Westfield, MA'),

-- ── SHOTGUN MAKERS ─────────────────────────────────────────────────────────────

('Benelli',
 ARRAY['Benelli Armi'],
 'Italy', 1967, true,
 ARRAY['Shotgun'],
 'Beretta Holding', NULL,
 'Italian manufacturer of premium semi-automatic and pump shotguns. The inertia-driven system is Benelli''s proprietary mechanism known for reliability.',
 ARRAY['M4','M2','SBE3','Nova','SuperNova','Ethos'],
 'benelliusa.com', 'Urbino, Italy'),

('Mossberg',
 ARRAY['O.F. Mossberg & Sons','O.F. Mossberg'],
 'USA', 1919, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 NULL, NULL,
 'America''s oldest family-owned firearms manufacturer. The Model 500 pump shotgun has been in production since 1960 and is one of the most popular shotguns ever made.',
 ARRAY['500','590','590A1','930','MC1sc','Patriot','MVP'],
 'mossberg.com', 'North Haven, CT'),

('Remington',
 ARRAY['Remington Arms','Remington Outdoor','Big Green'],
 'USA', 1816, true,
 ARRAY['Handgun','Rifle','Shotgun','Ammo'],
 'RemArms', NULL,
 'America''s oldest gun maker, founded by Eliphalet Remington. After bankruptcy, remade as RemArms. Famous for the 870 shotgun (over 11 million made) and the Model 700 rifle.',
 ARRAY['870','1100','700','783','RP9'],
 'remington.com', 'Ilion, NY'),

('Winchester Repeating Arms',
 ARRAY['Winchester','USRAC'],
 'USA', 1866, true,
 ARRAY['Rifle','Shotgun'],
 'FN Herstal / Olin (ammo)', NULL,
 'Iconic American manufacturer founded from the Volcanic Repeating Arms lineage. The Model 1873 "Gun That Won The West" and Model 70 are legendary. Firearms made by Miroku in Japan.',
 ARRAY['Model 70','Model 94','SXP','SX4','1873','1892'],
 'winchesterguns.com', 'New Haven, CT'),

('Browning',
 ARRAY['Browning Arms','BAC'],
 'USA', 1927, true,
 ARRAY['Rifle','Shotgun','Handgun'],
 'FN Herstal', NULL,
 'Named for the legendary designer John Moses Browning. Produces hunting rifles and shotguns, mostly manufactured in Japan by Miroku. The Maxus and Citori are flagship products.',
 ARRAY['Citori','Maxus II','X-Bolt','BPS','BAR MK3'],
 'browning.com', 'Morgan, UT'),

('Fabarm',
 ARRAY['Fabbrica Bresciana Armi'],
 'Italy', 1900, true,
 ARRAY['Shotgun'],
 NULL, NULL,
 'Italian manufacturer of quality semi-automatic and over/under shotguns. The L4S and XLR5 semi-autos are popular in the 3-Gun competition community.',
 ARRAY['L4S','XLR5','ELOS N2','Axis RS'],
 'fabarm.com', 'Travagliato, Italy'),

('TriStar',
 ARRAY['TriStar Sporting Arms'],
 'USA', 1994, true,
 ARRAY['Shotgun','Handgun'],
 NULL, NULL,
 'Missouri-based importer of Turkish-made shotguns and pistols. Offers budget-friendly options across pump, semi-auto, and over/under categories.',
 ARRAY['Viper G2','Raptor','Hunter Ex','TEC-12'],
 'tristarsportingarms.com', 'N. Kansas City, MO'),

('Stoeger',
 ARRAY['Stoeger Industries'],
 'USA', 1924, true,
 ARRAY['Shotgun','Handgun'],
 'Beretta Holding', NULL,
 'Value-brand subsidiary of Beretta Holding. Produces affordable shotguns, including the popular Condor O/U and Coach Gun. Also imports Cougar pistols.',
 ARRAY['M3000','P3000','Condor','Coach Gun','Cougar'],
 'stoegerindustries.com', 'Accokeek, MD'),

('Weatherby',
 ARRAY['Weatherby Inc'],
 'USA', 1945, true,
 ARRAY['Rifle','Shotgun'],
 NULL, NULL,
 'Founded by Roy Weatherby. Known for proprietary magnum cartridges and premium hunting rifles. The Mark V and Vanguard bolt-action series are core products.',
 ARRAY['Mark V','Vanguard','SA-08','Orion'],
 'weatherby.com', 'Sheridan, WY'),

-- ── HISTORICAL & HERITAGE ──────────────────────────────────────────────────────

('Winchester (historical)',
 ARRAY['Winchester Repeating Arms Company','New Haven Arms'],
 'USA', 1866, false,
 ARRAY['Rifle','Shotgun'],
 'Olin Corporation', NULL,
 'The original Winchester Repeating Arms Company operated from 1866 to 1981. Produced the iconic 1873, 1894, and Model 70. Firearms operations sold to USRAC; ammo retained by Olin.',
 ARRAY['Model 1873','Model 1894','Model 70','Model 12','Model 97'],
 NULL, 'New Haven, CT'),

('Marlin',
 ARRAY['Marlin Firearms','Marlin Firearms Co.'],
 'USA', 1870, true,
 ARRAY['Rifle','Shotgun'],
 'Ruger', NULL,
 'Connecticut maker of lever-action rifles, now owned by Ruger. The Model 336 (30-30) and Model 1895 (45-70) are classic American deer guns. Ruger restarted production after Remington bankruptcy.',
 ARRAY['Model 336','Model 1895','Model 1894','Golden 39A','XT-22'],
 'marlinfirearms.com', 'Madison, NC'),

('Henry Repeating Arms',
 ARRAY['Henry','Henry Rifles'],
 'USA', 1996, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'New Jersey-based manufacturer of American-made lever-action rifles. The Big Boy and Golden Boy series are popular. All manufacturing in USA; no imported parts.',
 ARRAY['Big Boy','Golden Boy','Long Ranger','X Model','Big Boy Steel'],
 'henryusa.com', 'Bayonne, NJ'),

('Ithaca Gun',
 ARRAY['Ithaca','Ithaca Guns'],
 'USA', 1883, true,
 ARRAY['Shotgun'],
 NULL, NULL,
 'Historic New York shotgun maker. The Model 37 pump shotgun remains in production. Known for historical prestige and classic American craftsmanship.',
 ARRAY['Model 37','Model 37 Defense','NID'],
 'ithacagun.com', 'Upper Sandusky, OH'),

('Webley & Scott',
 ARRAY['Webley','Webley Revolvers'],
 'UK', 1790, true,
 ARRAY['Handgun','Shotgun'],
 NULL, NULL,
 'British manufacturer best known for the Webley Revolver, standard British military sidearm from 1887 to World War II. Now produces air guns and shotguns.',
 ARRAY['Webley Mk VI','Webley Fosbery','Scott 835'],
 'webley.co.uk', 'Birmingham, UK'),

('Mauser',
 ARRAY['Mauser-Werke','Paul Mauser','Mauser Jagdwaffen'],
 'Germany', 1811, true,
 ARRAY['Rifle','Handgun'],
 'Blaser Group', NULL,
 'Historic German manufacturer with roots to 1811. The Mauser 98 bolt-action is the most influential rifle action in history. Now produces the M18 and M98 hunting rifles.',
 ARRAY['M98','M18','98 Magnum','Karabiner 98k','C96'],
 'mauser.com', 'Isny im Allgäu, Germany'),

-- ── INTERNATIONAL MANUFACTURERS ───────────────────────────────────────────────

('Zastava Arms',
 ARRAY['Zastava','ZPAP'],
 'Serbia', 1853, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Serbian state-owned arms manufacturer. Produces AK-pattern rifles (ZPAP M70, M91) and CZ99/EZ9 pistols imported into the US through Century Arms.',
 ARRAY['ZPAP M70','ZPAP M92','EZ9','CZ99'],
 'zastava-arms.com', 'Kragujevac, Serbia'),

('Arsenal Inc',
 ARRAY['Arsenal','Arsenal Arms'],
 'USA', 1992, true,
 ARRAY['Rifle'],
 'Arsenal AD (Bulgaria)', NULL,
 'US importer and manufacturer of Bulgarian-made AK-pattern rifles. Known for high-quality milled and stamped AK receivers.',
 ARRAY['SLR-107','SLR-106','SAM7','SAS M-7'],
 'arsenalinc.us', 'Las Vegas, NV'),

('Century Arms',
 ARRAY['Century International Arms','CAI'],
 'USA', 1961, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 NULL, NULL,
 'Vermont importer and manufacturer of surplus and commercial firearms. Produces AK-pattern, AR-pattern, and pistols under the VSKA, C39v2, and Canik (imported) brands.',
 ARRAY['VSKA','C39v2','RAS47','BFT47'],
 'centuryarms.com', 'Delray Beach, FL'),

('Pioneer Arms',
 ARRAY['Pioneer'],
 'Poland', 1922, true,
 ARRAY['Rifle'],
 NULL, NULL,
 'Polish manufacturer of AK-pattern rifles using original Polish Radom factory tooling. Imported via Inter Ordnance. Known for quality Polish-spec AKs.',
 ARRAY['Hellpup','Sporter','Forged Receiver Sporter'],
 'pioneerarms.pl', 'Radom, Poland'),

('Kalashnikov Concern',
 ARRAY['IZHMASH','Kalashnikov','IzhMash'],
 'Russia', 1807, true,
 ARRAY['Rifle','Handgun','Shotgun'],
 'Rostec', NULL,
 'Russian state manufacturer and original producer of the AK-47 and its descendants. Also produces the Saiga series shotguns. Currently under US sanctions.',
 ARRAY['AK-47','AK-74','AK-12','Saiga-12','MP-443'],
 'kalashnikov.com', 'Izhevsk, Russia'),

-- ── ADDITIONAL HANDGUN / SPECIALTY ─────────────────────────────────────────────

('Rock River Arms',
 ARRAY['RRA'],
 'USA', 1996, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Illinois manufacturer of AR-15/AR-10 and 1911 platform firearms. Known for the LAR-15 series and custom 1911 builds.',
 ARRAY['LAR-15','LAR-8','1911 A1','ATH Carbine'],
 'rockriverarms.com', 'Colona, IL'),

('Magnum Research',
 ARRAY['Desert Eagle','MRI'],
 'USA', 1979, true,
 ARRAY['Handgun','Rifle'],
 'Kahr Arms', NULL,
 'American designer of the iconic Desert Eagle pistol (manufactured by IWI in Israel) and the BFR revolver. The Desert Eagle is one of the most recognized handguns in popular culture.',
 ARRAY['Desert Eagle','Baby Eagle','BFR','Micro Desert Eagle'],
 'magnumresearch.com', 'Pillager, MN'),

('Uberti',
 ARRAY['A. Uberti','Uberti 1873'],
 'Italy', 1959, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 'Beretta Holding', NULL,
 'Italian manufacturer of high-quality reproduction firearms — primarily Colt Single Action Army revolvers and Winchester 1873/1886/1892 lever actions.',
 ARRAY['1873 Cattleman','1873 Single Action','1866 Yellowboy','El Patron'],
 'ubertireplicas.com', 'Gardone Val Trompia, Italy'),

('Taurus Judge (listed under Taurus)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

('Kel-Tec KSG (listed under Kel-Tec)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

('Rossi',
 ARRAY['Amadeo Rossi','BrazTech'],
 'Brazil', 1889, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 'Forjas Taurus', NULL,
 'Brazilian manufacturer of revolvers, lever-action rifles, and single-shot firearms. Now a standalone brand after separating from Taurus. The R92 lever-action is popular.',
 ARRAY['R92','RP63','Rio','Model 461'],
 'rossiusa.com', 'São Leopoldo, Brazil'),

('Inland Manufacturing',
 ARRAY['Inland','Inland Mfg'],
 'USA', 2012, true,
 ARRAY['Handgun','Rifle'],
 NULL, NULL,
 'Modern Dayton, Ohio manufacturer producing reproductions of the M1 Carbine and 1911A1 pistol — homage to the original WWII-era Inland Division of General Motors.',
 ARRAY['M1 Carbine','M1 Scout','1911A1 Service'],
 'inland-mfg.com', 'Dayton, OH'),

('Charles Daly',
 ARRAY['Chiappa Charlie Daly','Daly'],
 'USA', 1976, true,
 ARRAY['Handgun','Rifle','Shotgun'],
 NULL, NULL,
 'American importer of Turkish-made shotguns and Filipino/Turkish pistols. The 1911 and AR-pattern imports offer budget-friendly options.',
 ARRAY['1911','300','Triple Threat','AR-12S'],
 'charlesdaly.com', 'Harrisburg, PA'),

('ZEV Technologies',
 ARRAY['ZEV','Zev Tech'],
 'USA', 2010, true,
 ARRAY['Handgun','Rifle','Accessories'],
 NULL, NULL,
 'California manufacturer of custom Glock parts, complete pistols, and AR-platform rifles. Popular for competitive shooting upgrades.',
 ARRAY['OZ9','OZ9C','OZ9 Elite','AR Billet'],
 'zevtechnologies.com', 'Oxnard, CA'),

('Shadow Systems',
 ARRAY['Shadow Systems Corp','SSC'],
 'USA', 2016, true,
 ARRAY['Handgun'],
 NULL, NULL,
 'Texas manufacturer of Glock-compatible MR920 and CR920 pistols with upgraded features from the factory. Popular carry option.',
 ARRAY['MR920','CR920','DR920'],
 'shadowsystemscorp.com', 'Plano, TX'),

('Polymer80',
 ARRAY['P80','Poly80'],
 'USA', 2012, true,
 ARRAY['Handgun','Accessories'],
 NULL, NULL,
 'Nevada-based manufacturer of 80% pistol frames (Glock-compatible) and complete PF-series pistols. Subject of ongoing ATF regulatory scrutiny.',
 ARRAY['PF940C','PF940v2','PF9SS','PFC9'],
 'polymer80.com', 'Dayton, NV'),

('Taran Tactical',
 ARRAY['TTI','Taran Tactical Innovations'],
 'USA', 2009, true,
 ARRAY['Handgun','Accessories'],
 NULL, NULL,
 'California competition shooting shop run by world champion shooter Taran Butler. Known for high-end Glock, STI/Staccato, and shotgun competition builds.',
 ARRAY['JW3 Combat Master','Pit Viper','BattleHook'],
 'tarantacticalinnovations.com', 'Simi Valley, CA'),

('Gemtech',
 ARRAY['GEMTECH'],
 'USA', 1993, true,
 ARRAY['Suppressors','Accessories'],
 'Smith & Wesson / American Outdoor Brands', NULL,
 'Idaho manufacturer of suppressors (silencers) for pistols, rifles, and shotguns. One of the oldest and most respected names in the suppressor market.',
 ARRAY['LUNAR 45','ONE','GM-45','Trek'],
 'gemtech.com', 'Boise, ID'),

('SilencerCo',
 ARRAY['Silencer Co','SilCo'],
 'USA', 2008, true,
 ARRAY['Suppressors','Handgun','Accessories'],
 NULL, NULL,
 'Utah manufacturer of suppressors and the Maxim 9 integrally suppressed pistol. Leading innovator in the commercial suppressor market.',
 ARRAY['Omega 36M','Harvester 338','Hybrid 46','Maxim 9','Osprey 45'],
 'silencerco.com', 'West Valley City, UT'),

('Dead Air',
 ARRAY['Dead Air Armament'],
 'USA', 2014, true,
 ARRAY['Suppressors'],
 NULL, NULL,
 'Tennessee manufacturer of premium suppressors. The Sandman series for rifles and Mask for .22 are well-regarded for build quality and customer service.',
 ARRAY['Sandman-S','Sandman-L','Ghost-M','Mask','Wolfman'],
 'deadairsilencers.com', 'Morristown, TN'),

('Rugged Suppressors',
 ARRAY['Rugged'],
 'USA', 2014, true,
 ARRAY['Suppressors'],
 NULL, NULL,
 'Arkansas suppressor manufacturer with a reputation for robust, modular designs. The Obsidian 45 is one of the most versatile pistol suppressors available.',
 ARRAY['Obsidian 45','Surge 762','Razor 762'],
 'ruggedsuppressors.com', 'Benton, AR'),

('LaFrance Specialties',
 ARRAY['LaFrance'],
 'USA', 1981, false,
 ARRAY['Rifle','Accessories'],
 NULL, NULL,
 'San Diego custom shop known for the LAR Grizzly and M16K compact conversions. Now defunct.',
 ARRAY['LAR Grizzly','M16K'],
 NULL, 'San Diego, CA'),

('Detonics',
 ARRAY['Detonics Combat Handguns'],
 'USA', 1976, false,
 ARRAY['Handgun'],
 NULL, NULL,
 'Original American manufacturer of compact 1911-pattern pistols. Pioneered the compact 1911 concept. Went bankrupt; brand later revived briefly.',
 ARRAY['Combat Master','ScoreMaster'],
 NULL, 'Bellevue, WA'),

('Auto-Ordnance',
 ARRAY['Auto Ordnance'],
 'USA', 1919, true,
 ARRAY['Handgun','Rifle'],
 'Kahr Arms', NULL,
 'Originally designed the Thompson submachine gun. Now owned by Kahr Arms, producing semi-automatic Thompson reproductions and 1911 pistols.',
 ARRAY['Thompson M1','Tommy Gun','1911 WWII'],
 'auto-ordnance.com', 'Worcester, MA'),

('Traditions Firearms',
 ARRAY['Traditions'],
 'USA', 1987, true,
 ARRAY['Rifle','Handgun'],
 NULL, NULL,
 'Connecticut importer of muzzleloaders and reproduction black powder firearms, as well as modern centerfire rifles.',
 ARRAY['Buckstalker','Nitrofire','Pursuit XT'],
 'traditionsfirearms.com', 'Old Saybrook, CT')

ON CONFLICT (name) DO NOTHING;

-- Remove placeholder rows inserted for structural reasons
DELETE FROM public.manufacturers WHERE description IS NULL AND website IS NULL AND country_of_origin IS NULL;
