-- Gun models for manufacturers L through Z (batch 3 of 3)

INSERT INTO public.gun_models (
  make, model, caliber, type, action, capacity, year_introduced,
  discontinued, country_of_origin, description, msrp_usd,
  weight_oz_unloaded, overall_length_in, military_use, law_enforcement_use,
  notable_variants, production_status, platform_family, caliber_options,
  model_aliases, era, trigger_type, intended_use, trivia,
  country_of_manufacture, is_collectible, collector_notes
) VALUES

-- LLAMA
('Llama', 'Micromax', '.380 ACP', 'Pistol', 'Semi-Auto', 7, 1960, true, 'Spain',
 'Spanish compact semi-auto pistol based on Colt 1911 design, scaled down for .380 ACP.',
 NULL, 23.0, 6.5, false, false,
 ARRAY['Micromax 380', 'Minimax'],
 'Discontinued', 'Llama Micromax', ARRAY['.380 ACP', '.32 ACP'],
 ARRAY['micromax', 'llama 380', 'llama minimax'], 'Cold War', 'Single-Action', ARRAY['concealed carry', 'collector'],
 NULL, 'Spain', true, 'Spanish-made 1911-pattern pistols. Quality declined after the 1980s.'),

('Llama', 'Omni', '9mm Luger', 'Pistol', 'Semi-Auto', 13, 1982, true, 'Spain',
 'Double-action 9mm with double-column magazine. One of the first Spanish DA service pistols.',
 NULL, 32.0, 7.7, false, false, ARRAY['Omni standard'],
 'Discontinued', 'Llama Omni', ARRAY['9mm Luger', '.45 ACP'],
 ARRAY['omni', 'llama omni'], 'Cold War', 'Double-Action', ARRAY['home defense', 'collector'],
 NULL, 'Spain', true, NULL),

('Llama', 'MAX-I', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1995, true, 'Spain',
 'Full-size 1911-pattern .45 ACP pistol, last major Llama design before company closure.',
 NULL, 34.0, 8.5, false, false,
 ARRAY['MAX-I Compact', 'MAX-I .38 Super'],
 'Discontinued', 'Llama MAX', ARRAY['.45 ACP', '.38 Super', '9mm Luger'],
 ARRAY['max-i', 'llama max', 'llama 45'], 'Post-Cold War', 'Single-Action', ARRAY['home defense', 'collector'],
 NULL, 'Spain', true, NULL),

-- LORCIN ENGINEERING
('Lorcin Engineering', 'L-9', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 1991, true, 'United States',
 'Budget zinc alloy 9mm pocket pistol. Ring of Fire manufacturer.',
 NULL, 26.0, 6.0, false, false, ARRAY['L-9 standard'],
 'Discontinued', 'Lorcin L', ARRAY['9mm Luger'],
 ARRAY['l9', 'lorcin 9mm'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 'Lorcin was the highest-volume US pistol maker by units in 1993, selling primarily SNS guns.',
 'United States', false, NULL),

('Lorcin Engineering', 'L-380', '.380 ACP', 'Pistol', 'Semi-Auto', 7, 1989, true, 'United States',
 'Budget .380 ACP pocket pistol. Among the highest-volume US pistols in the early 1990s.',
 NULL, 23.0, 6.0, false, false, ARRAY['L-380 standard'],
 'Discontinued', 'Lorcin L', ARRAY['.380 ACP'],
 ARRAY['l380', 'lorcin 380'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

('Lorcin Engineering', 'L-25', '.25 ACP', 'Pistol', 'Semi-Auto', 7, 1989, true, 'United States',
 'Budget .25 ACP pocket pistol.',
 NULL, 13.0, 4.8, false, false, ARRAY['L-25 standard'],
 'Discontinued', 'Lorcin L', ARRAY['.25 ACP'],
 ARRAY['l25', 'lorcin 25'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

-- MKE
('MKE', 'T94', '9mm Luger', 'Rifle', 'Semi-Auto', 30, 1994, false, 'Turkey',
 'Turkish MP5 clone made by the state arms factory. Semi-auto version exported commercially.',
 NULL, 52.0, 19.0, false, true,
 ARRAY['T94 semi-auto', 'T94 select-fire'],
 'Active', 'MKE T94', ARRAY['9mm Luger'],
 ARRAY['t94', 'mke mp5', 'turkish mp5'], 'Post-Cold War', 'Trigger', ARRAY['law enforcement', 'military'],
 'MKE is the Turkish state arsenal — produces small arms for the Turkish military under license.',
 'Turkey', false, NULL),

('MKE', 'Kirikkale', '9x18mm Makarov', 'Pistol', 'Semi-Auto', 7, 1950, false, 'Turkey',
 'Turkish-made Walther PP clone. The standard Turkish military and police sidearm for decades.',
 350, 22.0, 6.7, false, true,
 ARRAY['Kirikkale commercial', 'Kirikkale 9mm Luger conversion'],
 'Active', 'MKE Kirikkale', ARRAY['9x18mm Makarov', '9mm Luger'],
 ARRAY['kirikkale', 'mke kirikkale', 'turkish pp'], 'Cold War', 'Double-Action', ARRAY['military', 'collector'],
 NULL, 'Turkey', false, NULL),

('MKE', 'AT-94', '9mm Luger', 'Rifle', 'Semi-Auto', 30, 2000, false, 'Turkey',
 'Updated MKE MP5 derivative with improved ergonomics and rail system.',
 NULL, 55.0, 21.0, false, true, ARRAY['AT-94 standard'],
 'Active', 'MKE AT', ARRAY['9mm Luger'],
 ARRAY['at94', 'mke at94'], 'Modern', 'Trigger', ARRAY['law enforcement', 'military'],
 NULL, 'Turkey', false, NULL),

-- MANURHIN
('Manurhin', 'MR 73', '.357 Magnum', 'Revolver', 'Double-Action', 6, 1973, false, 'France',
 'French precision revolver used by the GIGN. Considered among the finest production revolvers ever made.',
 3500, 35.0, 8.4, false, true,
 ARRAY['MR 73 Sport 6"', 'MR 73 Sport 4"', 'MR 73 Gendarmerie'],
 'Active', 'Manurhin MR 73', ARRAY['.357 Magnum', '.38 Special'],
 ARRAY['mr73', 'manurhin mr73', 'gign revolver'], 'Modern', 'Double-Action', ARRAY['law enforcement', 'competition', 'collector'],
 'The GIGN used the MR 73 in the 1994 Air France hostage rescue. Elite units still train with it.',
 'France', true, 'Extremely well-made and sought by collectors. Strong appreciation value.'),

('Manurhin', 'MR 96', '.357 Magnum', 'Revolver', 'Double-Action', 6, 1996, false, 'France',
 'Updated MR 73 with swing-out cylinder for faster reloading.',
 2800, 36.0, 9.0, false, false,
 ARRAY['MR 96 Sport', 'MR 96 Combat'],
 'Active', 'Manurhin MR 96', ARRAY['.357 Magnum', '.38 Special'],
 ARRAY['mr96', 'manurhin mr96'], 'Modern', 'Double-Action', ARRAY['competition', 'law enforcement'],
 NULL, 'France', true, NULL),

('Manurhin', 'PP Walther Licensed', '.32 ACP', 'Pistol', 'Semi-Auto', 8, 1952, true, 'France',
 'Manurhin-produced Walther PP under license. Made for French military and police.',
 NULL, 23.0, 6.7, false, true, ARRAY['Manurhin PP', 'Manurhin PPK'],
 'Discontinued', 'Manurhin PP', ARRAY['.32 ACP', '.380 ACP'],
 ARRAY['manurhin pp', 'french pp', 'manurhin ppk'], 'Cold War', 'Double-Action', ARRAY['military', 'collector'],
 'Manurhin produced Walther PPs for France while Walther''s German factory was rebuilding post-WWII.',
 'France', true, 'Collector interest for French police and military marked examples.'),

-- MASTERPIECE ARMS
('MasterPiece Arms', 'MPA30', '9mm Luger', 'Pistol', 'Semi-Auto', 30, 2004, false, 'United States',
 'Side-cocking MAC-10 pattern pistol in 9mm. American-made semi-auto.',
 399, 51.0, 11.0, false, false,
 ARRAY['MPA30 Side Cocker', 'MPA30T (top cocker)'],
 'Active', 'MPA MPA30', ARRAY['9mm Luger'],
 ARRAY['mpa30', 'masterpiece 30', 'mac clone 9mm'], 'Modern', 'Trigger', ARRAY['home defense'],
 NULL, 'United States', false, NULL),

('MasterPiece Arms', 'BA Lite', '.308 Winchester', 'Rifle', 'Bolt-Action', 5, 2015, false, 'United States',
 'Chassis precision rifle built around the Remington 700 action footprint.',
 1299, 90.0, 43.0, false, false,
 ARRAY['BA Lite 6.5 Creedmoor', 'BA Comp'],
 'Active', 'MPA BA Lite', ARRAY['.308 Winchester', '6.5 Creedmoor', '6mm Creedmoor'],
 ARRAY['ba lite', 'mpa ba lite'], 'Modern', 'Trigger', ARRAY['competition', 'hunting'],
 NULL, 'United States', false, NULL),

('MasterPiece Arms', 'DS9 Competition', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2018, false, 'United States',
 'Polymer frame competition pistol for USPSA and IDPA.',
 799, 28.0, 5.5, false, false,
 ARRAY['DS9 Hybrid', 'DS9 Commander'],
 'Active', 'MPA DS9', ARRAY['9mm Luger'],
 ARRAY['ds9', 'mpa ds9'], 'Modern', 'Striker-Fired', ARRAY['competition'],
 NULL, 'United States', false, NULL),

-- MATEBA
('Mateba', 'Autorevolver', '.357 Magnum', 'Revolver', 'Semi-Auto', 6, 1997, true, 'Italy',
 'Semi-automatic revolver — the cylinder rotates and the action cocks using recoil energy. One of the most unusual revolvers ever made.',
 NULL, 40.0, 9.0, false, false,
 ARRAY['Autorevolver 357', 'Autorevolver 44 Magnum', 'Unica 6'],
 'Discontinued', 'Mateba Autorevolver', ARRAY['.357 Magnum', '.44 Magnum', '.454 Casull'],
 ARRAY['autorevolver', 'mateba unica', 'mateba 357'], 'Modern', 'Single-Action', ARRAY['collector'],
 'Fires from the bottom chamber (6 o''clock position) instead of the top — reduces muzzle flip by lowering bore axis.',
 'Italy', true, 'Among the most collectible modern Italian firearms. Extremely rare and rising in value.'),

('Mateba', 'MTR-8', '.38 Special', 'Revolver', 'Double-Action', 8, 1983, true, 'Italy',
 'Conventional double-action revolver with 8-shot cylinder, predecessor to the Autorevolver.',
 NULL, 32.0, 8.5, false, false, ARRAY['MTR-8 standard'],
 'Discontinued', 'Mateba MTR', ARRAY['.38 Special'],
 ARRAY['mtr8', 'mateba 38'], 'Post-Cold War', 'Double-Action', ARRAY['collector'],
 NULL, 'Italy', true, NULL),

('Mateba', '6 Unica', '.357 Magnum', 'Revolver', 'Semi-Auto', 6, 1999, true, 'Italy',
 'Updated Autorevolver with improvements to the semi-automatic mechanism.',
 NULL, 40.0, 9.0, false, false, ARRAY['Unica 6 standard', 'Unica 6 carbine'],
 'Discontinued', 'Mateba Autorevolver', ARRAY['.357 Magnum', '.44 Magnum'],
 ARRAY['unica 6', 'mateba unica 6'], 'Modern', 'Single-Action', ARRAY['collector'],
 NULL, 'Italy', true, 'Extremely collectible. Carbine variant with shoulder stock is especially rare.'),

-- MAVERICK ARMS
('Maverick Arms', 'Model 88', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 1989, false, 'United States',
 'Budget pump shotgun based on the Mossberg 500 design. Made by Mossberg''s subsidiary.',
 249, 60.0, 40.0, false, false,
 ARRAY['Model 88 All Purpose', 'Model 88 Slug', 'Model 88 Security'],
 'Active', 'Maverick 88', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['model 88', 'maverick 88', 'mav 88'], 'Modern', 'Trigger', ARRAY['hunting', 'home defense'],
 'The Maverick 88 is mechanically identical to the Mossberg 500 but made with cost savings.',
 'United States', false, NULL),

('Maverick Arms', 'Model 91', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 1991, true, 'United States',
 'Pump-action shotgun based on the Remington 870, made by Maverick under a brief licensing period.',
 NULL, 62.0, 40.0, false, false, ARRAY['Model 91 standard'],
 'Discontinued', 'Maverick 91', ARRAY['12 Gauge'],
 ARRAY['model 91', 'maverick 91'], 'Post-Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'United States', false, NULL),

('Maverick Arms', 'Model 88 Security', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 1995, false, 'United States',
 'Home defense variant of the Model 88 with 18.5" barrel and cylinder bore.',
 249, 58.0, 38.0, false, false,
 ARRAY['Model 88 Security 8-shot', 'Model 88 Security pistol grip'],
 'Active', 'Maverick 88', ARRAY['12 Gauge'],
 ARRAY['88 security', 'maverick security'], 'Modern', 'Trigger', ARRAY['home defense'],
 NULL, 'United States', false, NULL),

-- MCMILLAN FIREARMS
('McMillan Firearms', 'TAC-50', '.50 BMG', 'Rifle', 'Bolt-Action', 5, 1987, false, 'United States',
 'Anti-materiel sniper rifle used by Canadian and other special forces. World record long-range kill shot (3,871m).',
 10000, 192.0, 57.0, true, true,
 ARRAY['TAC-50 A1', 'TAC-50 A1-R2'],
 'Active', 'McMillan TAC-50', ARRAY['.50 BMG'],
 ARRAY['tac50', 'mcmillan 50', 'tac-50'], 'Modern', 'Trigger', ARRAY['military'],
 'A Canadian JTF2 sniper used the TAC-50 to set the world record confirmed kill at 3,871 meters in 2017.',
 'United States', false, NULL),

('McMillan Firearms', 'TAC-338', '.338 Lapua Magnum', 'Rifle', 'Bolt-Action', 5, 2000, false, 'United States',
 'Precision long-range sniper rifle in .338 Lapua. Used by US and allied special forces.',
 5999, 148.0, 52.0, true, true,
 ARRAY['TAC-338 standard', 'TAC-338 folding'],
 'Active', 'McMillan TAC-338', ARRAY['.338 Lapua Magnum'],
 ARRAY['tac338', 'mcmillan 338'], 'Modern', 'Trigger', ARRAY['military', 'competition'],
 NULL, 'United States', false, NULL),

('McMillan Firearms', 'CS5', '.308 Winchester', 'Rifle', 'Bolt-Action', 10, 2012, false, 'United States',
 'Compact suppressor-ready precision rifle with folding chassis stock.',
 4999, 110.0, 32.0, false, true,
 ARRAY['CS5 .308', 'CS5 6.5 Creedmoor'],
 'Active', 'McMillan CS5', ARRAY['.308 Winchester', '6.5 Creedmoor'],
 ARRAY['cs5', 'mcmillan cs5'], 'Modern', 'Trigger', ARRAY['military', 'competition'],
 NULL, 'United States', false, NULL),

-- MERKEL
('Merkel', 'B3', '12 Gauge', 'Shotgun', 'Over-Under', 2, 2016, false, 'Germany',
 'Entry-level German O/U shotgun with proven Merkel reliability.',
 1699, 74.0, 45.0, false, false,
 ARRAY['B3 Standard', 'B3 Sporting'],
 'Active', 'Merkel B3', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['b3', 'merkel b3'], 'Modern', 'Trigger', ARRAY['hunting', 'sport'],
 NULL, 'Germany', false, NULL),

('Merkel', '200E', '12 Gauge', 'Shotgun', 'Side-by-Side', 2, 1960, false, 'Germany',
 'Classic German SxS with Anson & Deeley boxlock action. Standard German game shotgun.',
 3000, 66.0, 44.0, false, false,
 ARRAY['200E standard', '200EL (sidelock)'],
 'Active', 'Merkel 200', ARRAY['12 Gauge', '16 Gauge', '20 Gauge'],
 ARRAY['200e', 'merkel 200', 'merkel sxs'], 'Post-Cold War', 'Trigger', ARRAY['hunting'],
 NULL, 'Germany', false, NULL),

('Merkel', 'RX Helix', '.308 Winchester', 'Rifle', 'Straight-Pull', 5, 2011, false, 'Germany',
 'Modular straight-pull bolt-action with interchangeable barrel and caliber system.',
 2599, 88.0, 41.0, false, false,
 ARRAY['RX Helix Explorer', 'RX Helix Spine'],
 'Active', 'Merkel RX Helix', ARRAY['.308 Winchester', '.30-06 Springfield', '8x57mm JS', '9.3x62mm'],
 ARRAY['rx helix', 'merkel helix'], 'Modern', 'Trigger', ARRAY['hunting'],
 'Barrel changes in under a minute — one receiver covers many calibers and hunting situations.',
 'Germany', false, NULL),

-- MIROKU CORPORATION
('Miroku Corporation', 'MK 60', '12 Gauge', 'Shotgun', 'Over-Under', 2, 1974, false, 'Japan',
 'Japanese O/U manufactured under contract for Browning, Winchester, and Charles Daly.',
 NULL, 72.0, 45.0, false, false,
 ARRAY['MK 60 Grade I', 'MK 60 Grade II'],
 'Active', 'Miroku MK 60', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['mk60', 'miroku ou', 'japanese browning'], 'Modern', 'Trigger', ARRAY['hunting', 'sport'],
 'Miroku has manufactured Browning O/U shotguns in Japan since 1975 — most Browning Citoris are Miroku-made.',
 'Japan', false, NULL),

('Miroku Corporation', 'Model 1300', '.308 Winchester', 'Rifle', 'Bolt-Action', 4, 1980, false, 'Japan',
 'Miroku bolt-action rifle produced for Winchester and Browning brands.',
 NULL, 86.0, 42.0, false, false, ARRAY['Model 1300 standard'],
 'Active', 'Miroku Model 1300', ARRAY['.308 Winchester', '.30-06 Springfield'],
 ARRAY['miroku 1300', 'japanese winchester'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Japan', false, NULL),

('Miroku Corporation', 'BT-99', '12 Gauge', 'Shotgun', 'Break-Action', 1, 1969, false, 'Japan',
 'Single-barrel trap shotgun made by Miroku for Browning. Standard trap competition gun.',
 1599, 78.0, 48.0, false, false,
 ARRAY['BT-99 Plus', 'BT-99 Micro'],
 'Active', 'Miroku BT-99', ARRAY['12 Gauge'],
 ARRAY['bt99', 'browning bt99', 'miroku trap'], 'Modern', 'Trigger', ARRAY['competition'],
 NULL, 'Japan', false, NULL),

-- NAVY ARMS COMPANY
('Navy Arms Company', 'Henry Rifle', '.44-40 Winchester', 'Rifle', 'Lever-Action', 15, 1866, true, 'United States',
 'Replica of the original Henry lever-action rifle of 1860. Navy Arms was the pioneer of quality Western replica guns.',
 NULL, 82.0, 43.0, false, false,
 ARRAY['Henry .44-40', 'Henry .44 Rimfire reproduction'],
 'Discontinued', 'Navy Arms Henry', ARRAY['.44-40 Winchester', '.44 Rimfire'],
 ARRAY['henry rifle', 'navy arms henry'], 'Pre-WWI / Old West', 'Trigger', ARRAY['collector', 'hunting'],
 'Val Forgett founded Navy Arms in 1957 as the first major importer of quality replica firearms.',
 'United States', true, 'Early Navy Arms Henry replicas are collectible. Uberti-made examples are high quality.'),

('Navy Arms Company', 'Rolling Block', '.45-70 Government', 'Rifle', 'Single-Shot', 1, 1968, false, 'United States',
 'Replica of the Remington Rolling Block — the most widely used single-shot military rifle of the 19th century.',
 649, 90.0, 46.0, false, false,
 ARRAY['Rolling Block Sporting', 'Rolling Block Buffalo'],
 'Active', 'Navy Arms Rolling Block', ARRAY['.45-70 Government', '.357 Magnum', '.44-40 Winchester'],
 ARRAY['rolling block', 'navy arms rolling block'], 'Modern', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'United States', false, NULL),

('Navy Arms Company', 'SAA', '.45 Colt', 'Revolver', 'Single-Action', 6, 1975, false, 'United States',
 'Colt Single Action Army replica manufactured by Uberti for Navy Arms. High-quality Italian craftsmanship.',
 549, 40.0, 11.0, false, false,
 ARRAY['SAA 4.75"', 'SAA 5.5" Cavalry', 'SAA 7.5"'],
 'Active', 'Navy Arms SAA', ARRAY['.45 Colt', '.357 Magnum', '.44-40 Winchester'],
 ARRAY['saa', 'navy arms saa', 'navy arms colt'], 'Modern', 'Single-Action', ARRAY['hunting', 'collector'],
 NULL, 'United States', false, NULL),

-- NIGHTHAWK CUSTOM
('Nighthawk Custom', 'Agent 2', '9mm Luger', 'Pistol', 'Semi-Auto', 8, 2010, false, 'United States',
 'Custom 1911 Commander-size with Nighthawk''s one-gun-one-gunsmith build philosophy.',
 3499, 32.0, 7.8, false, false,
 ARRAY['Agent 2 Aluminum', 'Agent 2 Stainless'],
 'Active', 'Nighthawk Agent', ARRAY['9mm Luger', '.45 ACP'],
 ARRAY['agent 2', 'nighthawk agent'], 'Modern', 'Single-Action', ARRAY['competition', 'home defense'],
 'Each Nighthawk 1911 is built entirely by one gunsmith — one of the most labor-intensive production processes in the industry.',
 'United States', true, NULL),

('Nighthawk Custom', 'GRP', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 2000, false, 'United States',
 'Global Response Pistol — full-size 1911 with G10 grips, front strap checkering, and match trigger.',
 3199, 41.0, 8.7, false, false,
 ARRAY['GRP Stainless', 'GRP Black'],
 'Active', 'Nighthawk GRP', ARRAY['.45 ACP', '9mm Luger'],
 ARRAY['grp', 'nighthawk grp'], 'Modern', 'Single-Action', ARRAY['competition', 'home defense'],
 NULL, 'United States', true, NULL),

('Nighthawk Custom', 'T4', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2018, false, 'United States',
 'Polymer frame 2011-style pistol built on a Staccato-compatible chassis.',
 2799, 28.0, 5.5, false, false, ARRAY['T4 standard'],
 'Active', 'Nighthawk T4', ARRAY['9mm Luger'],
 ARRAY['t4', 'nighthawk t4'], 'Modern', 'Single-Action', ARRAY['competition'],
 NULL, 'United States', false, NULL),

-- NORINCO
('Norinco', 'NP7', '9mm Luger', 'Pistol', 'Semi-Auto', 15, 1985, false, 'China',
 'Chinese Browning Hi-Power clone with polymer-coated steel frame. Exported before US import ban.',
 NULL, 32.0, 7.8, false, false,
 ARRAY['NP7 standard'],
 'Discontinued', 'Norinco NP', ARRAY['9mm Luger'],
 ARRAY['np7', 'norinco np7', 'chinese hi-power'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 'Norinco firearms were banned from US import in 1994. Pre-ban examples are collectible.',
 'China', true, 'Pre-1994 US imports. Surprisingly good quality for the price when they were available.'),

('Norinco', 'Type 56', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 1956, false, 'China',
 'Chinese AKM copy. Millions produced; widely exported and militarily used globally.',
 NULL, 86.0, 34.3, true, true,
 ARRAY['Type 56-1 (folding stock)', 'Type 56-2 (underfolding)', 'MAK-90 (US import)'],
 'Active', 'Type 56', ARRAY['7.62x39mm'],
 ARRAY['type 56', 'chinese ak', 'mak90', 'norinco 56s'], 'Cold War', 'Trigger', ARRAY['military', 'collector'],
 'The Type 56 is one of the most numerous AK variants ever made, with production in the hundreds of millions.',
 'China', true, 'US-imported pre-ban variants (56S, MAK-90) are collectible. Milled receiver variants command premiums.'),

('Norinco', 'Model 97', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 1993, false, 'China',
 'Chinese Winchester Model 1897 reproduction. Hammer-fired exposed hammer pump shotgun.',
 199, 72.0, 39.0, false, false,
 ARRAY['Model 97 standard', 'Model 97 Trench Gun'],
 'Discontinued', 'Norinco 97', ARRAY['12 Gauge'],
 ARRAY['model 97', 'norinco 97', 'chinese 97'], 'Post-Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'China', false, NULL),

-- NORTH AMERICAN ARMS
('North American Arms', 'Mini-Revolver', '.22 LR', 'Revolver', 'Single-Action', 5, 1971, false, 'United States',
 'The smallest production revolver in the world. Fits in a closed fist. Stainless steel.',
 249, 4.0, 4.0, false, false,
 ARRAY['Mini .22 Magnum', 'Mini .17 HMR', 'Mini-Master'],
 'Active', 'NAA Mini', ARRAY['.22 LR', '.22 WMR', '.17 HMR'],
 ARRAY['mini revolver', 'naa mini', 'north american mini'], 'Modern', 'Single-Action', ARRAY['concealed carry'],
 'The NAA Mini-Revolver must be unloaded to safely lower the hammer. A half-cock notch on the cylinder pin is the safety.',
 'United States', false, NULL),

('North American Arms', 'Guardian', '.380 ACP', 'Pistol', 'Semi-Auto', 6, 1997, false, 'United States',
 'Stainless steel pocket pistol for deep concealment. Double-action only.',
 409, 18.7, 4.75, false, false,
 ARRAY['Guardian .32 ACP', 'Guardian .25 NAA', 'Guardian .380 ACP'],
 'Active', 'NAA Guardian', ARRAY['.380 ACP', '.32 ACP', '.25 NAA'],
 ARRAY['guardian', 'naa guardian'], 'Modern', 'DAO', ARRAY['concealed carry'],
 NULL, 'United States', false, NULL),

('North American Arms', 'Pug', '.22 WMR', 'Revolver', 'Single-Action', 5, 2004, false, 'United States',
 'Slightly larger Mini-Revolver with fixed sights and larger grip for improved handling.',
 324, 6.2, 4.4, false, false,
 ARRAY['Pug standard', 'Pug White Dot Sights'],
 'Active', 'NAA Pug', ARRAY['.22 WMR'],
 ARRAY['pug', 'naa pug'], 'Modern', 'Single-Action', ARRAY['concealed carry'],
 NULL, 'United States', false, NULL),

-- NOSLER
('Nosler', 'Model 21', '6.5 Creedmoor', 'Rifle', 'Bolt-Action', 5, 2019, false, 'United States',
 'Premium bolt-action built around Nosler''s proprietary action with Shilen barrel.',
 2495, 88.0, 42.0, false, false,
 ARRAY['Model 21 Long Range', 'Model 21 Short Action'],
 'Active', 'Nosler Model 21', ARRAY['6.5 Creedmoor', '.308 Winchester', '.28 Nosler', '.30 Nosler'],
 ARRAY['model 21', 'nosler 21'], 'Modern', 'Trigger', ARRAY['hunting', 'competition'],
 NULL, 'United States', false, NULL),

('Nosler', 'Model 48', '.300 Win Mag', 'Rifle', 'Bolt-Action', 3, 2005, false, 'United States',
 'Hunting rifle featuring Nosler''s long-action bolt with match-grade barrel.',
 1999, 96.0, 44.5, false, false,
 ARRAY['Model 48 Liberty', 'Model 48 Heritage', 'Model 48 Long Range Carbon'],
 'Active', 'Nosler Model 48', ARRAY['.300 Win Mag', '.30 Nosler', '.33 Nosler', '28 Nosler'],
 ARRAY['model 48', 'nosler 48'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'United States', false, NULL),

('Nosler', 'Model 48 Carbon', '6.5 PRC', 'Rifle', 'Bolt-Action', 3, 2020, false, 'United States',
 'Carbon fiber-stocked version of the Model 48 for lightweight backcountry hunting.',
 2799, 68.0, 44.0, false, false,
 ARRAY['Model 48 Carbon Western', 'Model 48 Carbon Woodlands'],
 'Active', 'Nosler Carbon', ARRAY['6.5 PRC', '.28 Nosler', '.30 Nosler'],
 ARRAY['nosler carbon', 'model 48 carbon'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'United States', false, NULL),

-- NOVESKE RIFLEWORKS
('Noveske Rifleworks', 'N4 Gen 3', '5.56x45mm NATO', 'Rifle', 'Semi-Auto', 30, 2012, false, 'United States',
 'Premium AR-15 known for extreme accuracy and reliability. Built to John Noveske''s standards.',
 2299, 62.0, 32.0, false, false,
 ARRAY['N4 Gen 3 Recon', 'N4 Gen 3 Light Recce', 'N4 Gen 3 SBR'],
 'Active', 'Noveske N4', ARRAY['5.56x45mm NATO', '.300 Blackout'],
 ARRAY['n4', 'noveske n4', 'noveske ar15'], 'Modern', 'Trigger', ARRAY['competition', 'home defense'],
 'Founder John Noveske died in a car crash in 2013. The company continues his quality standards.',
 'United States', false, NULL),

('Noveske Rifleworks', 'Ghetto Blaster', '.300 Blackout', 'Rifle', 'Semi-Auto', 30, 2010, false, 'United States',
 'Short-barreled .300 BLK rifle optimized for suppressed use.',
 2499, 58.0, 26.0, false, false, ARRAY['Ghetto Blaster standard'],
 'Active', 'Noveske Ghetto Blaster', ARRAY['.300 Blackout'],
 ARRAY['ghetto blaster', 'noveske 300'], 'Modern', 'Trigger', ARRAY['home defense'],
 NULL, 'United States', false, NULL),

('Noveske Rifleworks', 'Rogue Hunter', '.308 Winchester', 'Rifle', 'Semi-Auto', 20, 2015, false, 'United States',
 'AR-10 pattern precision rifle for long-range hunting and competition.',
 2999, 102.0, 38.0, false, false,
 ARRAY['Rogue Hunter .308', 'Rogue Hunter 6.5 Creedmoor'],
 'Active', 'Noveske Rogue', ARRAY['.308 Winchester', '6.5 Creedmoor'],
 ARRAY['rogue hunter', 'noveske rogue'], 'Modern', 'Trigger', ARRAY['hunting', 'competition'],
 NULL, 'United States', false, NULL),

-- OLYMPIC ARMS
('Olympic Arms', 'PCR-1', '5.56x45mm NATO', 'Rifle', 'Semi-Auto', 30, 1994, true, 'United States',
 'Post-ban compliant AR-15 with pinned flash hider and no bayonet lug. Made to comply with the 1994 AWB.',
 NULL, 62.0, 32.0, false, false,
 ARRAY['PCR-1', 'PCR-2 (20" barrel)'],
 'Discontinued', 'Olympic PCR', ARRAY['5.56x45mm NATO'],
 ARRAY['pcr1', 'olympic ar15', 'olympic pcr'], 'Post-Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 'Olympic Arms designed the PCR series specifically to comply with the 1994 AWB.',
 'United States', false, NULL),

('Olympic Arms', 'K3B', '5.56x45mm NATO', 'Rifle', 'Semi-Auto', 30, 2004, true, 'United States',
 'Post-ban carbine with M4 profile barrel. Produced until Olympic Arms closed in 2017.',
 NULL, 62.0, 32.0, false, false, ARRAY['K3B standard'],
 'Discontinued', 'Olympic K3B', ARRAY['5.56x45mm NATO'],
 ARRAY['k3b', 'olympic k3b'], 'Modern', 'Trigger', ARRAY['hunting', 'home defense'],
 NULL, 'United States', false, NULL),

('Olympic Arms', 'Plinker Plus', '.22 LR', 'Rifle', 'Semi-Auto', 10, 2000, true, 'United States',
 'AR-15 pattern .22 LR training rifle.',
 NULL, 48.0, 32.0, false, false, ARRAY['Plinker Plus standard'],
 'Discontinued', 'Olympic Plinker', ARRAY['.22 LR'],
 ARRAY['plinker plus', 'olympic 22 ar'], 'Modern', 'Trigger', ARRAY['training', 'plinking'],
 NULL, 'United States', false, NULL),

-- PARA ORDNANCE
('Para Ordnance', 'P14', '.45 ACP', 'Pistol', 'Semi-Auto', 14, 1990, true, 'Canada',
 'Double-stack 1911 with 14-round magazine. Revolutionary when introduced — put 1911 capacity on par with Glock.',
 NULL, 40.0, 8.5, false, false,
 ARRAY['P14-45', 'P16-40 (.40 S&W)', 'P18-9 (9mm)'],
 'Discontinued', 'Para P14', ARRAY['.45 ACP', '.40 S&W', '9mm Luger'],
 ARRAY['p14', 'para p14', 'para ordnance p14'], 'Post-Cold War', 'Single-Action', ARRAY['home defense', 'competition', 'collector'],
 'The P14 doubled the capacity of the 1911 without sacrificing the trigger or ergonomics.',
 'Canada', true, 'Para Ordnance absorbed by Remington in 2012. Well-made guns with collector interest.'),

('Para Ordnance', 'LDA', '.45 ACP', 'Pistol', 'Semi-Auto', 14, 1999, true, 'Canada',
 'Light Double Action 1911 — 1911 operating system with a DAO trigger.',
 NULL, 40.0, 8.5, false, false,
 ARRAY['LDA single stack', 'LDA double stack'],
 'Discontinued', 'Para LDA', ARRAY['.45 ACP', '9mm Luger'],
 ARRAY['lda', 'para lda'], 'Modern', 'DAO', ARRAY['home defense', 'collector'],
 NULL, 'Canada', true, NULL),

('Para Ordnance', 'Warthog', '.45 ACP', 'Pistol', 'Semi-Auto', 10, 2004, true, 'Canada',
 'Compact double-stack 1911 with 3.5" barrel for concealed carry.',
 NULL, 28.0, 6.5, false, false, ARRAY['Warthog standard', 'Hawg 9 (9mm)'],
 'Discontinued', 'Para Warthog', ARRAY['.45 ACP'],
 ARRAY['warthog', 'para warthog', 'hawg'], 'Modern', 'Single-Action', ARRAY['concealed carry', 'collector'],
 NULL, 'Canada', true, NULL),

-- PEDERSOLI
('Pedersoli', 'Sharps Sporting', '.45-70 Government', 'Rifle', 'Single-Shot', 1, 1970, false, 'Italy',
 'High-quality Italian reproduction of the Sharps 1874 sporting rifle.',
 1499, 128.0, 47.0, false, false,
 ARRAY['Sharps 1874 Long Range', 'Sharps 1874 Target', 'Sharps 1874 Quigley'],
 'Active', 'Pedersoli Sharps', ARRAY['.45-70 Government', '.45-90', '.45-120', '.38-55'],
 ARRAY['sharps', 'pedersoli sharps', 'pedersoli 1874'], 'Modern', 'Trigger', ARRAY['hunting', 'competition', 'collector'],
 'The "Quigley" variant reproduces the rifle used by Tom Selleck in Quigley Down Under.',
 'Italy', false, NULL),

('Pedersoli', 'Springfield Trapdoor', '.45-70 Government', 'Rifle', 'Single-Shot', 1, 1972, false, 'Italy',
 'Reproduction of the Springfield Model 1873 Trapdoor — the US Army''s first metallic cartridge rifle.',
 799, 96.0, 52.0, false, false,
 ARRAY['Trapdoor Carbine', 'Trapdoor Springfield Rifle'],
 'Active', 'Pedersoli Trapdoor', ARRAY['.45-70 Government'],
 ARRAY['trapdoor', 'pedersoli trapdoor', 'springfield 1873'], 'Modern', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'Italy', false, NULL),

('Pedersoli', 'Le Page', '.45 Caliber', 'Pistol', 'Single-Shot', 1, 1980, false, 'Italy',
 'Flintlock dueling pistol reproduction in the style of the 18th-century French master gunmaker LePage.',
 699, 22.0, 14.5, false, false,
 ARRAY['Le Page Flintlock', 'Le Page Percussion'],
 'Active', 'Pedersoli Le Page', ARRAY['.45 Caliber'],
 ARRAY['le page', 'pedersoli dueling'], 'Modern', 'Trigger', ARRAY['collector', 'competition'],
 NULL, 'Italy', false, NULL),

-- PHOENIX ARMS
('Phoenix Arms', 'HP22', '.22 LR', 'Pistol', 'Semi-Auto', 10, 1990, false, 'United States',
 'Budget single-action .22 LR semi-auto. More reliable than most Ring of Fire guns.',
 130, 20.0, 5.5, false, false,
 ARRAY['HP22A (safety upgraded)'],
 'Active', 'Phoenix HP22', ARRAY['.22 LR'],
 ARRAY['hp22', 'phoenix hp22'], 'Modern', 'Single-Action', ARRAY['plinking'],
 NULL, 'United States', false, NULL),

('Phoenix Arms', 'HP25', '.25 ACP', 'Pistol', 'Semi-Auto', 10, 1990, false, 'United States',
 'Budget single-action .25 ACP semi-auto pocket pistol.',
 130, 19.0, 5.5, false, false, ARRAY['HP25A'],
 'Active', 'Phoenix HP25', ARRAY['.25 ACP'],
 ARRAY['hp25', 'phoenix hp25'], 'Modern', 'Single-Action', ARRAY['plinking'],
 NULL, 'United States', false, NULL),

('Phoenix Arms', 'Raven', '.25 ACP', 'Pistol', 'Semi-Auto', 6, 1970, true, 'United States',
 'Original low-cost zinc alloy .25 ACP — one of the most common Saturday Night Specials.',
 NULL, 15.0, 4.75, false, false, ARRAY['Raven standard'],
 'Discontinued', 'Raven Arms Raven', ARRAY['.25 ACP'],
 ARRAY['raven', 'raven arms 25'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

-- PTR INDUSTRIES
('PTR Industries', 'PTR 91', '.308 Winchester', 'Rifle', 'Semi-Auto', 20, 2000, false, 'United States',
 'American-made HK91 clone. Uses the roller-delayed blowback action of the original G3.',
 999, 102.0, 40.5, false, false,
 ARRAY['PTR 91 GI', 'PTR 91 SC (Scout)', 'PTR 91 PDWR (short)'],
 'Active', 'PTR 91', ARRAY['.308 Winchester', '7.62x51mm NATO'],
 ARRAY['ptr91', 'ptr 91', 'hk91 clone'], 'Modern', 'Trigger', ARRAY['home defense', 'hunting'],
 'PTR Industries manufactures on original HK tooling purchased after HK discontinued the G3 line.',
 'United States', false, NULL),

('PTR Industries', 'PTR 32', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 2010, false, 'United States',
 'PTR 91 receiver adapted for AK-caliber 7.62x39mm.',
 999, 100.0, 40.0, false, false, ARRAY['PTR 32 KFR', 'PTR 32 KFM4'],
 'Active', 'PTR 32', ARRAY['7.62x39mm'],
 ARRAY['ptr32', 'ptr 32'], 'Modern', 'Trigger', ARRAY['home defense'],
 NULL, 'United States', false, NULL),

('PTR Industries', 'PTR 9CT', '9mm Luger', 'Rifle', 'Semi-Auto', 30, 2012, false, 'United States',
 'MP5-pattern 9mm carbine using PTR''s roller-delayed action.',
 1399, 65.0, 27.0, false, false,
 ARRAY['PTR 9CT pistol', 'PTR 9KT (short)'],
 'Active', 'PTR 9', ARRAY['9mm Luger'],
 ARRAY['ptr9ct', 'ptr 9mm', 'ptr mp5'], 'Modern', 'Trigger', ARRAY['home defense', 'competition'],
 NULL, 'United States', false, NULL),

-- QUALITY HARDWARE & MACHINE
('Quality Hardware & Machine', 'M1 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 15, 1943, true, 'United States',
 'WWII M1 Carbine manufactured by Quality Hardware & Machine Co. under government contract (~359,000 units).',
 NULL, 51.0, 35.6, true, false,
 ARRAY['Quality Hardware M1 1943', 'Quality Hardware M1 1944'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['quality hardware carbine', 'qhm carbine', 'qhm m1'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 'Quality Hardware was a Chicago auto parts manufacturer that pivoted to carbine production for WWII.',
 'United States', true, 'WWII contractor M1 Carbines are collectible. Quality Hardware examples in original condition are desirable.'),

('Quality Hardware & Machine', 'M1 Carbine (late war)', '.30 Carbine', 'Rifle', 'Semi-Auto', 30, 1944, true, 'United States',
 'Late-war Quality Hardware production with upgraded components.',
 NULL, 51.0, 35.6, true, false, ARRAY['Late QHM production'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['qhm late war', 'quality hardware 1944'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

('Quality Hardware & Machine', 'M1A1 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 30, 1944, true, 'United States',
 'Quality Hardware M1A1 paratrooper folding-stock variant.',
 NULL, 51.0, 35.6, true, false, ARRAY['QHM M1A1'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['qhm m1a1', 'quality hardware paratrooper'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

-- RAVEN ARMS
('Raven Arms', 'MP-25', '.25 ACP', 'Pistol', 'Semi-Auto', 6, 1970, true, 'United States',
 'Inexpensive zinc alloy .25 ACP — among the most common Saturday Night Specials.',
 NULL, 15.0, 4.75, false, false, ARRAY['MP-25 standard'],
 'Discontinued', 'Raven MP', ARRAY['.25 ACP'],
 ARRAY['mp25', 'raven 25', 'raven arms mp25'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 'Raven Arms sold millions of MP-25s before California''s Unsafe Handgun Act drove them out of business.',
 'United States', false, NULL),

('Raven Arms', 'MP-45', '.25 ACP', 'Pistol', 'Semi-Auto', 6, 1990, true, 'United States',
 'Late Raven Arms design chambered in .25 ACP with improved aesthetics over the MP-25.',
 NULL, 14.0, 5.0, false, false, ARRAY['MP-45 standard'],
 'Discontinued', 'Raven MP', ARRAY['.25 ACP'],
 ARRAY['mp45', 'raven mp45'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

('Raven Arms', 'MP-380', '.380 ACP', 'Pistol', 'Semi-Auto', 6, 1990, true, 'United States',
 'Raven Arms step-up to .380 ACP before the company ceased operations.',
 NULL, 23.0, 5.7, false, false, ARRAY['MP-380 standard'],
 'Discontinued', 'Raven MP', ARRAY['.380 ACP'],
 ARRAY['mp380', 'raven 380'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

-- REMINGTON RAND
('Remington Rand', 'M1911A1', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1943, true, 'United States',
 'WWII M1911A1 manufactured by Remington Rand typewriter company. Largest single WWII 1911 producer (~900,000 units).',
 NULL, 38.5, 8.6, true, false,
 ARRAY['Remington Rand 1943', 'Remington Rand 1944', 'Remington Rand 1945'],
 'Discontinued', 'M1911A1', ARRAY['.45 ACP'],
 ARRAY['remington rand 1911', 'rr 1911', 'remrand 45'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 'Remington Rand made typewriters, not guns, before WWII — yet produced more 1911s than any other WWII contractor.',
 'United States', true, 'WWII Remington Rand 1911s are highly collectible. Original examples command strong premiums.'),

('Remington Rand', 'M1911A1 (late war)', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1945, true, 'United States',
 'Late-production Remington Rand 1911A1 with Parkerized finish and simplified manufacturing.',
 NULL, 38.5, 8.6, true, false, ARRAY['RR late production'],
 'Discontinued', 'M1911A1', ARRAY['.45 ACP'],
 ARRAY['rr late war', 'remington rand parkerized'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

('Remington Rand', 'M1911A1 (1944)', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1944, true, 'United States',
 '1944-dated Remington Rand production at peak wartime output.',
 NULL, 38.5, 8.6, true, false, ARRAY['RR 1944 production'],
 'Discontinued', 'M1911A1', ARRAY['.45 ACP'],
 ARRAY['rr 1944', 'remington rand 1944'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

-- SC CUGIR
('SC Cugir', 'WASR-10', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 1990, false, 'Romania',
 'Romanian AKM-pattern semi-auto rifle. The most common Romanian AK in the US market.',
 699, 82.0, 34.3, false, false,
 ARRAY['WASR-10/63', 'WASR-10 with US parts'],
 'Active', 'WASR-10', ARRAY['7.62x39mm'],
 ARRAY['wasr10', 'wasr 10', 'romanian ak', 'cugir ak'], 'Post-Cold War', 'Trigger', ARRAY['home defense', 'hunting'],
 'WASR stands for "Wasser" (water) — a naming convention from the Romanian socialist era.',
 'Romania', false, NULL),

('SC Cugir', 'Draco', '7.62x39mm', 'Pistol', 'Semi-Auto', 30, 2007, false, 'Romania',
 'AK-pattern pistol with short 12.25" barrel. No stock. Very popular in the US market.',
 699, 67.0, 21.0, false, false,
 ARRAY['Draco NAK9 (9mm)', 'Micro Draco', 'Mini Draco'],
 'Active', 'Draco', ARRAY['7.62x39mm', '9mm Luger'],
 ARRAY['draco', 'cugir draco', 'romanian draco'], 'Modern', 'Trigger', ARRAY['home defense'],
 NULL, 'Romania', false, NULL),

('SC Cugir', 'Cugir MD63', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 1963, true, 'Romania',
 'Original Romanian military AKM, the predecessor to all WASR variants.',
 NULL, 84.0, 34.3, true, false,
 ARRAY['MD63', 'PM md. 63'],
 'Discontinued', 'Cugir MD', ARRAY['7.62x39mm'],
 ARRAY['md63', 'cugir md63', 'romanian pm63'], 'Cold War', 'Trigger', ARRAY['military', 'collector'],
 NULL, 'Romania', true, NULL),

-- SCCY INDUSTRIES
('SCCY Industries', 'CPX-2', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 2011, false, 'United States',
 'DAO subcompact 9mm with no external safety. Budget concealed carry option.',
 299, 15.0, 5.7, false, false,
 ARRAY['CPX-2 RD (red dot)', 'CPX-2 standard'],
 'Active', 'SCCY CPX', ARRAY['9mm Luger'],
 ARRAY['cpx2', 'sccy cpx2', 'sccy 9mm'], 'Modern', 'DAO', ARRAY['concealed carry'],
 NULL, 'United States', false, NULL),

('SCCY Industries', 'CPX-1', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 2010, false, 'United States',
 'DAO subcompact 9mm with manual thumb safety.',
 299, 15.0, 5.7, false, false,
 ARRAY['CPX-1 standard', 'CPX-1 RD'],
 'Active', 'SCCY CPX', ARRAY['9mm Luger'],
 ARRAY['cpx1', 'sccy cpx1'], 'Modern', 'DAO', ARRAY['concealed carry'],
 NULL, 'United States', false, NULL),

('SCCY Industries', 'DVG-1', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 2021, false, 'United States',
 'Updated SCCY design with striker-fired action and improved trigger.',
 299, 15.5, 5.7, false, false,
 ARRAY['DVG-1 RD', 'DVG-1 standard'],
 'Active', 'SCCY DVG', ARRAY['9mm Luger'],
 ARRAY['dvg1', 'sccy dvg'], 'Modern', 'Striker-Fired', ARRAY['concealed carry'],
 NULL, 'United States', false, NULL),

-- SKB ARMS
('SKB Arms', 'Model 505', '12 Gauge', 'Shotgun', 'Over-Under', 2, 1987, false, 'Japan',
 'Japanese over-under shotgun for field and sporting use. High-quality at mid-range price.',
 1299, 78.0, 45.0, false, false,
 ARRAY['Model 505 Field', 'Model 505 Sporting'],
 'Active', 'SKB 505', ARRAY['12 Gauge', '20 Gauge', '28 Gauge'],
 ARRAY['505', 'skb 505', 'skb ou'], 'Modern', 'Trigger', ARRAY['hunting', 'sport'],
 NULL, 'Japan', false, NULL),

('SKB Arms', 'Model 85TSS', '12 Gauge', 'Shotgun', 'Over-Under', 2, 1995, false, 'Japan',
 'Target-grade O/U with adjustable stock and porting. For trap, skeet, and sporting clays.',
 2299, 86.0, 47.0, false, false,
 ARRAY['85TSS Trap', '85TSS Skeet', 'SXS (side-by-side)'],
 'Active', 'SKB 85TSS', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['85tss', 'skb 85tss'], 'Modern', 'Trigger', ARRAY['competition', 'sport'],
 NULL, 'Japan', false, NULL),

('SKB Arms', 'Model 7300', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 1983, true, 'Japan',
 'Gas-operated semi-auto hunting shotgun from SKB''s production years in Japan.',
 NULL, 74.0, 47.0, false, false,
 ARRAY['Model 7300 standard', 'Model 7300 Slug'],
 'Discontinued', 'SKB 7300', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['7300', 'skb 7300'], 'Post-Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'Japan', false, NULL),

-- SMITH ENTERPRISE
('Smith Enterprise', 'M14', '7.62x51mm NATO', 'Rifle', 'Semi-Auto', 20, 1995, false, 'United States',
 'Smith Enterprise refurbishes and custom-builds M14/M1A-pattern rifles for military and civilian use.',
 2499, 110.0, 44.0, false, true,
 ARRAY['SEI M14 Tactical', 'SEI M14 Standard'],
 'Active', 'SEI M14', ARRAY['7.62x51mm NATO', '.308 Winchester'],
 ARRAY['sei m14', 'smith enterprise m14'], 'Modern', 'Trigger', ARRAY['military', 'competition', 'hunting'],
 'Smith Enterprise is the primary contractor for M14 rebuild and enhancement work for US military units.',
 'United States', false, NULL),

('Smith Enterprise', 'M1 Garand', '.30-06 Springfield', 'Rifle', 'Semi-Auto', 8, 2000, false, 'United States',
 'Smith Enterprise refinishes and rebuilds M1 Garand rifles to exacting standards.',
 1299, 105.0, 43.5, false, false,
 ARRAY['SEI M1 Standard', 'SEI M1 Tanker'],
 'Active', 'SEI M1 Garand', ARRAY['.30-06 Springfield', '.308 Winchester'],
 ARRAY['sei garand', 'smith enterprise garand'], 'Modern', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'United States', false, NULL),

('Smith Enterprise', 'Crazy Horse', '7.62x51mm NATO', 'Rifle', 'Semi-Auto', 20, 2005, false, 'United States',
 'Smith Enterprise M14-based precision rifle with Sage chassis and enhanced accuracy work.',
 3499, 108.0, 44.0, false, true,
 ARRAY['Crazy Horse standard', 'Crazy Horse Elite'],
 'Active', 'SEI Crazy Horse', ARRAY['7.62x51mm NATO'],
 ARRAY['crazy horse', 'sei crazy horse'], 'Modern', 'Trigger', ARRAY['military', 'competition'],
 NULL, 'United States', false, NULL),

-- STALLARD ARMS / SUNDANCE / STANDARD PRODUCTS
('Stallard Arms', 'JS-9', '9mm Luger', 'Pistol', 'Semi-Auto', 10, 1991, true, 'United States',
 'Budget 9mm pistol, precursor to the Hi-Point design. Made by the same family as Hi-Point.',
 NULL, 26.0, 6.5, false, false, ARRAY['JS-9 standard'],
 'Discontinued', 'Stallard JS', ARRAY['9mm Luger'],
 ARRAY['js9', 'stallard 9mm'], 'Post-Cold War', 'Trigger', ARRAY['collector'],
 'Stallard Arms became Hi-Point Firearms when the family reorganized the company.',
 'United States', false, NULL),

('Sundance Industries', 'Model A-25', '.25 ACP', 'Pistol', 'Semi-Auto', 7, 1989, true, 'United States',
 'Budget Ring of Fire .25 ACP pocket pistol.',
 NULL, 16.0, 5.2, false, false, ARRAY['Model A-25 standard'],
 'Discontinued', 'Sundance A', ARRAY['.25 ACP'],
 ARRAY['a25', 'sundance 25', 'sundance a-25'], 'Post-Cold War', 'Single-Action', ARRAY['collector'],
 NULL, 'United States', false, NULL),

('Standard Products', 'M1 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 15, 1943, true, 'United States',
 'WWII M1 Carbine manufactured by Standard Products Co. (~247,000 units produced).',
 NULL, 51.0, 35.6, true, false,
 ARRAY['Standard Products M1 1943', 'Standard Products M1 1944'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['standard products carbine', 'sp carbine', 'standard m1'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 'Standard Products was a Port Clinton, Ohio manufacturer that built M1 Carbines during WWII.',
 'United States', true, 'Collectible WWII contractor carbines. Standard Products stamped examples are sought.'),

-- STAR FIREARMS
('Star Firearms', 'Model BM', '9mm Luger', 'Pistol', 'Semi-Auto', 8, 1972, true, 'Spain',
 'Spanish 1911-influenced single-action 9mm. Compact, reliable, and widely exported.',
 NULL, 25.0, 6.9, true, true,
 ARRAY['BM commercial', 'BM military (Spanish Army)'],
 'Discontinued', 'Star BM', ARRAY['9mm Luger'],
 ARRAY['bm', 'star bm', 'star 9mm'], 'Cold War', 'Single-Action', ARRAY['military', 'collector'],
 'The Spanish Army issued the Star BM as a standard sidearm through the 1980s.',
 'Spain', true, 'Popular budget surplus pistol. Well-made and affordable on the surplus market.'),

('Star Firearms', 'Model B', '9mm Luger', 'Pistol', 'Semi-Auto', 8, 1934, true, 'Spain',
 'Prewar Spanish military pistol based on the Colt 1911. Served in WWII and beyond.',
 NULL, 34.0, 8.0, true, false,
 ARRAY['Model B Super', 'Model B military'],
 'Discontinued', 'Star Model B', ARRAY['9mm Luger', '9mm Largo'],
 ARRAY['model b', 'star b', 'star 9 largo'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 NULL, 'Spain', true, NULL),

('Star Firearms', 'Firestar', '9mm Luger', 'Pistol', 'Semi-Auto', 7, 1990, true, 'Spain',
 'Compact 1911-influenced DA/SA pistol. One of the last Star designs before the company closed.',
 NULL, 26.0, 6.3, false, false,
 ARRAY['Firestar Plus (double-stack)', 'Firestar M40 (.40 S&W)'],
 'Discontinued', 'Star Firestar', ARRAY['9mm Luger', '.40 S&W'],
 ARRAY['firestar', 'star firestar'], 'Post-Cold War', 'Double-Action', ARRAY['concealed carry', 'collector'],
 'Star Firearms closed in 1997 when the Spanish government ended their military contracts.',
 'Spain', true, NULL),

-- STEVENS ARMS
('Stevens Arms', 'Model 311', '12 Gauge', 'Shotgun', 'Side-by-Side', 2, 1931, true, 'United States',
 'Budget SxS shotgun made for generations of American hunters. Reliable and affordable.',
 NULL, 60.0, 44.0, false, false,
 ARRAY['311 Series A', '311 Series R', '311 Series H'],
 'Discontinued', 'Stevens 311', ARRAY['12 Gauge', '20 Gauge', '.410 Bore'],
 ARRAY['311', 'stevens 311', 'springfield 311'], 'Post-Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 'Millions of Model 311s were made — the default American farm and hunting SxS for decades.',
 'United States', true, 'Common and affordable. Original condition examples with all matching parts are more desirable.'),

('Stevens Arms', 'Model 520', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 1909, true, 'United States',
 'Early pump shotgun designed by John Browning. Used by US military in WWI as a trench gun.',
 NULL, 72.0, 38.0, true, false,
 ARRAY['Model 520 Trench Gun', 'Model 520-30'],
 'Discontinued', 'Stevens 520', ARRAY['12 Gauge'],
 ARRAY['520', 'stevens 520', 'springfield 520'], 'World War I', 'Trigger', ARRAY['military', 'collector'],
 'The Model 520 was one of four pump shotguns used as WWI trench guns alongside the Winchester 1897.',
 'United States', true, 'WWI trench gun variants are highly collectible. Heat shield and bayonet lug configurations command premiums.'),

('Stevens Arms', 'Model 94', '12 Gauge', 'Shotgun', 'Break-Action', 1, 1929, true, 'United States',
 'Single-shot break-action shotgun — one of the most common first guns for American youth.',
 NULL, 46.0, 42.0, false, false,
 ARRAY['Model 94 Youth', 'Model 94C'],
 'Discontinued', 'Stevens 94', ARRAY['12 Gauge', '20 Gauge', '.410 Bore'],
 ARRAY['model 94', 'stevens 94', 'springfield 94'], 'Cold War', 'Trigger', ARRAY['hunting', 'collector'],
 NULL, 'United States', false, NULL),

-- TANFOGLIO
('Tanfoglio', 'Stock III', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2005, false, 'Italy',
 'EAA-imported CZ 75-based competition pistol with match trigger and extended sights.',
 1299, 44.0, 8.7, false, false,
 ARRAY['Stock III 9mm', 'Stock III .40 S&W', 'Stock III .45 ACP'],
 'Active', 'Tanfoglio Stock', ARRAY['9mm Luger', '.40 S&W', '.45 ACP'],
 ARRAY['stock iii', 'tanfoglio stock 3', 'eaa witness stock'], 'Modern', 'Double-Action', ARRAY['competition'],
 'The Tanfoglio Stock III is one of the top choices for IPSC Standard division competition.',
 'Italy', false, NULL),

('Tanfoglio', 'Witness', '9mm Luger', 'Pistol', 'Semi-Auto', 16, 1992, false, 'Italy',
 'CZ 75-derived full-size DA/SA pistol imported by EAA Corporation.',
 499, 33.0, 8.1, false, false,
 ARRAY['Witness Compact', 'Witness P (polymer)', 'Witness Elite Match'],
 'Active', 'Tanfoglio Witness', ARRAY['9mm Luger', '.40 S&W', '.45 ACP', '10mm Auto'],
 ARRAY['witness', 'tanfoglio witness', 'eaa witness'], 'Post-Cold War', 'Double-Action', ARRAY['home defense', 'competition'],
 NULL, 'Italy', false, NULL),

('Tanfoglio', 'GT27', '.25 ACP', 'Pistol', 'Semi-Auto', 6, 1978, true, 'Italy',
 'Small DA/SA Italian pocket pistol, imported before the Witness era.',
 NULL, 13.0, 4.7, false, false, ARRAY['GT27 standard'],
 'Discontinued', 'Tanfoglio GT', ARRAY['.25 ACP'],
 ARRAY['gt27', 'tanfoglio 25'], 'Cold War', 'Double-Action', ARRAY['collector'],
 NULL, 'Italy', false, NULL),

-- TARAN TACTICAL
('Taran Tactical', 'Combat Master', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2015, false, 'United States',
 'Custom GLOCK-based competition pistol built by Taran Butler — gunsmith to action movie stars.',
 3500, 24.0, 7.4, false, false,
 ARRAY['Combat Master G17', 'Combat Master G34', 'Combat Master G19'],
 'Active', 'TTI Combat Master', ARRAY['9mm Luger'],
 ARRAY['combat master', 'tti glock', 'taran glock'], 'Modern', 'Striker-Fired', ARRAY['competition'],
 'Taran Butler built the Glocks used by Keanu Reeves in John Wick 2 and 3.',
 'United States', false, NULL),

('Taran Tactical', 'SandStorm', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2019, false, 'United States',
 'Custom Staccato 2011-based competition pistol.',
 3999, 27.0, 5.4, false, false, ARRAY['SandStorm 9mm', 'SandStorm .40'],
 'Active', 'TTI SandStorm', ARRAY['9mm Luger', '.40 S&W'],
 ARRAY['sandstorm', 'tti sandstorm'], 'Modern', 'Single-Action', ARRAY['competition'],
 NULL, 'United States', false, NULL),

('Taran Tactical', 'STI TTI', '9mm Luger', 'Pistol', 'Semi-Auto', 20, 2016, false, 'United States',
 'Custom 2011 pistol built on STI/Staccato frame for USPSA competition.',
 3799, 40.0, 8.5, false, false, ARRAY['STI TTI standard'],
 'Active', 'TTI STI', ARRAY['9mm Luger'],
 ARRAY['sti tti', 'taran sti'], 'Modern', 'Single-Action', ARRAY['competition'],
 NULL, 'United States', false, NULL),

-- THOMPSON/CENTER ARMS
('Thompson/Center Arms', 'Contender', '.22 LR', 'Pistol', 'Single-Shot', 1, 1967, false, 'United States',
 'Break-open single-shot pistol with interchangeable barrels in 30+ calibers. The benchmark of versatile single-shots.',
 699, 45.0, 13.0, false, false,
 ARRAY['Contender G2', 'Super 14 Contender', 'Super 16 Contender'],
 'Active', 'T/C Contender', ARRAY['.22 LR', '.357 Magnum', '.44 Magnum', '.45-70 Government', '7mm-08 Remington'],
 ARRAY['contender', 'tc contender', 'thompson center contender'], 'Modern', 'Single-Action', ARRAY['hunting', 'competition'],
 'The Contender can be converted to 30+ calibers by swapping barrels — one frame covers everything from .22 LR to .45-70.',
 'United States', false, NULL),

('Thompson/Center Arms', 'Encore', '.308 Winchester', 'Rifle', 'Single-Shot', 1, 1996, false, 'United States',
 'Larger Contender derivative designed for rifle calibers up to .375 H&H.',
 699, 80.0, 40.0, false, false,
 ARRAY['Encore Pro Hunter', 'Encore Rifle', 'Encore Muzzleloader'],
 'Active', 'T/C Encore', ARRAY['.308 Winchester', '.30-06 Springfield', '.300 Win Mag', '.45-70 Government', '.375 H&H Magnum'],
 ARRAY['encore', 'tc encore'], 'Modern', 'Single-Action', ARRAY['hunting'],
 NULL, 'United States', false, NULL),

('Thompson/Center Arms', 'Hawken', '.50 Caliber', 'Rifle', 'Single-Shot', 1, 1970, false, 'United States',
 'Traditional percussion muzzleloader based on the classic Hawken plains rifle design.',
 499, 80.0, 45.0, false, false,
 ARRAY['Hawken .45', 'Hawken .54', 'Hawken Flintlock'],
 'Active', 'T/C Hawken', ARRAY['.50 Caliber', '.45 Caliber', '.54 Caliber'],
 ARRAY['hawken', 'tc hawken', 'thompson hawken'], 'Modern', 'Trigger', ARRAY['hunting', 'collector'],
 'The T/C Hawken sparked the black powder revival of the 1970s and inspired thousands to take up muzzleloading.',
 'United States', false, NULL),

-- TRADITIONS FIREARMS
('Traditions Firearms', 'Buckstalker', '.50 Caliber', 'Rifle', 'Single-Shot', 1, 2005, false, 'United States',
 'In-line muzzleloader for deer hunting. Affordable and reliable.',
 249, 80.0, 42.0, false, false,
 ARRAY['Buckstalker XT', 'Buckstalker Ultralight'],
 'Active', 'Traditions Buckstalker', ARRAY['.50 Caliber'],
 ARRAY['buckstalker', 'traditions buckstalker'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'United States', false, NULL),

('Traditions Firearms', 'Nitrofire', '.50 Caliber', 'Rifle', 'Single-Shot', 1, 2020, false, 'United States',
 'Bolt-action in-line muzzleloader using Federal FireStick pre-loaded primer system.',
 449, 84.0, 44.0, false, false, ARRAY['Nitrofire standard', 'Nitrofire Elite XT'],
 'Active', 'Traditions Nitrofire', ARRAY['.50 Caliber'],
 ARRAY['nitrofire', 'traditions nitrofire'], 'Modern', 'Trigger', ARRAY['hunting'],
 'The FireStick system allows the muzzleloader to be safely unloaded — a first for in-line ignition.',
 'United States', false, NULL),

('Traditions Firearms', '1851 Navy', '.44 Caliber', 'Revolver', 'Single-Action', 6, 1980, false, 'United States',
 'Replica of the Colt Model 1851 Navy cap-and-ball revolver.',
 299, 39.0, 13.0, false, false, ARRAY['1851 Navy brass frame', '1851 Navy steel frame'],
 'Active', 'Traditions 1851 Navy', ARRAY['.44 Caliber'],
 ARRAY['1851 navy', 'traditions 1851'], 'Modern', 'Single-Action', ARRAY['hunting', 'collector'],
 NULL, 'United States', false, NULL),

-- TRISTAR ARMS
('TriStar Arms', 'Viper G2', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 2010, false, 'Turkey',
 'Gas-operated semi-auto with chrome-lined barrel. Value-priced Turkish import.',
 499, 68.0, 46.0, false, false,
 ARRAY['Viper G2 Youth', 'Viper G2 Synthetic', 'Viper G2 Wood'],
 'Active', 'TriStar Viper G2', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['viper g2', 'tristar viper'], 'Modern', 'Trigger', ARRAY['hunting', 'home defense'],
 NULL, 'Turkey', false, NULL),

('TriStar Arms', 'Cobra', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 2005, false, 'Turkey',
 'Budget pump-action shotgun in the Mossberg 500 style.',
 249, 60.0, 38.0, false, false,
 ARRAY['Cobra Field', 'Cobra Tactical'],
 'Active', 'TriStar Cobra', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['cobra', 'tristar cobra'], 'Modern', 'Trigger', ARRAY['hunting', 'home defense'],
 NULL, 'Turkey', false, NULL),

('TriStar Arms', 'TT-15', '12 Gauge', 'Shotgun', 'Over-Under', 2, 2012, false, 'Turkey',
 'Budget O/U shotgun imported from Turkey for entry-level sporting use.',
 499, 72.0, 44.0, false, false,
 ARRAY['TT-15 Field', 'TT-15 Sporting'],
 'Active', 'TriStar TT-15', ARRAY['12 Gauge'],
 ARRAY['tt15', 'tristar tt15'], 'Modern', 'Trigger', ARRAY['hunting', 'sport'],
 NULL, 'Turkey', false, NULL),

-- UNDERWOOD TYPEWRITER
('Underwood Typewriter', 'M1 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 15, 1943, true, 'United States',
 'WWII M1 Carbine manufactured by Underwood Typewriter Company (~545,000 units).',
 NULL, 51.0, 35.6, true, false,
 ARRAY['Underwood M1 1943', 'Underwood M1 1944'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['underwood carbine', 'underwood m1', 'underwood typewriter carbine'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 'Underwood Typewriter pivoted from typewriters to carbines during WWII, producing over half a million.',
 'United States', true, 'Well-regarded WWII contractor. Underwood-marked carbines in original condition are collectible.'),

('Underwood Typewriter', 'M1 Carbine (late)', '.30 Carbine', 'Rifle', 'Semi-Auto', 30, 1944, true, 'United States',
 'Late-production Underwood M1 Carbine with second-year improvements.',
 NULL, 51.0, 35.6, true, false, ARRAY['Underwood 1944 production'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['underwood 1944', 'underwood late war'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

('Underwood Typewriter', 'M1A1 Carbine', '.30 Carbine', 'Rifle', 'Semi-Auto', 30, 1944, true, 'United States',
 'Underwood M1A1 folding-stock paratrooper carbine.',
 NULL, 51.0, 35.6, true, false, ARRAY['Underwood M1A1'],
 'Discontinued', 'M1 Carbine', ARRAY['.30 Carbine'],
 ARRAY['underwood m1a1', 'underwood paratrooper'], 'World War II', 'Trigger', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

-- UNION SWITCH & SIGNAL
('Union Switch & Signal', 'M1911A1', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1943, true, 'United States',
 'WWII M1911A1 made by Union Switch & Signal (~55,000 units). Rarest of the major WWII 1911 contractors.',
 NULL, 38.5, 8.6, true, false,
 ARRAY['US&S 1911A1 1943'],
 'Discontinued', 'M1911A1', ARRAY['.45 ACP'],
 ARRAY['us&s 1911', 'union switch signal 1911', 'uss 1911'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 'US&S made only ~55,000 1911A1s — the rarest major WWII contractor. Made in Swissvale, Pennsylvania.',
 'United States', true, 'Most sought-after of all WWII 1911 contractors due to rarity. Premium condition examples sell for $4,000+.'),

('Union Switch & Signal', 'M1911A1 (matched)', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1943, true, 'United States',
 'US&S 1911A1 with all matching serial numbers — the holy grail for WWII 1911 collectors.',
 NULL, 38.5, 8.6, true, false, ARRAY['US&S matched set'],
 'Discontinued', 'M1911A1', ARRAY['.45 ACP'],
 ARRAY['us&s matched', 'union switch matched'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 NULL, 'United States', true, 'Fully matching US&S examples are among the most valuable production 1911s.'),

('Union Switch & Signal', 'M1911A1 (arsenal rework)', '.45 ACP', 'Pistol', 'Semi-Auto', 7, 1945, true, 'United States',
 'Arsenal-reworked US&S 1911A1 with mixed parts from multiple contractors.',
 NULL, 38.5, 8.6, true, false, ARRAY['US&S arsenal rework'],
 'Discontinued', 'M1911A1', ARRAY['.45 ACP'],
 ARRAY['us&s rework'], 'World War II', 'Single-Action', ARRAY['military', 'collector'],
 NULL, 'United States', true, NULL),

-- USFA (UNITED STATES FIRE ARMS)
('USFA', 'Single Action Army', '.45 Colt', 'Revolver', 'Single-Action', 6, 1993, true, 'United States',
 'American-made Colt SAA replica built to pre-war quality standards in Hartford, CT.',
 NULL, 40.0, 11.0, false, false,
 ARRAY['SAA Pre-War Frame', 'SAA Flattop', 'SAA Bisley'],
 'Discontinued', 'USFA SAA', ARRAY['.45 Colt', '.44-40 Winchester', '.38 Special'],
 ARRAY['usfa saa', 'usfa colt', 'us fire arms saa'], 'Modern', 'Single-Action', ARRAY['hunting', 'collector'],
 'USFA made arguably the finest modern SAA replicas — built by Colt toolmakers in Hartford.',
 'United States', true, 'Highly collectible. USFA closed in 2011. Quality equal to original Colts commands premiums.'),

('USFA', 'Rodeo', '.45 Colt', 'Revolver', 'Single-Action', 6, 2000, true, 'United States',
 'Entry-level USFA SAA for cowboy action shooting with matte finish.',
 NULL, 38.0, 11.0, false, false, ARRAY['Rodeo standard'],
 'Discontinued', 'USFA Rodeo', ARRAY['.45 Colt', '.38 Special'],
 ARRAY['rodeo', 'usfa rodeo'], 'Modern', 'Single-Action', ARRAY['hunting', 'sport', 'collector'],
 NULL, 'United States', true, NULL),

('USFA', 'ZIP .22', '.22 LR', 'Pistol', 'Semi-Auto', 10, 2013, true, 'United States',
 'Unusual bullpup .22 LR pistol — one of USFA''s final products before closure. Widely considered a failure.',
 NULL, 16.0, 6.5, false, false, ARRAY['ZIP .22 standard'],
 'Discontinued', 'USFA ZIP', ARRAY['.22 LR'],
 ARRAY['zip 22', 'usfa zip'], 'Modern', 'Striker-Fired', ARRAY['collector'],
 'The ZIP .22 was universally panned by reviewers and may have contributed to USFA''s closure.',
 'United States', true, 'Collectible as a curiosity and commercial failure.'),

-- VOERE
('Voere', 'Model 2165', '.22 LR', 'Rifle', 'Semi-Auto', 10, 1975, false, 'Austria',
 'Austrian semi-auto .22 LR rifle with detachable box magazine and walnut stock.',
 699, 56.0, 38.0, false, false,
 ARRAY['Model 2165 Deluxe', 'Model 2115'],
 'Active', 'Voere 2165', ARRAY['.22 LR'],
 ARRAY['2165', 'voere 22', 'voere semi'], 'Modern', 'Trigger', ARRAY['hunting', 'plinking'],
 NULL, 'Austria', false, NULL),

('Voere', 'Model 2185', '.222 Remington', 'Rifle', 'Bolt-Action', 5, 1985, false, 'Austria',
 'Austrian premium bolt-action for European game hunting.',
 1299, 88.0, 40.0, false, false,
 ARRAY['Model 2185 standard', 'Model 2185 Magnum'],
 'Active', 'Voere 2185', ARRAY['.222 Remington', '.308 Winchester', '.30-06 Springfield'],
 ARRAY['2185', 'voere bolt action'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Austria', false, NULL),

('Voere', 'VEC-91', '5.56x26mm UCC', 'Rifle', 'Bolt-Action', 5, 1991, true, 'Austria',
 'Electric primer ignition rifle using Voere''s caseless cartridge technology. Revolutionary concept.',
 NULL, 96.0, 42.0, false, false, ARRAY['VEC-91 standard'],
 'Discontinued', 'Voere VEC', ARRAY['5.56x26mm UCC'],
 ARRAY['vec91', 'voere caseless', 'voere vec'], 'Post-Cold War', 'Trigger', ARRAY['collector'],
 'The VEC-91 used battery-powered electric ignition of caseless ammunition — the first commercial caseless rifle.',
 'Austria', true, 'Extremely rare and collectible. Caseless ammunition is no longer manufactured.'),

-- YILDIZ
('Yildiz', 'SPZ ME', '12 Gauge', 'Shotgun', 'Semi-Auto', 4, 2005, false, 'Turkey',
 'Turkish gas-operated semi-auto hunting shotgun. Budget import with good reliability.',
 349, 70.0, 46.0, false, false,
 ARRAY['SPZ ME Youth', 'SPZ ME Synthetic'],
 'Active', 'Yildiz SPZ', ARRAY['12 Gauge', '20 Gauge'],
 ARRAY['spz me', 'yildiz semi'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Turkey', false, NULL),

('Yildiz', 'SPX ME', '12 Gauge', 'Shotgun', 'Over-Under', 2, 2000, false, 'Turkey',
 'Budget Turkish O/U for hunting and entry-level sporting.',
 349, 72.0, 44.0, false, false,
 ARRAY['SPX ME Field', 'SPX ME Sporting'],
 'Active', 'Yildiz SPX', ARRAY['12 Gauge', '20 Gauge', '28 Gauge'],
 ARRAY['spx me', 'yildiz ou'], 'Modern', 'Trigger', ARRAY['hunting', 'sport'],
 NULL, 'Turkey', false, NULL),

('Yildiz', 'TK36', '12 Gauge', 'Shotgun', 'Side-by-Side', 2, 2010, false, 'Turkey',
 'Turkish SxS budget hunting shotgun.',
 299, 64.0, 44.0, false, false, ARRAY['TK36 Field'],
 'Active', 'Yildiz TK36', ARRAY['12 Gauge', '20 Gauge', '.410 Bore'],
 ARRAY['tk36', 'yildiz sxs'], 'Modern', 'Trigger', ARRAY['hunting'],
 NULL, 'Turkey', false, NULL),

-- ZEV TECHNOLOGIES
('ZEV Technologies', 'OZ9', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2018, false, 'United States',
 'In-house striker-fired pistol with aluminum frame and modular chassis system.',
 999, 25.6, 7.5, false, false,
 ARRAY['OZ9 Standard', 'OZ9 Compact', 'OZ9 Elite'],
 'Active', 'ZEV OZ9', ARRAY['9mm Luger'],
 ARRAY['oz9', 'zev oz9', 'zev pistol'], 'Modern', 'Striker-Fired', ARRAY['competition', 'home defense'],
 NULL, 'United States', false, NULL),

('ZEV Technologies', 'HEX Dragonfly', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2021, false, 'United States',
 'Custom Glock-platform competition pistol with ZEV slide and frame modifications.',
 1299, 24.5, 7.4, false, false,
 ARRAY['Dragonfly G17', 'Dragonfly G19'],
 'Active', 'ZEV Dragonfly', ARRAY['9mm Luger'],
 ARRAY['dragonfly', 'zev dragonfly'], 'Modern', 'Striker-Fired', ARRAY['competition'],
 NULL, 'United States', false, NULL),

('ZEV Technologies', 'Core Elite Duty', '9mm Luger', 'Pistol', 'Semi-Auto', 17, 2020, false, 'United States',
 'Duty-oriented OZ9 variant with front rail and enhanced grip texture.',
 1099, 25.8, 7.5, false, true, ARRAY['Core Elite Duty standard'],
 'Active', 'ZEV Core', ARRAY['9mm Luger'],
 ARRAY['core elite', 'zev core'], 'Modern', 'Striker-Fired', ARRAY['law enforcement', 'home defense'],
 NULL, 'United States', false, NULL),

-- ZERMATT ARMS
('Zermatt Arms', 'RimX', '.22 LR', 'Rifle', 'Bolt-Action', 10, 2018, false, 'United States',
 'Precision rimfire action designed to drop into chassis systems. The go-to rimfire precision action.',
 799, 40.0, NULL, false, false,
 ARRAY['RimX barreled action', 'RimX barreled action threaded'],
 'Active', 'Zermatt RimX', ARRAY['.22 LR', '.17 HMR', '.22 WMR'],
 ARRAY['rimx', 'zermatt rimx', 'bighorn rimx'], 'Modern', 'Trigger', ARRAY['competition', 'hunting'],
 'The RimX is considered the benchmark precision rimfire action for PRS Rimfire competition.',
 'United States', false, NULL),

('Zermatt Arms', 'Origin', '6.5 Creedmoor', 'Rifle', 'Bolt-Action', 5, 2018, false, 'United States',
 'Bighorn Arms-branded precision centerfire action for custom rifle builds.',
 999, 48.0, NULL, false, false,
 ARRAY['Origin short action', 'Origin long action'],
 'Active', 'Zermatt Origin', ARRAY['6.5 Creedmoor', '.308 Winchester', '.300 Win Mag'],
 ARRAY['origin', 'zermatt origin', 'bighorn origin'], 'Modern', 'Trigger', ARRAY['competition', 'hunting'],
 NULL, 'United States', false, NULL),

('Zermatt Arms', 'TL3', '.308 Winchester', 'Rifle', 'Bolt-Action', 5, 2021, false, 'United States',
 'Hunting-oriented precision bolt action, lighter than the Origin.',
 699, 36.0, NULL, false, false, ARRAY['TL3 short action', 'TL3 long action'],
 'Active', 'Zermatt TL3', ARRAY['.308 Winchester', '6.5 Creedmoor', '7mm-08 Remington'],
 ARRAY['tl3', 'zermatt tl3'], 'Modern', 'Trigger', ARRAY['hunting', 'competition'],
 NULL, 'United States', false, NULL)

ON CONFLICT (make, model) DO NOTHING;
