-- ============================================================
-- Gun Models Batch A–E: Fill manufacturers with 0 models
-- ============================================================

INSERT INTO public.gun_models (
  make, model, caliber, type, action, capacity, year_introduced,
  discontinued, country_of_origin, description, msrp_usd,
  weight_oz_unloaded, overall_length_in,
  military_use, law_enforcement_use, notable_variants,
  production_status, platform_family, caliber_options, model_aliases,
  era, trigger_type, intended_use, trivia, country_of_manufacture,
  is_collectible, collector_notes
) VALUES

-- ── AMT ──────────────────────────────────────────────────────
('AMT', 'Hardballer', '.45 ACP', 'Pistol', 'Single-Action', 7, 1977, true, 'United States', 'All-stainless steel long-slide 1911 in .45 ACP. Made famous as the Terminator''s weapon in the 1984 film.', 400, 42.0, 8.5, false, false, ARRAY['Hardballer Longslide (7" barrel)'], 'Discontinued', 'AMT Hardballer', ARRAY['.45 ACP'], ARRAY['hardballer', 'amt 1911'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], 'Arnold Schwarzenegger''s T-800 used the Hardballer Longslide in The Terminator — making it one of the most recognizable pistols in cinema history.', 'United States', true, 'Original AMT examples command collector premiums; later Galena/IAI versions are less desirable.'),

('AMT', 'Backup', '.380 ACP', 'Pistol', 'DA/SA', 5, 1976, true, 'United States', 'Compact all-stainless backup pistol in .380 ACP with a smooth double-action trigger. One of the earliest production stainless pocket pistols.', 300, 18.0, 5.0, false, false, ARRAY['Backup .45 ACP', 'Backup .38 Super', 'Backup .357 SIG'], 'Discontinued', 'AMT Backup', ARRAY['.380 ACP', '.45 ACP'], ARRAY['amt backup', 'backup 380'], 'Modern', 'DA/SA', ARRAY['carry'], NULL, 'United States', false, NULL),

('AMT', 'Automag II', '.22 Magnum', 'Pistol', 'Semi-Auto', 9, 1987, true, 'United States', 'Stainless semi-automatic pistol chambered in .22 Winchester Magnum Rimfire — one of the few production pistols ever offered in this caliber.', 350, 24.0, 6.0, false, false, ARRAY['Automag III (.30 Carbine)', 'Automag IV (.45 Win Mag)'], 'Discontinued', 'AMT Automag', ARRAY['.22 Magnum'], ARRAY['automag ii', 'amt automag 22 mag'], 'Modern', 'Single-Action', ARRAY['hunting', 'collector'], 'The .22 Magnum semi-auto pistol is an extremely niche product category. The Automag II was one of only a handful of production pistols ever offered in this caliber.', 'United States', false, NULL),

-- ── AMERICAN DERRINGER ────────────────────────────────────────
('American Derringer', 'Model 1', '.38 Special', 'Pistol', 'Single-Action', 2, 1980, false, 'United States', 'Over-under double-barrel derringer available in over 50 calibers from .22 LR to .45-70 Government. The most versatile derringer line ever produced.', 320, 15.5, 4.8, false, false, ARRAY['Model 1 in .45 Colt', 'Model 1 in .45-70', 'Model 1 in .44 Magnum'], 'Active', 'American Derringer Model 1', ARRAY['.38 Special', '.357 Magnum', '.45 Colt', '.45-70'], ARRAY['model 1 derringer', 'adc model 1'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], 'American Derringer offers the Model 1 in more calibers than virtually any other production handgun, including .45-70 Government.', 'United States', false, NULL),

('American Derringer', 'Lady Derringer', '.38 Special', 'Pistol', 'Single-Action', 2, 1985, false, 'United States', 'Engraved over-under derringer with rosewood or mother-of-pearl grips, marketed as a refined concealed carry option for women. Same mechanism as the Model 1.', 395, 15.5, 4.8, false, false, NULL, 'Active', 'American Derringer Lady', ARRAY['.38 Special', '.32 H&R Mag'], ARRAY['lady derringer', 'adc lady'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], NULL, 'United States', false, NULL),

('American Derringer', 'Model 4', '.357 Magnum', 'Pistol', 'Single-Action', 2, 1985, false, 'United States', 'Larger over-under derringer with a longer 4.1" barrel, offering better ballistics with the .357 Magnum and .45-70 Government in a more manageable platform than the Model 1.', 425, 16.5, 6.0, false, false, ARRAY['Model 4 in .45-70', 'Model 4 Alaskan Survival'], 'Active', 'American Derringer Model 4', ARRAY['.357 Magnum', '.45-70'], ARRAY['model 4 derringer'], 'Modern', 'Single-Action', ARRAY['carry', 'hunting', 'collector'], NULL, 'United States', false, NULL),

-- ── AMERICAN TACTICAL ─────────────────────────────────────────
('American Tactical', 'AT-47 AK', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 2010, false, 'United States', 'AK-pattern semi-automatic rifle imported and assembled by American Tactical Imports. Available in Standard and Tactical configurations.', 599, 128.0, 36.5, false, false, ARRAY['AT-47 Tactical', 'AT-47 Milled'], 'Active', 'ATI AK', ARRAY['7.62x39mm'], ARRAY['at47', 'ati ak47'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'Turkey', false, NULL),

('American Tactical', 'FXH-45 1911', '.45 ACP', 'Pistol', 'Single-Action', 8, 2012, false, 'United States', 'Full-size 1911 imported by American Tactical, featuring a standard GI-spec layout at a competitive price point.', 549, 38.5, 8.5, false, false, ARRAY['FXH-45 Matte', 'FXH-45 GI'], 'Active', 'ATI 1911', ARRAY['.45 ACP'], ARRAY['fxh45', 'ati 1911'], 'Modern', 'Single-Action', ARRAY['sport', 'carry'], NULL, 'Philippines', false, NULL),

('American Tactical', 'Cavalry SX', '.45 ACP', 'Pistol', 'Single-Action', 8, 2015, false, 'United States', 'Enhanced 1911 with extended beavertail, skeletonized hammer, and combat sights. Positions above the basic FXH in the ATI lineup.', 699, 38.0, 8.5, false, false, NULL, 'Active', 'ATI 1911', ARRAY['.45 ACP'], ARRAY['cavalry sx', 'ati cavalry'], 'Modern', 'Single-Action', ARRAY['carry', 'competition'], NULL, 'Philippines', false, NULL),

-- ── ANDERSON MANUFACTURING ────────────────────────────────────
('Anderson Manufacturing', 'AM-15', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2010, false, 'United States', 'Budget mil-spec AR-15 carbine. One of the lowest-priced complete AR-15s from a US manufacturer, assembled on mil-spec components.', 499, 128.0, 32.0, false, false, ARRAY['AM-15 Pistol', 'AM-15 A4'], 'Active', 'Anderson AM-15', ARRAY['5.56 NATO', '.223 Rem'], ARRAY['am15', 'anderson ar15'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], 'Anderson''s AM-15 is frequently cited as one of the few complete AR-15s available under $500 from a US manufacturer.', 'United States', false, NULL),

('Anderson Manufacturing', 'AM-10', '.308 Winchester', 'Rifle', 'Semi-Auto', 20, 2014, false, 'United States', 'AR-10 platform semi-automatic rifle in .308 Winchester/7.62 NATO from Anderson Manufacturing. Uses DPMS-pattern lower.', 699, 152.0, 38.0, false, false, ARRAY['AM-10 Hunter', 'AM-10 Pistol'], 'Active', 'Anderson AM-10', ARRAY['.308 Win', '7.62 NATO'], ARRAY['am10', 'anderson 308'], 'Modern', 'Single-Action', ARRAY['hunting', 'sport'], NULL, 'United States', false, NULL),

('Anderson Manufacturing', 'AM-15 Pistol', '5.56 NATO', 'Pistol', 'Semi-Auto', 30, 2015, false, 'United States', 'AR-15 pistol configuration with short barrel and pistol brace. Budget entry into the AR pistol category.', 549, 112.0, 26.0, false, false, NULL, 'Active', 'Anderson AM-15', ARRAY['5.56 NATO', '.300 BLK'], ARRAY['anderson ar pistol'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

-- ── ANSCHUTZ ─────────────────────────────────────────────────
('Anschutz', '1710', '.22 LR', 'Rifle', 'Bolt-Action', 5, 1985, false, 'Germany', 'Anschutz 1710 is a precision .22 LR bolt-action sporting rifle offering competition-grade accuracy in a hunting-weight stock. Used by target shooters and benchrest competitors worldwide.', 1299, 87.0, 40.9, false, false, ARRAY['1710 D HB', '1710 Classic', '1710 D Classic'], 'Active', 'Anschutz 1700', ARRAY['.22 LR'], ARRAY['1710', 'anschutz 1710'], 'Modern', 'Single-Action', ARRAY['competition', 'hunting'], NULL, 'Germany', false, NULL),

('Anschutz', '1416', '.22 LR', 'Rifle', 'Bolt-Action', 5, 1990, false, 'Germany', 'Compact .22 LR bolt-action with classic European styling and the precision Anschutz 1416 action. Popular hunting and plinking rifle in Europe.', 899, 74.0, 39.0, false, false, ARRAY['1416 Classic', '1416 D HB'], 'Active', 'Anschutz 1400', ARRAY['.22 LR'], ARRAY['1416', 'anschutz 1416'], 'Modern', 'Single-Action', ARRAY['hunting', 'sport'], NULL, 'Germany', false, NULL),

('Anschutz', '1907', '.22 LR', 'Rifle', 'Bolt-Action', 5, 1957, false, 'Germany', 'Olympic-grade smallbore target rifle used in 50m prone and 3-position disciplines. The benchmark for .22 LR competition accuracy for over 60 years.', 2800, 122.0, 44.5, false, false, ARRAY['1907 in Precise', '1907 Club', '1913 Super Match'], 'Active', 'Anschutz 1900', ARRAY['.22 LR'], ARRAY['1907', 'anschutz 1907', 'anschutz match'], 'Cold War', 'Single-Action', ARRAY['competition'], 'Anschutz 1907 and 1913 rifles have won more Olympic and World Championship medals in smallbore shooting than any other rifle platform.', 'Germany', false, NULL),

-- ── ARMALITE ─────────────────────────────────────────────────
('Armalite', 'AR-10', '7.62 NATO', 'Rifle', 'Semi-Auto', 20, 1956, false, 'United States', 'The original AR-10, designed by Eugene Stoner and Armalite in 1956 — the direct ancestor of the M16. The modern Armalite AR-10 is a semi-auto .308 based on the original design. Lighter than contemporary .308 semi-autos at the time of its introduction.', 1499, 152.0, 40.5, false, false, ARRAY['AR-10 A4', 'AR-10 SuperSASS'], 'Active', 'Armalite AR-10', ARRAY['7.62 NATO', '.308 Win'], ARRAY['ar10', 'armalite ar10'], 'Cold War', 'Single-Action', ARRAY['military', 'hunting', 'competition'], 'Eugene Stoner designed the AR-10 before the AR-15; the AR-15 was a scaled-down AR-10 chambered in .223. The AR-10 is thus the grandfather of all modern AR-pattern rifles.', 'United States', true, 'Original Armalite AR-10s (1956-1960, made in Holland for Portugal/Sudan) are extremely rare and collectible.'),

('Armalite', 'AR-15', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 1964, false, 'United States', 'Armalite''s civilian version of the AR-15, the pattern that became the M16. The modern Armalite AR-15 is a mil-spec semi-automatic rifle.', 999, 128.0, 36.0, false, false, ARRAY['M15 Carbine', 'M15 Tactical'], 'Active', 'Armalite AR-15', ARRAY['5.56 NATO', '.223 Rem'], ARRAY['ar15', 'armalite ar-15', 'm15'], 'Cold War', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

('Armalite', 'M-15', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 1995, false, 'United States', 'Modern Armalite carbine-length AR-15 with M4-style features. The primary Armalite civilian AR offering in the post-AWB era.', 1099, 128.0, 32.0, false, false, ARRAY['M15 Competition', 'M15 Light Tactical'], 'Active', 'Armalite M-15', ARRAY['5.56 NATO'], ARRAY['m15', 'armalite m15'], 'Modern', 'Single-Action', ARRAY['sport', 'competition'], NULL, 'United States', false, NULL),

-- ── ARMI SPORT ───────────────────────────────────────────────
('Armi Sport', 'Sharps 1874', '.45-70 Government', 'Rifle', 'Single-Action', 1, 1990, false, 'Italy', 'Reproduction of the Sharps Model 1874 falling-block single-shot rifle. Used in BPCR silhouette competition and by Civil War/Old West reenactors.', 1199, 128.0, 47.0, false, false, ARRAY['Business Rifle', 'Sporting Rifle', 'Long Range Express'], 'Active', 'Armi Sport Sharps', ARRAY['.45-70', '.45-90', '.40-65'], ARRAY['armi sport sharps', '1874 sharps reproduction'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['competition', 'collector'], NULL, 'Italy', false, NULL),

('Armi Sport', '1858 Remington', '.44 Caliber', 'Revolver', 'Single-Action', 6, 1985, false, 'Italy', 'Percussion reproduction of the 1858 Remington Army revolver. One of the most popular Civil War revolver reproductions due to the Remington''s modern feel and top-strap frame.', 299, 41.0, 13.5, false, false, ARRAY['Stainless', 'Target', 'Sheriff'], 'Active', 'Armi Sport 1858', ARRAY['.44 Caliber'], ARRAY['1858 remington repro', 'remington army reproduction'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition'], NULL, 'Italy', false, NULL),

('Armi Sport', '1863 Springfield', '.58 Caliber', 'Rifle', 'Single-Action', 1, 1988, false, 'Italy', 'Percussion reproduction of the Model 1863 Springfield rifle-musket — the most common Union infantry rifle of the Civil War. Used extensively by reenactors and NSSA competition shooters.', 599, 128.0, 56.0, false, false, NULL, 'Active', 'Armi Sport Springfield', ARRAY['.58 Caliber'], ARRAY['springfield 1863', 'springfield musket reproduction'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition'], NULL, 'Italy', false, NULL),

-- ── ARMINIUS ─────────────────────────────────────────────────
('Arminius', 'HW3', '.22 LR', 'Revolver', 'DA/SA Revolver', 6, 1960, true, 'Germany', 'Inexpensive double-action .22 LR revolver made in Germany. Sold through European and US hardware stores as an affordable sporting revolver.', 60, 20.0, 6.5, false, false, NULL, 'Discontinued', 'Arminius HW', ARRAY['.22 LR'], ARRAY['hw3', 'arminius 22'], 'Cold War', 'DA/SA', ARRAY['sport', 'collector'], NULL, 'Germany', false, NULL),

('Arminius', 'HW38', '.38 Special', 'Revolver', 'DA/SA Revolver', 6, 1965, true, 'Germany', 'Double-action .38 Special revolver. Inexpensive service-caliber revolver imported to the US before GCA 1968 import restrictions.', 80, 24.0, 7.0, false, false, NULL, 'Discontinued', 'Arminius HW', ARRAY['.38 Special'], ARRAY['hw38', 'arminius 38'], 'Cold War', 'DA/SA', ARRAY['collector'], 'The Arminius HW38 and similar inexpensive German revolvers were directly targeted by the Gun Control Act of 1968''s sporting purposes import test.', 'Germany', false, NULL),

('Arminius', 'HW7', '.22 LR', 'Revolver', 'DA/SA Revolver', 8, 1968, true, 'Germany', 'Double-action .22 LR revolver with 8-round cylinder and adjustable sights. The most refined of the Arminius line.', 95, 22.0, 7.5, false, false, NULL, 'Discontinued', 'Arminius HW', ARRAY['.22 LR', '.22 Magnum'], ARRAY['hw7', 'arminius hw7'], 'Cold War', 'DA/SA', ARRAY['sport', 'collector'], NULL, 'Germany', false, NULL),

-- ── ASTRA ────────────────────────────────────────────────────
('Astra', 'Model 400', '9mm Largo', 'Pistol', 'Semi-Auto', 8, 1921, true, 'Spain', 'Spanish military service pistol chambered in 9mm Largo. The standard Spanish Army sidearm from the 1920s through the early 1980s. Notable for its ability to safely fire multiple 9mm variants.', NULL, 35.3, 9.4, true, true, ARRAY['Model 400 in 9mm Parabellum', 'Model 400 in .38 ACP'], 'Discontinued', 'Astra 400', ARRAY['9mm Largo', '9mm Parabellum'], ARRAY['astra 400', 'modelo 400'], 'World War II', 'Single-Action', ARRAY['military', 'collector'], 'The Astra 400 was designed to chamber and fire seven different pistol cartridges due to its strong recoil spring — including 9mm Largo, 9mm Parabellum, 9mm Steyr, and .38 ACP. This interchangeability was a significant military advantage.', 'Spain', true, 'Spanish military issue examples with matching numbers are most collectible. WWII German-contract Astra 600 variants are especially sought.'),

('Astra', 'Model 600', '9mm Parabellum', 'Pistol', 'Semi-Auto', 8, 1943, true, 'Spain', 'Wartime production pistol made under German contract in 9mm Parabellum. A compact version of the 400 series made specifically for the Wehrmacht. Approximately 59,000 produced before the war ended.', NULL, 32.0, 8.1, true, false, NULL, 'Discontinued', 'Astra 600', ARRAY['9mm Parabellum'], ARRAY['astra 600', 'modelo 600'], 'World War II', 'Single-Action', ARRAY['military', 'collector'], 'The Astra 600 was ordered by Germany in 1943 but the war ended before full delivery could be made. Many undelivered pistols were subsequently sold to the Spanish police and exported.', 'Spain', true, 'German-contract 600s with German acceptance stamps command significant premiums.'),

('Astra', 'Constable', '.380 ACP', 'Pistol', 'DA/SA', 7, 1969, true, 'Spain', 'Modern double-action compact pistol from Astra chambered in .380 ACP. Sold widely in the US through the 1970s and 1980s as a concealed carry pistol. Clean design with Walther PP-inspired layout.', 250, 26.0, 6.5, false, false, ARRAY['Constable in .22 LR', 'Constable Sport'], 'Discontinued', 'Astra Constable', ARRAY['.380 ACP', '.22 LR'], ARRAY['constable', 'astra constable'], 'Cold War', 'DA/SA', ARRAY['carry', 'collector'], NULL, 'Spain', false, NULL),

-- ── B&T AG ────────────────────────────────────────────────────
('B&T AG', 'APC9', '9mm Luger', 'Rifle', 'Semi-Auto', 30, 2015, false, 'Switzerland', 'Swiss-made 9mm semi-automatic carbine with a folding stock, ambidextrous controls, and modular rail system. Widely adopted by European law enforcement and military special units. Civilian semi-auto version available in the US.', 2299, 112.0, 26.8, false, true, ARRAY['APC9 Pro', 'APC9 SD (suppressed)', 'APC9 K (compact)'], 'Active', 'B&T APC', ARRAY['9mm Luger'], ARRAY['apc9', 'bt apc9'], 'Modern', 'Single-Action', ARRAY['military', 'sport'], NULL, 'Switzerland', false, NULL),

('B&T AG', 'USW-A1', '9mm Luger', 'Pistol', 'Striker-Fired', 17, 2016, false, 'Switzerland', 'Universal Service Weapon — a large-format pistol/PDW with a folding stock, making it both a pistol and a personal defense weapon. Features a proprietary folding arm brace. Designed for vehicle crews and plainclothes officers.', 2099, 39.0, 8.7, false, true, ARRAY['USW-A1 with suppressor mount'], 'Active', 'B&T USW', ARRAY['9mm Luger'], ARRAY['usw-a1', 'bt usw'], 'Modern', 'Striker-Fired', ARRAY['military', 'sport'], NULL, 'Switzerland', false, NULL),

('B&T AG', 'TP9', '9mm Luger', 'Pistol', 'Single-Action', 20, 2004, false, 'Switzerland', 'Swiss precision 9mm semi-automatic pistol used by Swiss military and law enforcement. Features a rotating barrel lockup, ambidextrous controls, and a modular design. The current standard sidearm of the Swiss Army.', 1899, 30.0, 7.5, true, true, ARRAY['TP9 N (no decocker)', 'TP9 SF (single-fire)'], 'Active', 'B&T TP9', ARRAY['9mm Luger'], ARRAY['tp9', 'bt tp9'], 'Modern', 'Single-Action', ARRAY['military', 'carry'], NULL, 'Switzerland', true, NULL),

-- ── BERNARDELLI ───────────────────────────────────────────────
('Bernardelli', 'P-018', '9mm Luger', 'Pistol', 'DA/SA', 16, 1985, true, 'Italy', 'Full-size 9mm double-action service pistol from Vincenzo Bernardelli. Offered a high-capacity 16+1 magazine when most DA/SA pistols were limited to 13-15 rounds.', 450, 35.0, 8.2, false, false, ARRAY['P-018 Compact'], 'Discontinued', 'Bernardelli P-018', ARRAY['9mm Luger'], ARRAY['p018', 'bernardelli 9mm'], 'Cold War', 'DA/SA', ARRAY['carry', 'collector'], NULL, 'Italy', false, NULL),

('Bernardelli', 'Model 60', '.22 LR', 'Pistol', 'Semi-Auto', 10, 1960, true, 'Italy', 'Target .22 LR semi-automatic pistol with adjustable sights and a well-regarded trigger. Popular for European target competition in the 1960s–1980s.', 350, 26.0, 8.5, false, false, NULL, 'Discontinued', 'Bernardelli Model 60', ARRAY['.22 LR'], ARRAY['model 60', 'bernardelli 22'], 'Cold War', 'Single-Action', ARRAY['competition', 'collector'], NULL, 'Italy', false, NULL),

('Bernardelli', 'Practical VB', '.32 ACP', 'Pistol', 'Semi-Auto', 8, 1975, true, 'Italy', 'Compact semi-automatic pocket pistol chambered in .32 ACP. Entry-level carry pistol for the European market. Imported to the US in limited quantities.', 250, 18.0, 6.0, false, false, ARRAY['Practical VB in .22 LR'], 'Discontinued', 'Bernardelli Practical', ARRAY['.32 ACP', '.22 LR'], ARRAY['practical vb', 'bernardelli 32'], 'Cold War', 'Single-Action', ARRAY['carry', 'collector'], NULL, 'Italy', false, NULL),

-- ── BERSA ────────────────────────────────────────────────────
('Bersa', 'Thunder 380', '.380 ACP', 'Pistol', 'DA/SA', 7, 1985, false, 'Argentina', 'Argentine DA/SA semi-automatic pistol in .380 ACP. One of the best-selling .380 carry pistols in Latin America and popular in the US as an affordable Walther PPK-style alternative.', 329, 20.5, 6.6, false, false, ARRAY['Thunder 380 Plus (15-round)', 'Thunder 380 CC'], 'Active', 'Bersa Thunder', ARRAY['.380 ACP'], ARRAY['thunder 380', 'bersa 380'], 'Modern', 'DA/SA', ARRAY['carry'], NULL, 'Argentina', false, NULL),

('Bersa', 'Thunder 9', '9mm Luger', 'Pistol', 'DA/SA', 17, 1993, false, 'Argentina', 'Full-size DA/SA service pistol in 9mm. Larger sibling to the Thunder 380, with an alloy frame and double-stack magazine. Used by Argentine law enforcement agencies.', 399, 30.0, 7.9, false, true, ARRAY['Thunder 9 Ultra Compact', 'Thunder 9 Pro'], 'Active', 'Bersa Thunder', ARRAY['9mm Luger'], ARRAY['thunder 9', 'bersa 9mm'], 'Modern', 'DA/SA', ARRAY['carry', 'service'], NULL, 'Argentina', false, NULL),

('Bersa', 'BP9CC', '9mm Luger', 'Pistol', 'Striker-Fired', 8, 2012, false, 'Argentina', 'Compact striker-fired 9mm with a polymer frame and single-stack magazine. Bersa''s entry into the modern CCW striker-fired market.', 349, 21.5, 6.4, false, false, NULL, 'Active', 'Bersa BP', ARRAY['9mm Luger'], ARRAY['bp9cc', 'bersa bp9'], 'Modern', 'Striker-Fired', ARRAY['carry'], NULL, 'Argentina', false, NULL),

-- ── BLASER ───────────────────────────────────────────────────
('Blaser', 'R8', 'Various', 'Rifle', 'Bolt-Action', 3, 1998, false, 'Germany', 'Straight-pull bolt-action hunting rifle with a unique radial collet locking system and modular barrel/caliber exchange. The R8 can be switched between calibers in seconds without tools. Used by professional hunters worldwide.', 3995, 112.0, 40.0, false, false, ARRAY['R8 Professional Success', 'R8 Ultimate', 'R8 Safari'], 'Active', 'Blaser R8', ARRAY['Various', '.30-06', '9.3x62', '.300 Win Mag', '6.5 Creedmoor'], ARRAY['blaser r8', 'r8'], 'Modern', 'Single-Action', ARRAY['hunting', 'competition'], 'The Blaser R8 straight-pull bolt requires only about 50mm of bolt movement to cycle — roughly half that of a conventional turn-bolt. This dramatically increases follow-up shot speed.', 'Germany', false, NULL),

('Blaser', 'R93', 'Various', 'Rifle', 'Bolt-Action', 3, 1993, true, 'Germany', 'Predecessor to the R8 — the first commercially successful straight-pull bolt-action hunting rifle. The R93 established the Blaser approach of modular caliber exchange and fast-cycling straight-pull operation.', 2999, 108.0, 40.0, false, false, ARRAY['R93 Synthetic', 'R93 Professional', 'R93 LRS2 (long-range sniper)'], 'Discontinued', 'Blaser R93', ARRAY['Various'], ARRAY['blaser r93', 'r93'], 'Modern', 'Single-Action', ARRAY['hunting', 'competition'], 'The R93 LRS2 variant was used as a military sniper rifle by several nations, making the Blaser straight-pull one of the rare hunting-origin rifles to see genuine military service.', 'Germany', true, NULL),

('Blaser', 'F3', '12 Gauge', 'Shotgun', 'Break-Action', 2, 2005, false, 'Germany', 'Competition over-and-under shotgun from Blaser, offered in sporting, trap, and skeet configurations. Features an adjustable comb and Blaser''s signature aesthetic.', 4200, 108.0, 47.0, false, false, ARRAY['F3 Supersport', 'F3 Attache', 'F3 Game'], 'Active', 'Blaser F3', ARRAY['12 Gauge', '20 Gauge'], ARRAY['blaser f3', 'f3 shotgun'], 'Modern', 'Single-Action', ARRAY['competition', 'hunting'], NULL, 'Germany', false, NULL),

-- ── BOND ARMS ─────────────────────────────────────────────────
('Bond Arms', 'Roughneck', '9mm Luger', 'Pistol', 'Single-Action', 2, 2018, false, 'United States', 'Entry-level over-under derringer from Bond Arms in 9mm Luger with a matte black finish. The most affordable Bond Arms derringer.', 299, 19.5, 4.5, false, false, NULL, 'Active', 'Bond Arms Roughneck', ARRAY['9mm Luger', '.357 Mag', '.45 ACP'], ARRAY['roughneck', 'bond roughneck'], 'Modern', 'Single-Action', ARRAY['carry'], NULL, 'United States', false, NULL),

('Bond Arms', 'Cowboy Defender', '.45 Colt', 'Pistol', 'Single-Action', 2, 2000, false, 'United States', 'Classic-style over-under derringer with a long trigger guard, chambered in .45 Colt/.410. Popular with cowboy action shooters and as a trail gun.', 399, 19.5, 5.0, false, false, NULL, 'Active', 'Bond Arms Classic', ARRAY['.45 Colt / .410', '.38 Special', '.357 Mag'], ARRAY['cowboy defender', 'bond cowboy'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], NULL, 'United States', false, NULL),

('Bond Arms', 'Snake Slayer', '.45 Colt', 'Pistol', 'Single-Action', 2, 2005, false, 'United States', 'Extended 3.5" barrel derringer chambered in .45 Colt/.410, designed as a trail and snake gun. The longer barrel provides better performance with .410 shotshell loads.', 459, 22.0, 5.5, false, false, ARRAY['Snake Slayer IV (4.25" barrel)'], 'Active', 'Bond Arms Snake Slayer', ARRAY['.45 Colt / .410'], ARRAY['snake slayer', 'bond snake slayer'], 'Modern', 'Single-Action', ARRAY['carry', 'hunting'], NULL, 'United States', false, NULL),

-- ── BRAVO COMPANY (BCM) ───────────────────────────────────────
('Bravo Company (BCM)', 'BCM4 RECCE-16', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2004, false, 'United States', 'Mil-spec AR-15 carbine with a 16" mid-length gas system barrel. BCM''s flagship configuration, built to Crane Naval Surface Warfare Center specifications. The standard by which mil-spec AR-15s are judged.', 1299, 128.0, 32.5, false, true, ARRAY['RECCE-14', 'RECCE-11', 'RECCE-16 MCMR'], 'Active', 'BCM RECCE', ARRAY['5.56 NATO', '.223 Wylde'], ARRAY['bcm recce-16', 'bcm ar15', 'recce 16'], 'Modern', 'Single-Action', ARRAY['military', 'sport', 'home defense'], 'BCM is one of a small number of civilian AR-15 manufacturers that builds to Crane Naval Surface Warfare Center standards — the same spec document used for US SOCOM rifles.', 'United States', false, NULL),

('Bravo Company (BCM)', 'GUNFIGHTER Pistol', '5.56 NATO', 'Pistol', 'Semi-Auto', 30, 2012, false, 'United States', 'AR-15 pistol configuration with 9" or 11.5" barrel and pistol brace, built to BCM''s mil-spec standard. Compact PDW-style platform.', 1199, 96.0, 24.0, false, false, ARRAY['GUNFIGHTER 11.5"', 'GUNFIGHTER 9"'], 'Active', 'BCM GUNFIGHTER', ARRAY['5.56 NATO', '.300 BLK'], ARRAY['bcm pistol', 'bcm gunfighter'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

('Bravo Company (BCM)', 'CQB', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2006, false, 'United States', 'BCM close-quarters battle configuration with a 10.5" barrel, suppressor-optimized, and carbine gas system. Closest civilian equivalent to SOCOM CQB configuration.', 1349, 112.0, 26.5, false, false, NULL, 'Active', 'BCM CQB', ARRAY['5.56 NATO'], ARRAY['bcm cqb', 'bcm 10.5'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

-- ── BUL ARMORY ────────────────────────────────────────────────
('Bul Armory', 'SAS II', '9mm Luger', 'Pistol', 'Single-Action', 17, 1998, false, 'Israel', 'Israeli polymer-frame double-stack 1911-style pistol. The SAS II combines the 1911''s single-action trigger with a modern polymer frame and higher capacity magazine. Manufactured in Israel and exported worldwide.', 799, 33.0, 8.5, false, false, ARRAY['SAS II Ultra', 'SAS II Compact', 'SAS II in .45 ACP'], 'Active', 'Bul SAS', ARRAY['9mm Luger', '.40 S&W', '.45 ACP'], ARRAY['bul sas ii', 'sas 2'], 'Modern', 'Single-Action', ARRAY['competition', 'carry'], 'Bul Armory''s double-stack polymer 1911 predates the widespread adoption of polymer-frame 1911s by American manufacturers by several years.', 'Israel', false, NULL),

('Bul Armory', 'Cherokee', '9mm Luger', 'Pistol', 'Single-Action', 15, 2005, false, 'Israel', 'Compact all-steel 1911-style pistol from Bul with a shorter grip and barrel. Aimed at the concealed carry market with traditional 1911 ergonomics in a more compact package.', 699, 28.0, 7.5, false, false, NULL, 'Active', 'Bul Cherokee', ARRAY['9mm Luger', '.40 S&W'], ARRAY['bul cherokee', 'cherokee 1911'], 'Modern', 'Single-Action', ARRAY['carry'], NULL, 'Israel', false, NULL),

('Bul Armory', 'M-5', '9mm Luger', 'Pistol', 'Single-Action', 17, 2010, false, 'Israel', 'Full-size competition-grade 1911 from Bul Armory with an extended barrel bushing, flared magwell, and match-grade barrel. Designed for IPSC/USPSA Limited and Open division competition.', 1299, 40.0, 8.9, false, false, ARRAY['M-5 Government', 'M-5 Transform'], 'Active', 'Bul M-5', ARRAY['9mm Luger', '.40 S&W', '.38 Super'], ARRAY['bul m5', 'm5 competition'], 'Modern', 'Single-Action', ARRAY['competition'], NULL, 'Israel', false, NULL),

-- ── BUSHMASTER ────────────────────────────────────────────────
('Bushmaster', 'XM15-E2S', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 1992, true, 'United States', 'Bushmaster''s flagship AR-15 carbine. One of the most widely sold AR-15s of the 1990s and 2000s. The XM15-E2S was a mil-spec carbine offered at competitive pricing.', 899, 128.0, 32.5, false, false, ARRAY['XM15 A2', 'XM15 M4 Patrolman'], 'Discontinued', 'Bushmaster XM15', ARRAY['5.56 NATO', '.223 Rem'], ARRAY['xm15', 'bushmaster ar15', 'xm15-e2s'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

('Bushmaster', 'ACR', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2009, true, 'United States', 'Adaptive Combat Rifle — a modular rifle originally developed by Magpul as the Masada concept. Features quick-change barrels, ambidextrous controls, and a folding stock. Originally promising but commercially unsuccessful at its price point.', 1999, 140.0, 36.0, false, false, ARRAY['ACR Enhanced', 'ACR Basic'], 'Discontinued', 'Bushmaster ACR', ARRAY['5.56 NATO', '.300 BLK', '6.8 SPC'], ARRAY['acr', 'bushmaster acr', 'masada'], 'Modern', 'Single-Action', ARRAY['sport', 'military'], 'The ACR (originally the Magpul Masada) was one of the most eagerly anticipated rifle designs of the 2000s. When it launched at $2,700 — nearly triple the rumored target price — it became one of the most disappointing commercial launches in modern firearms history.', 'United States', false, NULL),

('Bushmaster', 'Carbon 15', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 1993, true, 'United States', 'Ultra-lightweight AR-15 with a carbon fiber upper and lower receiver. The Carbon 15 weighed under 4 lbs — significantly lighter than any aluminum AR at the time.', 799, 56.0, 32.5, false, false, ARRAY['Carbon 15 Pistol', 'Carbon 15 Officer'], 'Discontinued', 'Bushmaster Carbon 15', ARRAY['5.56 NATO'], ARRAY['carbon 15', 'bushmaster carbon'], 'Modern', 'Single-Action', ARRAY['sport'], NULL, 'United States', false, NULL),

-- ── CVA ───────────────────────────────────────────────────────
('CVA', 'Optima V2', '.50 Caliber', 'Rifle', 'Single-Action', 1, 2009, false, 'United States', 'Inline muzzleloader with a break-action system for easy loading and cleaning. Reliable, affordable, and accurate. One of the best-selling hunting muzzleloaders in the US market.', 299, 64.0, 42.0, false, false, ARRAY['Optima V2 LR (long range)', 'Optima V2 Northwest'], 'Active', 'CVA Optima', ARRAY['.50 Caliber'], ARRAY['optima v2', 'cva optima'], 'Modern', 'Single-Action', ARRAY['hunting'], NULL, 'United States', false, NULL),

('CVA', 'Accura MR-X', '.50 Caliber', 'Rifle', 'Single-Action', 1, 2017, false, 'United States', 'Premium inline muzzleloader with a Nitride-finished Bergara barrel and a thumbhole stock. CVA''s top-of-line hunting muzzleloader offering sub-MOA accuracy capability.', 699, 72.0, 44.0, false, false, ARRAY['Accura MR (original)', 'Accura V2'], 'Active', 'CVA Accura', ARRAY['.50 Caliber'], ARRAY['accura mr-x', 'cva accura'], 'Modern', 'Single-Action', ARRAY['hunting', 'competition'], NULL, 'United States', false, NULL),

('CVA', 'Paramount', '.40 Caliber', 'Rifle', 'Single-Action', 1, 2019, false, 'United States', 'Long-range inline muzzleloader designed for 200-300 yard accuracy. Uses a proprietary PowerBelt ELR bullet system and is optimized for consistent long-range hunting performance.', 899, 80.0, 52.0, false, false, ARRAY['Paramount Pro', 'Paramount HTR'], 'Active', 'CVA Paramount', ARRAY['.40 Caliber', '.45 Caliber'], ARRAY['paramount', 'cva paramount'], 'Modern', 'Single-Action', ARRAY['hunting'], 'CVA Paramount created the "long-range muzzleloader" product category — no prior inline muzzleloader was specifically engineered for consistent accuracy at 300 yards.', 'United States', false, NULL),

-- ── CABOT GUNS ────────────────────────────────────────────────
('Cabot Guns', 'National Standard', '.45 ACP', 'Pistol', 'Single-Action', 8, 2011, false, 'United States', 'Cabot''s entry-level ultra-precision 1911. "Entry-level" here means $3,750 — every Cabot 1911 is machined from billet steel to tolerances measured in tenths of a thousandth of an inch.', 3750, 40.0, 8.75, false, false, NULL, 'Active', 'Cabot 1911', ARRAY['.45 ACP', '9mm Luger'], ARRAY['national standard', 'cabot 1911'], 'Modern', 'Single-Action', ARRAY['collector', 'competition'], 'Cabot''s manufacturing process uses aerospace-grade equipment to achieve 1911 fit tolerances that most shops consider impossible. Their slides fit frames with zero perceptible play — closer to a gauge block than a firearm.', 'United States', true, 'Cabot guns are among the most precisely manufactured production 1911s in existence. The One (a meteorite-steel 1911 sold at auction) sold for over $1,000,000.'),

('Cabot Guns', 'Jones', '.45 ACP', 'Pistol', 'Single-Action', 8, 2014, false, 'United States', 'Lightweight commander-size 1911 with carbon steel construction and Cabot''s full precision machining. The Jones is the Commander equivalent in the Cabot lineup.', 4250, 35.0, 8.0, false, false, NULL, 'Active', 'Cabot 1911', ARRAY['.45 ACP', '9mm Luger'], ARRAY['cabot jones', 'jones 1911'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], NULL, 'United States', true, NULL),

('Cabot Guns', 'American Joe', '.45 ACP', 'Pistol', 'Single-Action', 8, 2016, false, 'United States', 'Full-size 1911 with patriotic American theme — machined in the US from US-sourced steel. Cabot''s most decorated production model.', 4500, 40.0, 8.75, false, false, NULL, 'Active', 'Cabot 1911', ARRAY['.45 ACP'], ARRAY['american joe', 'cabot american'], 'Modern', 'Single-Action', ARRAY['collector'], NULL, 'United States', true, 'Limited production with documented serial numbers commands collector premium.'),

-- ── CADEX DEFENCE ─────────────────────────────────────────────
('Cadex Defence', 'CDX-30', '.30 Caliber', 'Rifle', 'Bolt-Action', 5, 2012, false, 'Canada', 'Precision bolt-action chassis rifle from Canadian manufacturer Cadex. The CDX-30 uses a modular chassis system that accepts a wide range of stocks and configurations. Used by military snipers and competitive long-range shooters.', 3500, 176.0, 47.0, false, true, ARRAY['CDX-30 Lite', 'CDX-30 Evo', 'CDX-30 Kraken'], 'Active', 'Cadex CDX-30', ARRAY['.308 Win', '6.5 Creedmoor', '.300 Win Mag'], ARRAY['cdx30', 'cadex 30'], 'Modern', 'Single-Action', ARRAY['military', 'competition'], NULL, 'Canada', false, NULL),

('Cadex Defence', 'CDX-50 Tremor', '.50 BMG', 'Rifle', 'Bolt-Action', 5, 2015, false, 'Canada', 'Semi-bullpup anti-materiel precision rifle in .50 BMG. The CDX-50 has been adopted by several military and law enforcement agencies for long-range precision applications.', 9500, 320.0, 55.0, true, true, NULL, 'Active', 'Cadex CDX-50', ARRAY['.50 BMG'], ARRAY['cdx50 tremor', 'cadex 50 bmg'], 'Modern', 'Single-Action', ARRAY['military', 'competition'], NULL, 'Canada', false, NULL),

('Cadex Defence', 'CDX-40 Shadow', '.375 CheyTac', 'Rifle', 'Bolt-Action', 5, 2016, false, 'Canada', 'Extreme long-range bolt-action rifle chambered in .375 CheyTac and similar ELR cartridges. Built for sub-MOA accuracy at ranges beyond 2000 meters.', 7500, 256.0, 52.0, false, true, ARRAY['CDX-40 in .416 Barrett', 'CDX-40 in .408 CheyTac'], 'Active', 'Cadex CDX-40', ARRAY['.375 CheyTac', '.408 CheyTac'], ARRAY['cdx40 shadow', 'cadex shadow'], 'Modern', 'Single-Action', ARRAY['military', 'competition'], NULL, 'Canada', false, NULL),

-- ── CENTURY ARMS ─────────────────────────────────────────────
('Century Arms', 'VSKA', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 2019, false, 'United States', 'American-made AK-47 pattern rifle assembled by Century Arms with US-manufactured components. The VSKA uses a tool-steel bolt and US-made trunnion for improved durability over previous Century AK imports.', 699, 144.0, 36.6, false, false, ARRAY['VSKA Trooper', 'VSKA Magpul'], 'Active', 'Century VSKA', ARRAY['7.62x39mm'], ARRAY['vska', 'century ak', 'century arms ak47'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

('Century Arms', 'WASR-10', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 2003, false, 'Romania', 'Romanian-manufactured AK-pattern semi-auto imported and refined by Century Arms. The WASR-10 is one of the most common and well-known AK imports in the US market. Later production WASR-10s improved significantly over early examples.', 699, 144.0, 36.5, false, false, ARRAY['WASR-10 V2', 'WASR-10 UF'], 'Active', 'Century WASR', ARRAY['7.62x39mm'], ARRAY['wasr10', 'wasr-10', 'century wasr'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], 'Early WASR-10 imports had quality control issues with canted front sights and sloppy magazine fit. Post-2010 examples were significantly improved after Century tightened their QC processes.', 'Romania', false, NULL),

('Century Arms', 'C39v2', '7.62x39mm', 'Rifle', 'Semi-Auto', 30, 2016, true, 'United States', 'US-manufactured milled-receiver AK-pattern rifle. The C39v2 used a machined-from-solid US steel receiver — more expensive to produce but beloved by AK purists who prefer milled over stamped.', 899, 144.0, 36.5, false, false, NULL, 'Discontinued', 'Century C39', ARRAY['7.62x39mm'], ARRAY['c39v2', 'century c39', 'milled ak century'], 'Modern', 'Single-Action', ARRAY['sport'], NULL, 'United States', false, NULL),

-- ── CHAPUIS ARMES ─────────────────────────────────────────────
('Chapuis Armes', 'Artisan', '9.3x74R', 'Rifle', 'Break-Action', 2, 1985, false, 'France', 'French double rifle from the workshops of Chapuis Armes in Saint-Bonnet-le-Chateau. The Artisan is a side-by-side or over-and-under double rifle for dangerous game, built to traditional French craftsmanship standards.', 5500, 192.0, 42.0, false, false, ARRAY['Artisan in .375 H&H', 'Artisan in .470 NE', 'Artisan in .300 Win Mag'], 'Active', 'Chapuis Artisan', ARRAY['9.3x74R', '.375 H&H', '.470 NE'], ARRAY['chapuis artisan', 'chapuis double rifle'], 'Modern', 'Single-Action', ARRAY['hunting', 'collector'], NULL, 'France', false, NULL),

('Chapuis Armes', 'Oural', '.30-06', 'Rifle', 'Bolt-Action', 4, 1995, false, 'France', 'French bolt-action sporting rifle on a Mauser-98 action. Traditional French styling with walnut stock and a clean, classic aesthetic.', 2200, 112.0, 42.0, false, false, ARRAY['Oural Prestige', 'Oural Savana'], 'Active', 'Chapuis Oural', ARRAY['.30-06', '.300 Win Mag', '9.3x62'], ARRAY['chapuis oural'], 'Modern', 'Single-Action', ARRAY['hunting'], NULL, 'France', false, NULL),

('Chapuis Armes', 'Progress RG Express', '9.3x74R', 'Rifle', 'Break-Action', 2, 2000, false, 'France', 'Double express rifle (Drilling or double-barrel configuration) for African hunting. Chapuis''s flagship dangerous game rifle.', 7500, 208.0, 43.0, false, false, ARRAY['RG in .375 H&H', 'RG in .470 NE'], 'Active', 'Chapuis Express', ARRAY['9.3x74R', '.375 H&H'], ARRAY['chapuis express', 'progress rg'], 'Modern', 'Single-Action', ARRAY['hunting'], NULL, 'France', false, NULL),

-- ── CHARLES DALY ──────────────────────────────────────────────
('Charles Daly', 'Honcho', '12 Gauge', 'Shotgun', 'Pump-Action', 5, 2018, false, 'Turkey', 'Compact pump-action 12-gauge with an AR-style pistol grip and 14.375" barrel. Features a Picatinny rail and modern tactical aesthetic at a budget price point.', 299, 88.0, 26.5, false, false, ARRAY['Honcho Tactical', 'Honcho PAK'], 'Active', 'Charles Daly Honcho', ARRAY['12 Gauge'], ARRAY['daly honcho', 'charles daly pump'], 'Modern', 'Single-Action', ARRAY['home defense', 'tactical'], NULL, 'Turkey', false, NULL),

('Charles Daly', '601', '12 Gauge', 'Shotgun', 'Semi-Auto', 5, 2015, false, 'Turkey', 'Gas-operated semi-automatic 12-gauge shotgun with a synthetic stock. Mid-range priced imported semi-auto targeting the hunting and sporting market.', 449, 96.0, 47.0, false, false, ARRAY['601 Field', '601 Tactical'], 'Active', 'Charles Daly 601', ARRAY['12 Gauge'], ARRAY['charles daly 601', 'daly 601'], 'Modern', 'Single-Action', ARRAY['hunting', 'sport'], NULL, 'Turkey', false, NULL),

('Charles Daly', '1911', '.45 ACP', 'Pistol', 'Single-Action', 8, 2000, false, 'Philippines', 'GI-spec 1911 imported by Charles Daly and manufactured in the Philippines. Budget-priced 1911 alternative positioned against Rock Island Armory.', 499, 38.0, 8.5, false, false, ARRAY['1911 Government', '1911 Commander', '1911 Officer'], 'Active', 'Charles Daly 1911', ARRAY['.45 ACP', '9mm Luger'], ARRAY['charles daly 1911', 'daly 1911'], 'Modern', 'Single-Action', ARRAY['carry', 'sport'], NULL, 'Philippines', false, NULL),

-- ── CHARTER ARMS ──────────────────────────────────────────────
('Charter Arms', 'Undercover', '.38 Special', 'Revolver', 'DA/SA Revolver', 5, 1964, false, 'United States', 'Lightweight 5-shot .38 Special revolver — one of the first snubnose revolvers designed specifically for concealed carry. The Undercover is significantly lighter than S&W J-frame equivalents due to an aluminum alloy frame.', 399, 16.0, 6.75, false, false, ARRAY['Undercover Lite', 'Undercover .32 H&R Mag'], 'Active', 'Charter Undercover', ARRAY['.38 Special', '.32 H&R Mag'], ARRAY['undercover', 'charter 38', 'charter arms undercover'], 'Cold War', 'DA/SA', ARRAY['carry'], 'An Undercover .38 Special was used by Squeaky Fromme in the 1975 assassination attempt on President Gerald Ford.', 'United States', false, NULL),

('Charter Arms', 'Bulldog', '.44 Special', 'Revolver', 'DA/SA Revolver', 5, 1973, false, 'United States', 'Compact 5-shot .44 Special revolver — one of the few production revolvers offering .44 Special in a concealable package. Popularized the concept of a large-caliber snubnose.', 399, 21.0, 7.0, false, false, ARRAY['Bulldog Pug', 'Bulldog Police', 'Bulldog .45 Colt'], 'Active', 'Charter Bulldog', ARRAY['.44 Special', '.45 Colt'], ARRAY['bulldog', 'charter bulldog', 'charter 44'], 'Cold War', 'DA/SA', ARRAY['carry'], 'The .44 Caliber Killer (Son of Sam) David Berkowitz used a Charter Arms Bulldog .44 Special in his 1976-1977 New York City murders. The notoriety drove massive public interest in the model.', 'United States', false, NULL),

('Charter Arms', 'Pitbull', '9mm Luger', 'Revolver', 'DA/SA Revolver', 5, 2012, false, 'United States', 'Rimless-cartridge revolver in 9mm Luger using Charter Arms''s proprietary spring-loaded extractor system — no moon clips required. One of the only production revolvers to chamber 9mm without moon clips.', 449, 22.0, 7.0, false, false, ARRAY['Pitbull .40 S&W', 'Pitbull .45 ACP'], 'Active', 'Charter Pitbull', ARRAY['9mm Luger', '.40 S&W', '.45 ACP'], ARRAY['pitbull', 'charter pitbull', 'charter 9mm revolver'], 'Modern', 'DA/SA', ARRAY['carry'], 'The Charter Arms Pitbull is one of only three production revolvers in history designed to fire rimless auto cartridges without moon clips — a genuinely unusual engineering achievement.', 'United States', false, NULL),

-- ── CHIAPPA FIREARMS ──────────────────────────────────────────
('Chiappa Firearms', 'Rhino', '.357 Magnum', 'Revolver', 'DA/SA Revolver', 6, 2009, false, 'Italy', 'Revolutionary revolver design by Emilio Ghisoni (also of Mateba) that fires from the bottom chamber of the cylinder rather than the top. This lowers the bore axis dramatically, reducing muzzle flip. Available in 2" to 6" barrels.', 999, 24.0, 7.0, false, false, ARRAY['Rhino 40DS (4")', 'Rhino 60DS (6")', 'Rhino 20DS (2")', 'Rhino in 9mm'], 'Active', 'Chiappa Rhino', ARRAY['.357 Magnum', '9mm Luger', '.40 S&W'], ARRAY['rhino', 'chiappa rhino'], 'Modern', 'DA/SA', ARRAY['carry', 'competition', 'collector'], 'Emilio Ghisoni patented the bottom-firing revolver concept with the Mateba Autorevolver in 1994 and refined it into the Rhino — the first commercially successful bottom-firing revolver.', 'Italy', false, NULL),

('Chiappa Firearms', 'Little Badger', '.22 LR', 'Rifle', 'Single-Action', 1, 2013, false, 'Italy', 'Ultra-compact single-shot folding rifle in .22 LR weighing just 2.9 lbs. The stock and barrel fold together for extreme portability. Popular as a survival/backpacking rifle.', 199, 46.4, 29.0, false, false, ARRAY['Little Badger in .22 Magnum', 'Little Badger in .17 HMR'], 'Active', 'Chiappa Little Badger', ARRAY['.22 LR', '.22 Magnum', '.17 HMR'], ARRAY['little badger', 'chiappa folding 22'], 'Modern', 'Single-Action', ARRAY['hunting', 'survival'], NULL, 'Italy', false, NULL),

('Chiappa Firearms', 'Triple Threat', '12 Gauge', 'Shotgun', 'Break-Action', 3, 2011, false, 'Italy', 'Triple-barrel break-action 12-gauge — one of the only production three-barrel shotguns available. Two side-by-side barrels plus a third under-barrel, all 18.5", with three independent triggers.', 1199, 144.0, 37.0, false, false, NULL, 'Active', 'Chiappa Triple Threat', ARRAY['12 Gauge'], ARRAY['triple threat', 'chiappa 3 barrel'], 'Modern', 'Single-Action', ARRAY['home defense', 'collector'], 'The Chiappa Triple Threat is one of only a handful of triple-barrel shotguns ever offered as a production firearm.', 'Italy', false, NULL),

-- ── CIMARRON FIREARMS ─────────────────────────────────────────
('Cimarron Firearms', 'Peacemaker SAA', '.357 Magnum', 'Revolver', 'Single-Action Revolver', 6, 1984, false, 'Italy', 'Faithful reproduction of the Colt Single Action Army revolver made by Uberti for Cimarron. The Peacemaker is Cimarron''s primary SAA reproduction, available in dozens of caliber and barrel configurations.', 549, 37.0, 11.0, false, false, ARRAY['Peacemaker in .45 Colt', 'Peacemaker in .44-40', 'Peacemaker Sheriff (3.5" barrel)'], 'Active', 'Cimarron SAA', ARRAY['.357 Magnum', '.45 Colt', '.44-40', '.44 Special'], ARRAY['peacemaker', 'cimarron saa', 'cimarron colt'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition', 'hunting'], NULL, 'Italy', false, NULL),

('Cimarron Firearms', '1873 Winchester', '.45 Colt', 'Rifle', 'Lever-Action', 13, 1987, false, 'Italy', 'Reproduction of the Winchester Model 1873 lever-action rifle, made by Uberti for Cimarron. The most authentic and widely used Winchester 1873 replica available. Popular for Cowboy Action Shooting (SASS).', 1199, 128.0, 43.0, false, false, ARRAY['El Patron', 'Frontier 1873', 'Deluxe Engraved'], 'Active', 'Cimarron 1873', ARRAY['.45 Colt', '.44-40', '.357 Magnum', '.38 Special'], ARRAY['cimarron 1873', '1873 winchester reproduction'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition'], NULL, 'Italy', false, NULL),

('Cimarron Firearms', 'Model P', '.45 Colt', 'Revolver', 'Single-Action Revolver', 6, 1984, false, 'Italy', 'Cimarron''s closest equivalent to a pre-war Colt SAA — the Model P uses period-correct dimensions and an action tuned to a light, crisp single-action pull. Often chosen over the standard Peacemaker by purists.', 599, 37.0, 11.0, false, false, ARRAY['Model P in .357 Mag', 'Model P New Sheriff (3.5")', 'Evil Roy (competition)'], 'Active', 'Cimarron Model P', ARRAY['.45 Colt', '.357 Magnum', '.44-40'], ARRAY['model p', 'cimarron model p'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition'], NULL, 'Italy', false, NULL),

-- ── COBRA ENTERPRISES ─────────────────────────────────────────
('Cobra Enterprises', 'CA380', '.380 ACP', 'Pistol', 'DA/SA', 5, 2001, true, 'United States', 'Inexpensive DAO .380 ACP semi-automatic pistol continuing the Davis Industries P-380 design. Budget concealed carry option at the lowest end of the price spectrum.', 149, 22.0, 5.4, false, false, NULL, 'Discontinued', 'Cobra CA', ARRAY['.380 ACP'], ARRAY['ca380', 'cobra 380'], 'Modern', 'DA/SA', ARRAY['carry'], NULL, 'United States', false, NULL),

('Cobra Enterprises', 'CB38', '.38 Special', 'Pistol', 'DA/SA', 5, 2005, true, 'United States', 'Derringer-style DAO pistol in .38 Special. Among the few production firearms offering .38 Special in an over-under derringer format at a budget price.', 179, 14.5, 5.4, false, false, NULL, 'Discontinued', 'Cobra CB', ARRAY['.38 Special', '.357 Magnum'], ARRAY['cb38', 'cobra derringer'], 'Modern', 'DA/SA', ARRAY['carry'], NULL, 'United States', false, NULL),

('Cobra Enterprises', 'Patriot', '.45 ACP', 'Pistol', 'Single-Action', 2, 2002, true, 'United States', 'Small two-shot derringer in .45 ACP, .45 Colt, or .410. Davis Industries-inherited design with updated safety mechanism.', 189, 22.0, 4.5, false, false, ARRAY['Patriot in .45 Colt/.410'], 'Discontinued', 'Cobra Patriot', ARRAY['.45 ACP', '.45 Colt'], ARRAY['cobra patriot', 'patriot derringer'], 'Modern', 'Single-Action', ARRAY['carry'], NULL, 'United States', false, NULL),

-- ── COBRAY ────────────────────────────────────────────────────
('Cobray', 'M11/Nine', '9mm Luger', 'Pistol', 'Semi-Auto', 32, 1982, true, 'United States', 'Semi-automatic MAC-11-pattern pistol in 9mm from SWD/Cobray. The civilian semi-auto successor to the MAC-11. Open-bolt design (early), later changed to closed-bolt to comply with BATF rulings.', 199, 53.0, 9.5, false, false, ARRAY['M11 in .380 ACP', 'PM11'], 'Discontinued', 'Cobray M11', ARRAY['9mm Luger', '.380 ACP'], ARRAY['m11/nine', 'cobray m11', 'm11 nine'], 'Cold War', 'Single-Action', ARRAY['collector'], NULL, 'United States', false, NULL),

('Cobray', 'M12', '.380 ACP', 'Pistol', 'Semi-Auto', 16, 1985, true, 'United States', 'Semi-automatic pistol in .380 ACP based on the MAC-12 pattern. Smaller and lighter than the M11.', 179, 42.0, 8.1, false, false, NULL, 'Discontinued', 'Cobray M12', ARRAY['.380 ACP'], ARRAY['m12', 'cobray m12'], 'Cold War', 'Single-Action', ARRAY['collector'], NULL, 'United States', false, NULL),

('Cobray', 'Terminator', '12 Gauge', 'Shotgun', 'Single-Action', 1, 1986, true, 'United States', 'Single-shot 12-gauge shotgun constructed from a large-diameter steel tube with a simple striker mechanism. Arguably the most primitive firearm ever mass-produced in the United States. Retailed for approximately $70 new.', 70, 64.0, 18.0, false, false, NULL, 'Discontinued', 'Cobray Terminator', ARRAY['12 Gauge'], ARRAY['terminator', 'cobray terminator shotgun'], 'Cold War', 'Single-Action', ARRAY['collector'], 'The Cobray Terminator was cited by Senator Dennis DeConcini on the floor of the Senate as an example of the dangerous cheapness of available firearms. A single-shot 12-gauge made of pipe retailing for $70 became a symbol of the "Saturday Night Special" legislative debate.', 'United States', true, 'Functional Cobray Terminators in any condition have genuine collector curiosity value due to their notoriety and crude construction.'),

-- ── COOPER FIREARMS OF MONTANA ────────────────────────────────
('Cooper Firearms of Montana', 'Model 21', 'Various', 'Rifle', 'Bolt-Action', 4, 1992, false, 'United States', 'Custom bolt-action varmint rifle built on the Kimber-derived Cooper action. Available in a wide range of varmint and small centerfire calibers with premium walnut stocks and hand-lapped barrels.', 1895, 96.0, 42.0, false, false, ARRAY['Model 21 Varmint', 'Model 21 Phoenix', 'Model 21 Western Classic'], 'Active', 'Cooper Model 21', ARRAY['.17 Rem', '.222 Rem', '.223 Rem', '.22 Hornet'], ARRAY['model 21', 'cooper 21'], 'Modern', 'Single-Action', ARRAY['hunting', 'competition'], NULL, 'United States', false, NULL),

('Cooper Firearms of Montana', 'Model 52', 'Various', 'Rifle', 'Bolt-Action', 4, 1999, false, 'United States', 'Full-length Cooper bolt-action rifle in standard and magnum calibers. Walnut stock with hand-cut checkering and a cooper-grade barrel known for exceptional accuracy.', 2295, 128.0, 44.0, false, false, ARRAY['Model 52 Open Country', 'Model 52 Western Classic', 'Model 52 Mannlicher'], 'Active', 'Cooper Model 52', ARRAY['.270 Win', '.30-06', '.308 Win', '6.5 Creedmoor'], ARRAY['model 52', 'cooper 52'], 'Modern', 'Single-Action', ARRAY['hunting'], NULL, 'United States', false, NULL),

('Cooper Firearms of Montana', 'Model 54', 'Various', 'Rifle', 'Bolt-Action', 4, 2008, false, 'United States', 'Cooper''s most popular hunting rifle action in a light-weight configuration. The Model 54 uses a Remington 700-footprint barrel thread for wide aftermarket accessory compatibility.', 1895, 96.0, 42.0, false, false, ARRAY['Model 54 Western Classic', 'Model 54 Excalibur'], 'Active', 'Cooper Model 54', ARRAY['.243 Win', '.308 Win', '7mm-08', '6.5 Creedmoor'], ARRAY['model 54', 'cooper 54'], 'Modern', 'Single-Action', ARRAY['hunting', 'competition'], NULL, 'United States', false, NULL),

-- ── DAEWOO PRECISION INDUSTRIES ──────────────────────────────
('Daewoo Precision Industries', 'DP51', '9mm Luger', 'Pistol', 'DA/SA', 13, 1992, true, 'South Korea', 'Semi-automatic 9mm service pistol with Daewoo''s proprietary "Fast Action" trigger — a unique system where the hammer partially cocks on the rearward slide travel, resulting in a pull between SA and DA weight.', 499, 28.2, 7.5, false, true, ARRAY['DP51 Compact (DP52)', 'DP51C'], 'Discontinued', 'Daewoo DP', ARRAY['9mm Luger'], ARRAY['dp51', 'daewoo 9mm', 'dp-51'], 'Cold War', 'DA/SA', ARRAY['military', 'carry', 'collector'], 'The Daewoo DP51''s Fast Action trigger is found on no other production pistol. The partially-cocked hammer results in a consistent, moderate-weight trigger pull that experienced shooters compare favorably to a well-tuned SA.', 'South Korea', false, NULL),

('Daewoo Precision Industries', 'AR-100', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 1988, true, 'South Korea', 'South Korean AR-15 pattern semi-automatic rifle with a gas-piston operating system and a quick-change barrel feature. Imported to the US in limited quantities before import restrictions.', 699, 128.0, 39.5, false, false, NULL, 'Discontinued', 'Daewoo AR', ARRAY['5.56 NATO'], ARRAY['ar100', 'daewoo ar-100', 'max-ii'], 'Cold War', 'Single-Action', ARRAY['sport', 'collector'], NULL, 'South Korea', false, NULL),

('Daewoo Precision Industries', 'DP52', '.22 LR', 'Pistol', 'DA/SA', 10, 1993, true, 'South Korea', 'Compact .22 LR version of the DP51, sharing the same Fast Action trigger system. Intended as a training pistol for DP51 users.', 349, 23.0, 6.6, false, false, NULL, 'Discontinued', 'Daewoo DP', ARRAY['.22 LR'], ARRAY['dp52', 'daewoo 22'], 'Cold War', 'DA/SA', ARRAY['sport', 'collector'], NULL, 'South Korea', false, NULL),

-- ── DAN WESSON ────────────────────────────────────────────────
('Dan Wesson', '715', '.357 Magnum', 'Revolver', 'DA/SA Revolver', 6, 1984, false, 'United States', 'Dan Wesson''s signature interchangeable-barrel .357 Magnum revolver. The 715 features Dan Wesson''s unique barrel shroud and nut system, allowing barrel swaps without tools. Known for exceptional accuracy and a superb single-action trigger.', 1399, 40.0, 10.5, false, false, ARRAY['715 with 4" barrel', '715 with 8" barrel', '715 with 2.5" barrel'], 'Active', 'Dan Wesson 715', ARRAY['.357 Magnum'], ARRAY['715', 'dw 715', 'dan wesson 357'], 'Modern', 'DA/SA', ARRAY['competition', 'hunting', 'collector'], 'Dan Wesson revolvers pioneered the interchangeable barrel concept — a single-frame revolver with multiple barrel lengths sold as a system. The nut-and-shroud design allows a non-gunsmith to change barrels in under 5 minutes with a simple tool.', 'United States', false, NULL),

('Dan Wesson', 'Kodiak', '10mm Auto', 'Revolver', 'DA/SA Revolver', 6, 1990, true, 'United States', 'Large-frame revolver in 10mm Auto — one of the few production revolvers ever chambered for this cartridge. Used as a hunting revolver and by handgun metallic silhouette competitors.', 899, 56.0, 12.0, false, false, ARRAY['Kodiak in .445 SuperMag'], 'Discontinued', 'Dan Wesson Large Frame', ARRAY['10mm Auto', '.445 SuperMag'], ARRAY['kodiak', 'dan wesson 10mm'], 'Modern', 'DA/SA', ARRAY['hunting', 'competition', 'collector'], NULL, 'United States', true, NULL),

('Dan Wesson', 'Pointman Major', '10mm Auto', 'Pistol', 'Single-Action', 9, 2001, false, 'United States', '1911-pattern semi-automatic pistol in 10mm Auto. The Pointman Major was among the first high-quality production 1911s offered in 10mm. Dan Wesson is now a CZ subsidiary making premium 1911s and 1911-influenced pistols.', 1549, 40.0, 8.75, false, false, ARRAY['Pointman Major in .45 ACP', 'Pointman Carry'], 'Active', 'Dan Wesson Pointman', ARRAY['10mm Auto', '.45 ACP', '9mm Luger'], ARRAY['pointman major', 'dw 1911 10mm'], 'Modern', 'Single-Action', ARRAY['competition', 'hunting'], NULL, 'United States', false, NULL),

-- ── DAVIS INDUSTRIES ──────────────────────────────────────────
('Davis Industries', 'P-380', '.380 ACP', 'Pistol', 'DA/SA', 5, 1987, true, 'United States', 'Inexpensive DAO .380 ACP semi-auto. One of the original Ring of Fire pistols from Jim Davis.', 99, 22.0, 5.4, false, false, NULL, 'Discontinued', 'Davis P', ARRAY['.380 ACP'], ARRAY['p-380', 'davis 380'], 'Modern', 'DA/SA', ARRAY['carry'], NULL, 'United States', false, NULL),

('Davis Industries', 'P-32', '.32 ACP', 'Pistol', 'DA/SA', 6, 1987, true, 'United States', 'Budget DAO .32 ACP semi-auto. Cheaper and smaller than the P-380.', 89, 20.0, 5.0, false, false, NULL, 'Discontinued', 'Davis P', ARRAY['.32 ACP'], ARRAY['p-32', 'davis 32'], 'Modern', 'DA/SA', ARRAY['carry'], NULL, 'United States', false, NULL),

('Davis Industries', 'D-380', '.380 ACP', 'Pistol', 'Single-Action', 5, 1988, true, 'United States', 'DAO pocket pistol in .380 ACP. The D-series was Davis''s lower-cost product line below the P-series.', 79, 21.5, 5.3, false, false, NULL, 'Discontinued', 'Davis D', ARRAY['.380 ACP'], ARRAY['d-380', 'davis d380'], 'Modern', 'DA/SA', ARRAY['carry'], NULL, 'United States', false, NULL),

-- ── DEL-TON ───────────────────────────────────────────────────
('Del-Ton', 'Echo 316', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2008, false, 'United States', 'Entry-level AR-15 carbine with 16" barrel, A2 flash hider, and standard M4 furniture. One of the most affordable complete AR-15 rifles from a US manufacturer.', 499, 128.0, 32.5, false, false, NULL, 'Active', 'Del-Ton Echo', ARRAY['5.56 NATO', '.223 Rem'], ARRAY['echo 316', 'del-ton echo'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

('Del-Ton', 'Sierra 316', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2010, false, 'United States', 'Mid-tier AR-15 from Del-Ton with a chrome-lined barrel and upgraded furniture. Steps up from the Echo with better barrel finishing.', 599, 128.0, 32.5, false, false, NULL, 'Active', 'Del-Ton Sierra', ARRAY['5.56 NATO'], ARRAY['sierra 316', 'del-ton sierra'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

('Del-Ton', 'Sport', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2014, false, 'United States', 'Lightweight AR-15 with a government-profile barrel and A2 furniture. The Sport line prioritizes affordability without sacrificing mil-spec dimensions.', 549, 120.0, 32.5, false, false, NULL, 'Active', 'Del-Ton Sport', ARRAY['5.56 NATO'], ARRAY['del-ton sport', 'sport ar15'], 'Modern', 'Single-Action', ARRAY['sport'], NULL, 'United States', false, NULL),

-- ── DETONICS ──────────────────────────────────────────────────
('Detonics', 'CombatMaster', '.45 ACP', 'Pistol', 'Single-Action', 6, 1976, true, 'United States', 'Ultra-compact 1911 in .45 ACP with a 3.5" barrel. One of the first commercially successful compact 1911s, predating most American manufacturers'' compact offerings by years. Produced in both Seattle and later revived versions.', 799, 28.0, 6.75, false, false, ARRAY['CombatMaster Mark V', 'CombatMaster in 9mm'], 'Discontinued', 'Detonics CombatMaster', ARRAY['.45 ACP', '9mm Luger', '.38 Super'], ARRAY['combatmaster', 'detonics 45'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], 'The Detonics CombatMaster was one of the first to demonstrate that a .45 ACP 1911 could be shortened to truly concealable dimensions without sacrificing function — a concept that Kimber, Springfield, and others later popularized.', 'United States', true, 'Original Seattle-production Detonics command collector premiums over later Indiana and Texas revival productions.'),

('Detonics', 'ScoreMaster', '.45 ACP', 'Pistol', 'Single-Action', 8, 1981, true, 'United States', 'Full-size competition 1911 from Detonics with a heavy barrel bushing, match trigger, and adjustable sights. Competing in the IPSC market of the early 1980s.', 899, 40.0, 8.75, false, false, NULL, 'Discontinued', 'Detonics ScoreMaster', ARRAY['.45 ACP', '.451 Detonics Magnum'], ARRAY['scoremaster', 'detonics competition'], 'Modern', 'Single-Action', ARRAY['competition', 'collector'], NULL, 'United States', true, NULL),

('Detonics', 'ServiceMaster', '.45 ACP', 'Pistol', 'Single-Action', 7, 1983, true, 'United States', 'Mid-size 1911 between the CombatMaster and full-size. Features a 4.25" barrel and Commander-length frame.', 749, 33.0, 7.5, false, false, NULL, 'Discontinued', 'Detonics ServiceMaster', ARRAY['.45 ACP'], ARRAY['servicemaster', 'detonics service'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], NULL, 'United States', false, NULL),

-- ── DIAMONDBACK FIREARMS ──────────────────────────────────────
('Diamondback Firearms', 'DB380', '.380 ACP', 'Pistol', 'Striker-Fired', 6, 2009, false, 'United States', 'Ultra-compact .380 ACP striker-fired pocket pistol from Diamondback. Competes with the Ruger LCP and Kel-Tec P-3AT in the pocket .380 category at a competitive price.', 249, 8.8, 5.0, false, false, NULL, 'Active', 'Diamondback DB', ARRAY['.380 ACP'], ARRAY['db380', 'diamondback 380'], 'Modern', 'Striker-Fired', ARRAY['carry'], NULL, 'United States', false, NULL),

('Diamondback Firearms', 'DB9', '9mm Luger', 'Pistol', 'Striker-Fired', 6, 2011, false, 'United States', 'Ultra-compact 9mm striker-fired pistol — the same footprint as the DB380 but chambered in the more powerful 9mm Luger. One of the smallest and lightest 9mm pistols ever produced.', 299, 11.0, 5.25, false, false, NULL, 'Active', 'Diamondback DB', ARRAY['9mm Luger'], ARRAY['db9', 'diamondback 9mm'], 'Modern', 'Striker-Fired', ARRAY['carry'], NULL, 'United States', false, NULL),

('Diamondback Firearms', 'DB15', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2012, false, 'United States', 'AR-15 carbine from Diamondback. Mil-spec lower, mid-length gas system, and a 16" barrel in a standard M4 configuration.', 599, 128.0, 32.5, false, false, ARRAY['DB15B (black)', 'DB15CB (carbon)'], 'Active', 'Diamondback DB15', ARRAY['5.56 NATO', '.300 BLK'], ARRAY['db15', 'diamondback ar15'], 'Modern', 'Single-Action', ARRAY['sport', 'home defense'], NULL, 'United States', false, NULL),

-- ── DS ARMS ───────────────────────────────────────────────────
('DS Arms', 'SA58', '.308 Winchester', 'Rifle', 'Semi-Auto', 20, 1996, false, 'United States', 'American-made FN FAL-pattern semi-automatic rifle produced by DS Arms using original FN tooling. Available in dozens of configurations. The definitive American FAL and regarded as the most faithful US-made FAL equivalent.', 1399, 204.0, 43.0, false, false, ARRAY['SA58 Para Tactical (folding stock)', 'SA58 Carbine (16")', 'SA58 Congo', 'SA58 OSW (8.5")'], 'Active', 'DS Arms SA58', ARRAY['.308 Win', '7.62 NATO'], ARRAY['sa58', 'dsarms fal', 'dsa fal'], 'Modern', 'Roller-Delayed Blowback', ARRAY['sport', 'military', 'competition'], 'DS Arms purchased original FN manufacturing tooling from Portugal — making the SA58 the only US-made FAL built on actual FN production equipment rather than reverse-engineered copies.', 'United States', false, NULL),

('DS Arms', 'ZM4', '5.56 NATO', 'Rifle', 'Semi-Auto', 30, 2005, false, 'United States', 'DS Arms AR-15/M4 pattern semi-automatic rifle. The ZM4 applies DS Arms'' precision manufacturing standards to the AR-15 platform.', 1099, 128.0, 32.5, false, false, ARRAY['ZM4 Carbine', 'ZM4 A1 SPR'], 'Active', 'DS Arms ZM4', ARRAY['5.56 NATO', '6.5 Grendel'], ARRAY['zm4', 'dsarms ar15'], 'Modern', 'Single-Action', ARRAY['sport'], NULL, 'United States', false, NULL),

('DS Arms', 'SA58 OSW', '.308 Winchester', 'Rifle', 'Semi-Auto', 20, 2003, false, 'United States', 'Ultra-compact SA58 FAL variant with an 8.5" barrel — one of the shortest .308 semi-auto carbines ever offered commercially. Intended for room-clearing applications.', 1699, 176.0, 27.0, false, false, NULL, 'Active', 'DS Arms SA58', ARRAY['.308 Win'], ARRAY['sa58 osw', 'dsarms osw', 'fal osw'], 'Modern', 'Roller-Delayed Blowback', ARRAY['military', 'sport'], NULL, 'United States', false, NULL),

-- ── DWM ───────────────────────────────────────────────────────
('DWM (Deutsche Waffen- und Munitionsfabriken)', 'Luger P08', '9mm Parabellum', 'Pistol', 'Single-Action', 8, 1900, true, 'Germany', 'The Luger P08 — designed by Georg Luger and manufactured by DWM from 1900. The toggle-lock semi-automatic pistol that became one of the most iconic firearms of the 20th century. Standard German military sidearm in WWI and WWII. DWM-manufactured examples from the pre-WWI and WWI era are among the most collectible military pistols.', NULL, 30.0, 8.75, true, true, ARRAY['Artillery Luger (8" barrel)', 'Navy Luger (6" barrel)', 'DWM Commercial'], 'Discontinued', 'Luger P08', ARRAY['9mm Parabellum', '7.65mm Parabellum'], ARRAY['luger', 'p08', 'dwm luger', 'pistole 08'], 'World War I', 'Single-Action', ARRAY['military', 'collector'], 'DWM also developed and manufactured the 9mm Parabellum cartridge specifically for the Luger pistol — the cartridge that became the most widely used pistol cartridge in history.', 'Germany', true, 'DWM-manufactured P08s from the 1900-1918 period command significant premiums. Artillery (Artillerieluger) variants with matching detachable stocks are extremely valuable. Chamber stamps, date codes, and proof marks are critical to valuation.'),

('DWM (Deutsche Waffen- und Munitionsfabriken)', 'Luger P08 Artillery', '9mm Parabellum', 'Pistol', 'Single-Action', 32, 1914, true, 'Germany', 'Long-barreled (8") Luger with a 32-round snail drum magazine, designed for German artillery and storm troops in WWI. The drum magazine was a revolutionary high-capacity design for its era.', NULL, 36.0, 13.5, true, false, ARRAY['With TM 08 snail drum', 'With 32-round drum'], 'Discontinued', 'Luger P08', ARRAY['9mm Parabellum'], ARRAY['artillerieluger', 'lange pistole 08', 'lp08', 'artillery luger'], 'World War I', 'Single-Action', ARRAY['military', 'collector'], 'The Artillery Luger with its snail drum magazine was one of the first high-capacity semi-automatic pistols ever issued to military forces. Matching examples with original drum, holster, and loading tools are among the most valuable WWI pistols.', 'Germany', true, 'Matching Artillery Lugers with original 32-round drum, buttstock holster, and loading tool are exceptional collector pieces worth $5,000-$30,000+ depending on condition and markings.'),

('DWM (Deutsche Waffen- und Munitionsfabriken)', 'Mauser C96 (manufactured)', '7.63x25mm Mauser', 'Pistol', 'Single-Action', 10, 1896, true, 'Germany', 'While DWM is most associated with the Luger, the company also manufactured C96 Broomhandle Mauser pistols under license at various periods. DWM was one of the primary ammunition manufacturers and supplied brass to virtually every major caliber of the era.', NULL, 44.0, 11.75, true, false, NULL, 'Discontinued', 'C96 Broomhandle', ARRAY['7.63x25mm Mauser', '9mm Parabellum'], ARRAY['c96', 'broomhandle', 'bolo mauser'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['military', 'collector'], NULL, 'Germany', true, NULL),

-- ── EAA CORPORATION ───────────────────────────────────────────
('EAA Corporation', 'Witness', '9mm Luger', 'Pistol', 'DA/SA', 16, 1991, false, 'Italy', 'Full-size CZ75-pattern DA/SA pistol from Tanfoglio, imported by EAA. The Witness is one of the most popular competition pistols in IPSC/USPSA due to its reliability and wide availability of aftermarket parts. Also available as the Witness Steel (all-steel) for competition divisions requiring it.', 499, 33.0, 8.1, false, false, ARRAY['Witness Steel', 'Witness Compact', 'Witness P Full Size', 'Witness Elite Match'], 'Active', 'EAA Witness', ARRAY['9mm Luger', '.40 S&W', '.45 ACP', '10mm Auto', '.38 Super'], ARRAY['witness', 'eaa witness', 'tanfoglio witness'], 'Modern', 'DA/SA', ARRAY['competition', 'carry', 'sport'], 'The EAA Witness in 10mm Auto is one of the most popular full-size 10mm pistols available — offering the full power of the cartridge in a double-stack format at an accessible price.', 'Italy', false, NULL),

('EAA Corporation', 'Windicator', '.357 Magnum', 'Revolver', 'DA/SA Revolver', 6, 1992, false, 'Germany', 'Double-action revolver manufactured by Weihrauch and imported by EAA. Available in .357 Magnum and .38 Special. Affordable European-made revolver with a solid reputation for reliability.', 329, 34.0, 9.0, false, false, ARRAY['Windicator in .38 Special', 'Windicator 2" (snub)'], 'Active', 'EAA Windicator', ARRAY['.357 Magnum', '.38 Special'], ARRAY['windicator', 'eaa windicator'], 'Modern', 'DA/SA', ARRAY['carry', 'sport'], NULL, 'Germany', false, NULL),

('EAA Corporation', 'MC312', '12 Gauge', 'Shotgun', 'Semi-Auto', 5, 2015, false, 'Turkey', 'Gas-operated semi-automatic 12-gauge shotgun from Turkey, imported by EAA. Available in sport and home defense configurations. Competes with Stoeger and GForce in the budget semi-auto shotgun segment.', 399, 96.0, 47.0, false, false, ARRAY['MC312 Sport', 'MC312 Slug'], 'Active', 'EAA MC312', ARRAY['12 Gauge'], ARRAY['mc312', 'eaa mc312'], 'Modern', 'Single-Action', ARRAY['hunting', 'home defense'], NULL, 'Turkey', false, NULL),

-- ── ED BROWN PRODUCTS ─────────────────────────────────────────
('Ed Brown Products', 'Kobra', '.45 ACP', 'Pistol', 'Single-Action', 8, 2000, false, 'United States', 'Full-size custom 1911 from Ed Brown with snakeskin pattern stippling on the mainspring housing and front strap. One of Ed Brown''s flagship production models.', 2995, 40.0, 8.75, false, false, ARRAY['Kobra Carry (4.25" barrel)', 'Kobra Carry Lightweight'], 'Active', 'Ed Brown Kobra', ARRAY['.45 ACP', '9mm Luger', '10mm Auto'], ARRAY['kobra', 'ed brown kobra'], 'Modern', 'Single-Action', ARRAY['carry', 'collector', 'competition'], NULL, 'United States', true, NULL),

('Ed Brown Products', 'Executive Carry', '.45 ACP', 'Pistol', 'Single-Action', 8, 1996, false, 'United States', 'Commander-length lightweight 1911 built for serious concealed carry. Ed Brown''s purpose-built carry gun with an aluminum frame and 4.25" barrel.', 2895, 28.0, 7.75, false, false, ARRAY['Executive Target (adjustable sights)', 'Executive Elite (SS frame)'], 'Active', 'Ed Brown Executive', ARRAY['.45 ACP', '9mm Luger'], ARRAY['executive carry', 'ed brown executive'], 'Modern', 'Single-Action', ARRAY['carry', 'collector'], NULL, 'United States', true, NULL),

('Ed Brown Products', 'Special Forces', '.45 ACP', 'Pistol', 'Single-Action', 8, 2004, false, 'United States', 'Combat-configured full-size 1911 with a dark Melonite finish, G10 grips, and enhanced operating controls. Ed Brown''s most tactical production model.', 2995, 40.0, 8.75, false, false, ARRAY['Special Forces Carry', 'Special Forces Light Rail'], 'Active', 'Ed Brown Special Forces', ARRAY['.45 ACP', '9mm Luger', '.38 Super'], ARRAY['special forces', 'ed brown sf'], 'Modern', 'Single-Action', ARRAY['carry', 'military', 'competition'], NULL, 'United States', true, NULL),

-- ── EUROARMS ──────────────────────────────────────────────────
('Euroarms', '1853 Enfield', '.577 Caliber', 'Rifle', 'Single-Action', 1, 1975, false, 'Italy', 'Percussion reproduction of the Pattern 1853 Enfield rifle-musket — the standard British military rifle of the Civil War era, widely used by both sides. Most common Civil War Enfield reproduction for reenactors and NSSA competition.', 499, 128.0, 55.0, false, false, NULL, 'Active', 'Euroarms Enfield', ARRAY['.577 Caliber'], ARRAY['1853 enfield', 'euroarms enfield', 'p53 enfield'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition'], NULL, 'Italy', false, NULL),

('Euroarms', 'Rogers & Spencer', '.44 Caliber', 'Revolver', 'Single-Action Revolver', 6, 1972, false, 'Italy', 'Percussion reproduction of the Rogers & Spencer Army revolver — a Civil War-era US military revolver that was ordered but arrived after the war ended. Considered by many black powder shooters to be the finest-shooting of all Civil War revolver reproductions.', 349, 48.0, 13.75, false, false, ARRAY['Rogers & Spencer Target'], 'Active', 'Euroarms Rogers & Spencer', ARRAY['.44 Caliber'], ARRAY['rogers and spencer', 'r&s revolver'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition'], 'The Rogers & Spencer was government-contracted but delivered after Appomattox. Had the war continued 90 more days, it would have been the Union Army''s standard revolver. Its design is considered superior to both the Colt and Remington it competed against.', 'Italy', false, NULL),

('Euroarms', '1861 Springfield', '.58 Caliber', 'Rifle', 'Single-Action', 1, 1978, false, 'Italy', 'Percussion reproduction of the Model 1861 Springfield rifle-musket. Along with the 1863, the most common Union infantry arm of the Civil War.', 549, 128.0, 56.0, false, false, NULL, 'Active', 'Euroarms Springfield', ARRAY['.58 Caliber'], ARRAY['1861 springfield', 'springfield musket repro'], 'Pre-WWI / Old West', 'Single-Action', ARRAY['collector', 'competition'], NULL, 'Italy', false, NULL)

ON CONFLICT (make, model) DO NOTHING;
